### ISSUE TITLE
Are the "Pi" characters gender coded m/f pink/blue?

### ISSUE THREAD

**Issue by danbri** [3b1b/manim#10]
This didn't occur to me until Jennifer [showed up](https://youtu.be/P2LTAUO1TdA?t=1m38s), but now when I see a row of blue Pi-people it makes me think of gender ratio issues in STEM. Maybe you could throw in a few more colours?

**Comment by 3b1b** [comment]
This is definitely a good thing to care about.  I never necessarily thought of blue ones as being gendered, I just set up teacher-student scenes to have 3 blue creatures and 1 brown creatures to match the channel name.  Perhaps the same goal can be reached just by referring to one of the students or to the teacher with a female pronoun now and then?

**Comment by danbri** [comment]
That could work. The pink kind of jumps off the page...

**Comment by TPVasconcelos** [comment]
I recommend closing this issue.
