### ISSUE TITLE
Manim is in streaming mode

### ISSUE THREAD

**Issue by FluppyDerDelphin** [3b1b/manim#1020]
when i try to render Scenes in my cmd-window occurs the following text:

Played 0 animations

Manim is now running in streaming mode. Stream animations by passing
them to manim.play(), e.g.
>>> c = Circle()
>>> manim.play(ShowCreation(c))

The comand i used was;

python -m manim.py example_scenes SquareToCircle -pl

But it happens with every Scene i try to render.
Yesterday manim worked normally. I didnt change anything.

Thank you for you help :)

**Comment by Aathish04** [comment]
Try the command `python3 manim.py example_scenes.py SquareToCircle -pl` (remove the -m tag)

If that doesn't work, tell us what error you got.

**Comment by FluppyDerDelphin** [comment]
It worked, thank you sooo much :)

**Comment by begintech** [comment]
hi, I am getting the same error. I tried doing what you said. getting the error

'python3' is not recognized as an internal or external command,
operable program or batch file.

pls help
thanks

**Comment by begintech** [comment]
after running            python manim.py test.py Tute -pl

it shows 

Played 0 animations

Manim is now running in streaming mode. Stream animations by passing
them to manim.play(), e.g.
>>> c = Circle()
>>> manim.play(ShowCreation(c))

>>>

pls help

**Comment by TonyCrane** [comment]
please use the newest code on GitHub, or reinstall it through pip.
because the stream mode had been removed in both the manimgl version and the cairo-backend version.
