### ISSUE TITLE
Angles failure

### ISSUE THREAD

**Issue by curenosm** [3b1b/manim#1021]
https://github.com/3b1b/manim/blob/af65c9d5d4ecbcffc5e569508053d56d1f7e86eb/manimlib/animation/transform.py#L124

For angle -2pi there's a failure in animation so if you transform a horizontal line into a circle it becomes a very weird shaped form.

**Comment by kevkevinpal** [comment]
would you be able to provide a sample of code that replicates this issue I would like to take a look at this issue, and it would help for anyone else who would like to help as well. Thanks!

**Comment by curenosm** [comment]
Tecnically this is not a problem due to the meaning of the setting "path_arc", because there is not sense at all of using that angle, but I had to search more deeply in the library to realize of that, it could be said that it was not really an issue
