### ISSUE TITLE
Docker: “Missing mandatory value for "volumes" option”               （input and output path setting problem）

### ISSUE THREAD

**Issue by HumbleHumbert** [3b1b/manim#1023]
I'm a total noob in programming, have struggled my way installing envs and everything, but I really cannot solve this. I'd really appreciate it if someone can help.
I'll go with the procedure first.

1. Installed docker desktop, docker pull eulertour/manim, run
` "docker-compose run manim example_scenes.py SquareToCircle -l"` command.
2. Then it appers
 `"ERROR: Missing mandatory value for "volumes" option interpolating ["${INPUT_PATH:?INPUT_PATH environment variable isn't set}:/tmp/input", "${OUTPUT_PATH:?OUTPUT_PATH environment variable isn't set}:tmp/output"] in service "manim": INPUT_PATH environment variable isn't set" `
3. My system is win10 pro 64x , and the command is running on cmd(admin), the docker is on though I don't know what's it for.

So it seems like an input an output directory setting problem, I did found the profile 
`"docker-compose.yml" `which contains
```
"  volumes:
      - ${INPUT_PATH:?INPUT_PATH environment variable isn't set}:/tmp/input
      - ${OUTPUT_PATH:?OUTPUT_PATH environment variable isn't set}:/tmp/output"
```
I tried several times changing it like `"INPUT_PATH:C:\Users\unrul\manim \"`
didn't work . So I run out of my brain here, can someone teach me on how to set it up properly?
and how can I change the input and out put directory when I run manim on python, 'cause
 the command `"manim example_scenes.py SquareToCircle -pl"` obviously doesn't define it.

Again, thank you for your response. Would be very useful to me.

**Comment by OneUp5hroom** [comment]
@HumbleHumbert 
Another noob to manim here... but I think I was able to figure this one out! :) 
In a docker-compose file the formatting is localDIR:containerDIR so, as an example this is how I configured my docker-compose.yml file (and it worked).

`version: '3.1'

services:
  manim:
    # comment this line if you build the image to prevent overwriting the tag
    image: eulertour/manim:latest
    # uncomment this line to build rather than pull the image
    # build: .
    entrypoint:
      - manim
      - --media_dir=/tmp/output
    volumes:
      - C:\Users\<username>\Documents\Animations\manim\manim\:/tmp/input
      - C:\Users\<username>\Documents\Animations\manim\OUTPUT\:/tmp/output
    working_dir: /tmp/input
    network_mode: "none"`

My folder structure inside Animations goes:
`-Animations
     |_ manim //big container for all things manim
          |_ OUTPUT //for output files
          |_ manim //Cloned repo`

Hope this helps!!

**Comment by OneUp5hroom** [comment]
Also just to throw this in as I am learning. Since you are running on Windows in a docker container the path's to subfiles need to be formatted as if they were in a linux environment. 

For example if you wanted to render the manim\logo\logo.py file... you'd pass it as:
```
docker-compose run manim ./logo/logo.py Thumbnail -l
```
where as in windows you'd think it would be: (But this does NOT work) :)
```
docker-compose run manim .\logo\logo.py Thumbnail -l
```
Good luck!

**Comment by HumbleHumbert** [comment]
@OneUp5hroom 
Got it! Though I have turned to anaconda, it turned out that I have been trying to modify the config files in the profile I `git clone` from `manim.git`. Obviously wrong, I should chang it where I installed manimlib, like `C:\Users\unrul\anaconda3\envs\manim\Lib\site-packages\manimlib` 
It genuinely sucks to be a noob :(  ,Thank you green mushroom bro!
