### ISSUE TITLE
Bug in Text mobject with latest version of master branch

### ISSUE THREAD

**Issue by qo4on** [3b1b/manim#1033]
`text1` renders with a default font. I suppose there is something wrong with [latest commit](https://github.com/3b1b/manim/pull/1030).
@Tony031218, @eulertour please take a look:
```
class test(Scene):
  def construct(self):
    text1 = Text('37.6', font="IBM Plex Sans", size=.52, stroke_width=0).move_to(UP)
    text2 = Text('37.6', font="IBM Plex Sans", stroke_width=0).move_to(DOWN)
    self.add(text1, text2)
    self.wait(.1)
```
[IBM Plex Sans](https://fonts.google.com/specimen/IBM+Plex+Sans)
![image](https://user-images.githubusercontent.com/35609308/81125168-d9a75800-8f50-11ea-8592-3817c54a56d2.png)

**Comment by Tony031218** [comment]
I don't have the same problem on my computer. Would you like to try running the same scene after cleaning(deleting) `media/texts/`?

**Comment by qo4on** [comment]
Thanks, this fixed the issue.
