### ISSUE TITLE
Change size and other properties of TextMobjects

### ISSUE THREAD

**Issue by baljeetrathi** [3b1b/manim#1034]
Hi,

I have been trying to create to make some changes to the text I write on screen using TextMobjects. Here is a sample line:

```
final_line = TextMobject(r"${S1 \times R1} \over {S1 + R1}$", color=ORANGE)
```

The color is the only property I could change for this TextMobject. I tried setting `size=0.5`. However, it did not have any effect. What about aligning the text?

I looked around for a couple of hours to find examples for positioning the text and found out about `Vgroup` and `arrange`. 

The `arrange` method solved the alignment issue. However, I still couldn't figure out how to change size or other properties.

Is there a central source of information where I can read about properties like `arrange` and the parameters they take etc. and objects like `Vgroup`?

Manim does have a lot of classes, methods, and parameters. However, I can only find about them from working examples after a lot of searching.

Is there a place where I can read about the whole library when I want to figure out how to do things?

Thanks. :)

**Comment by Tony031218** [comment]
1)  If you want to change the size of TextMobject, you can use `.scale()` method.
2)  If you want to align the text, you can use `next_to(),align_to()`and so on.
3)  The best way to find methods is to read the source codes of manimlib

If you don't have the ability to read the source codes, you can find some tutorial. My team made some tutorials on bilibili. If you want,here is the [link](https://b23.tv/BV1p54y197cC)

**Comment by baljeetrathi** [comment]
Thanks @Tony031218 :)

When I wanted to read about methods available for a TextMobject I read the code here: https://github.com/3b1b/manim/blob/master/manimlib/mobject/svg/tex_mobject.py but it does not have any functions for alignment like `next_to()` etc.

How can I figure out which file contains these methods?

**Comment by Tony031218** [comment]
The TextMobject is a subclass of SVGMobject, and SVGMobject is a subclass of VMobject, and VMobject is a subclass of Mobject.

So TextMobject has all methods which Mobject, VMobject and SVGMobject have.
Then you can find all methods in `mobject.py, types/vectorized_mobject.py, svg/svg_mobject.py`.

manim has a clear structure of Class inheritance, I made a mind map of the structure, you can see it at [here](https://github.com/manim-kindergarten/manim_sandbox/blob/master/documents/manim%E7%B1%BB%E7%BB%93%E6%9E%84.pdf)

**Comment by baljeetrathi** [comment]
@Tony031218 I am having one more problem. :)

The `next_to()` and `align_to()` functions work well when aliging the multi-line text within a single TextMobject?

I tried adding `\begin{flushleft}` and `\end{flushleft}` at the beginning and end of my sentences but it caused an error.

**Comment by baljeetrathi** [comment]
I managed to align the text to left by using `\raggedright`.
