### ISSUE TITLE
Basic install problems

### ISSUE THREAD

**Issue by lakeside-park** [3b1b/manim#1053]
just at the beginning - trying to get the first commands to work - pip install manimlib - the Visual Studio problem at the bottom is missing msvcp140_dll file.  I have spend 4 hours this afternoon trying to solve that problem and can't even get that done.  Any help is appreciated - here is the command and the result run in the cmd window.  I downloaded manim today so it is the latest version of files

C:\Users\Admin\Desktop\manim-master>pip install manimlib >install.txt
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\admin\appdata\local\programs\python\python37\python.exe'
 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Admin\\A
ppData\\Local\\Temp\\pip-install-vt3ww8c9\\pycairo\\setup.py'"'"'; __file__='"'"
'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-vt3ww8c9\\pycairo\\setup.py
'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace(
'"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"
'"'))' install --record 'C:\Users\Admin\AppData\Local\Temp\pip-record-lsh3vkpj\i
nstall-record.txt' --single-version-externally-managed --compile --install-heade
rs 'c:\users\admin\appdata\local\programs\python\python37\Include\pycairo'
         cwd: C:\Users\Admin\AppData\Local\Temp\pip-install-vt3ww8c9\pycairo\
    Complete output (18 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\cairo
    copying cairo\__init__.py -> build\lib.win-amd64-3.7\cairo
    copying cairo\__init__.pyi -> build\lib.win-amd64-3.7\cairo
    copying cairo\py.typed -> build\lib.win-amd64-3.7\cairo
    running build_ext
    building 'cairo._cairo' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\cairo
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe
/c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPYCAIRO_VERSION_MAJOR=1 -DPYCAIRO_VERSION_
MINOR=19 -DPYCAIRO_VERSION_MICRO=1 -Ic:\users\admin\appdata\local\programs\pytho
n\python37\include -Ic:\users\admin\appdata\local\programs\python\python37\inclu
de "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Prog
ram Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (
x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1
\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tccairo/
device.c /Fobuild\temp.win-amd64-3.7\Release\cairo/device.obj
    device.c
    c:\users\admin\appdata\local\temp\pip-install-vt3ww8c9\pycairo\cairo\pycairo
.h(37): fatal error C1083: Cannot open include file: 'cairo.h': No such file or
directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\B
IN\\x86_amd64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\admin\appdata\local\pro
grams\python\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.a
rgv[0] = '"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-vt3ww8c9\\pyca
iro\\setup.py'"'"'; __file__='"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-in
stall-vt3ww8c9\\pycairo\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)
(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(co
mpile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Admin\AppData
\Local\Temp\pip-record-lsh3vkpj\install-record.txt' --single-version-externally-
managed --compile --install-headers 'c:\users\admin\appdata\local\programs\pytho
n\python37\Include\pycairo' Check the logs for full command output.

**Comment by Aathish04** [comment]
You appear to have these issues when installing the Cairo package.

You can find a supported, prebuilt binary of it here: https://cdn.discordapp.com/attachments/669259565941915723/681912731708030987/pycairo-1.18.2-cp37-cp37m-win_amd64.whl
(Yes, it's from the Manim community on Discord.)

You can install it with `pip install <path/to/whl/file>`

Also, I wouldn't really recommend installing Manim via pip, at least for now. The Pip package hasn't been updated in some time and is missing out on many features of "Modern" Manim, most notably the Text() object. The better way, IMO, is to clone the git repo and `pip install -r requirements.txt` away.

**Comment by CodeForeverAndEver** [comment]
@Aathish04 Is the amd64 for amd cpu's? If so, do you have a download for intel ones? I only ask because when I use the wheel that you linked I get: ERROR: pycairo-1.18.2-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.

(on Windows)

**Comment by Aathish04** [comment]
The AMD64 wheel is for the 64-bit platform. It's just a name, and AMD were the first to implement it, followed by Intel and other chip companies.

Anyway, are you running 64 bit WIndows or 32Bit Windows? What's your processor?

**Comment by CodeForeverAndEver** [comment]
I am running 64 bit windows. cpu = intel core i7-8700H. When I install pycairo via `pip install pycairo==1.18.0` I get the same error as listed above @Aathish04

**Comment by Aathish04** [comment]
That's.... strange.

What does 'pip install pycairo' without any version numbers give you?

**Comment by CodeForeverAndEver** [comment]
Will try.

**Comment by CodeForeverAndEver** [comment]
@Aathish04 Same thing.

**Comment by Aathish04** [comment]
The same error?
Or was it something like `Could not find a version that satisfies the requirement <yada yada> from <yada yada>`?

**Comment by CodeForeverAndEver** [comment]
```
D:\Documents\Coding\Installations\manim>pip install pycairo
Collecting pycairo
  Using cached pycairo-1.19.1.tar.gz (205 kB)
Building wheels for collected packages: pycairo
  Building wheel for pycairo (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'd:\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-9bjq0tao\\pycairo\\setup.py'"'"'; __file__='"'"'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-9bjq0tao\\pycairo\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\username\AppData\Local\Temp\pip-wheel-rimy4zv3'
       cwd: C:\Users\username\AppData\Local\Temp\pip-install-9bjq0tao\pycairo\
  Complete output (18 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.7
  creating build\lib.win32-3.7\cairo
  copying cairo\__init__.py -> build\lib.win32-3.7\cairo
  copying cairo\__init__.pyi -> build\lib.win32-3.7\cairo
  copying cairo\py.typed -> build\lib.win32-3.7\cairo
  running build_ext
  building 'cairo._cairo' extension
  creating build\temp.win32-3.7
  creating build\temp.win32-3.7\Release
  creating build\temp.win32-3.7\Release\cairo
  D:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPYCAIRO_VERSION_MAJOR=1 -DPYCAIRO_VERSION_MINOR=19 -DPYCAIRO_VERSION_MICRO=1 -Id:\programs\python\python37-32\include -Id:\programs\python\python37-32\include "-ID:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tccairo/device.c /Fobuild\temp.win32-3.7\Release\cairo/device.obj
  device.c
  C:\Users\username\AppData\Local\Temp\pip-install-9bjq0tao\pycairo\cairo\pycairo.h(37): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory
  error: command 'D:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for pycairo
  Running setup.py clean for pycairo
Failed to build pycairo
Installing collected packages: pycairo
    Running setup.py install for pycairo ... error
    ERROR: Command errored out with exit status 1:
     command: 'd:\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-9bjq0tao\\pycairo\\setup.py'"'"'; __file__='"'"'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-9bjq0tao\\pycairo\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\username\AppData\Local\Temp\pip-record-_uh24cwt\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\programs\python\python37-32\Include\pycairo'
         cwd: C:\Users\username\AppData\Local\Temp\pip-install-9bjq0tao\pycairo\
    Complete output (18 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.7
    creating build\lib.win32-3.7\cairo
    copying cairo\__init__.py -> build\lib.win32-3.7\cairo
    copying cairo\__init__.pyi -> build\lib.win32-3.7\cairo
    copying cairo\py.typed -> build\lib.win32-3.7\cairo
    running build_ext
    building 'cairo._cairo' extension
    creating build\temp.win32-3.7
    creating build\temp.win32-3.7\Release
    creating build\temp.win32-3.7\Release\cairo
    D:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPYCAIRO_VERSION_MAJOR=1 -DPYCAIRO_VERSION_MINOR=19 -DPYCAIRO_VERSION_MICRO=1 -Id:\programs\python\python37-32\include -Id:\programs\python\python37-32\include "-ID:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tccairo/device.c /Fobuild\temp.win32-3.7\Release\cairo/device.obj
    device.c
    C:\Users\username\AppData\Local\Temp\pip-install-9bjq0tao\pycairo\cairo\pycairo.h(37): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory
    error: command 'D:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'd:\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-9bjq0tao\\pycairo\\setup.py'"'"'; __file__='"'"'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-9bjq0tao\\pycairo\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\username\AppData\Local\Temp\pip-record-_uh24cwt\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\programs\python\python37-32\Include\pycairo' Check the logs for full command output.
```

So, pretty much the same.

**Comment by Aathish04** [comment]
Because if you got the second one, you could look at prebuilt Windows binaries from some other source, like https://www.lfd.uci.edu/~gohlke/pythonlibs/#pycairo

**Comment by Aathish04** [comment]
> ```
> D:\Documents\Coding\Installations\manim>pip install pycairo
> Collecting pycairo
>   Using cached pycairo-1.19.1.tar.gz (205 kB)
> Building wheels for collected packages: pycairo
>   Building wheel for pycairo (setup.py) ... error
>   ERROR: Command errored out with exit status 1:
>    command: 'd:\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-9bjq0tao\\pycairo\\setup.py'"'"'; __file__='"'"'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-9bjq0tao\\pycairo\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\username\AppData\Local\Temp\pip-wheel-rimy4zv3'
>        cwd: C:\Users\username\AppData\Local\Temp\pip-install-9bjq0tao\pycairo\
>   Complete output (18 lines):
>   running bdist_wheel
>   running build
>   running build_py
>   creating build
>   creating build\lib.win32-3.7
>   creating build\lib.win32-3.7\cairo
>   copying cairo\__init__.py -> build\lib.win32-3.7\cairo
>   copying cairo\__init__.pyi -> build\lib.win32-3.7\cairo
>   copying cairo\py.typed -> build\lib.win32-3.7\cairo
>   running build_ext
>   building 'cairo._cairo' extension
>   creating build\temp.win32-3.7
>   creating build\temp.win32-3.7\Release
>   creating build\temp.win32-3.7\Release\cairo
>   D:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPYCAIRO_VERSION_MAJOR=1 -DPYCAIRO_VERSION_MINOR=19 -DPYCAIRO_VERSION_MICRO=1 -Id:\programs\python\python37-32\include -Id:\programs\python\python37-32\include "-ID:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tccairo/device.c /Fobuild\temp.win32-3.7\Release\cairo/device.obj
>   device.c
>   C:\Users\username\AppData\Local\Temp\pip-install-9bjq0tao\pycairo\cairo\pycairo.h(37): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory
>   error: command 'D:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
>   ----------------------------------------
>   ERROR: Failed building wheel for pycairo
>   Running setup.py clean for pycairo
> Failed to build pycairo
> Installing collected packages: pycairo
>     Running setup.py install for pycairo ... error
>     ERROR: Command errored out with exit status 1:
>      command: 'd:\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-9bjq0tao\\pycairo\\setup.py'"'"'; __file__='"'"'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-9bjq0tao\\pycairo\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\username\AppData\Local\Temp\pip-record-_uh24cwt\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\programs\python\python37-32\Include\pycairo'
>          cwd: C:\Users\username\AppData\Local\Temp\pip-install-9bjq0tao\pycairo\
>     Complete output (18 lines):
>     running install
>     running build
>     running build_py
>     creating build
>     creating build\lib.win32-3.7
>     creating build\lib.win32-3.7\cairo
>     copying cairo\__init__.py -> build\lib.win32-3.7\cairo
>     copying cairo\__init__.pyi -> build\lib.win32-3.7\cairo
>     copying cairo\py.typed -> build\lib.win32-3.7\cairo
>     running build_ext
>     building 'cairo._cairo' extension
>     creating build\temp.win32-3.7
>     creating build\temp.win32-3.7\Release
>     creating build\temp.win32-3.7\Release\cairo
>     D:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPYCAIRO_VERSION_MAJOR=1 -DPYCAIRO_VERSION_MINOR=19 -DPYCAIRO_VERSION_MICRO=1 -Id:\programs\python\python37-32\include -Id:\programs\python\python37-32\include "-ID:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tccairo/device.c /Fobuild\temp.win32-3.7\Release\cairo/device.obj
>     device.c
>     C:\Users\username\AppData\Local\Temp\pip-install-9bjq0tao\pycairo\cairo\pycairo.h(37): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory
>     error: command 'D:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: 'd:\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-9bjq0tao\\pycairo\\setup.py'"'"'; __file__='"'"'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-9bjq0tao\\pycairo\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\username\AppData\Local\Temp\pip-record-_uh24cwt\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\programs\python\python37-32\Include\pycairo' Check the logs for full command output.
> ```
> 
> So, pretty much the same.

So for some reason, your computer is unable to compile Pycairo. No issues. Just look into any of the prebuilt binaries from the site I linked. The newer ones _are_ supported by manim, so there's no need to restrict yourself.

**Comment by CodeForeverAndEver** [comment]
@Aathish04 I believe I had downloaded them from that site.

**Comment by Aathish04** [comment]
Well that’s infuriating. Could you try installing Visual C++ if it isn’t already installed and giving  `pip install pycairo` another go?

**Comment by CodeForeverAndEver** [comment]
Hmm, I believe I did that. I’ll make sure that I check the Visual C++ option when I installed it. Now that I think of it, I am 90% sure that I didn’t.

**Comment by Aathish04** [comment]
Hmm. While you do that, install pig-config while you’re at it.
The issue over at
https://github.com/3b1b/manim/issues/954 <https://github.com/3b1b/manim/issues/954>  says you need it to built PyCairo.

**Comment by CodeForeverAndEver** [comment]
@Aathish04 How would I install that on Windows?

**Comment by CodeForeverAndEver** [comment]
I think it may be working when I use the wheel installer. Just doesn't work otherwise. Just to make sure, though. I am installing everything that you mentioned.

**Comment by CodeForeverAndEver** [comment]
Alright, installed the build tools with the same problem.

**Comment by lakeside-park** [comment]
> 
> 
> You appear to have these issues when installing the Cairo package.
> 
> You can find a supported, prebuilt binary of it here: https://cdn.discordapp.com/attachments/669259565941915723/681912731708030987/pycairo-1.18.2-cp37-cp37m-win_amd64.whl
> (Yes, it's from the Manim community on Discord.)
> 
> You can install it with `pip install <path/to/whl/file>`
> 
> Also, I wouldn't really recommend installing Manim via pip, at least for now. The Pip package hasn't been updated in some time and is missing out on many features of "Modern" Manim, most notably the Text() object. The better way, IMO, is to clone the git repo and `pip install -r requirements.txt` away.

Thanks for your reply and help.  I was able to get example-scenes to run with some file errors.  I also ran perf-scenes and was able to create some .mp4 files.  This stuff looks quite complicated.  I appreciate your help getting me running at least.  Looks like some work to do to get good using this stuff.

**Comment by lakeside-park** [comment]
> 
> 
> You appear to have these issues when installing the Cairo package.
> 
> You can find a supported, prebuilt binary of it here: https://cdn.discordapp.com/attachments/669259565941915723/681912731708030987/pycairo-1.18.2-cp37-cp37m-win_amd64.whl
> (Yes, it's from the Manim community on Discord.)
> 
> You can install it with `pip install <path/to/whl/file>`
> 
> Also, I wouldn't really recommend installing Manim via pip, at least for now. The Pip package hasn't been updated in some time and is missing out on many features of "Modern" Manim, most notably the Text() object. The better way, IMO, is to clone the git repo and `pip install -r requirements.txt` away.

Thanks for your reply and help.  I was able to get example-scenes to run with some file errors.  I also ran perf-scenes and was able to create some .mp4 files.  This stuff looks quite complicated.  I appreciate your help getting me running at least.  Looks like some work to do to get good using this stuff.
