### ISSUE TITLE
Please help me. FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\ Users\\Jeremiah\\Downloads\\manim-master\\manim-master\\media\\videos\\example_s cenes\\480p15\\SquareToCircle.mp4'

### ISSUE THREAD

**Issue by jnhyjere** [3b1b/manim#1054]
How do I solve this issue for my manim?

C:\Users\Jeremiah\Downloads\manim-master\manim-master>python -m manim example_sc
enes.py SquareToCircle -pl
Media will be written to ./media\. You can change this behavior with the --media
_dir flag.
[concat @ 000000e20553c840] Impossible to open 'CC:/Users/Jeremiah/Downloads/man
im-master/manim-master/media/videos/example_scenes/480p15/partial_movie_files/Sq
uareToCircle/00000.mp4'
C:\Users\Jeremiah\Downloads\manim-master\manim-master\media\videos\example_scene
s\480p15\partial_movie_files\SquareToCircle\partial_movie_file_list.txt: Protoco
l not found
Did you mean file:C:\Users\Jeremiah\Downloads\manim-master\manim-master\media\vi
deos\example_scenes\480p15\partial_movie_files\SquareToCircle\partial_movie_file
_list.txt?

File ready at C:\Users\Jeremiah\Downloads\manim-master\manim-master\media\videos
\example_scenes\480p15\SquareToCircle.mp4

Played 3 animations

Traceback (most recent call last):
  File "C:\Users\Jeremiah\Downloads\manim-master\manim-master\manimlib\extract_s
cene.py", line 156, in main
    open_file_if_needed(scene.file_writer, **config)
  File "C:\Users\Jeremiah\Downloads\manim-master\manim-master\manimlib\extract_s
cene.py", line 35, in open_file_if_needed
    os.startfile(file_path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\
Users\\Jeremiah\\Downloads\\manim-master\\manim-master\\media\\videos\\example_s
cenes\\480p15\\SquareToCircle.mp4'

**Comment by Tony031218** [comment]
See #1051 first.

**Comment by jnhyjere** [comment]
#1051
