### ISSUE TITLE
 Impossible to open 'CC:/manim/manim_3_feb/media/videos/example_scenes/480p15/partial_movie_files/SquareToCircle/00000.mp4'

### ISSUE THREAD

**Issue by Miho27ForLife** [3b1b/manim#1059]
![Screenshot_1](https://user-images.githubusercontent.com/65260808/81756436-479cd380-94ab-11ea-89e1-af386563bfcd.png)
Help me solve this

**Comment by gregovin** [comment]
I'm still experiencing this issue, installed manim today. I'm running Windows 10, version 1903 64 bit.

**Comment by NavpreetDevpuri** [comment]
> I'm still experiencing this issue, installed manim today. I'm running Windows 10, version 1903 64 bit.

Use latest version from github
https://github.com/3b1b/manim/issues/1075#issuecomment-629607483

**Comment by gregovin** [comment]
Thank you much. That worked
