### ISSUE TITLE
Some bugs of code_mobject.py

### ISSUE THREAD

**Issue by TonyCrane** [3b1b/manim#1067]
Here is some bugs of #1036 

## Bug 1. For `Text()`
The front spaces are not in front of the first character, but in the front of all of the characters, like this:
```python
text1 = Text("  ab\ncd", font="Consolas", size=2)
```
![](https://tonycrane.github.io/images/Text__bug1.png)
So it will look not good when TransformText:
```python
text2 = Text("ef\ngh", font="Consolas", size=2)
self.play(Transform(text1, text2))
```
![](https://tonycrane.github.io/images/Text__bug1.gif)

## Bug 2. For `Code()`
Background color of codes is choosed by html file pygments made, so if I let `style='vim'`, the background color of codes will be the same as the background color of Scene.
![](https://tonycrane.github.io/images/Text__bug3.png)
And if I let `style='autumn`, the background color would be the same as the color of line numbers:
![](https://tonycrane.github.io/images/Text__bug4.png)

These are the 2 bugs I have found so far.
code_mobject.py is a good idea, but it ’s too early to submit pull requests and merge.
@NavpreetDevpuri  Hope that you can fix these bugs.

I'm poor in English, hope you can understand me :)

**Comment by NavpreetDevpuri** [comment]
nice work
