### ISSUE TITLE
name 'Text' is not defined

### ISSUE THREAD

**Issue by nosnakeob** [3b1b/manim#1075]
![image](https://user-images.githubusercontent.com/47769817/82108734-3382fb80-9763-11ea-8d43-e58ccc374c56.png)
![image](https://user-images.githubusercontent.com/47769817/82108741-40075400-9763-11ea-8d52-98c9538241d3.png)
![image](https://user-images.githubusercontent.com/47769817/82108762-675e2100-9763-11ea-8484-651da1ee7f87.png)

I use `pip install manimlib` and I think that's the latest version

**Comment by NavpreetDevpuri** [comment]
this version does not contains `Text_mobject.py`

**Comment by Tony031218** [comment]
the version on pypi is very low. so you need to clone the newest source code in this repo.

**Comment by nosnakeob** [comment]
> the version on pypi is very low. so you need to clone the newest source code in this repo.

Yeah, I downloaded it and replaced the older one. It works perfectly.
