### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'loader'

### ISSUE THREAD

**Issue by Reck210** [3b1b/manim#1076]
When I installed Manim and all the other libraries and extensions that makes it work, every animation worked properly. No problem at all.

But then, I think out of nowhere, the following error began showing up when I tried to animate any class or animation that exists on the manim folder, as long as I write the command that will be showed next, and even ones that I've written for testing.

`File "manim.py", line 10, in <module>
    config = manimlib.config.get_configuration(args)
  File "C:\Users\filip\Apps\Programming\Manim\manimlib\config.py", line 158, in get_configuration
    module = get_module(args.file)
  File "C:\Users\filip\Apps\Programming\Manim\manimlib\config.py", line 152, in get_module       
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 580, in module_from_spec
AttributeError: 'NoneType' object has no attribute 'loader'`

 I tried to animate those test files as said with this command:

`python manim.py \My_Projects Test.py -pm`

Evidently, the folder 'My_Projects' is a folder located in the 'Manim' folder.
However, I've tried to move the 'Test.py' file out of the 'My_Projects' subfolder, mantain that file in the 'Manim' folder and run the animation, by using the command:

`python -m manim Test.py Positions -pm`

And it works perfectly, as it should.

Does anyone knows how to solve this? I have already searched on Google, Github and StackOverflow, and no one seems to have the same problem as me.
I use Win10.

**Comment by Aathish04** [comment]
`python manim.py \My_Projects Test.py -pm` isn't the right command to animate a Test.py file inside a folder named My_Projects

The correct syntax would be:
`python C:\path\to\manim.py C:\path\to\MyProjects\Test.py -pm`

If that doesn't work tell us the error you got when running it and tell us how exactly you installed Manim.

**Comment by Reck210** [comment]
Worked!
I don't know how I've come to that command for trying to animate, but for sure that was the wrong approach.
Thanks for the help!
