### ISSUE TITLE
Adding 3D Image?

### ISSUE THREAD

**Issue by sexyzeky** [3b1b/manim#1077]
Is it possible add 3D image to screen by manim?

**Comment by Aathish04** [comment]
An image, by definition, is 2D.

What do you mean by a 3D image?

If you mean like something you export from Blender, then no, there is no support for that yet.

However, you can still create many 3D objects with Manim.

**Comment by NavpreetDevpuri** [comment]
For now you can put images in 3d space but, a 3d model is not supported.

**Comment by sexyzeky** [comment]
Well, can we create the Earth? I know we can create a sphere, but can we paint it as we desire?

**Comment by Aathish04** [comment]
Ehh, no. Probably not.

**Comment by sexyzeky** [comment]
:')
