### ISSUE TITLE
Error,runting Error

### ISSUE THREAD

**Issue by heguohui2018** [3b1b/manim#1079]
python : 3.7
from manimlib.imports import *
class Text_18(Scene):
    """description"""
    def construct(self):
        text1 = TextMobject("Thsi is a regular Text")
        text2 = TextMobject("Text")
        text1.move_to(text2,LEFT,buff=2)
        self.play(Write(text1),Write(text2))
        self.wait(3)

<img width="1104" alt="截屏2020-05-17 07 36 21" src="https://user-images.githubusercontent.com/35359288/82132374-bc587080-9811-11ea-8053-b66098806ddd.png">

Error:

![image](https://user-images.githubusercontent.com/35359288/82132313-02610480-9811-11ea-9d88-b03bb0d7b08b.png)

**Comment by NavpreetDevpuri** [comment]
move_to() takes 3d array of coordinates like `np.array([0,0,0])` or `text1.get_center()` or `text1.get_left()` 
You may want to use `next_to()` which takes `mobject`, `direction` and `buff`
use `text1.next_to(text2, LEFT, buff=2)`

**Comment by heguohui2018** [comment]
I want to achieve this effect, 
<img width="687" alt="截屏2020-05-17 08 54 05" src="https://user-images.githubusercontent.com/35359288/82133252-63420a00-981c-11ea-8b81-61246e7b7f32.png">


but the  move_to()  function cannot receive the buff=2 parameter,

Don't know where the problem is

**Comment by NavpreetDevpuri** [comment]
> `move_to()` takes vector as 3d array of coordinates like `np.array([0,0,0])` or `text1.get_center()` which return 3d array of center point or `text1.get_left()` which returns 3d array of mid point of left edge.
> You may want to use `next_to()` which takes `mobject`, `direction` and `buff`
> use `text1.next_to(text2, LEFT, buff=2)`


As i told about `move_to()` 
and if you use `text2.move_to(text)` which moves text2 to the center point of `text`
`move_to()` does not takes `buff` argument.
i told use `text1.next_to(text2, LEFT, buff=2)`

**Comment by heguohui2018** [comment]
Turns out I used the wrong function，Thanks You，
