### ISSUE TITLE
please help me i am new to manim

### ISSUE THREAD

**Issue by lisaraj2009** [3b1b/manim#1081]
Help me!

i got this error: 
Impossible to open 'CC:/manim/manim_4_feb/media/videos/example_scenes/480p15/partial_movie_files/SquareToCircle/00000.mp4'
C:\manim\manim_4_feb\media\videos\example_scenes\480p15\partial_movie_files\SquareToCircle\partial_movie_file_list.txt: Protocol not found
Did you mean file:C:\manim\manim_4_feb\media\videos\example_scenes\480p15\partial_movie_files\SquareToCircle\partial_movie_file_list.txt?

File ready at C:\manim\manim_4_feb\media\videos\example_scenes\480p15\SquareToCircle.mp4

Played 3 animations

Traceback (most recent call last):
  File "C:\manim\manim_4_feb\manimlib\extract_scene.py", line 154, in main
    open_file_if_needed(scene.file_writer, **config)
  File "C:\manim\manim_4_feb\manimlib\extract_scene.py", line 35, in open_file_if_needed
    os.startfile(file_path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\manim\\manim_4_feb\\media\\videos\\example_scenes\\480p15\\SquareToCircle.mp4'

**Comment by NavpreetDevpuri** [comment]
Download latest version this error is fixed.
Or manually apply this changes https://github.com/3b1b/manim/pull/1057/files

**Comment by lisaraj2009** [comment]
thanks so much i already figured it out
