### ISSUE TITLE
Help with Manim please

### ISSUE THREAD

**Issue by lisaraj2009** [3b1b/manim#1084]
I was following Theorem of Beethoven's tutorial on using manim, and I got stuck while doing the WriteText Example. Help?

Impossible to open 'CC:/manim/videos/1_text_format/1440p60/partial_movie_files/WriteText/00000.mp4'
C:\manim\videos\1_text_format\1440p60\partial_movie_files\WriteText\partial_movie_file_list.txt: Protocol not found
Did you mean file:C:\manim\videos\1_text_format\1440p60\partial_movie_files\WriteText\partial_movie_file_list.txt?
I got a similar error while following the squaretocircle example, but i fixed it by downloading the latest version of manim

**Comment by NavpreetDevpuri** [comment]
> I'm still experiencing this issue, installed manim today. I'm running Windows 10, version 1903 64 bit.

Use latest version from github.
https://github.com/3b1b/manim/issues/1075#issuecomment-629607483

**Comment by lisaraj2009** [comment]
I think i downloaded the latest commit. Since I may install linux today, I'll get back to you. I think that this doesn't have much compatibility

**Comment by lisaraj2009** [comment]
Anyways thanks for it so i'll get back to you if i fix it

**Comment by lisaraj2009** [comment]
Wait where do i insert the code snippet?

**Comment by NavpreetDevpuri** [comment]
> I think i downloaded the latest commit. Since I may install linux today, I'll get back to you. I think that this doesn't have much compatibility on windows because windows uses '' not '/' :(


m also using windows it works fine.

**Comment by NavpreetDevpuri** [comment]
> Wait where do i insert the code snippet?

`manimlib/scene/scene_file_writer.py` 
You can see this file location at the top of code windows  https://github.com/3b1b/manim/pull/1057/files

**Comment by lisaraj2009** [comment]
i think i fixed it thx.
