### ISSUE TITLE
FileNotFoundError with example_scenes

### ISSUE THREAD

**Issue by KMKay** [3b1b/manim#1089]
### If this is a support request:

**Please attempt to solve the problem on your own before opening an issue.**
Between old issues, StackOverflow, and Google, you should be able to find
solutions to most of the common problems.

Include at least:
1. Steps to reproduce the issue (e.g. the command you ran)
I downloaded all the necessary files and executed this command:
manim example_scenes.py SquareToCircle -p

2. The unexpected behavior that occurred (e.g. error messages or screenshots)
I attached a screenshot of the error message.
The command above does create the partial movie files in this directory:
C:\manim\videos\example_scenes\1440p60\partial_movie_files\SquareToCircle

But from the error message, it seems like the final .mp4 file is not being created in this location:
'C:\\manim\\videos\\example_scenes\\1440p60\\SquareToCircle.mp4'

3. The environment (e.g. operating system and version of manim)
Windows 10
I believe I downloaded the most recent version of manim
Python 3.7

### If this is a feature request:
Include the motivation for making this change.
![Annotation 2020-05-19 181046](https://user-images.githubusercontent.com/43647236/82387235-1cab0600-99fc-11ea-87eb-732d3653994c.jpg)

**Comment by NavpreetDevpuri** [comment]
Download latest version, this error is fixed.
Or manually apply this changes https://github.com/3b1b/manim/pull/1057/files

**Comment by NavpreetDevpuri** [comment]
that one also had same problem https://github.com/3b1b/manim/issues/1081

**Comment by NavpreetDevpuri** [comment]
https://www.google.com/search?q=manim+impossible+to+open

See 1st result contains solution.

**Comment by NavpreetDevpuri** [comment]
We should learn what to search, how to search, how to break big problems into small parts and then how to search those small parts, how to combine those small part's solutions together to solve big problem.

**Comment by KMKay** [comment]
Thank you so much. I solved the problem.
I checked out the first result but your answer (#1081) was much clearer.
Thanks again!
