### ISSUE TITLE
ModuleNotFoundError: No module named 'manimlib.stream_starter'

### ISSUE THREAD

**Issue by amannnnagu** [3b1b/manim#1090]
I am trying to run Manim on a macOS. I was unable to run the example scenes after I initially installed Manim, as there was no module named 'manimlib.stream_starter'. I tried to reinstall Manim numerous times, but it still does not work. Could someone please help!!?

**Comment by Tony031218** [comment]
Are you the one who asked this question on discord. If you solve it, you can close this issue.

**Comment by Ahmed2942** [comment]
I am stuck in this problem, could you tell me how you figured it out?

**Comment by Tony031218** [comment]
Please update your source code to the newest version in this repo. And check the command you run.

**Comment by Ahmed2942** [comment]
Thanks alot, It seems the source code was out of date so I've updated it and now it works fine
