### ISSUE TITLE
Graphing Query

### ISSUE THREAD

**Issue by im-AMS** [3b1b/manim#1092]
Hi,
So I was wondering is there a way to graph a function within a custom range,I mean the function takes the range given in config.
Is there a way to avoid this.
Have a look at this
![CreateGraphfrom0](https://user-images.githubusercontent.com/52029061/82524110-bb924800-9b4b-11ea-946f-2f522ec0b6d4.png)

```python
from manimlib.imports import *
from math import sin, pi

class CreateGraph(GraphScene):
    CONFIG = {
        'x_min' : 0,
        'x_max':2.1*pi,
        "x_tick_frequency": pi/4,
        'y_min': -1.5,
        'y_max':1.5,
        "y_tick_frequency": 0.5,
        'graph_origin': 4*LEFT,
        'axes_color': BLUE
    }

    def construct(self):
        self.setup_axes(animate=True)
        self.wait()

        sine = self.get_graph(lambda x: sin(x), color = WHITE)

        self.play(ShowCreation(sine))
        self.wait(2)
```

So if I use the custom range I can plot sine within a custom range say [0,pi] but I want my x axis to go from [0,2pi].

Is there a way to do this,If not please consider this for the next update its a handy feature.

**Comment by Level-314** [comment]
Yes, it is possible. Modify your code as such:

        sine = self.get_graph(lambda x: sin(x), color = WHITE,
        x_min = 0,
        x_max = 2*pi)

- - - - - - - - - - - - - -
https://www.youtube.com/channel/UCgfJSRv4F86RDx8mDR-rK4Q/

https://level314.com

**Comment by im-AMS** [comment]
Thanks a lot..Im just a noob in both python and manim,just trying to have fun!!!
