### ISSUE TITLE
Graph Ticks

### ISSUE THREAD

**Issue by im-AMS** [3b1b/manim#1093]
I observed something strange when i was graphing.
![CreateGraphfrom0-5](https://user-images.githubusercontent.com/52029061/82524608-082a5300-9b4d-11ea-92fb-191d95728528.png)

Can you notice something strange in the ticks,have a look at the code

```python
from manimlib.imports import *
from math import sin, pi

class CreateGraph(GraphScene):
    CONFIG = {
        'x_min' : -0.5,
        'x_max':2.1*pi,
        "x_tick_frequency": pi/4,
        'y_min': -1.5,
        'y_max':1.5,
        "y_tick_frequency": 0.5,
        'graph_origin': 4*LEFT,
        'axes_color': BLUE
    }

    def construct(self):
        self.setup_axes(animate=True)
        self.wait()

        sine = self.get_graph(lambda x: sin(x), color = WHITE)

        self.play(ShowCreation(sine))
        self.wait(2)
```

I have asked it to give tick frequency of pi/4 (Indirectly asking it to give ticks from origin).
It starts giving ticks from x_min.
Is there a way to avoid this i.e, start ticks from the origin and move towards +x and -x separately
so its behaving as I expected.

How can I achieve this.
If no Please consider this for the following update.

**Comment by Level-314** [comment]
First, to guide you on how to fish. For questions like this the first thing you should do is find the code for the object you are inheriting from. In this case GraphScene. The code for that class can be found in the file: manim\manimlib\scene\graph_scene.py

There you can see a list of all available parameters; one of which is "x_leftmost_tick". Using that you can fix your code as below and get the desired result.

class CreateGraph(GraphScene):
    CONFIG = {
        'x_min' : -0.5,
        'x_max':2.1*pi,
        "x_tick_frequency": pi/4,
        "x_leftmost_tick": pi/4,
        'y_min': -1.5,
        'y_max':1.5,
        "y_tick_frequency": 0.5,
        'graph_origin': 4*LEFT,
        'axes_color': BLUE
    }


- - - - - - - - - - - - - - - - - - -
https://www.youtube.com/channel/UCgfJSRv4F86RDx8mDR-rK4Q/

https://level314.com
