### ISSUE TITLE
Problem with Latex code

### ISSUE THREAD

**Issue by icesonata** [3b1b/manim#1095]
Currently, I'm planning using manim for my project about math inspired by 3Blue1Brown's Linear Algebra on youtube. After I had installed manim, I try to run and figure out how the code in old project of 3b1b works and get stuck in converting TexMobject to dvi. 
```Exception: Latex error converting to dvi. See log output above or the log file: ./media/Tex/1a918a0dd1827c14.log```
Here are two functions of TrackBasisVectorsExample class in an old project [eola](https://github.com/3b1b/manim/blob/master/from_3b1b/old/eola/chapter3.py#L601).
```python
    def write_linear_map_rule(self):
        rule = TexMobject([
            "\\text{Transformed}\\vec{\\textbf{v}}",
            " = %s"%self.v_coord_strings[0],
            "(\\text{Transformed}\\hat{\\imath})",
            "+%s"%self.v_coord_strings[1],
            "(\\text{Transformed}\\hat{\\jmath})",
        ])
```
```python
    def get_v_definition(self):
        v_def = TexMobject([
            "\\vec{\\textbf{v}}",
            " = %s"%self.v_coord_strings[0],
            "\\hat{\\imath}",
            "+%s"%self.v_coord_strings[1],
            "\\hat{\\jmath}",
        ])
```
and here is part of output of log file ```1a918a0dd1827c14.log```:
```
LaTeX Font Info:    Try loading font information for U+msa on input line 24.
(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/umsa.fd
File: umsa.fd 2013/01/14 v3.01 AMS symbols A
) (/usr/share/texlive/texmf-dist/tex/latex/microtype/mt-msa.cfg
File: mt-msa.cfg 2006/02/04 v1.1 microtype config. file: AMS symbols (a) (RS)
)
LaTeX Font Info:    Try loading font information for U+msb on input line 24.
(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/umsb.fd
File: umsb.fd 2013/01/14 v3.01 AMS symbols B
) (/usr/share/texlive/texmf-dist/tex/latex/microtype/mt-msb.cfg
File: mt-msb.cfg 2005/06/01 v1.0 microtype config. file: AMS symbols (b) (RS)
)
LaTeX Font Info:    Try loading font information for U+rsfs on input line 24.
(/usr/share/texlive/texmf-dist/tex/latex/jknapltx/ursfs.fd
File: ursfs.fd 1998/03/24 rsfs font definition file (jk)
)
LaTeX Font Info:    Try loading font information for U+wasy on input line 24.
(/usr/share/texlive/texmf-dist/tex/latex/wasysym/uwasy.fd
File: uwasy.fd 2003/10/30 v2.0 Wasy-2 symbol font definitions
)
! Missing } inserted.
<inserted text> 
                }
l.26 \end{align*}
                  
Here is how much of TeX's memory you used:
 14964 strings out of 492983
 265524 string characters out of 6134921
 335729 words of memory out of 5000000
 18398 multiletter control sequences out of 15000+600000
 534419 words of font info for 40 fonts, out of 8000000 for 9000
 1141 hyphenation exceptions out of 8191
 39i,9n,56p,10423b,275s stack positions out of 5000i,500n,10000p,200000b,80000s

No pages of output.
```
**Environments**
I run manim on Ubuntu 18.04.
I have read some posts in Issues tag and installed texlive package so I think I have enough package to be able to run Latex. There might be some problem with Latex code and I'm new to Latex.
Is there any way to fix this ?

**Comment by Tony031218** [comment]
remove `[` and `]` in TexMobject.

just like:
```python
rule = TexMobject(
    "\\text{Transformed}\\vec{\\textbf{v}}",
    " = %s"%self.v_coord_strings[0],
    "(\\text{Transformed}\\hat{\\imath})",
    "+%s"%self.v_coord_strings[1],
    "(\\text{Transformed}\\hat{\\jmath})",
)
```

**Comment by icesonata** [comment]
@Tony031218 You mean editing it like this:
```python
rule = TexMobject(
    "\\text{Transformed}\\vec{\\textbf{v}}",
    " = %s"%self.v_coord_strings,
    "(\\text{Transformed}\\hat{\\imath})",
    "+%s"%self.v_coord_strings,
    "(\\text{Transformed}\\hat{\\jmath})",
)
```
But how can I get element by index in v_coord_strings ?

**Comment by icesonata** [comment]
@Tony031218 I try your idea and change
```python 
rule = TexMobject(
    "\\text{Transformed}\\vec{\\textbf{v}}",
    " = %s"%self.v_coord_strings,
    "(\\text{Transformed}\\hat{\\imath})",
    "+%s"%self.v_coord_strings,
    "(\\text{Transformed}\\hat{\\jmath})",
)
```
to 
```python
        a = self.v_coord_strings[0] #
        b = self.v_coord_strings[1] #
        rule = TexMobject([
            "\\text{Transformed}\\vec{\\textbf{v}}",
            " = %s"%a,
            "(\\text{Transformed}\\hat{\\imath})",
            "+%s"%b,
            "(\\text{Transformed}\\hat{\\jmath})",
        ])
```
But still get the same error

**Comment by Tony031218** [comment]
no, I mean replace `TexMobject([...])` with `TexMobject(...)`, not remove all of `[..]`
and I gave you the code, don't you see it?

**Comment by Tony031218** [comment]
> @Tony031218 I try your idea and change
> 
> ```python
> rule = TexMobject(
>     "\\text{Transformed}\\vec{\\textbf{v}}",
>     " = %s"%self.v_coord_strings[0],
>     "(\\text{Transformed}\\hat{\\imath})",
>     "+%s"%self.v_coord_strings[1],
>     "(\\text{Transformed}\\hat{\\jmath})",
> )
> ```
> 
> to
> 
> ```python
>         a = self.v_coord_strings[0] #
>         b = self.v_coord_strings[1] #
>         rule = TexMobject([
>             "\\text{Transformed}\\vec{\\textbf{v}}",
>             " = %s"%a,
>             "(\\text{Transformed}\\hat{\\imath})",
>             "+%s"%b,
>             "(\\text{Transformed}\\hat{\\jmath})",
>         ])
> ```
> 
> But still get the same error

Here you still use `TexMobject([ ... ])`, so it get the same error.
TexMobject need to receive some strings not a list.

**Comment by icesonata** [comment]
Thanks a lot, the problem are solved but unfortunately there is another Latex problem pop up at:
```python
        result = TexMobject(self.result_coords_string)
```
have latext converting error while self.result_coords_string is in CONFIG:
```
    CONFIG = {
        "transposed_matrix" : [[1, -2], [3, 0]],
        "v_coords" : [-1, 2],
        "v_coord_strings" : ["-1", "2"],
        "result_coords_string" : """
            =
            \\left[ \\begin{array}{c}
                -1(1) + 2(3) \\\\
                -1(-2) + 2(0)
            \\end{arary}\\right] 
            = 
            \\left[ \\begin{array}{c}
                5 \\\\
                2
            \\end{arary}\\right] 
        """
    }
```

**Comment by icesonata** [comment]
Problem solved, I change the wrong syntax command from ```\end{arary}``` to ```\end{array}``` in and it worked smoothly.
I also recommend trying ```{bmatrix}``` which gives you ```[]``` or ```{pmatrix}``` which gives you ```()``` instead of ```{array}```.
