### ISSUE TITLE
Why do I get an error although the code is very simple?

### ISSUE THREAD

**Issue by sexyzeky** [3b1b/manim#1096]
I don't know what is going wrong. Probably ı changed something without my aware. Here is my simple code:

```
class KaraTahta(Scene):
    def construct(self):
        a = Circle()
        self.play(ShowCreation(a))        
        self.wait()
```
And ı get this error:

> Traceback (most recent call last):
>   File "D:\Manim\manim 11.11.2019\manimlib\extract_scene.py", line 155, in main
>     scene = SceneClass(**scene_kwargs)
>   File "D:\Manim\manim 11.11.2019\manimlib\scene\scene.py", line 53, in __init__
>     self.construct()
>   File "DenemeTahtası.py", line 873, in construct
>     self.wait()
>   File "D:\Manim\manim 11.11.2019\manimlib\scene\scene.py", line 406, in wrapper
>     func(self, *args, **kwargs)
>   File "D:\Manim\manim 11.11.2019\manimlib\scene\scene.py", line 517, in wait
>     self.update_frame()
>   File "D:\Manim\manim 11.11.2019\manimlib\scene\scene.py", line 140, in update_frame
>     self.capture_mobjects_in_camera(mobjects, **kwargs)
>   File "D:\Manim\manim 11.11.2019\manimlib\scene\scene.py", line 118, in capture_mobjects_in_camera
>     self.camera.capture_mobjects(mobjects, **kwargs)
>   File "D:\Manim\manim 11.11.2019\manimlib\camera\camera.py", line 269, in capture_mobjects
>     func(batch, self.pixel_array)
>   File "D:\Manim\manim 11.11.2019\manimlib\camera\camera.py", line 317, in display_multiple_vectorized_mobjects
>     self.display_multiple_non_background_colored_vmobjects(batch, pixel_array)
>   File "D:\Manim\manim 11.11.2019\manimlib\camera\camera.py", line 322, in display_multiple_non_background_colored_vmobjects
>     self.display_vectorized(vmobject, ctx)
>   File "D:\Manim\manim 11.11.2019\manimlib\camera\camera.py", line 325, in display_vectorized
>     self.set_cairo_context_path(ctx, vmobject)
>   File "D:\Manim\manim 11.11.2019\manimlib\camera\camera.py", line 341, in set_cairo_context_path
>     subpaths = vmobject.get_subpaths_from_points(points)
>   File "D:\Manim\manim 11.11.2019\manimlib\mobject\types\vectorized_mobject.py", line 623, in get_subpaths_from_points
>     range(nppcc, len(points), nppcc)
> TypeError: 'NoneType' object cannot be interpreted as an integer

How can I fix it?

**Comment by Tony031218** [comment]
Maybe you accidentally changed some source code.
You'd better replace your manim folder to the latest.
And it is best to ensure that there are no space characters in the path.

**Comment by sexyzeky** [comment]
Ahh.. Okay...
