### ISSUE TITLE
Help,How to create a collection

### ISSUE THREAD

**Issue by heguohui2018** [3b1b/manim#1097]
math_text_1 = TexMobject()
How to create a collection,This collection contains：a ，b，c，d

Can it be like this：
A={a,b,c,d}

**Comment by Tony031218** [comment]
```python
text = TexMobject("abcd")
```
then `text[0][0]` is 'a', `text[0][1]` is 'b', `text[0][2]` is 'c' and `text[0][3]` is 'd'.

Or.
```python
text = TexMobject("a", "b", "c", "d")
```
then `text[0]` is 'a', `text[1]` is 'b', `text[2]` is 'c'.

I have a tutorial of this, here are the links: [on bilibili](https://www.bilibili.com/video/BV1CC4y1H7kp) or [on YouTube](https://youtu.be/XYgNyjKU0Es)

**Comment by heguohui2018** [comment]
my code
mtext_1 = TexMobject("A","=","{","a","b","c","d","e","f","}")

result
<img width="315" alt="截屏2020-05-23 20 04 03" src="https://user-images.githubusercontent.com/35359288/82730383-b0007600-9d31-11ea-8c2c-ac616ece066d.png">

but：Missing "{}"braces,Can not be displayed

**Comment by Level-314** [comment]
https://artofproblemsolving.com/wiki/index.php/LaTeX:Symbols

**Comment by Tony031218** [comment]
sorry, I misunderstood you. use "\{" and "\}" instead of "{" and "}".

**Comment by heguohui2018** [comment]
Thank You very much
![Uploading 截屏2020-05-23 20.52.11.png…]()

**Comment by Tony031218** [comment]
You're welcome, and you can close this issue.:)
