### ISSUE TITLE
Latex error converting to dvi.

### ISSUE THREAD

**Issue by joda2802** [3b1b/manim#110]
Hello, I'm using ubuntu 17.04. Whenever I try "sudo python extract_scene.py -p example_scenes.py WriteStuff", the error  "Latex error converting to dvi." occurs. Can anybody help me with that issue?

**Comment by maoshunyu** [comment]
Me too!!!!!
I'm using Windows 10 64bits.I've spent two hours trying to using it.
I've tried #36 but it still can't work one my computer.Can anybody help me???

**Comment by eulertour** [comment]
Closing, as this issue is inactive and the solution seems to be in one of #36, #64, and #124.
