### ISSUE TITLE
Why "Mobject.get_merged_array()" function is called twice? Is it by intention?

### ISSUE THREAD

**Issue by mjmjmtl** [3b1b/manim#1103]
I just notice that the get_merged_array() function is called twice during the recursion (see line 701 and 704 below). Is line 704 redundant?
![image](https://user-images.githubusercontent.com/39451663/82782620-96366000-9e11-11ea-88b7-aac543775a73.png)
See source code here: https://github.com/3b1b/manim/blob/master/manimlib/mobject/mobject.py#L704

**Comment by andre-caldas** [comment]
I had made a patch some days ago. Patch #1123.

I also think it is redundant. The result is not attributed anywhere, but the function has no "side-effects" (it does not change anything).

**Comment by mjmjmtl** [comment]
Glad to hear that. Thanks @andre-caldas

**Comment by Tony031218** [comment]
Fixed in #1043
