### ISSUE TITLE
Unscale arrow thickness and tip

### ISSUE THREAD

**Issue by stevenschn** [3b1b/manim#1104]
I use `arrows` in a video about coordinates. Now the arrows will scale automatically, depending on their length. Both the `thickness/width` and the `tip` will be larger as the length of the arrow is larger.

Now I do not want this. But I can not find anything in the `manlib` that tells me whether I can disable this automatic scaling. I would like to have a certain tipsize and thickness of the line, no matter how long the arrow will be.

Any suggestions?

**Comment by Tony031218** [comment]
Try to use `Line()` and use method `.add_tip(...)` to create a tip like arrow.

**Comment by stevenschn** [comment]
That works perfectly. Thank you! I'll close this thread.
