### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'example_scene.py'

### ISSUE THREAD

**Issue by anasbekheit** [3b1b/manim#1107]
![Capture](https://user-images.githubusercontent.com/61153587/82950722-1988ba80-9fa6-11ea-9ffd-2f7a5a2174ca.PNG)

**Comment by node-rookie** [comment]
I have the same problem, solved by adding LaTex to the environment variable

**Comment by TonyCrane** [comment]
> I have the same problem, solved by adding LaTex to the environment variable

Please see clearly which file cannot be found in the error message. This is not the same problem as yours.
This problem is just because example_scenes.py was not downloaded or entered into the corresponding directory.
