### ISSUE TITLE
GraphScene range config

### ISSUE THREAD

**Issue by DaliborCimr** [3b1b/manim#1109]
I need to draw data with specific range on **y** axis.
Here is my CONFIG for GraphScene:
        "x_min": 0,
        "x_max": 150,
        "x_axis_width": 20,
        "x_axis_label": "$t$",
        "y_min": 50,
        "y_max": 95,
        "y_axis_height": 11,
        "y_axis_label": "$HR$",

but here is draw result:
![image](https://user-images.githubusercontent.com/30354208/83062542-20273880-a05f-11ea-8663-e4cc5cced0c6.png)

so range is from 0 to 45 and data are draw off the camera.

**Comment by Level-314** [comment]
Can you post code that will generate the scene that is in error? (i.e. a complete class derived from Scene or GraphScene which will create the bug.)

**Comment by DaliborCimr** [comment]
`class PlotFunctions(GraphScene):
    CONFIG = {
        "x_min": 0,
        "x_max": 150,
        "x_axis_width": 20,
        "x_axis_label": "$t$",
        "y_min": 50,
        "y_max": 95,
        "y_axis_height": 11,
        "y_axis_label": "$HR$",
        "graph_origin": 4.5 * DOWN + 9 * LEFT,
        "function_color": RED,
        "axes_color": GREEN,
        "x_labeled_nums": range(0, 150, 5),
        "y_labeled_nums": range(50, 95, 5),

    }

    def construct(self):
        self.setup_axes(animate=True)

        values = np.asarray([55,70,60,70])
        for i in np.arange(0, len(values), 1):
            point = Dot(radius=0.04)
            if (values[i] > 0):
                coords = self.coords_to_point(i + 1, values[i])
                point.move_to([coords[0], coords[1], 0])
                self.play(ShowCreation(point))
                #self.add(point)`

There was first problem "y_labeled_nums": range(50, 95, 5), where first value was 0 instead of 50 but still, range not start on 50 on y axis. So is it some option to start by y_min and not from 0?

**Comment by Level-314** [comment]
The code you copied has a number of issues, including the formatting. In the future, try copying the block of code that s needed (including spacing and tabs), highlighting the block in the comment window, and enclosing it in code tags using the <> icon.

I cleaned it up a bit and fixed some issues and this was the result.

![image](https://user-images.githubusercontent.com/63604621/83264800-a2624a80-a18e-11ea-9ea2-5b6ba75feb0b.png)

Here is the code:

```python
from manimlib.imports import *

class PlotFunctions(GraphScene):
    CONFIG = { "x_min": 0, "x_max": 150
              # , "x_axis_width": 20
              , "x_axis_label": "$t$"
              , "y_min": 50, "y_max": 100
              # , "y_axis_height": 11
              , "y_axis_label": "$HR$"
              # , "graph_origin": 4.5 * DOWN + 9 * LEFT
              , "function_color": RED, "axes_color": GREEN
              , "x_labeled_nums": range(0, 150, 10)
              , "y_labeled_nums": range(50, 100, 10)
              , "x_tick_frequency": 5
              , "y_tick_frequency": 5}
    
    def construct(self):
        self.setup_axes(animate=True)
        values = np.asarray([55,70,60,70])
        for i in np.arange(0, len(values), 1):
            point = Dot(radius=0.04)
            if (values[i] > 0):
                coords = self.coords_to_point(i + 1, values[i])
                point.move_to([coords[0], coords[1], 0])
                self.play(ShowCreation(point))
                #self.add(point)
```

- - - - - - - - - - - - - - - - - - -

https://www.youtube.com/channel/UCgfJSRv4F86RDx8mDR-rK4Q/

https://level314.com

**Comment by Level-314** [comment]
ps: I just realized that my code may have worked better than yours because I have a customized version of manimlib files where I have modified some of the classes. If my code above didn't work for you, let me know and I will send the change you need to make when I get back home.

**Comment by DaliborCimr** [comment]
![image](https://user-images.githubusercontent.com/30354208/83328728-7d9cce80-a285-11ea-8253-7fb0737c5562.png)

This is the result so you are right that there is some need of code modification out of main python file

**Comment by Level-314** [comment]
Sorry I'm out of the house a bit this weekend. I'll give you just the section you need.

Open the file [manimdir]/manimlib/scene/graph_scene.py

In the function class GraphScene, method setup_axes you need to make the following change (the commented code is the original code if you want to search for it, the other code is my modification):

```python
        # Level314 modification 22/03/2020
        # y_axis.shift(self.graph_origin - y_axis.number_to_point(0))
        # y_axis.rotate(np.pi / 2, about_point=y_axis.number_to_point(0))
        y_axis.shift(self.graph_origin - y_axis.number_to_point(self.y_bottom_tick))
        y_axis.rotate(np.pi / 2, about_point=y_axis.number_to_point(self.y_bottom_tick))
        # EOM
```

Let me know if you have questions. I'll do my best to answer from the road.

- - - - - - - - - - - - - - - - - - -

https://www.youtube.com/channel/UCgfJSRv4F86RDx8mDR-rK4Q/

https://level314.com

**Comment by DaliborCimr** [comment]
Thanks for everything, now it works so closing issue
