### ISSUE TITLE
SVG rendered inaccurately

### ISSUE THREAD

**Issue by mjmjmtl-pony** [3b1b/manim#1113]
I just found that the svg file is not rendered accurately in manim. For example, this is the svg file:
[afed61182cb6d368.svg.zip](https://github.com/3b1b/manim/files/4706549/afed61182cb6d368.svg.zip)

Ideally it should be rendered like this (note that the curve is quite smooth):
![image](https://user-images.githubusercontent.com/42982445/83339222-88a13000-a280-11ea-8bae-79731e2b3f5c.png)

But in manim, it's rendered like this:
![image](https://user-images.githubusercontent.com/42982445/83339235-9c4c9680-a280-11ea-8b6f-5cbcc8fe12ed.png)

You can reproduce it using following codes:
<pre>
from manimlib.imports import *

class ProblemDescription(Scene):
    def construct(self):
        self.add(SVGMobject('/path/to/that_svg_file'))
</pre>

Does anybody have any ideas about this?

**Comment by yoshiask** [comment]
I suspect this is a product of how manim handles smoothing. It looks like Manim is moving the handles of the curves closet to the anchors, which makes the shape less round
