### ISSUE TITLE
TextMobject text in manim goes beyond the screen instead of wrapping around.

### ISSUE THREAD

**Issue by baljeetrathi** [3b1b/manim#1115]
Hi,

I have been facing this issue for some time now. When there is very long text inside a `TextMobject`. Manim does not wrap it into the next line at the right place. Here is an example:

```
TextMobject(r"This is a very long line of text. When I render it as an animation using manim, it breaks at unexpected points on the(1) screen. So, some text overflows out of the visible(2) area.", color="#C62828")
```

For the above `TextMobject`, manim will wrap the text into a new line at point (2). Ideally, it should have moved on to the next line at point (1). All the text after point (1) up to (2) stays on line 1 but it is invisible because it is rendered outside the visible area.

How can I force Manim to properly wrap text into multiple lines at the correct points?

**Comment by Tony031218** [comment]
Manim uses LaTeX to render TextMobject, so it will not automatically wrap based on the size of manim's frame.

If you want to make sure to wrap at the position you want, you can use \\ (LaTeX syntax) in the TextMobject string to manually wrap, like:
`TextMobject(r"a\\b")`, `TextMobject("a\\\\b")`
```python
TextMobject(r"This is a very long line of text. When I render it as an animation using manim, it breaks at unexpected points on the \\ (1) screen. So, some text overflows out of the visible \\ (2) area.", color="#C62828")
```

But using VGroup to wrap the TextMobject of each line may be a better choice, which can easily adjust the alignment and spacing between lines:
```python
text = VGroup(
    TextMobject("line 1"),
    TextMobject("this is line 2"),
    TextMobject("and this is line 3"),
).arrange(DOWN, aligned_edge=LEFT, buff=0.1)
```

**Comment by baljeetrathi** [comment]
Thanks @Tony031218 :)
