### ISSUE TITLE
Invalid syntax Manim

### ISSUE THREAD

**Issue by PackSciences** [3b1b/manim#1118]
Hello,

I use Python 3.5.3 on Windows. (with `python --version`)
I have installed the requirements successfully.
I have a path setup such that it is `python` and not `python3` to type a command. I have downloaded manimlib through pip successfully.
Then when I type:

`python -m manim example_scenes.py SquareToCircle -p`

(python3 instead just does nothing)

And here is the error message:

> Traceback (most recent call last):
>
>File "C:\Miniconda3\lib\runpy.py", line 193, in _run_module_as_main
>  "__main__", mod_spec)
>
>File "C:\Miniconda3\lib\runpy.py", line 85, in _run_code
>  exec(code, run_globals)
>
>File "C:\Users\X\manim-master\manim-master\manim.py", line 2, in <module>
>    import manimlib
>
>File "C:\Users\X\manim-master\manim-master\manimlib\__init__.py", line 2, in <module>
    import manimlib.config
>
>File "C:\Users\X\manim-master\manim-master\manimlib\config.py", line 144
    print(f"Failed to render scene: {str(e)}")
>
>                                            ^
>
>SyntaxError: invalid syntax

I use Miniconda3 but it doesn't seem to be the problem here.

Could someone please indicate to me where is the error from?

**Comment by Tony031218** [comment]
f-string is only included in python3.6 and above, so the python version of manim you should be above 3.6

**Comment by PackSciences** [comment]
Ah thank you Tony031218, after re-reading the readme I missed that part. Thank you for pointing it out. I'll close the issue if that worked out.

**Comment by PackSciences** [comment]
It did fixed the issue but I got a different error so I'll open another ticket.
