### ISSUE TITLE
Fading Animation for the opacity of a VMobject

### ISSUE THREAD

**Issue by 21Manu09** [3b1b/manim#1131]
Hi,

i want to change the opacity of a VMobject with an animation and don't know how to manage this.
Does anybody know a solution for my problem?

Thank you in advance for your time and valuable help.

**Comment by Tony031218** [comment]
```python
self.play(ApplyMethod(mob.set_opacity, <opacity>))
# or
self.play(mob.set_opacity, <opacity>)
```
Or
```python
self.play(ApplyMethod(mob.fade, <darkness>))
# or
self.play(mob.fade, <darkness>)
```

**Comment by 21Manu09** [comment]
Thanks a lot!

I already tried your first described solution yesterday, but made another mistake and so i thought it doesn't work.
