### ISSUE TITLE
I do every step but when run the example file get an error

### ISSUE THREAD

**Issue by MohammedAlbaqerH** [3b1b/manim#1136]
I do every step in the readme file and install it as conda environment but when I run:
`python3 -m manim example_scenes.py SquareToCircle -pl
`get this error:
`ModuleNotFoundError: No module named 'pygments'`

this my conda envirnomant info
**name: manim
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2020.1.1=0
  - cairo=1.14.12=h8948797_3
  - certifi=2020.4.5.1=py37_0
  - colour=0.1.5=py37_0
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.9.1=h8a8886c_1
  - glib=2.63.1=h3eb4bd4_1
  - graphite2=1.3.13=h23475e2_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=he6710b0_3
  - intel-openmp=2019.4=243
  - jasper=2.0.14=h07fcdf6_1
  - jpeg=9b=h024ee3a_2
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.3=he6710b0_1
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.10=he19cac6_1
  - lz4-c=1.9.2=he6710b0_0
  - mkl=2018.0.3=1
  - mkl_fft=1.0.6=py37h7dd41cf_0
  - mkl_random=1.0.1=py37h4414c95_1
  - ncurses=6.2=he6710b0_1
  - numpy=1.15.0=py37h1b885b7_0
  - numpy-base=1.15.0=py37h3dfced4_0
  - olefile=0.46=py37_0
  - opencv=3.4.2=py37h6fd60c2_1
  - openssl=1.1.1g=h7b6447c_0
  - pcre=8.43=he6710b0_0
  - pillow=5.2.0=py37heded4f4_0
  - pip=20.0.2=py37_3
  - pixman=0.38.0=h7b6447c_0
  - py-opencv=3.4.2=py37hb342d67_1
  - pycairo=1.18.0=py37h2a1e443_0
  - pydub=0.23.0=py_0
  - python=3.7.7=hcff3b4d_5
  - readline=8.0=h7b6447c_0
  - scipy=1.1.0=py37hc49cb51_0
  - setuptools=47.1.1=py37_0
  - sqlite=3.31.1=h62c20be_1
  - tbb=2020.0=hfd86e86_0
  - tbb4py=2020.0=py37hfd86e86_0
  - tk=8.6.8=hbc83047_0
  - tqdm=4.24.0=py37_0
  - wheel=0.34.2=py37_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.4=h0b5b093_3
  - pip:
    - manimlib==0.1.12.dev3
    - pyreadline==2.1
prefix: /home/baqer/anaconda3/envs/manim**

**Comment by Tony031218** [comment]
`pip install pygments`
now, manim need pygments to display highlighted code for code_mobject.py

**Comment by MohammedAlbaqerH** [comment]
Thank you it is work, actually, I try to install pygments using `sudo apt-get install python-pygments` but it didn't work, but it is work with `pip install pygments`
