### ISSUE TITLE
Manimlib.stream_starter

### ISSUE THREAD

**Issue by Ashraful7525** [3b1b/manim#1148]
When i wan't to play the animation named examle_scenes ,it shows,
 import manimlib.stream_starter
ModuleNotFoundError: No module named 'manimlib.stream_starter'
SO, what can i do for manimlib.stream_starter????

**Comment by Tony031218** [comment]
What's your code and the command you run.

stream mode is no longer supported, so there is no reason to need the stream_starter module.

**Comment by Ashraful7525** [comment]
> What's your code and the command you run.
> 
> stream mode is no longer supported, so there is no reason to need the stream_starter module.

**Comment by Ashraful7525** [comment]
N

> What's your code and the command you run.
> 
> stream mode is no longer supported, so there is no reason to need the stream_starter module.

I used the following command:
Python -m manim example_scenes.py SquareToCircle -pl

**Comment by Tony031218** [comment]
Are you using the latest source code? That can't be wrong.
