### ISSUE TITLE
Link to ManimCommunity is needed in Readme

### ISSUE THREAD

**Issue by cobordism** [3b1b/manim#1157]
It seems many people are futzing around with this code trying to make their own videos and stumbling over the idiosyncrasies of this code.

There should be a prominent link to https://github.com/ManimCommunity/manim in the Readme file so that people know to look there instead.

**Comment by huguesdevimeux** [comment]
I completly agree but I think this is too soon.
ManimCommunity is not ready yet.

**Comment by co-bordism** [comment]
>  but I think this is too soon.

perhaps, but it already would have saved me months of futzing around with code the community was already cleaning up / refactoring.

**Comment by gargVader** [comment]
Link to the discord group would be fine

**Comment by huguesdevimeux** [comment]
There is already a link to the discord :)

**Comment by cobordism** [comment]
May I suggest putting a link in the README? It took me 6 months to find the discord and to find out about the existence of ManimCommunity.

How about replacing:

> Manim is an animation engine for explanatory math videos. It's used to create precise animations programmatically, as seen in the videos at 3Blue1Brown.


With:

> Manim is an animation engine for explanatory math videos. It's used to create precise animations programmatically, as seen in the videos at 3Blue1Brown.
>     
> This repository contains the version of manim used by 3Blue1Brown. There is also a community maintained version at https://github.com/ManimCommunity/manim/. 
> To get help or to join the development effort, please join the discord (https://discord.gg/mMRrZQW).
>

**Comment by Tony031218** [comment]
![image](https://user-images.githubusercontent.com/44120331/87033277-808dc600-c218-11ea-8d2d-11df8da9d6dd.png)

**Comment by cobordism** [comment]
I know. right next to the license and the travis checks. 
completely invisible to most humans!

**Comment by cobordism** [comment]
Or put the reference at the bottom in the "Contributing" section.. but that button shown above is invisible

**Comment by huguesdevimeux** [comment]
> Or put the reference at the bottom in the "Contributing" section..

This is a good idea !

**Comment by eulertour** [comment]
This should be fixed by 9174ec3.
