### ISSUE TITLE
Binomial distribution toy animation

### ISSUE THREAD

**Issue by pedroslrey** [3b1b/manim#1162]
Hi! I would like to animate a "galton board" (see the image below),  but I didn't find any tutorial or implementation of gravity.

![binomial_distribution_toy](https://user-images.githubusercontent.com/53320122/87078386-ecf9cc80-c1fa-11ea-86c1-8e1180bff71f.png)

Thanks in advance.

**Comment by pedroslrey** [comment]
I could do it using some caluclations.

**Comment by Tony031218** [comment]
See: https://github.com/3b1b/manim/pull/818 and https://www.bilibili.com/video/av78234079?t=50
