### ISSUE TITLE
[Hiring] Need  help creating animation

### ISSUE THREAD

**Issue by OGALI** [3b1b/manim#1167]
Hello, 

I have a simple project which requires a simple animation and though manim would be perfect. Since there is a time contraint, I won't be able to create an animation. Would anyone be willing to for hire?

**Comment by Lemmih** [comment]
I would be interested as long as I can use reanimate: https://github.com/reanimate/reanimate#readme
View my profile to find my email address.

**Comment by tshrpl** [comment]
@OGALI 
I think this kind of discussion is unfit for this place. Reddit or freelancing websites like fiver are your best options to get programmers to hire.

**Please don't create issues for topics not related to manim codebase**

**Comment by SkyCo** [comment]
This YouTuber [Theorem of Beethoven](https://www.youtube.com/channel/UCxiWCEdx7aY88bSEUgLOC6A) maybe help you to create a series of animations. You can watch his/her the lastest video [Projects, Freelance work and some problems](https://www.youtube.com/watch?v=dPHCOPcDf9c).
