### ISSUE TITLE
repeatedly failing to install manim

### ISSUE THREAD

**Issue by nikolaydonin** [3b1b/manim#1174]
I'm trying to install Manim on an Oracle VM machine. The guest system is Lubuntu 20.04, host and guest don't have any shared folders or anything like that. Host system ist Win10, but I don't do anything in windows.
I have reproduced this issue on version 19.10 and 20.04 multiple times each. I always used the tutorial made by theory of beethoven.
1. I can't install python3.7-minimal, apt and apt-get seem to not find this package, so I googled and added another repository and then install python3.7.8
2. When getting pip It gives the note "Defaulting to user installation because normal site-packages is not writeable", an Error message "ERROR: launchpadlib 1.10.13 requires testresources, which is not installed" and several warnings about being not on PATH
3. When installing pyreadline and pydub: "Defaulting to user installation because normal site-packages is not writeable"

After executing all the commands shown in the video and executing the example manim-command, Manim produces an error stating "ImportError: cannot import name '_imaging'"... 
![VirtualBox_lubuntuformanim-Klon_17_07_2020_06_32_24](https://user-images.githubusercontent.com/68412550/87748839-54b1a800-c7f7-11ea-8e94-c827db28c944.png)

**Comment by gargVader** [comment]
Check it out. https://github.com/gargVader/Manim-Tutorial#using-virtual-box . All the dependencies are pre-installed so that you are directly use manim.

**Comment by nikolaydonin** [comment]
thx a lot, but still: whats the cause for my problem?
