### ISSUE TITLE
Working with hypotenuses in triangles.

### ISSUE THREAD

**Issue by NoobAtManim** [3b1b/manim#1179]
Hi there. I am trying to uses braces to label the 3 sides of a 3, 4, 5 triangle. The vertical and horizontal lines are easy to brace. However, I don't know how I can brace the hypotenuse accurately. My code says:
`triangle = Polygon((-2, -1.5, 0), (2, -1.5, 0), (2, 1.5, 0))`
`braceonhypotenuse = Brace(triangle, ?)`
The ? is because I don't know which direction to write to make sure I brace the hypotenuse accurately. If you have any code or links that could help me, that would be greatly appreciated. Thanks :)

**Comment by anil100391** [comment]
The second "direction" keyword argument is just a numpy array representing a direction vector. All the commonly used manim constants are the same too. You can find the definitions of these constants in constant.py
`UP = np.array((0., 1., 0.))
DOWN = np.array((0., -1., 0.))
RIGHT = np.array((1., 0., 0.))
LEFT = np.array((-1., 0., 0.))`

So what i wanted to say is you can pass a custom direction too. In your case the direction should align with the way your hypotenuse is oriented. Give below a try.
`        braceonhypotenuse = Brace(triangle, np.array((-3, 4, 0)))`

**Comment by NoobAtManim** [comment]
Ah thanks for the help.
