### ISSUE TITLE
Latex error converting to dvi

### ISSUE THREAD

**Issue by popohet** [3b1b/manim#1196]
I am sorry to be posting this issue (because there are many threads about it) but I couldn't find any solution.
The issue doesn't happen if I remove the "á". I have installed it follwing [this](https://www.youtube.com/watch?v=ZltiKHFWmv8) instructions. What I have tried: everything I could find in the other issues. I have uninstalled MikTex and reinstalled 3 times, I spent 5 hours installing full texlive (after uninstalling MikTex). My python version is 3.7.3

What happen: when I try to execute the following code:
```
 class Texto(Scene):
    def construct(self):
        text = TextMobject("Matemática")
        self.add(text)
        self.wait(5)
```

```Traceback (most recent call last):
  File "c:\Manim\manimlib\extract_scene.py", line 153, in main
    scene = SceneClass(**scene_kwargs)
  File "c:\Manim\manimlib\scene\scene.py", line 54, in __init__
    self.construct()
  File "example_scenes.py", line 29, in construct
    text = TextMobject("Matemática")
  File "c:\Manim\manimlib\mobject\svg\tex_mobject.py", line 144, in __init__
    self, self.arg_separator.join(tex_strings), **kwargs
  File "c:\Manim\manimlib\mobject\svg\tex_mobject.py", line 45, in __init__
    self.template_tex_file_body
  File "c:\Manim\manimlib\utils\tex_file_writing.py", line 19, in tex_to_svg_file
    dvi_file = tex_to_dvi(tex_file)
  File "c:\Manim\manimlib\utils\tex_file_writing.py", line 67, in tex_to_dvi
    "See log output above or the log file: %s" % log_file)
Exception: Latex error converting to dvi. See log output above or the log file: c:\Manim\manimlib\files\Tex\f898e0963e234790.log
```

This is my tex_template.tex file:

```
\documentclass[preview]{standalone}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{dsfont}
\usepackage{setspace}
\usepackage{tipa}
\usepackage{relsize}
\usepackage{textcomp}
\usepackage{mathrsfs}
\usepackage{calligra}
\usepackage{wasysym}
\usepackage{ragged2e}
\usepackage{physics}
\usepackage{xcolor}
\usepackage{microtype}
\DisableLigatures{encoding = *, family = * }
%\usepackage[UTF8]{ctex}
\linespread{1}

\begin{document}

YourTextHere

\end{document}
```

PS: I am not new to coding

**Comment by Tony031218** [comment]
have you changed `TEX_USE_CTEX` in `constants.py` to `True`?

**Comment by popohet** [comment]
> have you changed `TEX_USE_CTEX` in `constants.py` to `True`?

Thank you for answering. Yes, I did. And then I get this error instead: ``` Exception: Xelatex error converting to xdv. See log output above or the log file: c:\Manim\manimlib\files\Tex\0c41808cc715cd39.log ```

I couldn't find anything useful in the logs, btw.

**Comment by Tony031218** [comment]
Then try #1187

**Comment by popohet** [comment]
> Then try #1187

I tried. Now I get this error: ```Sorry, but miktex-maketfm did not succeed.

The log file hopefully contains the information to get MiKTeX going again```

The log file:  No creation rule for font OT:script=hani;language=dflt;.

**Comment by Tony031218** [comment]
I installed texlive-full, which maybe full enough to avoid many strange Tex errors.
So if you have enough time, try uninstalling MiKTeX and then install TeXLive-full.

**Comment by popohet** [comment]
> I installed texlive-full, which maybe full enough to avoid many strange Tex errors.
> So if you have enough time, try uninstalling MiKTeX and then install TeXLive-full.

Thanks for answering again. I already have TexLive-full installed, it took me 5 hours yesterday and I ran the code with MiKTeX uninstalled. But I installed it again, so now I have MiKTeX and TexLive, do you think uninstalling MiKTeX may help ?

**Comment by popohet** [comment]
How I solved it:

It turns out I was using an old version of manim (this may be your problem too). Installing the new one fixed it.
