### ISSUE TITLE
How to make the object follow the other one?

### ISSUE THREAD

**Issue by ToBY1206** [3b1b/manim#1201]
I recently signed up GitHub and started to learn Manim. 

I learned the use of 
`object.next_to(Reference, , )`
or 
`object.move_to(Reference, , )`
to set the relative position of the object.

But, I couldn't make the object follow the other one in every time.

More specifically, as shown in the following figure, I do wanted to make the tex "\\alpha = {\\pi\\over 4}" follow the tip of the yellowish arrow and rotate together, but I failed to code using them. I also thought of using _ReplaceTransform_ function, but it cannot make the tex have a circular motion along the movement of the tip of the arrow. So, unfortunately, I stucked.

![image](https://user-images.githubusercontent.com/69422473/89732075-31d98300-da87-11ea-8a58-d4bd14ae3a9a.png)

<When the arrow moves, I want to make the text follow along the tip of the arrow(or the dot).>

![image](https://user-images.githubusercontent.com/69422473/89732108-811fb380-da87-11ea-80e1-ecc2db2f4f0a.png)

Is there another order(or a function) to make it? Thanks for giving help on this issue.

**Comment by Tony031218** [comment]
See the last example scene in `example_scenes.py`

You can use updater function to achieve this, such as `a.add_updater(lambda m: m.next_to(b, ...))`, then the updater function `lambda m: m.next_to(b, ...)` will be called every frame, so `a` will next to `b` all the time.

And if you don’t want to use a updater function or you don’t want them still be together, `MaintainPositionRelativeTo` maybe a better choice, here is an example: https://manim.ml/animation/update.html#maintainpositionrelativeto

**Comment by ToBY1206** [comment]
That helped very much! I finally solved the issue. Thanks so much ;D
