### ISSUE TITLE
Latex error converting to dvi. See log output above or the log file: media/Tex/4475e3a270ecfb06.log 

### ISSUE THREAD

**Issue by atheistrepublic** [3b1b/manim#1202]
Hi there i am trying to write something on the screen but it gives an error like 
 **Exception: Latex error converting to dvi. See log output above or the log file:media/Tex/4475e3a270ecfb06.log**
Everything else is working fine for example animations are working fine but not able to write on the screen.
Also **_there is no .log file_** in the mentioned folder .I am attaching the screenshot so that the error can be seen and also that there is no .log file there but only .tex file.How can i fix this?
![Screenshot (5261)](https://user-images.githubusercontent.com/58817288/89992531-04692100-dca3-11ea-98ed-52a4e21c6a21.png)

**Comment by pvjosue** [comment]
Hi, I get this kind of errors when I write some LaTeX text wrong, try changing your text until you get it write.
This notation works for me
`TextMobject(r"$P(\Omega)$")`
