### ISSUE TITLE
python3 -m pip install -r requirements.txt not working

### ISSUE THREAD

**Issue by BearJere** [3b1b/manim#1205]
This is on Mac OS Catalina.
Typing python3 -m pip install -r requirements.txt in the correct directory brings
``Collecting argparse==1.4.0
  Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Collecting colour==0.1.5
  Using cached colour-0.1.5-py2.py3-none-any.whl (23 kB)
Collecting numpy==1.15.0
  Using cached numpy-1.15.0.zip (4.5 MB)
Collecting Pillow==5.2.0
  Using cached Pillow-5.2.0.tar.gz (14.5 MB)
Collecting progressbar==2.5
  Using cached progressbar-2.5.tar.gz (10 kB)
Collecting scipy==1.1.0
  Using cached scipy-1.1.0.tar.gz (15.6 MB)
Collecting tqdm==4.24.0
  Using cached tqdm-4.24.0-py2.py3-none-any.whl (43 kB)
ERROR: Could not find a version that satisfies the requirement opencv-python==3.4.2.17 (from -r requirements.txt (line 8)) (from versions: 3.4.8.29, 3.4.9.31, 3.4.9.33, 3.4.10.35, 3.4.10.37, 3.4.11.39, 3.4.11.41, 4.1.2.30, 4.2.0.32, 4.2.0.34, 4.3.0.36, 4.3.0.38, 4.4.0.40, 4.4.0.42)
ERROR: No matching distribution found for opencv-python==3.4.2.17 (from -r requirements.txt (line 8))``
How do I fix the error?

**Comment by SkyCo** [comment]
This error may be caused by the following information.
```
ERROR: Could not find a version that satisfies the requirement opencv-python==3.4.2.17 (from -r requirements.txt (line 8)) (from versions: 3.4.8.29, 3.4.9.31, 3.4.9.33, 3.4.10.35, 3.4.10.37, 3.4.11.39, 3.4.11.41, 4.1.2.30, 4.2.0.32, 4.2.0.34, 4.3.0.36, 4.3.0.38, 4.4.0.40, 4.4.0.42) 
ERROR: No matching distribution found for opencv-python==3.4.2.17 (from -r requirements.txt (line 8))
```
So we need to install a specific `opencv-python` version manually. 

> `pip3 install opencv-python==4.3.0.36`

Have a try!

**Comment by BearJere** [comment]
I tried that, it gives the same error.

**Comment by BearJere** [comment]
I fixed it by changing the requirements.txt to opencv-python==4.3.0.36.
