### ISSUE TITLE
Manim can't find my png file

### ISSUE THREAD

**Issue by rdownieMath** [3b1b/manim#1206]
I'm new to coding and am trying to learn manim, which I'm using on my macbook pro. I'm trying to create a scene where manim draws a png file I saved. I saved the png file as "shirt.png" in my manim folder. I then ran the following code:

```
from manimlib.imports import *

class OutFit(Scene):
	def construct(self):
		
		shirt = ImageMobject("shirt")
		
		self.play(Write(shirt))
```
I've looked up several ways of how to get manim to do images and some solutions, but since I'm pretty new at this I don't always understand the answers I've found from other people's issues or if it applies to mine. I keep getting this error response:

raise IOError("File {} not Found".format(file_name))
OSError: File shirt not Found

Any help is much appreciated.

**Comment by SkyCo** [comment]
There are two errors in your code snippet. But, don’t worry!
### First error
Obviously, your photo file path causes this error.

File path has two concepts.
- Absolute path
- Relative path

#### Absolute path
If you put the `shirt.png` photo into desktop, the path is `/Users/A/Desktop/shirt.png`. (A is your computer username)

#### Relative path
If the `shirt.png` photo location is the same as the `OutFit.py` file location, the path is `shirt.png`.

### Second error
By the way, you should not use `Write()` to display the photo. Bacause this method parameter is `DrawBorderThenFill` that only works for VMobjects.  

You can use the `FadeIn()` to display the photo. Have a try :)

```py
from manimlib.imports import *


class OutFit(Scene):
    def construct(self):
        # Absolute path
        # image = ImageMobject("/Users/A/Desktop/shirt.png")
        # Relative path
        image = ImageMobject("shirt.png")
        self.play(FadeIn(image))
        self.wait()
```

### Reference
- [Path (computing)](https://en.wikipedia.org/wiki/Path_(computing))
- [Write() declaration](imation/creation.py#L100)
- [Manim tutorial | 7 - Add sounds, svgs and images](https://www.youtube.com/watch?time_continue=15&v=tsMGRN3ZfAg&feature=emb_logo)

**Comment by rdownieMath** [comment]
Thank you! That's very helpful!
