### ISSUE TITLE
How Can I Make a Thin-Edged Lens?

### ISSUE THREAD

**Issue by sexyzeky** [3b1b/manim#1219]
How can I create a class that makes thin-edged lens? I'm beginner, so if you show an example, I will be thankfull.
Here is what I done:
```
class ThinEdgedLens_1(Arc):
    CONFIG = {
        "starting": DOWN,
        "ending": UP
    }

    def generate_points(self):

        arc_1 = ArcBetweenPoints(
                start=self.starting,
                end=self.ending,
                angle=TAU/6
            )

        arc_2 = ArcBetweenPoints(
                start=self.ending,
                end=self.starting,
                angle=TAU/6
            )

        self.append_points(arc_1.points)
        self.append_points(arc_2.points)
```
This is printed by above code:
![Adsız1223](https://user-images.githubusercontent.com/58697394/91713527-9f626600-eb92-11ea-80da-08e236dedbf7.png)

```
class ThinEdgedLens_2(Arc):

    CONFIG = {
        "starting": DOWN,
        "ending": UP
    }

    def generate_points(self):

        arc_1 = ArcBetweenPoints(
                start=self.starting,
                end=self.ending,
                angle=TAU/6
            )

        arc_2 = ArcBetweenPoints(
                start=self.ending,
                end=self.starting,
                angle=TAU/6
            )

        self.add(arc_1, arc_2)
```
This is printed by above code:
![Adsız342](https://user-images.githubusercontent.com/58697394/91713637-d173c800-eb92-11ea-88bf-efe63944d94e.png)

Why the edges are different? What is the actual work of  "self.append_points(arc_1.points)"?

One more question: I colorized it by purple and yellow. Its same color edges are congruent but I try opposite. Different colors must be congruent:
![image](https://user-images.githubusercontent.com/58697394/91714859-40eab700-eb95-11ea-9b5c-f4fc8734dd41.png)
I try to fix it by adding arc_2.reverse_points()  but it didn't work.

**Comment by NeoPlato** [comment]
What exactly do you mean by thin lens?

Could you show a picture?

**Comment by sexyzeky** [comment]
Bi-convex lense
![img1424](https://user-images.githubusercontent.com/58697394/92213254-ec4c8200-ee9b-11ea-9370-e29624da2568.png)

**Comment by SkyCo** [comment]
## Intuition
We can draw the lenses with a series of 2D shapes like Line, Arc, etc. But if we combine the shapes without decoration, we will find that the combined graphics lacks transitional round angles.

## Solution
This problem reminds me of Polygon. As we know, the Polygon did not lack any transitional round angles. So we should look at its [source code](https://github.com/3b1b/manim/blob/master/manimlib/mobject/geometry.py#L711). We can find `self.append_points(arc1.points)` statement in `round_corners()` method. The [append_points()](https://github.com/3b1b/manim/blob/master/manimlib/mobject/types/vectorized_mobject.py#L418) method is the key to solve the problem.  

The `append_points()` method could add the transitional section between adjacent and overlapping shapes. Actually, I think you have found this feature.

Bi-concave Lens, for example:  
```python
from manimlib.imports import *


class Graphics(Scene):
    def construct(self):
        lens = Lens()
        self.add(lens)


class Lens(VMobject):
    def generate_points(self):
        line_1 = Line(start=np.array([-0.5, 1, 0]), end=np.array([0.5, 1, 0]))

        arcBetweenPoints_1 = ArcBetweenPoints(start=np.array([0.5, 1, 0]),
                                              end=np.array([0.5, -1, 0]),
                                              angle=TAU / 6)

        line_2 = Line(start=np.array([0.5, -1, 0]), end=np.array([-0.5, -1, 0]))

        arcBetweenPoints_2 = ArcBetweenPoints(start=np.array([-0.5, -1, 0]),
                                              end=np.array([-0.5, 1, 0]),
                                              angle=TAU / 6)

        self.append_points(line_1.points)
        self.append_points(arcBetweenPoints_1.points)
        self.append_points(line_2.points)
        self.append_points(arcBetweenPoints_2.points)

        self.add(line_1, arcBetweenPoints_1, line_2, arcBetweenPoints_2)
```

### Effect
![Graphics](https://user-images.githubusercontent.com/40890227/92297600-8e8b6900-ef73-11ea-8997-a4f082cd056a.png)

### Attention
- The graphics’ coordinate must be from start to end according to the clockwise order of combined shapes.
- The `self.append_points` also must comply with the clockwise order of combined shapes.

## End
I think you could deduce many things from one case. Enjoy yourself :)

**Comment by sexyzeky** [comment]
Thanks! It was helpful
