### ISSUE TITLE
Plot a circle in Manim graph using coordinate equations.

### ISSUE THREAD

**Issue by baljeetrathi** [3b1b/manim#1227]
Hi,

I want to plot the circle `x^2 + y^2 = 25` in Manim. I am currently using the following code to get the corresponding values of `y` for a given `x`:

```
circle = axes.get_graph(
            lambda x: math.sqrt(25 - x**2),
            x_range=[-5,5, 0.01]
        )
```

However, there will be two values of `y` for each value of `x`. This means that I the function only plots a semi-circle. How can I get it to plot the full circle?

Thanks.

**Comment by NeoPlato** [comment]
If you look very closely in the definition of the Axes object right next to where _get_graph_ method was defined there's literally _get_parametric_function_

And also one thing you must learn with a meagerly documented tool like Manim, for peace of mind just define for yourself what you can't find

Trust me

Really, I have much PTSD with this tool

**Comment by NeoPlato** [comment]
Hold on to your hat brother, cause you are about to see a mad lad in action.

```
circle = axes.get_parametric_curve(
    lambda t: 5 * np.cos(t) * RIGHT + 5 * np.sin(t) * UP,
    t_min = 0,
    t_max = TAU,
    stroke_color = ORANGE,
    stroke_width = 2
)
```

You get it. It's _get_parametric curve_. You could also create a **literal circle** mainly because it'll be easier to do animations with, especially transforms into other things like ellipses and stuff. But anyway...

**Comment by baljeetrathi** [comment]
Thanks @NeoPlato 😄

When you say, literal circle, do you mean a circle using the `Circle()`  method in Manim?

**Comment by NeoPlato** [comment]
Exactly!

Then the radius of $\sqrt{25}$ in the implicit equation is merely the radius of the circle all in a single setting.

Also, you don't have to think about it as much as you would when using the parametric version. Small disadvantage I see here is the circle won't be an attribute of the axes so you'd either move it independently or add a new method to Axes in _manimlib\mobject\coordinate_systems.py_ to handle this for you, which is recommended.

I think I can sort you out here. Just copy paste this code(better in the CoordinateSystems class than the Axes class since it is the base class thus extending it automatically to ThreeDAxes and NumberPlane and ComplexPlane):

![Screenshot 2020-09-13 123337](https://user-images.githubusercontent.com/67624028/93015053-ca9b7b00-f5be-11ea-9e4e-c0a5d7917aef.jpg)

Add the import line at the top for obvious reasons:

![Screenshot 2020-09-13 123548](https://user-images.githubusercontent.com/67624028/93015074-f74f9280-f5be-11ea-89e7-6a3924247bc0.jpg)


And you're good to go

**Comment by baljeetrathi** [comment]
Thanks @NeoPlato :)

You are awesome. How did you learn so much about Manim? I have been trying to learn some things myself but most old tutorials no longer work.

**Comment by NeoPlato** [comment]
Oh that's easy.

After banging my head against a wall (figuratively of course) my brain reset and I gave up completely on any outside help.

Since then I've been studying the original master's code and actually learning Python and I can say I'm making good progress.

**Comment by NeoPlato** [comment]
> Exactly!
> 
> Then the radius of $\sqrt{25}$ in the implicit equation is merely the radius of the circle all in a single setting.
> 
> Also, you don't have to think about it as much as you would when using the parametric version. Small disadvantage I see here is the circle won't be an attribute of the axes so you'd either move it independently or add a new method to Axes in _manimlib\mobject\coordinate_systems.py_ to handle this for you, which is recommended.
> 
> I think I can sort you out here. Just copy paste this code(better in the CoordinateSystems class than the Axes class since it is the base class thus extending it automatically to ThreeDAxes and NumberPlane and ComplexPlane):
> 
> ![Screenshot 2020-09-13 123337](https://user-images.githubusercontent.com/67624028/93015053-ca9b7b00-f5be-11ea-9e4e-c0a5d7917aef.jpg)
> 
> Add the import line at the top for obvious reasons:
> 
> ![Screenshot 2020-09-13 123548](https://user-images.githubusercontent.com/67624028/93015074-f74f9280-f5be-11ea-89e7-6a3924247bc0.jpg)
> 
> And you're good to go!

Quick update on this thing. I just realized that the circle initialized stays at the center meaning if the Axes method was called on a spot that wasn't the origin the circle would be left there undisturbed which is not helpful. Like so:

```
        axes = Axes(y_min=0)
        axes.shift(DOWN * 3)
        graph = axes.get_circle(radius=3)
        self.add(axes, graph)
        self.play(
            axes.shift, UP * 4,
            run_time = 3
        )
        self.wait()
```

Try this on the original version and the circle doesn't go to the correct origin.

Solution:

![Screenshot 2020-09-13 174313](https://user-images.githubusercontent.com/67624028/93021083-79ed4780-f5e9-11ea-841d-6c2741182ab1.jpg)

The play method executed in the code above will leave the circle hanging even though it's been correctly placed this time. For that, remember that Axes is a VGroup so a simple `axes.add(circle)` will do the trick quite nicely.

Just thought that might help. Happy animating

**Comment by baljeetrathi** [comment]
Thanks @NeoPlato :)
