### ISSUE TITLE
 There are no scenes inside that module

### ISSUE THREAD

**Issue by zhangj563** [3b1b/manim#1228]
[09/15/20 04:18:10] ERROR                                                                                __main__.py:83
                                There are no scenes inside that module

**Comment by huguesdevimeux** [comment]
Without the code we can't really do anything. 
It's most likely that you forget to make your scene inherit from `Scene`

**Comment by liuzh1206** [comment]
I also have this problem.
This is my code.
```py
from manimlib.imports import *

class Shapes(Scene):
    #A few simple shapes
    def construct(self):
        circle = Circle()
        square = Square()
        line=Line(np.array([3,0,0]),np.array([5,0,0]))
        triangle=Polygon(np.array([0,0,0]),np.array([1,1,0]),np.array([1,-1,0]))

        self.add(line)
        self.play(ShowCreation(circle))
        self.play(FadeOut(circle))
        self.play(GrowFromCenter(square))
        self.play(Transform(square,triangle))
```
and it show that 
![001](https://user-images.githubusercontent.com/46163571/99898002-18c4ad00-2cd9-11eb-806d-dd9e9b45134d.png)

**Comment by oyekamal** [comment]
(venv) ➜  manim git:(master) python3 -m manim example_scenes.py SquareToCircle 
[02/14/21 21:53:19] ERROR                                                                 module_ops.py:65
                                There are no scenes inside that module                                    
 


same error. Plz help

**Comment by oyekamal** [comment]
> Without the code we can't really do anything.
> It's most likely that you forget to make your scene inherit from `Scene`

how? im confused as hell.

**Comment by accompanyling** [comment]
I also the same issue. There is no answer from google. How to solve the problem makes me mad.
![image](https://user-images.githubusercontent.com/32995469/108041886-1aa0d100-707a-11eb-8cf7-7120bc4f0c4e.png)

**Comment by TonyCrane** [comment]
If this is an issue of [ManimCommunity/manim](https://github.com/ManimCommunity/manim), please open an issue there instead of here.
