### ISSUE TITLE
Tips of DoubleArrow scale differently

### ISSUE THREAD

**Issue by bhbr** [3b1b/manim#123]
Something I have noticed, but don't need to work right now. And couldn't figure out how to fix fast.

```
from helpers import *
from mobject import Mobject
from mobject.vectorized_mobject import *
from animation.animation import Animation
from animation.transform import *
from animation.simple_animations import *
from topics.geometry import *
from scene import Scene
from camera import Camera


class SampleScene(Scene):

    def construct(self):

        mob = DoubleArrow([-1,-1,0],[1,1,0])
        self.add(mob)

        self.play(
            mob.scale,2
        )
```

gives:

![samplescene](https://user-images.githubusercontent.com/13440601/36206940-829f5b0c-1194-11e8-9520-298b4c0acd41.png)

**Comment by DanWaxman** [comment]
I wrote a quick solution to this which should fix the issue, albeit in a not-so-beautiful way in #174. The issue was that self.tip only preserves the first init tip and not any subsequent ones, and also does not preserve the add_at_end parameter. Keeping track of both of these fixes this.
