### ISSUE TITLE
Feature request: Add color to `Matrix`

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [3b1b/manim#1230]
When running an animation to illustrate a series of matrix operations it is clearer to transform values between matrices without transforming the brackets of the matricies. When using many matricies it often useful to color matricies to help differentiate what they represent.

I cannot see how to transform values from a matrix declared using a `TexMobject` and I cannot see how one would color a `Matrix` object.

The easiest approach I believe here would be the ability to color `Matrix` objects.

**Comment by huguesdevimeux** [comment]
This is indeed an interesting suggestion. Unfortunately, this version of manim is not meant get feature requests, as no one is developing it except Grant. 

Could you open a new issue on ManimCommunity ? You'll find the link in README.

**Comment by JimChr-R4GN4R** [comment]
Do you mean this:
```
		matrix1 = Matrix([ ['1','2'], ['3','4'], ['5','6'], ['7','8'] ]).set_color(GREEN)
		a = TextMobject('9').next_to(matrix1[0][0],DOWN*0)
		self.play(Write(matrix1))
		self.play(ReplacementTransform(matrix1[0][0],a))
```
?

**Comment by JonathanWoollett-Light** [comment]
@JimChr-R4GN4R  That actualy is what I'm looking for. Can't beleive I missed that, thanks!.
