### ISSUE TITLE
How to achieve a line with different styles of starting/ending tip?

### ISSUE THREAD

**Issue by Tapyu** [3b1b/manim#1231]
Hello, I'm new here

I'm trying to create a scene that has a line with a dot in ending/starting. It would look like this...

![image](https://user-images.githubusercontent.com/22801918/93498234-eae17780-f8e7-11ea-851f-10dacc325e5c.png)

I'm following [this](https://manimce.readthedocs.io/en/latest/reference/manim.mobject.geometry.ArrowTip.html) doc, I tried to run the following code:

```
class Viterbi(Scene):
    def construct(self):
        arrow = Arrow(np.array([0, 0, 0]), np.array([1, 1, 0]), tip_shape=ArrowCircleTip)
        self.add(arrow)
        self.wait()
```

I received this warning:

`NameError: name 'ArrowCircleTip' is not defined`

I am not a specialist in reading documents, but [based in this doc](https://manimce.readthedocs.io/en/latest/reference/manim.mobject.geometry.ArrowCircleFilledTip.html#manim.mobject.geometry.ArrowCircleFilledTip), `manim.mobject.geometry.ArrowCircleFilledTip` means that the class `ArrowCircleFilledTip` should be located in `manim/mobject/geometry.py`, doesn't?

Anyway, this path doesn't exist. But I found the path [`manim/manimlib/mobject/geometry.py`](https://github.com/3b1b/manim/blob/master/manimlib/mobject/geometry.py), and there isn't the statement of the `ArrowCircleTip` class. If I'm not wrong, I should find this class there. That's the problem? how can I solve it?

I have an interesting case:

1. When I change `ArrowCircleTip` to `RegularPolygon` (which exists in`manim/manimlib/mobject/geometry.py`), this code still gives me an arrow-styled line, that is 
![image](https://user-images.githubusercontent.com/22801918/93553830-6411b680-f94a-11ea-9ca7-9a9ee197bd32.png)

PS: Sorry if this question is stupid, I didn't find it anywhere...

**Comment by NeoPlato** [comment]
You mean this?

```
class ArrowCircleTip(Line):
    def __init__(self, *args, **kwargs):
        Line.__init__(self, *args, **kwargs)
        self.add_dot_tip()

    def add_dot_tip(self, tip_length=None, at_start=True):
        """
        Returns a tip that has been stylistically configured,
        but has not yet been given a position in space.
        """
        if tip_length is None:
            tip_length = DEFAULT_DOT_RADIUS
        color = self.get_color()
        style = {
            "fill_color": color,
            "stroke_color": color
        }
        style.update(self.tip_style)
        tip = Dot(radius=tip_length, **style)
        tip.move_to(self.get_end())
        self.add(tip)
        if at_start:
            end_tip = tip.copy()
            end_tip.move_to(self.get_start())
            self.add(end_tip)
```

**Comment by Tapyu** [comment]
Exactly @NeoPlato ! Thank you. I gotta study your code to understand fully...

About my confusion, I found out what is going on: Actually, that doc is about [another manim](https://github.com/ManimCommunity/manim) (of the community) that has more tools. There, I found the class `ArrowCircleFilledTip` in `./manim/mobject/geometry.py`, as it should be.

Which manim I should use?

**Comment by NeoPlato** [comment]
I don't really know if I can give fully accurate advice.

Best plan: go for the community version. It's in the name, help and documentation will be closer to you than in the main version.

**Comment by Tapyu** [comment]
Thank you for the advice.

**Comment by Tapyu** [comment]
Just updating with the code using the [manim community](https://github.com/ManimCommunity/manim). It looks soo better/easier. I wish it helps someone.

Best regards.

```
from manim import *
from manim.mobject.geometry import ArrowCircleFilledTip, ArrowCircleTip

class Viterbi(Scene):
    def construct(self):
        path = DoubleArrow(np.array([-2,-1,0]), np.array([2, -1, 0]), tip_shape_start=ArrowCircleFilledTip, tip_shape_end=ArrowCircleFilledTip)
        self.add(path)
        self.wait(1)
```
The result:

![image](https://user-images.githubusercontent.com/22801918/94280743-24d3fe80-ff24-11ea-9158-1a1568122c02.png)
