### ISSUE TITLE
latex problems

### ISSUE THREAD

**Issue by GustavoSantosBahia** [3b1b/manim#1232]
why the theta argument is not appearing

![Sem título](https://user-images.githubusercontent.com/68217264/93688864-997be880-fa9f-11ea-8cd1-26bc76469d76.png)

![image](https://user-images.githubusercontent.com/68217264/93688877-b7e1e400-fa9f-11ea-89bd-4f67d607c4d3.png)

**Comment by Tony031218** [comment]
This is a string in python, so you need to use `\\` instead of a single `\`. Or use r-string, like `r"\theta"`
For this, you may want:
```
TexMobject("(L-r)\\cdot \\sin(\\theta)")
# Or
TexMobject(r"(L-r)\dot \sin(\theta)")
```

**Comment by GustavoSantosBahia** [comment]
thank you
