### ISSUE TITLE
Latex error converting to DVI on macOS

### ISSUE THREAD

**Issue by vegerot** [3b1b/manim#124]
When attempting to animate any TexMobject, I get an error saying
`Exception: Latex error converting to dvi`

I have looked at all the relevant issues here (including #64 and #36 ) and none of them seem to work.  Perhaps I just didn't see the post the solved my issue.

For example, while trying to run SpinAroundCube:
`Traceback (most recent call last):
  File "extract_scene.py", line 242, in main
    handle_scene(SceneClass(**scene_kwargs), **config)
  File "/Users/MaxCoplan/Documents/workspace/manim/scene/scene.py", line 68, in __init__
    self.construct(*self.construct_args)
  File "/Users/MaxCoplan/Documents/workspace/manim/./example_scenes.py", line 171, in construct
    text = TextMobject("Your ad here")
  File "/Users/MaxCoplan/Documents/workspace/manim/mobject/tex_mobject.py", line 52, in __init__
    self.template_tex_file
  File "/Users/MaxCoplan/Documents/workspace/manim/mobject/tex_mobject.py", line 321, in tex_to_svg_file
    dvi_file = tex_to_dvi(tex_file)
  File "/Users/MaxCoplan/Documents/workspace/manim/mobject/tex_mobject.py", line 366, in tex_to_dvi
    "See log output above or the log file: %s" % log_file)
Exception: Latex error converting to dvi. See log output above or the log file: /Users/MaxCoplan/Documents/workspace/manim/files/Tex/-6949998171807781965.log` 

[-6949998171807781965.log](https://github.com/3b1b/manim/files/1725755/-6949998171807781965.log)

**Comment by hmuar** [comment]
I had same prob (also macOS).  My .log file seemed to point to missing fonts as the issue, specifically the STHeiti font. I did what was suggested in #64 by both [using .xdv](https://github.com/3b1b/manim/issues/64#issuecomment-365987932) and [not using CTEX](https://github.com/3b1b/manim/issues/64#issuecomment-365240137).

 When I first tried not using CTEX, it didn't work. But it was because it was using the existing .tex from the `files/Tex` folder that were generated from before I modified the `template.tex` and `text_template.tex` files. After I cleared out my `files/Tex` folder, it worked.

I think first step might be to look at your log file and see if it's a font related issue vs something else.

**Comment by bcordo** [comment]
I had the exact same issues, and none of the other methods solved it for me. I realized I didn't have all of the dependencies installed, namely,
- ffmpeg
- latex
- sox

After I installed these (I'm on Mac 10.11.6), everything worked, without needing to make any other modification. Not sure if this is helpful, but thought I would post this just in case.

**Comment by ddxtanx** [comment]
I had the same problem. What you want to do is to make sure you have dvisvgm installed (which is installed along with most latex distros). Then go into mobjects/tex_mobject.py and edit the commands in tex_to_dvi to "xelatex" instead of "latex". Hope this helps!

**Comment by fincle** [comment]
@bcordo I'm having this issue too on Mac (10.12.6).  I installed ffmpeg and sox with brew but installed latex from the MacTex GUI installer.  Just wondering how you installed latex on your setup?

**Comment by left0077** [comment]
I had the same problem. I delete the `\usepackage[UTF8]{ctex}` in `text_template.tex`. Then it works! But I find that no `.svg` file is created in `/manim-master/files/Tex`.

**Comment by bcordo** [comment]
Hi Andrew,

I did the exact same steps. Just to be sure I also copy and pasted this
snippet into the appropriate file (don’t remember the exact file right now,
I’m on my phone):

```

def tex_to_dvi(tex_file):
	result = tex_file.replace(".tex", ".xdv")
	if not os.path.exists(result):
		commands = [
			"xelatex",
			"-no-pdf",
			"-interaction=batchmode",
			"-halt-on-error",
			"-output-directory=" + TEX_DIR,
			tex_file,
			">",
			get_null()
		]
		exit_code = os.system(" ".join(commands))
		if exit_code != 0:
			latex_output = ''
			log_file = tex_file.replace(".tex", ".log")
			if os.path.exists(log_file):
				with open(log_file, 'r') as f:
					latex_output = f.read()
			raise Exception(
				"Latex error converting to dvi. "
				"See log output above or the log file: %s" % log_file)
	return result

def dvi_to_svg(dvi_file, regen_if_exists = False):
	"""
	Converts a dvi, which potentially has multiple slides, into a
	directory full of enumerated pngs corresponding with these slides.
	Returns a list of PIL Image objects for these images sorted as they
	where in the dvi
	"""
	result = dvi_file.replace(".xdv", ".svg")
	if not os.path.exists(result):
	    commands = [
	        "dvisvgm",
	        dvi_file,
	        "-n",
	        "-v",
	        "0",
	        "-o",
	        result,
	        ">",
	        get_null()
	    ]
	    os.system(" ".join(commands))
	return result

```

I didn’t write that explicitly in the last message.

Hope that helps.

Brad

**Comment by eulertour** [comment]
Closing, as this issue is inactive and seems to be resolved. Feel free to reopen it if this is still a problem.

**Comment by Akai-Shuuichi** [comment]
> I had the exact same issues, and none of the other methods solved it for me. I realized I didn't have all of the dependencies installed, namely,
> 
> * ffmpeg
> * latex
> * sox
> 
> After I installed these (I'm on Mac 10.11.6), everything worked, without needing to make any other modification. Not sure if this is helpful, but thought I would post this just in case.

How to install Latex. I have tried to use pip, but it can't work. So does ffmpeg. Then I install ffmpeg 
from homebrew and solved it. But now I can't install Latex from homebrew. What I need to do?

**Comment by icreiuheciijc** [comment]
@Akai-Shuuichi Just install a LaTeX distribution. I personally installed MacTeX and it works great on macOS. You can also install other distributions like MiKTeX.
