### ISSUE TITLE
WikiHow tutorial link in the README for installation of FFmpeg is outdated

### ISSUE THREAD

**Issue by khssupriya** [3b1b/manim#1253]
Hi, I was trying to install manim and I found that the [wikiHow page](https://www.wikihow.com/Install-FFmpeg-on-Windows) that was linked in the [README](https://github.com/3b1b/manim#directly-windows) for installation of manim in windows is outdated. The wikiHow wants us to download from [http://ffmpeg.zeranoe.com/](http://ffmpeg.zeranoe.com/), but that website is closed now.

As quoted on the website before it was closed:
> ffmpeg.zeranoe.com will close on Sep 18, 2020, and all builds will be removed

Please provide the correct link to download from

**Comment by ankur3g** [comment]
If you are using pycharm, then follow following method for installation of packages: <https://www.jetbrains.com/help/pycharm/installing-uninstalling-and-upgrading-packages.html>

There you can search for ffmpeg-python

This will perhaps resolve your issue

**Comment by khssupriya** [comment]
Thank you. I don't use Pycharm but I have downloaded it from https://pypi.org/project/ffmpeg-python/
