### ISSUE TITLE
Camera angles

### ISSUE THREAD

**Issue by singularity0614** [3b1b/manim#1254]
Is it possible to view a scene not from the centre, but rather like a horizon instead. In the picture below, I am viewing it from the centre so both cylinders aren't vertical from my perspective. Is there a way to fix that and make it so that the two cylinders are completely upright.

p.s. if you have an answer could you provide me with the code please, I'm not too good with code yet so I'll need a bit of guidance before I can work fully by myself.
![Thumbnail](https://user-images.githubusercontent.com/68496417/95647960-6e753980-0b1f-11eb-8c11-ebd6e45fde50.png)

**Comment by Level-314** [comment]
Please provide the code you have at this point. It will make it much easier to provide the answer with code.

**Comment by NoobAtManim** [comment]
```
class Test(ThreeDScene):
    def construct(self):
        cylinder = ParametricSurface(
            lambda u, v: np.array([
                np.cos(TAU * v),
                np.sin(TAU * v),
                2 * (1 - u)
            ]),
            resolution=(20, 100))  # Resolution of the surfaces
        cylinder.rotate(-PI/3, RIGHT).scale(2).shift(3*RIGHT)
        self.add(cylinder)
        cylinder1 = ParametricSurface(
            lambda u, v: np.array([
                np.cos(TAU * v),
                np.sin(TAU * v),
                2 * (1 - u)
            ]),
            resolution=(20, 100))  # Resolution of the surfaces
        cylinder1.rotate(-PI/3, RIGHT).scale(2).shift(3*LEFT)
        self.add(cylinder1)
```

It's not very neat.
