### ISSUE TITLE
Rotating and moving objects at the same time

### ISSUE THREAD

**Issue by ContestMath** [3b1b/manim#1277]
Hello,
I am relatively new to manim and programming in general and want to ask how you can rotate and move objects in manim at the same time. I searched the internet and tryed it myself but could not get it to work properly for hours. I suspect it has something to do with the .rotate modifier but I do not know how I can use it in the right way. Thank you for any help.

**Comment by DVCosmos** [comment]
I think [this](https://stackoverflow.com/a/57364870) stackoverflow answer might be useful to you.

**Comment by kkin1995** [comment]
Are you looking for VGroup() ?

```
circle = Circle().move_to(2 * UP)
square = Square()
grouped = VGroup(circle, square)
self.play(grouped.rotate, 90)
```

**Comment by ContestMath** [comment]
@DVCosmos Thank you so much! Update functions seem to work really well.

@kkin1995 My problem was that .rotate warps objects in weird ways. I should have been more clear in what the problem was, sorry. But thank you anyways.
