### ISSUE TITLE
How to graphing parametric equations or complex function?

### ISSUE THREAD

**Issue by luneice** [3b1b/manim#1279]
There is no result that explains how to graph this function:
```
x = 16 * sin(t) * sin(t),
y = 13 * cos(t) + 6 * cos(4*t)
```
or this function that ```x``` ```y``` cannot insepare: 
```
xy + x^2 + y^3 -3 =0
```
And how to use ```manim``` to graph those function? Thanks!

**Comment by NeoPlato** [comment]
I'm touching this mainly because I've covered this before.

```python
class ThreeDParametricSpring(ThreeDScene):
    def construct(self):
        curve1 = ParametricFunction(
            lambda u: np.array([
                16 * np.sin(u) * sin(u),
                13 * np.cos(u) + 6 * np.cos(4 * u),
                0
            ]), color=RED, t_min=0, t_max=TAU,
        ).set_shade_in_3d(True)
        axes = ThreeDAxes()
        self.add(axes, curve1)
        self.set_camera_orientation(phi=80 * DEGREES, theta=-60 * DEGREES)
        self.wait()
```

As for the implicit one, you can't really have a definitive solution. You can only solve for a particular case eg #1229 
And your particular example isn't so easy

**Comment by luneice** [comment]
@NeoPlato thank you. i found the issue that the graph is out of the canvas, so the graph was not graph in the canvas. If the graph was zoomed, it can be shown in the canvas.

**Comment by Level-314** [comment]
If you're interested I made a video covering parametric graphing in MANIM for another question:

https://youtu.be/zReqQ8NMsI0
