### ISSUE TITLE
Does Manim work with BasicTex on the Mac ?

### ISSUE THREAD

**Issue by kkin1995** [3b1b/manim#1291]
Hi, I have just installed Manim (cloned it from this repo today) and BasicTex on a Mac and am trying to render a TextMobject using code similar to the following:

```
text = TextMobject("Text")
text.move_to(2*UP + 2*RIGHT)
self.add(text)
```

However, It seems to give an error saying:

```
Exception: Latex error converting to dvi. See log output above or the log file:
```
And, when checking the log file:
```
! LaTeX Error: File `standalone.cls' not found.
```
Does Manim work with BasicTex or do I have to install the complete MacTex? Or, am I doing something wrong here?

**Comment by SkyCo** [comment]
I think that you should uninstall BasicTex, and install MacTeX. Even if the BasicTeX needs less storage, it may lack relative packages for macOS or Manim like standalone class.

#### Reference
- [MacTeX vs BasicTeX](https://sourabhbajaj.com/mac-setup/LaTeX/)
- [Installing latex standalone in ubuntu for humans](https://tex.stackexchange.com/questions/270888/installing-latex-standalone-in-ubuntu-for-humans)
- [The MacTeX-2020 Distribution](https://www.tug.org/mactex/)

**Comment by kkin1995** [comment]
Alright thanks! I’ll try with MacTex and post back here if it works. 

I had installed BasicTex because Manim Community docs said that either MacTex or BasicTex should work.

I posted the issue here because I had installed this version of Manim.

**Comment by ngg1995** [comment]
Yes it does work but you need to install the required dependancies 

[See here ](https://docs.manim.community/en/latest/installation/mac.html)

**Comment by kkin1995** [comment]
@ngg1995 Alright ! Thank You! I think I missed that command.
