### ISSUE TITLE
How to use Pango or CairoText?

### ISSUE THREAD

**Issue by tmelorc** [3b1b/manim#1297]
I'm using:

> Linux Mint 20 (updated)
> Python 3.8.5
> manim 0.1.1

I'm trying to reproduce this example from Documentation (saved in `test.py`):

```
from manim import *

class Example1Text(Scene):
    def construct(self):
        text = Text('Hello world').scale(3)
        self.add(text)
```
Running `manim test.py` I got:

![Terminal - thiago@xerxi: ~-Documentos-project_002](https://user-images.githubusercontent.com/15181573/103044694-40b96180-4560-11eb-8b4d-095464a75d90.png)

Since I don't know how to work with Pango, I tried `CairoText` as suggested and I got:

![Terminal - thiago@xerxi: ~-Documentos-project_003](https://user-images.githubusercontent.com/15181573/103044795-c50be480-4560-11eb-94e2-3cd8c004e15a.png)

As said in the warning, I tried to pass a font using `font='Ubuntu'` and I got:

![Terminal - thiago@xerxi: ~-Documentos-project_004](https://user-images.githubusercontent.com/15181573/103044876-1025f780-4561-11eb-8e37-942f1e231622.png)

So, no info nor warning about fonts but no movie was produced. I'm not able to follow the red lines as shown in the output above.

Any help is appreciated. 
Regards.

**Comment by tmelorc** [comment]
I've just discovered that the missing `self.wait()` is causing the problem. Adding it as last line solves the problem.

**Comment by naveen521kk** [comment]
I think wrong repo?

**Comment by TonyCrane** [comment]
Please open an issue in [ManimCommunity/manim](https://github.com/ManimCommunity/manim) if you are using the community edition.
