### ISSUE TITLE
Error while trying to run example_scenes.py SquareToCircle -pl

### ISSUE THREAD

**Issue by trag1c** [3b1b/manim#1306]
Ran the command `python -m manim example_scenes.py SquareToCircle -pl`

Tried looking for a solution on Google, StackOverflow, and in other issue threads here but couldn't find anything that'd help me.

```
D:\Manim\manim_3_feb>python -m manim example_scenes.py SquareToCircle -pl
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\Manim\manim_3_feb\manim.py", line 2, in <module>
    import manimlib.config
ImportError: No module named manimlib.config
```

**Comment by P0intMaN** [comment]
I think the problem lies while importing the module. I can see that you have traversed till manim_3_b directory. You must traverse till manim\manim-master directory. May i see the folder in which these are stored? That might help me to figure out the problem

**Comment by trag1c** [comment]
> I think the problem lies while importing the module. I can see that you have traversed till manim_3_b directory. You must traverse till manim\manim-master directory. May i see the folder in which these are stored? That might help me to figure out the problem

Do you mean the `D:\Manim` folder?

**Comment by kaloomte** [comment]
Did you try `python -m manim example_scenes.py SquareToCircle -pl` in main ` D:\Manim` directory?

**Comment by trag1c** [comment]
> Did you try `python -m manim example_scenes.py SquareToCircle -pl` in main ` D:\Manim` directory?

It won't work, \manim_3_feb is the directory where I have Manim installed and D:\Manim is the directory where I have all the other stuff needed installed (e.g. FFmpeg or SoX)

I did try that in fact, and what I got in return was:
```C:\Python27\python.exe: No module named manim```

**Comment by P0intMaN** [comment]
python displays "no module named manim" only when it cant locate manim. Have you tried making D:\Manim as an env variable?

**Comment by P0intMaN** [comment]
Also, try making ffmpeg and sox too as env variables

**Comment by trag1c** [comment]
> Have you tried making D:\Manim as an env variable?
> Also, try making ffmpeg and sox too as env variables

All of them are env variables

I don't really get the `ImportError: No module named manimlib.config` part since in the directory I'm running the command in has a `manimlib` folder with a `config.py` file in it
