### ISSUE TITLE
pyglet.window.NoSuchConfigException when running "Get Started Example Code"

### ISSUE THREAD

**Issue by Sebastian-Nielsen** [3b1b/manim#1337]
Running the "get started example code":
```
# This is start.py
from manimlib.imports import *
class SquareToCircle(Scene):
  def construct(self):
    circle = Circle()
    circle.set_fill(BLUE, opacity=0.5)
    circle.set_stroke(BLUE_E, width=4)
    
    self.add(circle)
```
Yields the following error:
`pyglet.window.NoSuchConfigException`

The get started code is run using the command: `python manim.py start.py SquareToCircle`

What might be the reason for this? 

I successfully installed all requirements in `requirements.txt` as well as FFmpg.

**Comment by naveen521kk** [comment]
> What might be the reason for this?
Maybe your computer is super old?
I think OpenGL 3.3+ is required as per https://github.com/moderngl/moderngl#is-my-old-pc-supported
Maybe your graphics driver is not updated or something like that?

**Comment by aburousan** [comment]
In D:\Manim\manim-shaders\manim-shaders\manimlib there is window.py , just change the sample = 0. It is in line 15.

**Comment by Sebastian-Nielsen** [comment]
> In D:\Manim\manim-shaders\manim-shaders\manimlib there is window.py , just change the sample = 0. It is in line 15.

That worked, thank you!

Out of curiosity, why does that work though? What was the problem?
