### ISSUE TITLE
Error loading the example_scenes.py OpeningManimExample

### ISSUE THREAD

**Issue by pedrommaiaa** [3b1b/manim#1339]
sh: 1: latex: not found\LaTeX"
ERROR:root:

 LaTeX Error!  Not a worry, it happens to the best of us.

Traceback (most recent call last):
...
  File "/home/pedrommaiaa/Desktop/manim/manimlib/utils/tex_file_writing.py", line 94, in tex_to_dvi
    with open(log_file, "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/Tex/ff2ad2cc1ce93b1c.log'

**Comment by Khan-qi** [comment]
same problem！！How to solve？

**Comment by TonyCrane** [comment]
> same problem！！How to solve？

Have you installed LaTeX correctly?

**Comment by Khan-qi** [comment]
Use Texlive initially，Then install miktex，，，

**Comment by pedrommaiaa** [comment]
> same problem！！How to solve？

I uninstalled everything and followed [this](https://www.youtube.com/watch?v=Jfgtl-AW5Oc) tutorial, I use linux so the Mac part of the tutorial helped me solve the issue.

**Comment by Khan-qi** [comment]
Thank you...............maybe latex problem, It's difficult for me.

**Comment by lucasvitti** [comment]
On Windows I've intalled Miktex and added it to the path and got this error. What I needed to to was restart cmd to refresh the path after alteration and it worked fine.
