### ISSUE TITLE
Running the manim main branch example gives me pyglet.window.NoSuchConfigException

### ISSUE THREAD

**Issue by baljeetrathi** [3b1b/manim#1341]
I am on Windows. FFmpeg and MiXTeX are already installed on my PC. Here are the steps I followed:

```
git clone https://github.com/3b1b/manim.git
cd manim
pip install -r requirements.txt
python manim.py example_scenes.py OpeningManimExample
```

It gives me an exception about `pyglet.window.NoSuchConfigException`. Did I do anything wrong?

Thanks.

**Comment by TonyCrane** [comment]
Please search in the issues page first. See #1330 #1337.
