### ISSUE TITLE
ShowCreation not working for 3d Mobjects

### ISSUE THREAD

**Issue by sahilmakhijani** [3b1b/manim#1347]
### Bug
ShowCreation Animation is not working for three-dimensional mobjects.

**Code**:
```
class CubeCreation(Scene):
    def construct(self):
        cube = Cube()
        self.add(cube)
        self.play(ShowCreation(cube))
        self.wait()

class SphereCreation(Scene):
    def construct(self):
        sphere = Sphere()
        self.add(sphere)
        self.play(ShowCreation(sphere))
        self.wait()
```

**Error traceback**:
For Cube Creation, I am getting this:
>"..manim\manimlib\animation\creation.py", line 30, in interpolate_submobject
>&nbsp;start_submob, *self.get_bounds(alpha)
>
>"..manim\manimlib\mobject\types\surface.py", line 113, in pointwise_become_partial
>&nbsp;for arr in smobject.get_surface_points_and_nudged_points()
>
>"..manim\manimlib\mobject\types\surface.py", line 132, in get_partial_points_array
>&nbsp;col = interpolate(points[:, index], points[:, index + 1], residue)
>
>"..manim\manimlib\mobject\types\surface.py", line 113, in <listcomp>
>&nbsp;for arr in smobject.get_surface_points_and_nudged_points()
>
>IndexError: index 0 is out of bounds for axis 1 with size 0

For SphereCreation,
>The video is rendered but there is no sphere in the video, it's just blank background.

**Comment by TonyCrane** [comment]
3D Mobjects now are subclasses of `ParametricSurface`, which is the subclass of `Mobject` not `VMobject`. But `ShowCreation` can only be used on `VMobject`. So you can only use `FadeIn` and other Animations to create a 3D Mobjects.

**Comment by sahilmakhijani** [comment]
ShowCreation Animation is based on the pointwise_become_partial method which is not implemented in Mobject. But it is implemented in Parametric Surface, so it should work.

**Comment by TonyCrane** [comment]
Oh, sorry, it was my fault. I am trying to figure out the problem.

**Comment by 3b1b** [comment]
Thanks for pointing this out, I believe it is now fixed.  Feel free to reopen if other issues arise.

**Comment by sahilmakhijani** [comment]
It working now, thanks
