### ISSUE TITLE
What is the purpose of alignment_vect in align_to of MObject

### ISSUE THREAD

**Issue by RYNEQ** [3b1b/manim#1353]
I wonder what is the purpose of `alignment_vect` of `Mobject` 's `align_to` method?  
I checked "[mobject/mobject.py](https://github.com/3b1b/manim/blob/8f52c7bda8e298d15d3958ba76bc56648d4a9e19/manimlib/mobject/mobject.py#L1103)" but `alignment_vect` is unused !  

Am i missing something?

**Comment by 3b1b** [comment]
You're right!  It's a relic from back when align_to was used for the same purpose that match_x, match_y, match_z can now be used for.

In fact, in general, those methods can always do what align_to does,
