### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement opencv-python==3.4.2.17 ERROR: No matching distribution found for opencv-python==3.4.2.17

### ISSUE THREAD

**Issue by ayalaortiz** [3b1b/manim#1365]
Help me:(

Microsoft Windows [Version 10.0.18363.1316]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Manim>python -m pip install -r requirements.txt
Collecting argparse==1.4.0
  Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: colour==0.1.5 in c:\users\oscar\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 2)) (0.1.5)
Collecting numpy==1.15.0
  Using cached numpy-1.15.0.zip (4.5 MB)
Collecting Pillow==5.2.0
  Using cached Pillow-5.2.0.tar.gz (14.5 MB)
Requirement already satisfied: progressbar==2.5 in c:\users\oscar\appdata\local\programs\python\python39\lib\site-packages (from -r requirements.txt (line 5)) (2.5)
Collecting scipy==1.1.0
  Using cached scipy-1.1.0.tar.gz (15.6 MB)
Collecting tqdm==4.24.0
  Using cached tqdm-4.24.0-py2.py3-none-any.whl (43 kB)
ERROR: Could not find a version that satisfies the requirement opencv-python==3.4.2.17
ERROR: No matching distribution found for opencv-python==3.4.2.17
windows10
manim-3b088b12843b7a4459fe71eba96b70edafb7aa78
python 3.9.1

**Comment by aliPMPAINT** [comment]
That's because opencv-python version 3.4.2.17 doesn't support python 3.9.x . You can download and install python version 3.7.x and then use it in a virtual environment, or maybe change opencv-python==3.4.2.17 to a newer version(like the latest 4.5.1.48), but that might break stuff.

**Comment by TonyCrane** [comment]
Which version of the manim source code are you using. 
In the current master branch and cairo-backend branch, we have not specified the version of each python package in requirements.txt.
