### ISSUE TITLE
-pl argument is not working

### ISSUE THREAD

**Issue by Envoy-VC** [3b1b/manim#1369]
whe i try to use `python -m manim example_scenes.py TextExample -pl` it throws an error that -pl is not a recognised argument please help

**Comment by TonyCrane** [comment]
Please search in the issues page first. See #1361.
Manim has been updated, and the old `-p` and `-l` options will no longer be supported. 
See the documentation for all current options: https://3b1b.github.io/manim/getting_started/configuration.html#command-line-interface
