### ISSUE TITLE
no attribute 'points' - replaced?

### ISSUE THREAD

**Issue by Azelide** [3b1b/manim#1371]
So I've tried to run this program (```lorenztrick.py```):

```python
from manimlib.imports import *

class Lorenz_Attractor(ThreeDScene):
    def construct(self):
        axes = ThreeDAxes(x_min=-3.5,x_max=3.5,y_min=-3.5,y_max=3.5,z_min=0,z_max=6,axis_config={"include_tip": True,"include_ticks":True,"stroke_width":1})
        dot = Sphere(radius=0.05,fill_color=BLUE).move_to(0*RIGHT + 0.1*UP + 0.105*OUT)
        
        self.camera.frame.set_euler_angles(phi=65 * DEGREES,theta=30*DEGREES,gamma = 90*DEGREES)  
        self.camera.frame.add_updater(lambda m, dt: m.increment_theta(0.05 * dt))         #Start move camera

        dtime = 0.01
        numsteps = 30

        self.add(axes,dot)

        def lorenz(x, y, z, s=10, r=28, b=2.667):
            x_dot = s*(y - x)
            y_dot = r*x - y - x*z
            z_dot = x*y - b*z
            return x_dot, y_dot, z_dot

        def update_trajectory(self, dt):
            new_point = dot.get_center()
            if get_norm(new_point - self.points[-1]) > 0.01:
                self.add_smooth_curve_to(new_point)

        traj = VMobject()
        traj.start_new_path(dot.get_center())
        traj.set_stroke(BLUE, 1.5, opacity=0.8)
        traj.add_updater(update_trajectory)
        self.add(traj)

        def update_position(self,dt):
            x_dot, y_dot, z_dot = lorenz(dot.get_center()[0]*10, dot.get_center()[1]*10, dot.get_center()[2]*10)
            x = x_dot * dt/10
            y = y_dot * dt/10
            z = z_dot * dt/10
            self.shift(x/10*RIGHT + y/10*UP + z/10*OUT)

        dot.add_updater(update_position)
        self.wait(420)
```
It should produce something similar to this --> [here](https://www.youtube.com/watch?v=oqDQwEvHGfE&ab_channel=Visualization101), but I got this traceback:
```
Traceback (most recent call last):
  File "C:\Users\Azelide\manim\manim.py", line 5, in <module>
    manimlib.main()
  File "C:\Users\Azelide\manim\manimlib\__init__.py", line 12, in main
    scene.run()
  File "C:\Users\Azelide\manim\manimlib\scene\scene.py", line 76, in run
    self.construct()
  File "lorenztrick.py", line 30, in construct
    traj.add_updater(update_trajectory)
  File "C:\Users\Azelide\manim\manimlib\mobject\mobject.py", line 500, in add_updater
    self.update()
  File "C:\Users\Azelide\manim\manimlib\mobject\mobject.py", line 467, in update
    updater(self, dt)
  File "lorenztrick.py", line 24, in update_trajectory
    if get_norm(new_point - self.points[-1]) > 0.01:
AttributeError: 'VMobject' object has no attribute 'points'

```
The part of the code with an error should create a smooth curve between newly added points corresponding to the method ```lorenz```.

**Does this error have something to do with the attribute 'points' being replaced by something else in the newer versions of Manim?**

I've already had a similar [issue](https://github.com/3b1b/manim/issues/1370) with this code but likely wouldn't have found the solution by myself.

I found ```Point``` as a class in the ```mobject.py``` file in manimlib, but replacing it with points in line 24 nor importing the class separately at the start of the code actually helped. BTW I'm a manim beginner, so if there are any other compatibility/other kind of issues in this code, I would kindly appreciate if you pointed them out.

I'm running on Python 3.9.1, Windows 10 64-bit, in virtualenv.

**Comment by TonyCrane** [comment]
Try to use `self.get_points()` instead of `self.points`, currently Mobject does not directly include the `points` property, but is included in the `data` property.
Maybe we should add back this property later.

**Comment by Azelide** [comment]
I put it in and the animation works now! The only problem now's that the camera is completely static and I cannot move it except for somewhat centralizing the graph by pressing 'R', even though the part ```
self.camera.frame.add_updater(lambda m, dt: m.increment_theta(0.05 * dt)) ```, should apparently move the camera, shouldn't it?

**Comment by abhi-6988** [comment]
> even though the part `self.camera.frame.add_updater(lambda m, dt: m.increment_theta(0.05 * dt))`, should apparently move the camera, shouldn't it?

Try adding the `frame` to your scene along with `axes` and `dot`:
```self.add(axes, dot, self.camera.frame)```

**Comment by Azelide** [comment]
I've got it now! Thank you @TonyCrane and @abhi-6988
