### ISSUE TITLE
no graph_scene.py in manimlib/scenes

### ISSUE THREAD

**Issue by Envoy-VC** [3b1b/manim#1372]
just to ask the graph_scenes.py is not there in  manimlib/scenes folder

**Comment by TonyCrane** [comment]
`GraphScene` is no longer recommended, and its functions are basically moved to `CoordinateSystem`, so `Axes`, `NumberPlane`, etc. can directly use the original `GraphScene` functions.
`graph_scene.py` is currently in the `once_useful_construct/s` folder
