### ISSUE TITLE
manim.py: error: unrecognized arguments: -pl

### ISSUE THREAD

**Issue by ayalaortiz** [3b1b/manim#1377]
Help me:(

C:\Manim>python -m manim examples_scenes.py SquareToCircle -pl
usage: manim.py [-h] [-w] [-s] [-l] [-m] [--hd] [--uhd] [-f] [-g] [-i] [-t] [-q] [-a] [-o] [--finder]
                [--file_name FILE_NAME] [-n START_AT_ANIMATION_NUMBER] [-r RESOLUTION] [--frame_rate FRAME_RATE]
                [-c COLOR] [--leave_progress_bars] [--video_dir VIDEO_DIR]
                [file] [scene_names [scene_names ...]]
manim.py: error: unrecognized arguments: -pl

### Environment
**windows 10**: 
**master**: master 
**python 3.8.3**:

**Comment by TonyCrane** [comment]
PLEASE SEARCH IN [THE ISSUES PAGE](https://github.com/3b1b/manim/issues) FIRST!!
See #1361, #1369.

**Comment by TonyCrane** [comment]
PLEASE SEARCH IN [THE ISSUES PAGE](https://github.com/3b1b/manim/issues) FIRST!!
See #1361, #1369.
