### ISSUE TITLE
The `turn_animation_into_updater` function does not work properly in the master branch

### ISSUE THREAD

**Issue by widcardw** [3b1b/manim#1378]
I would like to apply a function to a square when playing the `ShowCreation` animation. However, the two animations are played one by one rather than at the same time. Here is my code. 
```python
class TestAnim(Scene):
    def construct(self):
        squ = Square().shift(LEFT*3)
        anim = ShowCreation(squ, run_time=3)
        squ.add_updater(lambda m, dt: m.shift(dt*2*RIGHT))
        self.add(squ)
        turn_animation_into_updater(anim)
        self.wait(6)
```

It runs like this in cairo-backend.
![anim1](https://user-images.githubusercontent.com/55699713/107529668-1138e400-6bf6-11eb-9c1a-2fe26584a364.gif)(It may take some time to load this gif)

Maybe something goes wrong with the function `turn_animation_to_updater`. 
![anim](https://user-images.githubusercontent.com/55699713/107529377-c5863a80-6bf5-11eb-8e36-a5ed296d637b.gif)

Also, when it comes to TexText, this problem seems somewhat strange. 
```python
class TextExample
(Scene):
    def construct(self):
        t1 = TexText("Updater").scale(2).shift(UP/2).to_edge(LEFT)
        def anim_to_center(obj, dt):
            obj.shift(np.array([
                -obj.get_center()[0] * dt * 2,0,0
            ]))
        t1.add_updater(anim_to_center)
        anim1 = Write(t1)
        self.add(t1)
        turn_animation_into_updater(anim1)
        self.wait(3)
```
Result of cairo-backend: 
![out2](https://user-images.githubusercontent.com/55699713/107531571-f2d3e800-6bf7-11eb-997b-db562d9bda1f.gif)

Result of master branch(shaders): 
![textshaders](https://user-images.githubusercontent.com/55699713/107531732-15fe9780-6bf8-11eb-8823-b903348588a5.gif)

Please take a look at this issue, and I am considering create a new method to make it work properly. 
(~~Oh My Poor English~~)

**Comment by 3b1b** [comment]
It should be fixed now, thanks for pointing it out.
