### ISSUE TITLE
Bug in Interactive Mobjects

### ISSUE THREAD

**Issue by sahilmakhijani** [3b1b/manim#1385]
### Bug
When running `ControlsExample` Scene in ExampleScenes.py, I am getting maximum recursion depth exceeded error.

**Code**:
`ControlsExample` Scene in `example_scenes.py`.

**Wrong display or Error traceback**:
```RecursionError: maximum recursion depth exceeded```

### Analysis
This bug is caused because of the following:
1. `text.add_updater(text_updater)` calls `text_updater` (because add_updater has call_updater default to True)
2. `text_updater` calls `old_text.become(new_text)`
3. `become` calls `align_family`
4. `align_family` calls `add_n_more_submobjects`
5. `add_n_more_submobjects` calls `self.copy()`
6. `copy()` calls `match_updaters`
7. `match_updaters` calls `add updater(text_updater)` on `copy_mobject`
8. `add_updater(text_updater)` calls `text_updater` (because add_updater has call_updater default to True)
9. This takes back to 1. and this continues indefinately

I tried to figure out which commit broke this Scene, and found that before this commit https://github.com/3b1b/manim/commit/d7f3f5ad24b22ed7bc85ee27df03319498fa863f, everything was working fine.
So this bug is caused due to something changed in https://github.com/3b1b/manim/commit/d7f3f5ad24b22ed7bc85ee27df03319498fa863f commit.

**Comment by sahilmakhijani** [comment]
By adding `self.suspend_updating(recurse)` back in `clear_updaters` method of `Mobject` fixes this issue. I don't know why?
This line was removed in https://github.com/3b1b/manim/commit/d7f3f5ad24b22ed7bc85ee27df03319498fa863f commit.

But now the `Scene`'s mouse_point is off of mouse_cursor which breaks interactive mobjects that respond to mouse_cursor.
To check where the mouse_point is, try running the below scene:

```
class ShowMouseCursorLocation(Scene):
    def construct(self):
        mouse_dot = Dot()
        mouse_dot.add_updater(lambda mob: mob.move_to(self.mouse_point))
        self.add(mouse_dot)
        self.interact()
```

**Comment by sahilmakhijani** [comment]
Instead of adding `self.suspend_updating(recurse)`, you could move `self.refresh_has_updater_status()` in `clear_updaters()` below `submob.clear_updaters()` just above `return_self`.

```
def clear_updaters(self, recurse=True):
        self.time_based_updaters = []
        self.non_time_updaters = []
        if recurse:
            for submob in self.submobjects:
                submob.clear_updaters()
        self.refresh_has_updater_status()
        return self
```

**Comment by TonyCrane** [comment]
Any progress on this issue?
`ControlsExample` scene still can't run, which I think is really a big problem.

**Comment by sahilmakhijani** [comment]
By adding `self.suspend_updating(recurse)` back in `clear_updaters` method of `Mobject` class fixes this issue.
This line was removed in https://github.com/3b1b/manim/commit/d7f3f5ad24b22ed7bc85ee27df03319498fa863f commit.

**Comment by sahilmakhijani** [comment]
I am not sure why it was removed earlier that's why I opened this issue.

**Comment by sahilmakhijani** [comment]
On a side note, I earlier added `"listen_to_events"` attribute in `Mobject` `CONFIG` while developing this and never used it!!
Should I make a pull request removing it?

**Comment by sahilmakhijani** [comment]
@TonyCrane, I've made a pr addressing this

**Fix ControlsExample Scene** https://github.com/3b1b/manim/pull/1551
