### ISSUE TITLE
KeyError: 'window_monitor'

### ISSUE THREAD

**Issue by liyiliuxingyu** [3b1b/manim#1388]
### Describe the error
KeyError: 'window_monitor'

### Code and Error
**Code**:
E:\code\manim (master -> origin)
(manim) λ manimgl example_scenes.py OpeningManimExample
Warning: Using the default configuration file, which you can modify in e:\code\manim\manimlib\default_config.yml
        If you want to create a local configuration file, you can create a file named custom_config.yml, or run manimgl --config

Traceback (most recent call last):
  File "D:\ProgramData\Miniconda3\envs\manim\Scripts\manimgl-script.py", line 33, in <module>

    sys.exit(load_entry_point('manimgl', 'console_scripts', 'manimgl')())
  File "e:\code\manim\manimlib\__main__.py", line 13, in main
    config = manimlib.config.get_configuration(args)
  File "e:\code\manim\manimlib\config.py", line 237, in get_configuration
    monitor = get_monitors()[custom_config["window_monitor"]]
KeyError: 'window_monitor'

**Error**:
KeyError: 'window_monitor'

### Environment
**OS System**: Windows 7
**manim version**: master 
**python version**: Python 3.8.5

**Comment by TonyCrane** [comment]
Try refreshing your manim source code, `window_monitor` is in `default_config.yml`:
https://github.com/3b1b/manim/blob/b7e2abb8016021f468c2f4c98790c94a75040a3f/manimlib/default_config.yml#L36

**Comment by liyiliuxingyu** [comment]
Thank you! Mk
