### ISSUE TITLE
Manim example.py SqaureToCircle error

### ISSUE THREAD

**Issue by Shantanu-Manim** [3b1b/manim#1409]
i have just installed Manim.
new to this, i am unable to solve this issue please tell me a detailed solution for this
-l is deprecated and there is no scence in module
WARNING  Option -l is deprecated please use the --quality/-q flag.                     utils.py:137
(process:10476): GLib-GIO-WARNING **: 01:19:57.924: Unexpectedly, UWP app `20815shootingapp.AirFileViewer_1.4.10.0_x64__xcg28tkrsnqww' (AUMId `20815shootingapp.AirFileViewer_xcg28tkrsnqww!App') supports 316 extensions but has no verbs
                    ERROR                                                                              module_ops.py:65
                                There are no scenes inside that module
![manim_example py_issue](https://user-images.githubusercontent.com/79604276/109058861-871a7080-7709-11eb-983d-41e6df699192.png)

**Comment by FuckerLinda** [comment]
same problem!😅

**Comment by TonyCrane** [comment]
I think this is an issue of community version, please open an issue in [ManimCommunity/manim](https://github.com/ManimCommmunity/manim) instead of here.
