### ISSUE TITLE
Tex File doesn't exist in example_scenes.py example

### ISSUE THREAD

**Issue by starskyC** [3b1b/manim#1414]
### Describe the error
The display of example scene went wrong while running. Tex File doesn't exist.

### Code and Error
**Code**:
1. Clone the repo
2. `cd` into and `pip install -e .`
3. `manimgl example_scenes.py OpeningManimExample` as described in the README

**Error**:
The first line is from `print(f"opening {os.path.dirname(tex_file)}")` in `utils/tex_file_writing.py:text_to_dvi` function, I think this is where the problem is: something went wrong when parsing the IntegerMatrix's brackets string and got it into the `text_file` variable.
```
opening C:\Users\ADMINI~1\AppData\Local\Temp\Tex\end{array}\right]"
ERROR:root:

 LaTeX Error!  Not a worry, it happens to the best of us.

Traceback (most recent call last):
  File "D:\Program Files\Python3\Scripts\manimgl-script.py", line 33, in <module>
    sys.exit(load_entry_point('manimgl', 'console_scripts', 'manimgl')())
  File "d:\public\manim\manimlib\__main__.py", line 17, in main
    scene.run()
  File "d:\public\manim\manimlib\scene\scene.py", line 75, in run
    self.construct()
  File "example_scenes.py", line 29, in construct
    IntegerMatrix(matrix, include_background_rectangle=True),
  File "d:\public\manim\manimlib\mobject\matrix.py", line 81, in __init__
    self.add_brackets()
  File "d:\public\manim\manimlib\mobject\matrix.py", line 111, in add_brackets
    bracket_pair = Tex("".join([
  File "d:\public\manim\manimlib\mobject\svg\tex_mobject.py", line 167, in __init__
    super().__init__(full_string, **kwargs)
  File "d:\public\manim\manimlib\mobject\svg\tex_mobject.py", line 42, in __init__
    filename = tex_to_svg_file(full_tex)
  File "d:\public\manim\manimlib\utils\tex_file_writing.py", line 54, in tex_to_svg_file
    tex_to_svg(tex_file_content, svg_file)
  File "d:\public\manim\manimlib\utils\tex_file_writing.py", line 62, in tex_to_svg
    svg_file = dvi_to_svg(tex_to_dvi(tex_file))
  File "d:\public\manim\manimlib\utils\tex_file_writing.py", line 97, in tex_to_dvi
    with open(log_file, "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\Tex\\cf5d7f9f2e57398a.log'
```
### Environment
**OS System**: Windows 10
**manim version**: master 
**python version**: `3.9.0`

**Comment by GalymzhanTutkushev** [comment]
I had the same problem. And today I finally solved it. You have "~" sign in your directory name. I have changed my path and it worked for me.

**Comment by dizlex** [comment]
you cannot have any special characters, spaces or numbers in any parent directory where you intend to use manim.

**Comment by crobinson96** [comment]
I'm getting the same error. I have

> I had the same problem. And today I finally solved it. You have "~" sign in your directory name. I have changed my path and some modified the source code and then it worked for me.

Can you share the changes you made to the path/source code?

**Comment by joacortez** [comment]
> I'm getting the same error. I have
> 
> > I had the same problem. And today I finally solved it. You have "~" sign in your directory name. I have changed my path and some modified the source code and then it worked for me.
> 
> Can you share the changes you made to the path/source code?

What I did was directly in my C drive (or somewhere where there aren't any special characters) I created my own folder for temporary files. Then in \manimlib\utils\directories.py I edited the function called  get_temp_dir() and changed the return value to the path of the folder that I created. It also helps to clone the manimgl repository to a folder directly on your C drive.
Hope it helps! If not let me know.

**Comment by Shafagh777** [comment]
Hi Joa

I have the same issue. I have done as per your suggestion like creating a drive TempL in my C drive but don't know here i have to apply these changes in directories.py. do you mean on the following line:

def get_temp_dir():
    return get_directories()["temporary_storage"]

**Comment by Shafagh777** [comment]
Dear Ali

Thank you so much for your great direction. Now, everything works fine...

**Comment by AllestorOakley** [comment]
I also got the same error, I think it is because there is space in my user folder

So I run a test, I create a new local user account, without a space in its name
and the error gone

**Comment by ArmZam** [comment]
Hi,

Sorry for adding to a closed ticket but if you face this issue too, there is a simpler solution which is to specify a temp path in the manim config (<PATH_TO_MANIM_SRC>/manimlib/default_config.yml). You'll find a parameter named "temporary_storage", just give a valid path for this one. 

If not present the librairy will fetch this from your TMP environment variable, which may contains a ~ causing this issue, by providing the path you bypass this problem.
