### ISSUE TITLE
Error using Elbow()

### ISSUE THREAD

**Issue by yerovi84** [3b1b/manim#1416]
### Describe the error
I tried to use the Elbow() object but I got an error.
 
### Code and Error
**Code**:
class ElbowExample(Scene):
    def construct(self):
        triangle = Polygon(ORIGIN, RIGHT, RIGHT+UP)
        elbow = Elbow(color=RED)
        elbow.set_points_as_corners([ORIGIN, RIGHT, RIGHT+UP])
        elbow.set_width(elbow.width, about_point=RIGHT+np.array([-0.1, 0.1, 0.0]))
        self.add(triangle)
        self.add(elbow)
        self.wait(2)

**Error**:
...geometry.py", line 572, in __init__ 
in __init__
    super().__init__(self, **kwargs)
TypeError: __init__() takes 1 positional argument but 2 were given

### Environment
**OS System**: Win10 
**manim version**: version of 23/02/2021
**python version**: 3.8.1

**Comment by JWro** [comment]
The problem is passing `self` to `super().__init__`, see https://github.com/3b1b/manim/pull/1419/commits/63b497c352eff38cd5b16b32fd9f385fd902a59f
