### ISSUE TITLE
Latex Error converting to dvi. (Other issues concerning this don't work...)

### ISSUE THREAD

**Issue by jacobhelbig** [3b1b/manim#142]
Hi! I'm on mac, got all the requirements installed, but everytime I run WriteStuff in example_scenes.py:
`$ python extract_scene.py example_scenes.py WriteStuff -p`
and I get the following error:
`Writing to /Users/jacob 1/Desktop/manim-master/animations/example_scenes/WriteStuffTemp.mp4
Traceback (most recent call last):
  File "extract_scene.py", line 255, in main
    handle_scene(SceneClass(**scene_kwargs), **config)
  File "/Users/jacob 1/Desktop/manim-master/scene/scene.py", line 69, in __init__
    self.construct(*self.construct_args)
  File "/Users/jacob 1/Desktop/manim-master/./example_scenes.py", line 66, in construct
    self.play(Write(TextMobject("Stuff").scale(3)))
  File "/Users/jacob 1/Desktop/manim-master/mobject/tex_mobject.py", line 56, in __init__
    self.template_tex_file
  File "/Users/jacob 1/Desktop/manim-master/mobject/tex_mobject.py", line 331, in tex_to_svg_file
    dvi_file = tex_to_dvi(tex_file)
  File "/Users/jacob 1/Desktop/manim-master/mobject/tex_mobject.py", line 376, in tex_to_dvi
    "See log output above or the log file: %s" % log_file)
Exception: Latex error converting to dvi. See log output above or the log file: /Users/jacob 1/Desktop/manim-master/files/Tex/2819777233570814671.log`
I know that there are a few issues concerning similar errors, but I either don't understand the solutions or they just don't work for me. Can someone help me? Thank you so much!

**Comment by left0077** [comment]
Try to delete the `\usepackage[UTF8]{ctex}` in `text_template.tex`.

**Comment by jacobhelbig** [comment]
Doesn't work for me, thanks anyway!

**Comment by left0077** [comment]
https://github.com/3b1b/manim/issues/64
May be this can help you.

**Comment by jacobhelbig** [comment]
Already tried it, didn't work.

**Comment by npetrangelo** [comment]
I'm having the same issue. Are you getting this log as well?
[-3638975780047885032.log](https://github.com/3b1b/manim/files/1798556/-3638975780047885032.log)

**Comment by not7cd** [comment]
also getting this

**Comment by kiranajij** [comment]
[https://github.com/3b1b/manim/pull/260](url)
check the pull request, this request regards the issue.

**Comment by bhopro** [comment]
I am also getting this same error. Were any of you able to get past this point?

**Comment by eulertour** [comment]
Closing, since this issue was resolved in the issue referenced above.
