### ISSUE TITLE
no module named manim

### ISSUE THREAD

**Issue by lkssmr** [3b1b/manim#1422]
DISCLAIMER: I have no experience with coding.....
### Describe the error
I want to install manim, after that I want to run the example scene and it shows this: 

### Code and Error
**Code**:
cd manim
python -m manim example_scenes.py SquareToCircle -pl

**Error**:
C:\Users\lkssm\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe: No module named manim

### Environment
**OS System**: WINDOWS
**python version**: 3.0

**Comment by TONJA233** [comment]
You should use Code：pip install manim

**Comment by fabriciosb** [comment]
> u should use Code：**pip install manim**

This will install the other version of Manim (the Comunity Edition one: https://www.manim.community/). Then, 
`python -m manim` will call that other Manim (which has different CLI flags and run different scripts). For the 3b1b edition you need to use `pip install manimgl` and you should create scenes with `manimgl scene.py`.
