### ISSUE TITLE
How to make the text full screen? 

### ISSUE THREAD

**Issue by Just-Math** [3b1b/manim#1426]
Hello! 
I have a text. I use `a = TextMobject("""Text on screen""").scale(0.5).to_edge(UL).set_color("#383838")`. 
As a result, the text is visible only half of the screen. How do I make the text appear all over the screen? How to reduce the margin from the edges? Is there any way to make the alignment to the left or to the width.

[screenshot link](https://prnt.sc/10b5s1c)

_Originally posted by @Just-Math in https://github.com/3b1b/manim/discussions/1425_

**Comment by TonyCrane** [comment]
Seems solved in #1425, so closing this.
