### ISSUE TITLE
manim cannot find ffmpeg

### ISSUE THREAD

**Issue by CyrilSLi** [3b1b/manim#1435]
OS: macOS 11.2.2

error:

Warning (from warnings module):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pydub/utils.py", line 170
    warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work

**Comment by chongchonghe** [comment]
Try `ffmpeg -version` and see what happens

**Comment by pseudo-usama** [comment]
Probably you did not set path for ffmpeg. Check it by typing ffmpeg in terminal.

**Comment by raunak51299** [comment]
Don't install it from pip, download and install form [here](https://www.ffmpeg.org/)

**Comment by zbrun** [comment]
i got the same issues,that when i show it just on screen it worked,but when i want to storage  it will show "Couldn't find ffmpeg ".

**Comment by TonyCrane** [comment]
Did you install ffmpeg, `brew install ffmpeg` first.
