### ISSUE TITLE
Chained animations don't work

### ISSUE THREAD

**Issue by rolisz** [3b1b/manim#1457]
### Describe the bug
When running multiple animations in on self.play call, only the last one is executed. 

**Code**:
Minimal code example:
```
class CoordinateSystemExample(Scene):
    def construct(self):
        dot = Dot(color=RED)
        self.play(FadeIn(dot, scale=0.5))

        self.play(
            dot.animate.scale(75),
            dot.animate.to_corner(UL),
            run_time=2,
        )
```

**Wrong display or Error traceback**:
What I get is:
![CoordinateSystemExample](https://user-images.githubusercontent.com/426313/113418757-9c905380-93b5-11eb-974d-336339dec97a.png)
What I expect is a a huge dot in the top right corner. 

### Additional context
The CoordinateSystemExample example exhibits the same issue: the axes and the dot get moved to top right corner, but they don't get scaled, like in the video.

**Comment by 3b1b** [comment]
See https://github.com/3b1b/manim/issues/1463
