### ISSUE TITLE
Hving problems in cmd

### ISSUE THREAD

**Issue by wargod1632** [3b1b/manim#1460]
I have problems in cmd like when I write manim -m ok.py  TestScene -pl  i do not get my desired products
and ultimately i do not get any of the animations

**Comment by alayoalex** [comment]
I advice you read the docs again, because authors have changed things around. For example, the main command now is manimgl. I hope this could be helpfull.

**Comment by wargod1632** [comment]
'manimgl' is not recognized as an internal or external command,
operable program or batch file.

**Comment by TonyCrane** [comment]
Please install manim as the doc says.
If you are using the community version, please open an issue there instead of here.
