### ISSUE TITLE
NumberPlane() axis_config.x_min and x_max do not seem to update the axis bounds

### ISSUE THREAD

**Issue by 3dfernando** [3b1b/manim#1470]
Hopefully this is not a bug (I'm still learning to use Manim); but I think it might be worth looking into by a more experienced user.

If I create a NumberPlane defining its axis bounds with x_axis_config, it behaves as expected; changing the axis bounds. On the other hand, if the definition of the axis bounds is made under the axis_config parameter, then it does not update the bounds.

Here's an MWE:

```
class XboundsError(MovingCameraScene):           
    def setup(self):
        MovingCameraScene.setup(self)
    def construct(self):
        self.camera.frame.save_state()


        #This line below creates the grid correctly
        #grid = NumberPlane(x_axis_config={"x_min": -20, "x_max": 20}) 
        #This line below creates the grid **BUT IT IGNORES THE AXIS BOUNDS**
        grid = NumberPlane(axis_config={"x_min": -20, "x_max": 20})

        self.play(Create(grid),run_time=1)
        self.wait(1)
        self.play(self.camera.frame.animate.move_to([5,0,0])) #When creating NumberPlane with axis_config, this camera motion reveals where the plane ends
        self.wait(1)
        self.play(self.camera.frame.animate.move_to([-5,0,0]))
        self.wait(1)

**Comment by TonyCrane** [comment]
<img width="1374" alt="截屏2021-06-12 下午6 11 11" src="https://user-images.githubusercontent.com/44120331/121772699-a39fc300-cba9-11eb-899a-a6f3ffb207e2.png">
I think this is a correct performance?
