### ISSUE TITLE
ThreeDScene methods not implemented but give no warning

### ISSUE THREAD

**Issue by CodingPower472** [3b1b/manim#1476]
### Describe the bug
The methods in the ThreeDScene class are unimplemented, with simply a comment with "TODO" in them.

**Code**:
class VField(ThreeDScene):
    def electric_field(self, x, y, z):
        if (x*x + y*y + z*z == 0):
            return np.array([0, 0, 0])
        scale_factor = 1 / (x*x + y*y + z*z)
        return np.array([x*scale_factor, y*scale_factor, z*scale_factor])
    def construct(self):
        vector_field = VectorField(self.electric_field,  ThreeDAxes())
        self.add(vector_field)
        self.add(ThreeDAxes())
        self.wait(5)
        self.move_camera(phi=PI, theta=2*PI)

**Wrong display or Error traceback**:
It just doesn't do anything when the method is run

### Additional context
I understand that it can't immediately be implemented because other features have to be prioritized, but there should at least be a warning when the method is run that it isn't implemented, because someone could easily spend hours trying to figure out why their code isn't working only to find out that the method is simply not implemented.

**Comment by TonyCrane** [comment]
In the new version, ThreeDScene is nearly the same as Scene. You can change the position of `self.camera.frame` to achieve your goal.
