### ISSUE TITLE
ImportError: cannot import name

### ISSUE THREAD

**Issue by bencheung8506** [3b1b/manim#148]
While running the code of example scene (or other file, e.g. basel.py), I get stuck into the ImportError:

File "extract_scene.py", line 15, in <module>
    from scene import Scene
ImportError: cannot import name 'Scene'

The error varies as I try to run different files, which the same error ImportError is encountered in different modules/classes in different py file.

I suppose that the cause is somehow related to location of files I should put. Now I just download the file , move nothing and compile the code. Is there any clue what might be the cause of the error?

**Comment by cclauss** [comment]
The definition of __scene.Scene__ is here https://github.com/3b1b/manim/blob/master/scene/scene.py#L28

**Comment by eulertour** [comment]
Closing, as this issue is old and inactive. Feel free to reopen it if this is still an issue.
