### ISSUE TITLE
cannot import name 'Paragraph' from 'manimlib.mobject.svg.text_mobject'

### ISSUE THREAD

**Issue by LavMehta** [3b1b/manim#1489]
![image](https://user-images.githubusercontent.com/45895526/115379928-4e12ef80-a1d2-11eb-9d7f-503f7891f8c3.png)

from manimlib.imports import* throwing above mentioned error.

On the repository i am not able to find the file code_mobject.py whereas after downloading the package using pip, i do see this file in my local machine.

**Comment by TonyCrane** [comment]
Update your source code and reinstall it.
