### ISSUE TITLE
Manim IndexError: List index out of range when using Tex() 

### ISSUE THREAD

**Issue by ShahrOZe69** [3b1b/manim#1495]
from manim import *
class HelloTex(Scene):
    def construct(self):
        tex = Tex(r'\LaTeX').scale(3)
        self.play(Write(tex))

Why is it giving me an error??

    Manim Community v0.5.0                                                          c:\users\abc\appdata\local\programs\python\python38\lib\site-packages\manim\mobject\svg\svg_mobject.py:263: UserWarning: media/Tex/b19590c23cea3796.svg contains a reference to id #g1-76, which is not recognized                                warnings.warn(warning_text)                                                   c:\users\abc\appdata\local\programs\python\python38\lib\site-packages\manim\mobject\svg\svg_mobject.py:263: UserWarning: media/Tex/b19590c23cea3796.svg contains a reference to id #g0-65, which is not recognized                                warnings.warn(warning_text)                                                   c:\users\abc\appdata\local\programs\python\python38\lib\site-packages\manim\mobject\svg\svg_mobject.py:263: UserWarning: media/Tex/b19590c23cea3796.svg contains a reference to id #g1-84, which is not recognized                                warnings.warn(warning_text)                                                   c:\users\abc\appdata\local\programs\python\python38\lib\site-packages\manim\mobject\svg\svg_mobject.py:263: UserWarning: media/Tex/b19590c23cea3796.svg contains a reference to id #g1-69, which is not recognized                                warnings.warn(warning_text)                                                   c:\users\abc\appdata\local\programs\python\python38\lib\site-packages\manim\mobject\svg\svg_mobject.py:263: UserWarning: media/Tex/b19590c23cea3796.svg contains a reference to id #g1-88, which is not recognized                                warnings.warn(warning_text)                                                   Traceback (most recent call last):                                              ┌─────────────────────────────────────────────────────────────────────────────┐ │ File "c:\users\abc\appdata\local\programs\python\python38\lib\site-packages\│ │manim\__main__.py", line 76, in main                                         │ │    73             for SceneClass in scene_classes_from_file(input_file):    │ │    74                 try:                                                  │ │    75                     scene = SceneClass()                              │ │  ? 76                     scene.render()                                    │ │    77                 except Exception:                                     │ │    78                     console.print_exception()                         │ │    79                                                                       │ │ File "c:\users\abc\appdata\local\programs\python\python38\lib\site-packages\│ │manim\scene\scene.py", line 183, in render                                   │ │     180         """                                                         │ │     181         self.setup()                                                │ │     182         try:                                                        │ │  ?  183             self.construct()                                        │ │     184         except EndSceneEarlyException:                              │ │     185             pass                                                    │ │     186         self.tear_down()                                            │ │ File "D:\Py\MathAnim\intro.py", line 4, in construct                        │ │    1 from manim import *                                                    │ │    2 class HelloTex(Scene):                                                 │ │    3     def construct(self):                                               │ │  ? 4         tex = Tex(r'\LaTeX').scale(3)                                  │ │    5         self.play(Write(tex))                                          │ │ File "c:\users\abc\appdata\local\programs\python\python38\lib\site-packages\│ │manim\mobject\svg\tex_mobject.py", line 515, in __init__                     │ │    512     def __init__(                                                    │ │    513         self, *tex_strings, arg_separator="", tex_environment="center│ │    514     ):                                                               │ │  ? 515         MathTex.__init__(                                            │ │    516             self,                                                    │ │    517             *tex_strings,                                            │ │    518             arg_separator=arg_separator,                             │ │ File "c:\users\abc\appdata\local\programs\python\python38\lib\site-packages\│ │manim\mobject\svg\tex_mobject.py", line 394, in __init__                     │ │    391             tex_template=self.tex_template,                          │ │    392             **kwargs,                                                │ │    393         )                                                            │ │  ? 394         self.break_up_by_substrings()                                │ │    395         self.set_color_by_tex_to_color_map(self.tex_to_color_map)    │ │    396                                                                      │ │    397         if self.organize_left_to_right:                              │ │ File "c:\users\abc\appdata\local\programs\python\python38\lib\site-packages\│ │manim\mobject\svg\tex_mobject.py", line 443, in break_up_by_substrings       │ │    440                 # positioned in the right part of the MathTex        │ │    441                 sub_tex_mob.submobjects = [VectorizedPoint()]        │ │    442                 last_submob_index = min(curr_index, len(self.submobje│ │  ? 443                 sub_tex_mob.move_to(self.submobjects[last_submob_inde│ │    444             else:                                                    │ │    445                 sub_tex_mob.submobjects = self.submobjects[curr_index│ │    446             new_submobjects.append(sub_tex_mob)                      │ └─────────────────────────────────────────────────────────────────────────────┘ IndexError: list index out of range

**Comment by kolibril13** [comment]
Hello @ShahrOZe69,
as you are using the community version, please report your issue here:
https://github.com/ManimCommunity/manim/issues
and close this issue at the 3b1b repo.
