### ISSUE TITLE
Manim write text out of the window

### ISSUE THREAD

**Issue by Leoriem-code** [3b1b/manim#1497]
### Describe the error
When I use the Scene TextExample found [here](https://3b1b.github.io/manim/getting_started/example_scenes.html), only part of the text show up. I need to zoom out to see everything, and when I save the video, I can only see like I haven't zoom out.

### Code and Error
**Code**:
[This](https://3b1b.github.io/manim/getting_started/example_scenes.html) Scene TextExample.

**Error**:
Can't see some words.

### Environment
**OS System**: Windows 10
**manim version**: Release 1.0.0
**python version**: 3.9.4

**Comment by Leoriem-code** [comment]
This is the output:

https://user-images.githubusercontent.com/73761711/115927849-665e6500-a485-11eb-95d2-fd50e69fe841.mp4

**Comment by julio4** [comment]
I have the same problem.
Related issues #1399 #1405
