### ISSUE TITLE
Cosine Graph Error

### ISSUE THREAD

**Issue by mra31693** [3b1b/manim#1520]
I am trying to create a cosine graph using Manim but it was different from the actual graph.
**Code**:
```
from manim import *
from numpy import cos

class CreateGraph(GraphScene):
    def __init__(self, **kwargs):
        GraphScene.__init__(
            self,
            x_min=-5,
            x_max=5,
            y_min=-5,
            y_max=5,
            graph_origin=ORIGIN,
            axes_color=GREEN)


    def construct(self):
        # Create Graph
        self.setup_axes(animate=True)
        f1 = self.get_graph(lambda x: cos(1/x) , x_min=-4, x_max=4)
        
        # Construct the Figures
        self.play(ShowCreation(f1))
        self.wait(1)
```
**Error**:
![cos](https://user-images.githubusercontent.com/84633335/119231937-c3693b80-bb55-11eb-9ea6-541390769420.PNG)
![cos2](https://user-images.githubusercontent.com/84633335/119231939-c49a6880-bb55-11eb-89d0-64a8f1b8bcc5.PNG)

### Environment
**OS System**: Windows 10
**manim version**: master <V.6 Community Version>
**python version**: .3.7.0

**Comment by TonyCrane** [comment]
I think you are using the community version of manim.
So you're supposed to ask this question on discord of ManimCommunity or open an issue in [ManimCommunity/manim](https://github.com/ManimCommunity/manim) instead of here.
