### ISSUE TITLE
Complex transformation of line behaving weirdly

### ISSUE THREAD

**Issue by ShahrOZe69** [3b1b/manim#1524]
```
from manim import *
#config['frame_height'] = 10.0
#config['frame_width'] = 10.0
class Method(Scene):
    def construct(self):

       text = Tex(r"Applying Complex Transformations")
       self.play(Create(text))

class Complex(Scene):
    def construct(self):
        d=ComplexPlane()
        k=d.copy()
        self.play(Create(d))
        self.add(k)
        line = Line(start=[2,0,0],end=[2,5,0],stroke_width=3,color=RED)
        circle = Circle().shift(RIGHT)
        self.add(line)
        c = Circle().shift(RIGHT)
        self.play(c.animate.apply_complex_function(lambda z:z**2)) #works correctly
        self.play(line.animate.apply_complex_function(lambda z:1/z),run_time=5) #behaving wierdly
        self.play(circle.animate.apply_complex_function(lambda z:1/z),run_time=5) #behaving wierdly
```
    The complex transformation of the line should map the line to a circle passing through the origin, also the complex transformation of the circle centered at 1,0,0 of radius 1 should map to a line.

![manim1](https://user-images.githubusercontent.com/78975075/119939496-9a103b80-bfab-11eb-8675-e2593b9c59c7.png)
![manim2](https://user-images.githubusercontent.com/78975075/119939506-9d0b2c00-bfab-11eb-88f1-58da25cc1d75.png)

**Comment by TonyCrane** [comment]
I think you are using the community version of manim.
So you're supposed to ask this question on discord of ManimCommunity or open an issue in [ManimCommunity/manim](https://github.com/ManimCommunity/manim) instead of here.
