### ISSUE TITLE
Error: No such option: -m

### ISSUE THREAD

**Issue by Kalako** [3b1b/manim#1525]
![image](https://user-images.githubusercontent.com/79514552/120066251-11120680-c076-11eb-8039-148d9c9b20f4.png)
I'm guessing that the problem is at line 7.

**Comment by Bruno-Noobador** [comment]
I am having the same problem with all flags. It doesnt work even by command line.

**Comment by Bruno-Noobador** [comment]
Now, to use this flag, you need to type "-qm". And if you want to preview, you need to write "-pqm".

**Comment by TonyCrane** [comment]
There is no option `-p` now, you can just use `-m` only.
