### ISSUE TITLE
Tex text not the correct size

### ISSUE THREAD

**Issue by Leoriem-code** [3b1b/manim#1533]
### Describe the error
When running the code, the size doesn't match the one expected (and quite a bit)

### Code and Error
**Code**:
```
#Made by JsonV on the Manim Discord
class NumGenerator(Scene):
    def construct(self):
        num_gen_tex = Tex("Number Generator: ").to_edge(UL)
        self.play(Write(num_gen_tex))

        i = 0
        nums = []
        animations = []
        for k in range(10):
            a = np.random.normal(loc=100, scale=15)
            num = DecimalNumber(num_decimal_places=0).set_value(a)
            num.next_to(num_gen_tex, RIGHT)
            nums.append(num)
            animations.append(Write(num))
            animations.append(num.animate.to_edge(DL).shift(RIGHT*i))
            i += 1.3

        for animation in animations:
            self.play(animation)
        for num in nums:
            num.set_fill(ORANGE)
        nums[0].set_fill(BLUE)

        self.wait()
```

### Output
**Result Expected**
https://user-images.githubusercontent.com/73761711/121065729-62826a00-c7c9-11eb-92c2-ee10d007166f.mp4

**Result Get**
https://user-images.githubusercontent.com/73761711/121065787-6f06c280-c7c9-11eb-8ae9-69710c64889d.mp4

### Environment
**OS System**: Windows 10
**manim version**: master 
**python version**: 3.9.5

**Comment by Leoriem-code** [comment]
I will annoy you again but this is not resolved.
I installed the new version of manim (this one, with the branch merged), launch the code and it still has numbers oversized. I can't manage to understand what is wrong:
![image](https://user-images.githubusercontent.com/73761711/122615278-90e52c80-d088-11eb-80ca-23f2061e398a.png)

**Comment by TonyCrane** [comment]
> I will annoy you again but this is not resolved.
> I installed the new version of manim (this one, with the branch merged), launch the code and it still has numbers oversized. I can't manage to understand what is wrong:
> ![image](https://user-images.githubusercontent.com/73761711/122615278-90e52c80-d088-11eb-80ca-23f2061e398a.png)

Try #1555

**Comment by Leoriem-code** [comment]
I tried, it didn't work. This issue is certainly linked with the DecimalNumber Class, more specifically with set_submobjects_from_number() that is called by set_value(), in which we try to scale the numbers (either with self.arrange() line 44 or with string_to_mob() line 35)

**Comment by TonyCrane** [comment]
I had a look at it. This issue is not linked with `DecimalNumber`. It is just because that `Text` is still a little larger than `TexText` and `Tex`. `TEXT_MOB_SCALE_FACTOR = 0.0076` works well for me, so do you think I should modify `TEXT_MOB_SCALE_FACTOR` to 0.0076?

**Comment by Leoriem-code** [comment]
I looked at it too and yes, I think that 0.0076 is better

**Comment by Leoriem-code** [comment]
But now I have a bigger problem. The text in the example `OpeningManimExample` is, for a lack of better words, broken:

https://user-images.githubusercontent.com/73761711/122640896-296bc300-d102-11eb-8fbf-5df02c0bc376.mp4

**Comment by TonyCrane** [comment]
But it works fine with me.

https://user-images.githubusercontent.com/44120331/122641263-c9dbda80-d136-11eb-8ae4-6a4d7f9fa221.mp4

My command:
```sh
gh pr checkout 1555        # GitHub CLI
python -m manimlib example_scenes.py OpeningManimExample -wo
```

**Comment by Leoriem-code** [comment]
I will look into the camera problem another time, thanks for trying. Do you have an idea why `complex_map_words = TexText("""Or thinking of the plane as $\\mathds{C}$, this is the map $z \\rightarrow z^2$""")` write just the LaTeX syntax ?

**Comment by TonyCrane** [comment]
Maybe you can find it in issues page. I remember that I have seen it before.

**Comment by Leoriem-code** [comment]
I will search, thanks
