### ISSUE TITLE
Bug of always_redraw in animations

### ISSUE THREAD

**Issue by TonyCrane** [3b1b/manim#1544]
### Describe the bug

I found a bug about updater in CoordinateSystemExample

https://user-images.githubusercontent.com/44120331/122047649-f62fe800-ce12-11eb-8593-081da852f0e2.mp4

As in this video, `h_line` and `v_line` are two mobjects with updater function `always_redraw`. And they only show the effect of `add` in `ShowCreation`, and only show the effect of `remove` in `FadeOut`.

I think this is a problem that occurs when the mobject with `always_redraw` is animated, so I tried the following code to prove my opinion:

**Code**:

```python
class Test(Scene):
    def construct(self):
        text = always_redraw(Text, "Text")
        self.wait()
        self.play(Write(text))
        self.play(FadeOut(text))
        self.wait()
```

**Wrong display or Error traceback**:

https://user-images.githubusercontent.com/44120331/122047789-1f507880-ce13-11eb-91bb-626dc72c7297.mp4

@3b1b, can you take a look at this?

**Comment by 3b1b** [comment]
Changing the default value of "suspend_mobject_updating" fixes this, which I just [pushed](https://github.com/3b1b/manim/commit/5ff8e28ba573ff0365c7f685e476fac1b7113197).

I'm not entirely sure why it was ever set to False. Also, it occurs to me that this could use a better name. The idea is that by suspending updating for Animation.mobject, but continuing the updating for Animation.starting_submobject (or in the case of animations like Transform things like target_submobject), the behavior should be as expected.
