### ISSUE TITLE
I want to install manimgl

### ISSUE THREAD

**Issue by peterdruska** [3b1b/manim#1561]
### Describe the error
Hi, I am trying to install new version of Manim called ManimGL using this guide: https://3b1b.github.io/manim/getting_started/installation.html

And I am using this command

### Code and Error
**Code**:
`pip install manimgl`

But with this error during istallation:

**Error**:
```
ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/cc/xvb27tps0pnfm2016lfhg0l40000gn/T/pip-install-sZu51G/moderngl/setup.py", line 13, in <module>
        raise Exception('Python 2 is not supported!')
    Exception: Python 2 is not supported!
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/cc/xvb27tps0pnfm2016lfhg0l40000gn/T/pip-install-sZu51G/moderngl/
```

### Environment
**OS System**: macOS 11.2.3 Big Sur
**manim version**: master v0.5.0
**python version**: 3.9.4

**Comment by TonyCrane** [comment]
`Exception: Python 2 is not supported!`
Maybe `pip` in your computer is a version of python 2.
Try `pip3` insteadl?

**Comment by peterdruska** [comment]
> `Exception: Python 2 is not supported!`
> Maybe `pip` in your computer is a version of python 2.
> Try `pip3` insteadl?

Thank you. This helps me.
