### ISSUE TITLE
Problem import scenes

### ISSUE THREAD

**Issue by yerovi84** [3b1b/manim#1562]
Hi, I am using manimgl under windows 10 64bits, with python 3.9.5 and manimgl updated.

When I run the next code:

from manimlib import *

class Plot1(GraphScene):
    def construct(self):
        self.setup_axes()
        func_graph=self.get_graph(lambda x: np.sin(x))
        self.add(func_graph)

I got the error:

    class Plot1(GraphScene):
NameError: name 'GraphScene' is not defined.

I run the opening examples without problems, please help me.

Thanks

Alejandro Yerovi

**Comment by yerovi84** [comment]
I found that 'GraphScene' is only present in manim the community edition, but I had the same trouble with 'VectorScene' and 'LinearTransformationScene', those classes are in manimlib - scene - vector_space_scene.py 

If someone knows the solution please help me.

Thanks

**Comment by TonyCrane** [comment]
See #1420.
`GraphScene` has been remvoed in the new version, but all its functions can be achieved by `CoordinateSystem`. For more details, see `CoordinateSystemExample` and `GraphExample` in example_scenes.py.
As for `VectorScene` and `LinearTransformationScene`, they have not be modified to adjust to the new version which use OpenGL to render. So they are not imported in `__init__.py`. If you want to use them, you can import them manually.

By the way, if you want to use them like before, you can use the version in the `cairo-backend` branch.
