### ISSUE TITLE
'ScreenRectangle' object has no attribute 'animate' (MovingCameraScene)

### ISSUE THREAD

**Issue by crapthecoder** [3b1b/manim#1571]
The following piece of code (except for imports) was taken from https://docs.manim.community/en/v0.4.0/reference/manim.scene.moving_camera_scene.html#changingcamerawidthandrestore

```
from manim import *
from manimlib.imports import *


class ChangingCameraWidthAndRestore(MovingCameraScene):
    def construct(self):
        text = Text("Hello World").set_color(BLUE)
        self.add(text)
        self.camera.frame.save_state()
        self.play(self.camera.frame.animate.set(width=text.width * 1.2))
        self.wait(0.3)
        self.play(Restore(self.camera.frame))
```

The code results in the following error:

```
Traceback (most recent call last):
  File "c:\users\***\pycharmprojects\testproject\venv\lib\site-packages\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "c:\users\***\pycharmprojects\testproject\venv\lib\site-packages\manimlib\scene\scene.py", line 75, in __init__
    self.construct()
  File "test.py", line 10, in construct
    self.play(self.camera.frame.animate.set(width=text.width * 1.2))
AttributeError: 'ScreenRectangle' object has no attribute 'animate'
```

But I think there's a temporary fix, which is using `self.play(self.camera_frame.set_width, 10)`

**Comment by TonyCrane** [comment]
The code you written is of community version. But you ran it under the 3b1b's cairo-backend version.
If you want to use the community version, follow their docs uninstall 3b1b's manim and reinstall community's manim.

`from manim import *` import everything of community version.
`from manimlib.imports import *` import everything of 3b1b's cairo-backend version.
`from manimlib import *` import everything of 3b1b's new version (manimgl).
Please don't confuse them.
