### ISSUE TITLE
Error with using pip install 

### ISSUE THREAD

**Issue by cltj** [3b1b/manim#1593]
Tried two of the suggested methods for installing this . Here where the results. 

On linux Ubuntu, (WSL)
--------------------------------------------
### Describe the error
ERROR: Could not build wheels for pycairo which use PEP 517 and cannot be installed directly

### Code and Error
pip install manimlib

**Error**:
Building wheels for collected packages: manimpango
Building wheel for manimpango (PEP 517) ... error
ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmp4snc243p build_wheel /tmp/tmpbrxfeyzv
       cwd: /tmp/pip-install-l4lpjr7c/manimpango
  Complete output (31 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/manimpango
  copying manimpango/utils.py -> build/lib.linux-x86_64-3.8/manimpango
  copying manimpango/_version.py -> build/lib.linux-x86_64-3.8/manimpango
  copying manimpango/__init__.py -> build/lib.linux-x86_64-3.8/manimpango
  copying manimpango/cairo.pxd -> build/lib.linux-x86_64-3.8/manimpango
  copying manimpango/cmanimpango.pxd -> build/lib.linux-x86_64-3.8/manimpango
  copying manimpango/glib.pxd -> build/lib.linux-x86_64-3.8/manimpango
  copying manimpango/pango.pxd -> build/lib.linux-x86_64-3.8/manimpango
  copying manimpango/register_font.pxd -> build/lib.linux-x86_64-3.8/manimpango
  copying manimpango/cmanimpango.pyx -> build/lib.linux-x86_64-3.8/manimpango
  copying manimpango/enums.pyx -> build/lib.linux-x86_64-3.8/manimpango
  copying manimpango/register_font.pyx -> build/lib.linux-x86_64-3.8/manimpango
  running build_ext
  building 'manimpango.cmanimpango' extension
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/manimpango
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.8 -c manimpango/cmanimpango.c -o build/temp.linux-x86_64-3.8/manimpango/cmanimpango.o
  manimpango/cmanimpango.c:641:10: fatal error: glib.h: No such file or directory
    641 | #include "glib.h"
        |          ^~~~~~~~
  compilation terminated.
  setup.py:92: RuntimeWarning: pkg-config doesn't exists or doesn't seem to workWe assume that you give the compiler flags usingcorresponding environment variables.
    warnings.warn(
  setup.py:92: RuntimeWarning: pkg-config doesn't exists or doesn't seem to workWe assume that you give the compiler flags usingcorresponding environment variables.
    warnings.warn(
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for manimpango
Failed to build manimpango
ERROR: Could not build wheels for manimpango which use PEP 517 and cannot be installed directly

On windows 10
--------------------------------------------------------------------------
### Describe the error
ERROR: requires a setup.py

### Code and Error
Cloning into 'manim'...
remote: Enumerating objects: 25845, done.
remote: Counting objects: 100% (855/855), done.
remote: Compressing objects: 100% (391/391), done.
remote: Total 25845 (delta 533), reused 675 (delta 385), pack-reused 24990
Receiving objects: 100% (25845/25845), 71.34 MiB | 8.02 MiB/s, done.
Resolving deltas: 100% (18614/18614), done.
$ cd manim/
pip install -e .

ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /mnt/c/local/dev/cl/fun_with/manim
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)

### Environment
**OS System**: Ubuntu-20.04 (in WSL/Windows Subsystem for Linux) / windows 10
**manim version**: I assume it tries to get the latest version
**python version**: 3.8.10

Any tips on what I should try?

**Comment by TonyCrane** [comment]
On Ubuntu, maybe you need to build manimpango manually, see https://github.com/ManimCommunity/manimpango#linuxmacos

As for Windows, maybe you can try to upgrade `pip`, or use `pip install -e . --no-use-pep517` instead?
Anyway, I will try to improve it recently.

Thanks for your feedback :)

**Comment by TonyCrane** [comment]
I just tested it on my windows platform, I successfully ran `pip install -e .` without any errors or warnings.

python version: 3.8.11
pip version: 21.2.2

**Comment by cltj** [comment]
So we have a "It works on my computer" situation, because the docs and my implementation is clearly far apart. 
I think I finally got the "manimpango" installed, but more troubles emerged. 
First it was: 
ImportError: Library "GLU" not found.
The fix for this was "sudo apt install freeglut3-dev" 

The next error was: 
pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"
I have no fix for this. 

Reflecting on this. What happened to just a .exe file you download, run, go through a wizard and boom "it works"? 
Why is the true installation time days when we take into account all the troubleshooting ?
Why is the bar on installing something, anything really set so high, and in such a way that one have to have a big list of pre-requisite and memorized CLI commands to get anywhere?  
Is there any other way of distributing a smoother experience? 
Is there a better way to stop all this "it works on my computer" stuff?

**Comment by TonyCrane** [comment]
Because it's an animation engine, and also a python library. So inevitably you need a lot of dependencies to run, and because they're system dependencies, it's not a good idea to install them directly into the system.

Manim is not very complete at the moment, so it can be a bit cumbersome to use.

As for your question, my guess is that you are using a computer without display system (such as a docker environment, WSL, or remote server). The solution is to create a virtual display system (but I failed to do it). This is a really annoying problem, but there is no better solution. Sorry for that.

**Comment by GaussianZero** [comment]
I am on a WSL Ubuntu, and I was hitting the same issue. I was able to resolve it with the recommendation from TonyCrane, in particular:

```
apt install libpango1.0-dev pkg-config python3-dev
pip install manimpango
pip install manim
```

**Comment by SeseMueller** [comment]
I am on Mac M1 and the manual building of manimpango worked flawlessly, thank you!
https://github.com/ManimCommunity/manimpango#linuxmacos 
For anyone following the instructions, the GitHub repository needs to be cloned before the pip install -e . command is executed.

**Comment by Ultimatedude10** [comment]
> I am on Mac M1 and the manual building of manimpango worked flawlessly, thank you!
> https://github.com/ManimCommunity/manimpango#linuxmacos
> For anyone following the instructions, the GitHub repository needs to be cloned before the pip install -e . command is executed.

Perfect thank you so much! Just commenting to increase search engine hits

**Comment by saurabh-kadian** [comment]
> I am on a WSL Ubuntu, and I was hitting the same issue. I was able to resolve it with the recommendation from TonyCrane, in particular:
> 
> ```
> apt install libpango1.0-dev pkg-config python3-dev
> pip install manimpango
> pip install manim
> ```

Adding here for reference, in case someone is trying to install for specific version of Python3, just add the minor version like 
```
apt install libpango1.0-dev pkg-config python3.x-dev
```

**Comment by CompileZero** [comment]
This worked on my M1 Mac, run the following command first:
`brew install pango pkg-config`

And then run `pip3 install manim`

**Comment by vaibhav3099** [comment]
Faced the same issue on M1 mac, 

`brew install pkg-config`
`pip3 install cython`

and then

`pip3 install manim`

It solved the issue.

### Environment
Chip: M1
OS System: MacOS 12.4
Python: 3.11.2

**Comment by AnadeOre** [comment]
> Faced the same issue on M1 mac,
> 
> `brew install pkg-config` `pip3 install cython`
> 
> and then
> 
> `pip3 install manim`
> 
> It solved the issue.
> 
> ### Environment
> Chip: M1 OS System: MacOS 12.4 Python: 3.11.2

This worked for me as well on M2 mac:

Chip: M2
Os System: MacOS 13.3
Python: 3.11.2

**Comment by JosephMiPatchen** [comment]
> So we have a "It works on my computer" situation, because the docs and my implementation is clearly far apart. I think I finally got the "manimpango" installed, but more troubles emerged. First it was: ImportError: Library "GLU" not found. The fix for this was "sudo apt install freeglut3-dev"
> 
> The next error was: pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None" I have no fix for this.
> 
> Reflecting on this. What happened to just a .exe file you download, run, go through a wizard and boom "it works"? Why is the true installation time days when we take into account all the troubleshooting ? Why is the bar on installing something, anything really set so high, and in such a way that one have to have a big list of pre-requisite and memorized CLI commands to get anywhere? Is there any other way of distributing a smoother experience? Is there a better way to stop all this "it works on my computer" stuff?

I have never related more to a comment.
