### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'sort'

### ISSUE THREAD

**Issue by HarryJoyce** [3b1b/manim#1595]
### Describe the error
https://github.com/cai-hust/manim-tutorial-CN#4-%E5%9F%BA%E7%A1%80%E5%8A%A8%E7%94%BB%E7%B1%BB-scene
11.4 add_fixed_in_frame_mobjects
example run error

### Code and Error
**Code**:
from manimlib.imports import *

class Text3D3(ThreeDScene):
    def construct(self):
        axes = ThreeDAxes()
        self.set_camera_orientation(phi=75 * DEGREES, theta=-45 * DEGREES)
        text3d = TextMobject("This is a 3D text")

        self.add_fixed_in_frame_mobjects(text3d)
        text3d.to_corner(UL)

        self.add(axes)
        self.begin_ambient_camera_rotation()
        self.play(Write(text3d))

        sphere = ParametricSurface(
            lambda u, v: np.array([
                1.5 * np.cos(u) * np.cos(v),
                1.5 * np.cos(u) * np.sin(v),
                1.5 * np.sin(u)
            ]), v_min=0, v_max=TAU, u_min=-PI/2, u_max=PI/2, checkerboard_colors=[RED_D, RED_E],
            resolution=(15, 32)).scale(2)

        self.play(LaggedStartMap(ShowCreation, sphere))
        self.wait(2)

**Error**:
Traceback (most recent call last):
  File "E:\manim\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "E:\manim\manimlib\scene\scene.py", line 75, in __init__
    self.construct()
  File "test.py", line 9, in construct
    self.add_fixed_in_frame_mobjects(text3d)
  File "E:\manim\manimlib\scene\three_d_scene.py", line 184, in add_fixed_in_frame_mobjects
    self.camera.add_fixed_in_frame_mobjects(*mobjects)
  File "E:\manim\manimlib\camera\three_d_camera.py", line 221, in add_fixed_in_frame_mobjects
    for mobject in self.extract_mobject_family_members(mobjects):
  File "E:\manim\manimlib\camera\camera.py", line 212, in extract_mobject_family_members
    mobjects.sort(key=lambda m: m.plot_depth)
AttributeError: 'tuple' object has no attribute 'sort'

### Environment
**OS System**: win10
**manim version**: master 
**python version**:3.9.6

**Comment by TonyCrane** [comment]
You said your manim version is master, but I'm sure you are not using the new version of manim (manimgl) in the master branch in this repo.
And I notice that in traceback there has `plot_depth`, so maybe you are using the mk version of old manim.

So you'd better not to open this issue here (and said your manim version is `master`).
