### ISSUE TITLE
Help,The error how to solve?

### ISSUE THREAD

**Issue by onloner2012** [3b1b/manim#16]
C:\Users\Administrator\Desktop\github\manim>python extract_scene.py -p example_scenes.py SquareToCircle
Traceback (most recent call last):
  File "extract_scene.py", line 185, in <module>
    main()
  File "extract_scene.py", line 163, in main
    module = get_module(config["file"])
  File "extract_scene.py", line 155, in get_module
    last_module = imp.load_module(".", *imp.find_module("."))
`ImportError: No module named .`

**Comment by sramsay64** [comment]
I think you may mean to run `python extract_scene.py -p example_scenes.py SquareToCircle` as one command on a single line.

**Comment by onloner2012** [comment]
what do you mean i dont konw

**Comment by happytommyl** [comment]
Yes, I'm stuck with the same problem, too. Maybe because I'm running the code under windows 10 environment?

**Comment by eulertour** [comment]
Closing, as this issue is old and inactive.

**Comment by FathyEltanany** [comment]
iam stuck with this issue too

**Comment by atantos** [comment]
Same here..this issue is NOT resolved!
