### ISSUE TITLE
List of Updater Functions Default to End of the List

### ISSUE THREAD

**Issue by pretzel583** [3b1b/manim#1603]
cross posted to reddit. 
### Describe the bug
I am trying to make a variable length list of updater functions. When I explicitly write out the list, the code works. However, if I try to use list comprehension or just append functions to a list, it only uses the last function added. This might be some Python behavior I am not familiar with?

**Code**:
Here is version 1: This code works with the dots going in different directions. 
```
 %%manim Lambda_Test_1
  class Lambda_Test_1(Scene):
      def construct(self):
  
  
          t = ValueTracker(0)
          d = np.array([[1, 1, 0],
                    [1, 0, 0],
                    [0, 1, 0]])
  
          lambdas = [lambda x: x.move_to(d[0] * t.get_value()),
                      lambda x: x.move_to(d[1] * t.get_value()),
                      lambda x: x.move_to(d[2] * t.get_value())]
          
          dots = []
          for i in [0, 1, 2]:
              color = ['BLUE', "GREEN", "RED"][i]
              dot = Dot(color = color, radius = (2.3-i)/10).add_updater(lambdas[i])
              dots.append(dot)
              
          self.add(*dots)
          self.play(t.animate.set_value(2), time = 10)

```

In this version, all the dots move in the UP direction in unison. 

```

  %%manim Lambda_Test_2
  class Lambda_Test_2(Scene):
      def construct(self):
          t = ValueTracker(0)
          d = np.array([[1, 1, 0],
                    [1, 0, 0],
                    [0, 1, 0]])
  
          lambdas = []
          for i in range(3):
              lambdas.append(lambda x: x.move_to(d[i] * t.get_value()))
          
          dots = []
          for i in [0, 1, 2]:
              color = ['BLUE', "GREEN", "RED"][i]
              dot = Dot(color = color, radius = (2.3-i)/10).add_updater(lambdas[i])
              dots.append(dot)
              
          self.add(*dots)
          self.play(t.animate.set_value(2), time = 10)
```

Any ideas? Thanks!

https://user-images.githubusercontent.com/88741828/128925293-1d122301-05d7-40be-8233-fcddc7d07edc.mp4

https://user-images.githubusercontent.com/88741828/128925294-9ad356fa-5ea6-4bac-b645-41fb3056d16c.mp4

**Comment by TonyCrane** [comment]
This is totally a classic python issue.

You wrote:
```python
for i in range(3):
      lambdas.append(lambda x: x.move_to(d[i] * t.get_value()))
```
but here `i` is a global variable, so after this loop, all of the `i` in the lambda expressions are equal to `2`.
so the updater functions in lambdas are the same.

And to solve this, you just need to turn `i` into a local variable in each lambda expressions, so this will solve your problem:
```python
lambdas = []
for i in range(3):
    lambdas.append(lambda x, y=i: x.move_to(d[y] * t.get_value()))
```

---
Besides, I noticed that you are using the community version of manim, so you'd better ask questions on their discord channel or open an issue in their repository, instead of here.

**Comment by pretzel583** [comment]
Got it, thanks!!
