### ISSUE TITLE
Make MEDIA_DIR configurable without code changes

### ISSUE THREAD

**Issue by vors** [3b1b/manim#161]
This is first thing that come out for everybody who tries to use manim.

```
Exception:
        Redefine MEDIA_DIR in constants.py to point to
        a valid directory where movies and images will
        be written
```

Changing the source code is not very practical way of customizing the output.
A better alternative could be a config file, parameter, env variable, etc.

**Comment by devneal** [comment]
This was recently addressed by f2f9c61ee1e5140f876ff769b2f8066a7dfd214e.
