### ISSUE TITLE
Incomplete display with Tex

### ISSUE THREAD

**Issue by AnisaAisha** [3b1b/manim#1612]
I have tried to generate a simple text using `Tex`, but the text keeps cutting off from the end. I have tried removing the last part of color map `"Paper 1: TEAL"` and it seemed to work fine. I also tried with some other text samples and they worked perfectly as well, I think this text triggered some edge case due to which it does not get rendered properly.

**Code**:

```py
from manim import *

class MainScene(Scene):
    def construct(self):
        intro1 = Tex(r"""This is the series of videos where we are going to discuss\\ selected but challenging problems of JEE (Adv.) 
                            2020\\Paper 1. In this series there are total 8 problems, and\\we shall discuss one problem in each video. We 
                            shall\\upload videos on consecutive days today onwards at 3\\PM IST. Stay tuned with us.""",
                            tex_to_color_map={"JEE (Adv.) 2020":TEAL, "challenging": ORANGE, "selected": BLUE, "tuned":RED, "Paper 1": 
                            TEAL}, tex_environment = "flushleft", stroke_width=1.5)
        intro1.width = config.frame_width-0.5
        self.play(Write(intro1), run_time=1)
        self.wait(4)
        self.play(FadeOut(intro1))
        self.wait(0.1)
```

**Wrong display**: As you can see, the text gets cut off from the end. Sometimes it displays some more characters than this, but there are always few missing characters.

![image](https://user-images.githubusercontent.com/35626637/130519382-abd7f96b-350c-4b6a-8c72-c7b37b9d2fc1.png)

### Additional context

I am using Manim Community v0.9.0.

**Comment by TonyCrane** [comment]
It seems that you are using the community version of manim, so you'd better ask this question in their discord channel or open an issue in [ManimCommunity/manim](https://github.com/ManimCommunity/manim) instead of here.
