### ISSUE TITLE
self.play can't play two and more animate correctly

### ISSUE THREAD

**Issue by umm233** [3b1b/manim#1618]
### Describe the bug
When run the animation`self.play(circle.animate.shift(2 * RIGHT), circle.animate.scale(0.25))`, the result is circle scale but do not move to right. 
And then I change the animate run order, run `self.play(circle.animate.scale(0.25), circle.animate.shift(2 * RIGHT))`, it move but not scale. 

**Code**:

```python
class CircleScaleAndMove(Scene):
    def construct(self):
        circle = Circle()
        circle.set_fill(BLUE, opacity=0.5)
        circle.set_stroke(BLUE_E, width=4)
        self.play(circle.animate.shift(2 * RIGHT), circle.animate.scale(0.5))
        self.wait()
```

**Wrong display or Error traceback**:

 wrong: above code result is circle scale but do not move to right. 
expect:  circle scale and move to right.

**Comment by DevilYang1997** [comment]
**change to :** self.play(circle.animate**.shift(2 * RIGHT).scale(0.5)**)

**Comment by DevilYang1997** [comment]
**change to:**self.play(circle.animate.shift(2 * RIGHT).scale(0.5))

**Comment by TonyCrane** [comment]
use `self.play(circle.animate.shift(2 * RIGHT).scale(0.5)`.

**Comment by umm233** [comment]
I konw how to implement the animation, but it is a bug, right?
