### ISSUE TITLE
ImportError Paragraph

### ISSUE THREAD

**Issue by Olexandr-Andriyenko** [3b1b/manim#1638]
Hey I like to write a text like in the documentation:

```
from manimlib.imports import *

class Demo(Scene):
    def construct(self):
        text = Text('Hello, world!')
        self.play(Write(text))

```

I get always the error:
ImportError: cannot import name 'Paragraph' from 'manimlib.mobject.svg.text_mobject' (c:\users\olexa\appdata\local\programs\python\python38\lib\site-packages\manimlib\mobject\svg\text_mobject.py)

**How to fix this ?**

**Comment by TonyCrane** [comment]
`Paragraph` has already been removed from manimgl, so you're supposed to update your source code. Maybe try to reinstall it?

**Comment by herosanja** [comment]
Sry I am a total beginner, can you maybe give me a step by step solution how to do it.

**Comment by TonyCrane** [comment]
The best way is to create a new environment and install manimgl according to the docs. (3b1b.github.io/manim)

**Comment by crmathieu** [comment]
> Hey I like to write a text like in the documentation:
> 
> ```
> from manimlib.imports import *
> 
> class Demo(Scene):
>     def construct(self):
>         text = Text('Hello, world!')
>         self.play(Write(text))
> ```
> 
> I get always the error: ImportError: cannot import name 'Paragraph' from 'manimlib.mobject.svg.text_mobject' (c:\users\olexa\appdata\local\programs\python\python38\lib\site-packages\manimlib\mobject\svg\text_mobject.py)
> 
> **How to fix this ?**

replace 
**from manimlib.imports import ***
with
**from manimlib import ***

That should do it
