### ISSUE TITLE
NumberPlane not showing it's lines

### ISSUE THREAD

**Issue by aburousan** [3b1b/manim#1652]
### Describe the bug
I have used manimgl before but after changing the version (almost 4-5 months old) with new version, whenever i am running the example scene (**OpeningManimExample**), the lines in the **NumberPlane** is not showing.
**Image**
![Screenshot (394)](https://user-images.githubusercontent.com/60939745/137588140-c671e317-67aa-43ba-8d6e-0e20f110a645.png)

**Version Used**:
Manim - 1.1.0

**Comment by TonyCrane** [comment]
See: https://github.com/3b1b/manim/discussions/1546

**Comment by aburousan** [comment]
Thanks working now...

**Comment by aburousan** [comment]
Thank you .... Now it's working
