### ISSUE TITLE
move_camera rotate too much

### ISSUE THREAD

**Issue by meitnerium** [3b1b/manim#1657]
### Describe the bug
The camera make several fast rotation when asking for pi/10 rotation. 
**Code**:
from manim import *

class Hello3Dworld(ThreeDScene):
    def construct(self):
        axes = ThreeDAxes(
            x_range=[-6, 6, 1],
            y_range=[-6, 6, 1],
            z_range=[-6, 6, 1],
            x_length=8,
            y_length=6,
            z_length=6,
        )

        self.set_camera_orientation(phi=90,theta=0,focal_distance=6)
        self.add(axes)
        #
        graph2 = axes.get_parametric_curve(
            lambda t: np.array([t, t, t]),
            t_range=[0, 3.5],
            color=RED,
        )
        self.play(Create(graph2))
        dot = Dot(color=WHITE)
        dot.move_to(axes.i2gp(3.5, graph2))
        self.play(Create(dot))
        self.move_camera(np.pi/10, np.pi/10)
        self.wait(2)

**Wrong display or Error traceback**:

https://user-images.githubusercontent.com/149830/138025839-e56da29e-1a8f-44a2-8686-92bcbb8ac870.mp4

**Comment by TonyCrane** [comment]
I see `from manim import *` in the first line.
So I guess you are using the community version of manim.
If so, you'd better ask this question on their discord channel or open an issue in [ManimCommunity/manim](https://github.com/ManimCommunity/manim) instead of here.
