### ISSUE TITLE
Flash animation is always at center

### ISSUE THREAD

**Issue by zaneduffield** [3b1b/manim#1670]
### Describe the bug

The  'Flash' animation always renders at the center of the Scene, regardless of the arguments.
Even the documentation example shows this bug: https://docs.manim.community/en/stable/reference/manim.animation.indication.Flash.html?highlight=flash#usingflash

**Code**:

The following will only generate flashes at the center of the screen.
```python
from manim import *

class FlashAtCenterOnly(Scene):
    def construct(self):
        self.play(Flash(DOWN), Flash(UP), Flash(LEFT), Flash(RIGHT))
        self.wait()
```

**Comment by TonyCrane** [comment]
Seems that you are using the community version of manim. So you're supposed to ask this question on their discord channel, or open an issue in ManimCommunity/manim instead of here.

**Comment by zaneduffield** [comment]
Oops, my bad. I now see that this is also already an issue on community version's Github.
