### ISSUE TITLE
Errno 2: no such file or directory

### ISSUE THREAD

**Issue by lhardt** [3b1b/manim#17]
Traceback (most recent call last):
  File "extract_scene.py", line 175, in main
    handle_scene(SceneClass(**scene_kwargs), **config)
  File "extract_scene.py", line 107, in handle_scene
    scene.write_to_movie(os.path.join(config["movie_prefix"], name))
  File "/home/leohardt/Programação/Python/manim-master/scene/scene.py", line 380, in write_to_movie
    process = sp.Popen(command, stdin=sp.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

play WARN alsa: under-run
play WARN alsa: under-run
play WARN alsa: under-run
play WARN alsa: under-run
play WARN alsa: under-run
play WARN alsa: under-run
play WARN alsa: under-run
play WARN alsa: under-run
play WARN alsa: under-run
play WARN alsa: under-run
play WARN alsa: under-run
play WARN alsa: under-run
play WARN alsa: under-run
play WARN alsa: under-run
play WARN alsa: under-run
play WARN alsa: under-run

**Comment by sramsay64** [comment]
Do you have `ffmpeg` installed? If that's not the problem then what command did you run do produce this error. I think it's just that it can't find `ffmpeg` though. The repeated warnings at the end probably aren't that important. They're just to do with playing a sound to indicate the program has finished.

**Comment by jacenre** [comment]
I currently have the same problem, and my `where ffmpeg` also gives me my installed path.

**Comment by jackdark** [comment]
I got the same problem as you ,
so ,
I create a new file path which just follow the contant in the warning ,
then
video came out ,
I was so excited~~~~
You can try if you didn't.

**Comment by eulertour** [comment]
Closing, as this issue is old and inactive.
