### ISSUE TITLE
Manim install script cannot handle MS OneDrive

### ISSUE THREAD

**Issue by xjordanx** [3b1b/manim#1710]
### Describe the bug
I have GitHub root in the default %USERPROFILE%\Documents\GitHub

This means following the instructions on the install page here: https://3b1b.github.io/manim/getting_started/installation.html
...should work but doesn't when OneDrive is "enabled". OneDrive moves all the user's Documents folder contents and subdirectories into a new location (without telling the user): 
%USERPROFILE%\OneDrive\Documents\GitHub

This would not be a problem, except that while OneDrive is running in the background, it's taken over sync and read-write privileges, which prevent the installer from being able to write to any of this folder structure. It errors out, even if running in a command window that's opened with "Run As Administrator".

**Code**:
pip install -e .

**Wrong display or Error traceback**:
 Running setup.py develop for manimgl
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python38\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\benjo\\OneDrive\\Documents\\GitHub\\manim\\setup.py'"'"'; __file__='"'"'C:\\Users\\benjo\\OneDrive\\Documents\\GitHub\\manim\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: C:\Users\benjo\OneDrive\Documents\GitHub\manim\
    Complete output (7 lines):
    running develop
    running egg_info
    C:\Users\benjo\AppData\Local\Temp\pip-build-env-6xurb79s\overlay\Lib\site-packages\setuptools\command\easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    C:\Users\benjo\AppData\Local\Temp\pip-build-env-6xurb79s\overlay\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    error: [Errno 13] Permission denied: 'manimgl.egg-info\\PKG-INFO'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\program files\python38\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\benjo\\OneDrive\\Documents\\GitHub\\manim\\setup.py'"'"'; __file__='"'"'C:\\Users\\benjo\\OneDrive\\Documents\\GitHub\\manim\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

### Additional context
I believe it's a conflict with OneDrive because I disabled OneDrive sync and then executing the setup again did not seem to repeat the error messages.

**Comment by TonyCrane** [comment]
This problem is entirely caused by OneDrive, it has nothing to do with manim.

**Comment by xjordanx** [comment]
The bug exists in the Manim installer, not OneDrive.

**Comment by TonyCrane** [comment]
```text
error: [Errno 13] Permission denied: 'manimgl.egg-info\PKG-INFO'
```

Please make it clear that the system is preventing you from installing, not that the manim installation script does not install it for you.
If you clone other python packages and install them manually in a editable mode with `pip install -e .` it should also have the same problem.
So it has nothing to do with manim ...
