### ISSUE TITLE
Error of annulus rendering

### ISSUE THREAD

**Issue by Dagwbl** [3b1b/manim#1713]
### Describe the error

When I write a simple script to plot an annulus, I meet an Expected condition.
Like this, But I  want to fill the entire annulus.
![annulus](https://gitee.com/Dagwbl/cloudPicture/raw/master/typora/150938682-b62bc497-a65d-4696-9978-7eb32b3333cb.png)
### Code and Error
**Code**:

```py
from manimlib import *
from os import system


class annulus(Scene):
    def construct(self):
        annulus = Annulus(
            inner_radius=2,
            outer_radius=3,
            # color=BLUE_A,
            fill_opacity=0.8
        )
        annulus.set_color(BLUE_E)

        self.add(annulus)
        



if __name__=="__main__":
    system("manimgl annulus.py annulus -so") 
```
**Error**:

No error traceback.
### Environment
**OS System**: Windows 11DEV
**manim version**: master 0.13
**python version**:3.8.12

**Comment by TonyCrane** [comment]
Try: `Annulus(...).reverse_points()`.
(But I don't know why)

**Comment by Dagwbl** [comment]
> 

This is a way and I successfully render it. Thank you, but I still want to know what happened in this.
