### ISSUE TITLE
ImportError: cannot import name 'main', from manimlib import main 

### ISSUE THREAD

**Issue by vignesh99** [3b1b/manim#1729]
### Describe the error

The current pip3 version of manimlib does not have get_rows() command for the Matrix mobject. I saw that this was present in the current version of the repo (March 2021 it was committed with this update). So I tried to pip install the current git version and run the code. However I faced the above error. Is there a way to install the current git version without facing import error? 
### Code and Error
**Code**:

1) Command line
`pip3 install git+git://github.com/3b1b/manim@master ` 

2) Command line
`manim file.py GetRowsExample -c WHITE`  

file.py
```
from manimlib.imports import *

class GetRowsExample(Scene):
    def construct(self):
        m0 = Matrix([["\pi", 3], [1, 5]])
        m0.add(SurroundingRectangle(m0.get_rows()[1]))
        self.add(m0)
```

**Error**:

Errors for 1) and 2) are correspondingly given below :
1)
```
 .local/bin/manim", line 5, in <module>
    from manimlib import main
ImportError: cannot import name 'main'  
```

2)
```
 .local/lib/python3.6/site-packages/manimlib/scene/scene.py", line 75, in __init__
    self.construct()
  File "file.py", line 9, in construct
    m0.add(SurroundingRectangle(m0.get_rows()[1]))
AttributeError: 'Matrix' object has no attribute 'get_rows'
```

### Environment
**OS System**: Ubuntu 18.04 LTS
**manim version**: master (latest version) 
**python version**:3.6.9

@eulertour @TonyCrane  and anyone else, please request you to help.

**Comment by TonyCrane** [comment]
PLEASE read the README or documentation before using!!!
I really wonder what are you doing.
- `pip install ...`: you install ManimGL via pip
- `from manimlib.imports import *`: you import it like Manim-cairo-backend
- `manim file.py ...`: you run the command of ManimCE

You've got all three versions of Manim mixed up, you'd be surprised if it didn't go wrong!
All usage is already stated in the README and documentation, so why don't you look at that and guess for yourself?

> btw, please don't @ others unless it's urgent

**Comment by vignesh99** [comment]
Hello,
Initially I did `pip3 install manimlib`, Imported manimlib, and ran the command manim because there is no manimlib command. However, this version had no get_rows() in the pip version as mentioned above.

Installing both community version of manim and manimgl gave me errors hence I used the manimlib route. I apologise if I bothered you by tagging. I did not know this was used only for urgent issues.

Please note I got the below error when I ran `manimgl  file.py classname`
`ImportError: cannot import name 'get_shaded_rgb' `
I'm looking for a version (manim/manimgl) that can run get_rows() and manimnx. Would be great if you can help here. I will also try to post the issue in community manim version.
