### ISSUE TITLE
Installed Manim and my 3.10.1/2 started failing

### ISSUE THREAD

**Issue by SNR20db** [3b1b/manim#1733]
### Describe the bug
I've just got manim installed via pip on windows 10 and my Python started to raise this error:

![image](https://user-images.githubusercontent.com/47638730/153507222-a1d6b9cc-a637-4d97-bead-60c54a7ceda6.png)

I am aware that several people got the same issue. I have `pyreadline.py` installed with the most recent version.

### Additional info.

Uninstalling `manim` and `Pango` doesn't help.

**Comment by TonyCrane** [comment]
`pip uninstall pyreadline`
`pyreadline` is no longer maintained, so it is not compatible with python 3.9+ and this dependency is no longer needed in manim.
