### ISSUE TITLE
Bugs of presenter mode and embed terminal's local variable

### ISSUE THREAD

**Issue by TonyCrane** [3b1b/manim#1741]
### Describe the bug

Here are two bugs from #1739 @3b1b 

### Bug from https://github.com/3b1b/manim/pull/1739/commits/9a9cc8bdacb7541b7cd4a52ad705abc21f3e27fe
The first `scene.wait` won't wait for key press because of https://github.com/3b1b/manim/blob/b3b7d214adff2088f6c75cbc814cbbf8f1a9b4e4/manimlib/scene/scene.py#L66
and https://github.com/3b1b/manim/blob/b3b7d214adff2088f6c75cbc814cbbf8f1a9b4e4/manimlib/scene/scene.py#L497-L500
I think here `self.hold_on_wait` should be equal to `self.presenter_mode` (or `True` because if `self.presenter_mode == False` then `self.hold_on_wait` won't be used in anywhere)

### Bug from https://github.com/3b1b/manim/pull/1739/commits/9df12fcb7d8360e51cd7021d6877ca1a5c31835e
The locals() variables in the iPython terminal opened by typing `e` in the interactive mode are not local variables in the users file:
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/44120331/153815804-71f6e36a-974b-45d7-95aa-4f4e44e33b1d.png">
So users can't do anything like `play(FadeOut(circle))` (because both `FadeOut` and `circle` are not in the `locals()` dict or `globals()` dict)

This issue happend because `embed()` is executed by `scene.on_key_press()` instead of `UserScene.construct()`, so the `local_ns` in `scene.embed()` is read from `scene.on_key_press`'s frame.
https://github.com/3b1b/manim/blob/b3b7d214adff2088f6c75cbc814cbbf8f1a9b4e4/manimlib/scene/scene.py#L137-L143
But the whole stack of frame is:
```python
<frame at 0x7fe5aaf59040, file '/.../manimlib/scene/scene.py', line 140, code embed>
<frame at 0x7fe5aae3ddd0, file '/.../manimlib/scene/scene.py', line 639, code on_key_press>
<frame at 0x7fe5aae49c80, file '/.../manimlib/window.py', line 106, code on_key_press>
<frame at 0x7fe59fea05a0, file '/.../site-packages/pyglet/event.py', line 408, code dispatch_event>
<frame at 0x7fe5a9dd5040, file '/.../site-packages/pyglet/window/__init__.py', line 1343, code dispatch_event>
<frame at 0x7fe5aaf58210, file '/.../site-packages/pyglet/window/cocoa/pyglet_view.py', line 199, code pygletKeyDown_>
<frame at 0x7fe5aaf58040, file '/.../site-packages/pyglet/libs/darwin/cocoapy/runtime.py', line 1141, code objc_method>
<frame at 0x7fe5aaf51840, file '/.../site-packages/pyglet/libs/darwin/cocoapy/runtime.py', line 775, code __call__>
<frame at 0x7fe5aae4aa60, file '/.../site-packages/pyglet/libs/darwin/cocoapy/runtime.py', line 805, code __call__>
<frame at 0x7fe5aae48220, file '/.../site-packages/pyglet/window/cocoa/__init__.py', line 317, code dispatch_events>
<frame at 0x7fe5aae44ba0, file '/.../site-packages/moderngl_window/context/pyglet/window.py', line 181, code swap_buffers>
<frame at 0x7fe5aae49ac0, file '/.../manimlib/scene/scene.py', line 175, code update_frame>
<frame at 0x7fe5aae47c40, file '/.../manimlib/scene/scene.py', line 179, code update_frame>
<frame at 0x7fe5aae1ea60, file '/.../manimlib/scene/scene.py', line 113, code interact>
<frame at 0x7fe5aae17ba0, file '/.../manimlib/scene/scene.py', line 102, code tear_down>
<frame at 0x7fe5aae11950, file '/.../manimlib/scene/scene.py', line 83, code run>
<frame at 0x7fe5a1eb5210, file '/.../manimlib/__main__.py', line 25, code main>
<frame at 0x7fe5a1908a90, file '/.../bin/manimgl', line 33, code <module>>
```
It won't go through the user's code. So I don't know how to fix it elegantly ¯\\\_(ツ)\_/¯

**Comment by 3b1b** [comment]
> Bug from 9a9cc8b

Very right! The effect seems to be that it doesn't halt on the first wait call, then does after. Thanks for the note.

To be honest, the "presenter" mode was just something hastily thrown in there as I wanted to record certain intereacitons for the wordle video, so it may not have been fully thought out.

> Bug from 9df12fc

Very true, my original intent with this was just to be able to drop into a scene and call the scenes methods, even if the local variable of construct might not be accessible. I also can't think of a clean way to access the construct locals, unless there's some deep python magic I'm unaware of.

What do you think, is this useful enough to keep, or should we just remove it entirely?

**Comment by TonyCrane** [comment]
For the second one, I can't solve it either.
I'm taking a wild guess that there isn't a way to read the construct's locals without changing the user's file, since they're dynamically generated when running, and locals in user's constructs have no connection to scene.py.

So I think removing this feature is the right choice for now.

**Comment by 3b1b** [comment]
What I'll do for now is just change the keybinding to something that requires being more deliberate. (https://github.com/3b1b/manim/pull/1746).  Even if it's not something where you can drop into an environment with the local variables of construct, I can still see it being useful for recording certain presentations where at some point I want to interact with the scene in a way that doesn't yet have GUI support. 

Also, in a longer-term future, it may be nice to have a more seamless relationship with the interactive mode and the embedded mode, such that someone could do things like click a Mobjct and copy an id for it to their clipboard, which they could then reference in the terminal, in which case access to local variables wouldn't matter as much.
