### ISSUE TITLE
I've installed manim, but can't get it to run the example scenes

### ISSUE THREAD

**Issue by hoonle131** [3b1b/manim#1747]
I've installed manim, but can't get it to run the example scenes

python -m manim example_scenes.py SquareToCircle -pl

And I get the following back:

RuntimeWarning: 'manim.__main__' found in sys.modules after import of package 'manim', but prior to execution of 'manim.__main__'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Manim Community v0.14.0

Usage: python -m manim render [OPTIONS] FILE [SCENE_NAMES]...
Try 'python -m manim render --help' for help.

Error: No such option: -l

I'm running Python 3.10 on a Windows 11 OS.

**Comment by TonyCrane** [comment]
Could please read the document or README first before you start using manim?
How to install and how to run it are both writen in the README file, why don't you read it but ask it here?
