### ISSUE TITLE
not able to run 'python manage.py runserver' in django

### ISSUE THREAD

**Issue by machha5658** [3b1b/manim#1750]
### Describe the error
I want to check whether the django install correctly or not but i'm not able to check 
i run the command "python manage.py runserver" but shows this issues, pls help me 

### Code and Error
**Code**:
#############################################################
       # Start the process
            try:
                hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                                         # no special security
                                         None, None,
                                         int(not close_fds),
                                         creationflags,
                                         env,
                                         os.fspath(cwd) if cwd is not None else None,
                                         startupinfo)
            finally:
                # Child is launched. Close the parent's copy of those pipe
                # handles that only the child should have open.  You need
                # to make sure that no handles to the write end of the
                # output pipe are maintained in this process or else the
                # pipe will not close when the child process exits and the
                # ReadFile will hang.
                if p2cread != -1:
                    p2cread.Close()
                if c2pwrite != -1:
                    c2pwrite.Close()
##############################################################
**Error**:

  File "C:\Users\user\AppData\Local\Programs\Python\Python37-32\Lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

### Environment
**windows7 32 bit**: 
**python 3.7 **
**django  3.2.12**:

**Comment by TonyCrane** [comment]
Please don't ask questions unrelated to manim here.
