### ISSUE TITLE
GraphExample: import numpy as np missing in functions.py

### ISSUE THREAD

**Issue by vchizhov** [3b1b/manim#1799]
### Describe the error
While trying to run the GraphExample from the [example scenes](https://3b1b.github.io/manim/getting_started/example_scenes.html), I got the error "NameError: name 'np' is not defined". I could fix it by adding:
`import numpy as np` 
after `from __future__ import annotations` in manim\manimlib\mobject\functions.py.

### Code and Error
**Code**:
GraphExample

**Error**:
...\manim\manimlib\mobject\functions.py", line 51, in init_points
    jumps = np.array(self.discontinuities)
NameError: name 'np' is not defined

### Environment
**OS System**: Windows 10
**manim version**: master ManimGL v1.6.1
**python version**: Python 3.9.6

**Comment by TonyCrane** [comment]
Fixed in https://github.com/3b1b/manim/commit/587bc4d0bd662c8ecaf369c371d35e175ffeb08e
