### ISSUE TITLE
What's the best way to run the scenes that need Pi creatures?

### ISSUE THREAD

**Issue by Glidos** [3b1b/manim#18]
Yet to experiment in this area yet, but I'm wondering, will any replacement SVG file do? Or are certain "keys"
needed for the animations? I know little about SVG.

I'm hoping someone else has found a work around. No need for the scenes to look good. I just want to use them as  a way to understand the system.

**Comment by julien-blanchon** [comment]
Yes same issues, I got a svg error when the svg is missing (normal ^^). And when I download a new svg (like http://www.clker.com/cliparts/6/J/p/U/f/h/animated-pi.svg), I got a index error. For some scene we can just delete all Pi creatures command but it's very long.

**Comment by mirefek** [comment]
This interests me too. I have no idea what are the requirements on the SVG file so that I can use it as a pi creature. I just know that a general SVG does not work. At least one example would be appreciated.

**Comment by mirefek** [comment]
Hi, I understand it better now.
3b1b has lots of different pi creatures: angry, confused, dance_kick, erm, guilty, happy, hesitant, hooray, maybe, plain, pleading, pondering, raise_left_hand, raise_right_hand, sassy, show, shruggie, speaking, surprised, thinking, well
but he probably do not intend to publish them.
Pi creatures are in the directory files/images/PiCreature/ and they are named PiCreatures_<name>.svg
Every pi creature image is supposed to contain 6 paths. In order: left eye, right eye, left pupil, right pupil, body, mouth.
I have made an [example pi creature](http://atrey.karlin.mff.cuni.cz/~mirecek/PiCreatures_plain.svg)
I still do not understand the SVG reading well, but I have already found two bugs in the code. So for using my image, you will probably need to do two minor changes in file mobject/svg_mobject.py:

1. After comment "Handle situations where there's multiple relative control points" modify line
`        if isLower and len(points) > 3:`
to
`        if isLower and len(new_points) > 3:`
2. A few lines below, after line
`        coord_string = coord_string.replace("-",",-")`
insert line
`        coord_string = coord_string.replace("e,-","e-")`

Then, following example may work:
```
class PiCreatureExampleScene(PiCreatureScene):
    def construct(self):
        mortimer = self.create_pi_creature()
        self.dither()
```
For more sophisticated examples, copy the original one to other names and make minor changes in them.

I still do not understand it perfectly. For instance, eyes and the mouth are shifted to the right and I do not know the reason. I need to get through it for my SVG picture... Well, manupulation with SVG obviously is not the strong side of the library :-)

**Comment by mirefek** [comment]
The "shifted mouth" problem solved. Use [my version of svg_mobject](https://github.com/mirefek/manim/blob/master/mobject/svg_mobject.py). It also contains these slight changes which I mentioned earlier.

3b1b apparently uses another SVG editor than me (I use InkScape) and the parser is not very generic. I have made a pull request, so it may become official, eventually.

**Comment by 3b1b** [comment]
I have added the simple plain expression and made it so that scenes with pi creatures should fall back on this svg, so those scenes should run now.  Let me know if they don't.  The full palette of expressions is somewhat 3b1b specific, so I'd prefer to keep it out of the public repo.

**Comment by rajdakin** [comment]
@3b1b, as suggested in #24, you could just licence the pictures so that we can have these...

**Comment by Fredo699** [comment]
@3b1b Scanning through some of this code, it looks pretty dense and impenetrable, and I think it's probably going to remain that way the fewer assets you share with the community.

**Comment by eulertour** [comment]
Closing, as this issue is old and seems to be resolved.

**Comment by CaftBotti** [comment]
If you want to make pi creature scenes like in 3b1b's videos, [**here**](https://github.com/CaftBotti/manim_pi_creatures) is a good choice. Follow the steps in README.md and make a video that shows different emotions of pi creatures which were not released by 3b1b. [**An example video**](https://user-images.githubusercontent.com/111475301/209333597-63a97dca-75e8-4f96-9927-fa2bc4b925ff.mp4) is given in README.md.

https://user-images.githubusercontent.com/111475301/209333597-63a97dca-75e8-4f96-9927-fa2bc4b925ff.mp4

**Comment by 3b1b** [comment]
Just FYI, a trademark protects the use of this particular design in the settings of online video, and certain kinds of merchandise. I'm delighted if people find manim code useful in creating new math animations, but at the same time would not encourage using designs specific to the 3blue1brown channel. I'd much rather encourage others to find their own voice/look/feel.

I see why you made this repo, and I suppose if someone wants to rerun a scene locally that involves pi creatures and it's unsatisfying for the modes to all default to "plain", that seems fine. But as long as people know that the IP around those designs is distinct from the licensing behind manim.

**Comment by CaftBotti** [comment]
> Just FYI, a trademark protects the use of this particular design in the settings of online video, and certain kinds of merchandise. I'm delighted if people find manim code useful in creating new math animations, but at the same time would not encourage using designs specific to the 3blue1brown channel. I'd much rather encourage others to find their own voice/look/feel.
> 
> I see why you made this repo, and I suppose if someone wants to rerun a scene locally that involves pi creatures and it's unsatisfying for the modes to all default to "plain", that seems fine. But as long as people know that the IP around those designs is distinct from the licensing behind manim.

It's good to protect the use of lovely pi's, because you really need them as a eye-catching character image to become your symbol, and we should all respect you. But many people saw them appeared in your videos, and in addition that you use manim to render videos about math, they will certainly wonder how to make pi creature scenes. If you tend to share your popular symbol to manim, I believe manim will be more and more satisfying and useful for its users. However, if you suppose to keep your intellectual property, you have no need to that and you can keep those design secret until forever.

Wish manim have a better future!
