### ISSUE TITLE
Inconsistant text kerning when using Text Class

### ISSUE THREAD

**Issue by Yupjun** [3b1b/manim#1813]
### Describe the bug

It seems like reducing font size can affect the text kerning space.

**Seems not good**:
```
class Textfontcheck(Scene):
    def construct(self):
        obj = VGroup()
        font_group = ["Consolas","Noto Sans","Times New Roman",
        "Cambria","MS Gothic","Sans Medium Not-Rotated 10"]
        for index in range(len(font_group)):
            obj.add(Text("abcdefghijklnmopqrstuvwxyz",font_size=20,font=font_group[index]))
        obj.move_to(np.array([0,3,0]))
        obj.arrange(DOWN)


        self.add(obj)
```

**Wrong display or Error traceback**:
![CircleExample_ManimCE_v0 15 2](https://user-images.githubusercontent.com/25025997/168738140-ba71446a-1f70-4ded-b4e3-05f265d11c93.png)

**Seems good**:
```
class Textfontcheck_sizeup(Scene):
    def construct(self):
        obj = VGroup()
        font_group = ["Consolas","Noto Sans","Times New Roman",
        "Cambria","MS Gothic","Sans Medium Not-Rotated 10"]
        for index in range(len(font_group)):
            obj.add(Text("abcdefghijklnmopqrstuvwxyz",font_size=40,font=font_group[index]))
        obj.move_to(np.array([0,3,0]))
        obj.arrange(DOWN)


        self.add(obj)
```

![Textfontcheck_ManimCE_v0 15 2](https://user-images.githubusercontent.com/25025997/168739281-1f97c81c-8b0c-4e62-b3e8-9a53d37480c1.png)

Configs in manim has not been modified. 
I want to know why this problem is happening.

### Additional context
OS: Window 11
GPU: Nvidia RTX 3060ti
Python: 3.8.13
nvcc: cuda_11.6.r11.6
Installed packged in conda env:

asttokens                 2.0.5                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.4.26            haa95532_0    anaconda
certifi                   2021.10.8                pypi_0    pypi
charset-normalizer        2.0.12                   pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
click-default-group       1.2.2                    pypi_0    pypi
cloup                     0.13.0                   pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
colour                    0.1.5                    pypi_0    pypi
commonmark                0.9.1                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
executing                 0.8.3                    pypi_0    pypi
fonttools                 4.33.3                   pypi_0    pypi
glcontext                 2.3.6                    pypi_0    pypi
idna                      3.3                      pypi_0    pypi
ipython                   8.3.0                    pypi_0    pypi
isosurfaces               0.1.0                    pypi_0    pypi
jedi                      0.18.1                   pypi_0    pypi
kiwisolver                1.4.2                    pypi_0    pypi
libffi                    3.4.2                h8ffe710_5    conda-forge
libzlib                   1.2.11            h8ffe710_1014    conda-forge
manim                     0.15.2                   pypi_0    pypi
manimgl                   1.6.1                    pypi_0    pypi
manimpango                0.4.1                    pypi_0    pypi
mapbox-earcut             0.12.11                  pypi_0    pypi
matplotlib                3.5.1                    pypi_0    pypi
matplotlib-inline         0.1.3                    pypi_0    pypi
moderngl                  5.6.4                    pypi_0    pypi
moderngl-window           2.4.1                    pypi_0    pypi
mpmath                    1.2.1                    pypi_0    pypi
multipledispatch          0.6.0                    pypi_0    pypi
networkx                  2.8                      pypi_0    pypi
numpy                     1.22.3                   pypi_0    pypi
openssl                   3.0.2                h8ffe710_1    conda-forge
packaging                 21.3                     pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.1.0                    pypi_0    pypi
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.29                   pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pycairo                   1.21.0                   pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pyglet                    1.5.23                   pypi_0    pypi
pygments                  2.12.0                   pypi_0    pypi
pyopengl                  3.1.6                    pypi_0    pypi
pyparsing                 3.0.8                    pypi_0    pypi
pyrr                      0.10.3                   pypi_0    pypi
python                    3.8.13          hcf16a7b_0_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.8                      2_cp38    conda-forge
pyyaml                    6.0                      pypi_0    pypi
requests                  2.27.1                   pypi_0    pypi
rich                      12.3.0                   pypi_0    pypi
scipy                     1.8.0                    pypi_0    pypi
screeninfo                0.8                      pypi_0    pypi
setuptools                62.1.0           py38haa244fe_0    conda-forge
six                       1.16.0                   pypi_0    pypi
skia-pathops              0.7.2                    pypi_0    pypi
sqlite                    3.38.3               h8ffe710_0    conda-forge
srt                       3.5.2                    pypi_0    pypi
stack-data                0.2.0                    pypi_0    pypi
svgelements               1.6.13                   pypi_0    pypi
sympy                     1.10.1                   pypi_0    pypi
tk                        8.6.12               h8ffe710_0    conda-forge
tqdm                      4.64.0                   pypi_0    pypi
traitlets                 5.1.1                    pypi_0    pypi
typing-extensions         4.2.0                    pypi_0    pypi
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
urllib3                   1.26.9                   pypi_0    pypi
validators                0.18.2                   pypi_0    pypi
vc                        14.2                 hb210afc_6    conda-forge
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
watchdog                  2.1.7                    pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge

**Comment by TonyCrane** [comment]
This is caused by the font itself, not manim.

**Comment by TheCrowned** [comment]
See https://github.com/ManimCommunity/manim/issues/2844 for solution
