### ISSUE TITLE
FadeOut does not work if an updater is added to Mobject

### ISSUE THREAD

**Issue by mginesi** [3b1b/manim#1819]
### Describe the bug
On manim v 15.2 Objects with an updater attached do not fade out (nor in) but disappear (or appear) suddenly.
(Un)create works properly though.
I attach a minimal example

**Code**:

from manim import *

class fadeout_error(Scene):
    def construct(self):
        s = ValueTracker(0)
        txt = MathTex(r"\text{e}^{\mathbf{i}\pi}+1=0").move_to((s.get_value(),0,0))
        txt.add_updater(lambda m : m.become(MathTex(r"\text{e}^{\mathbf{i}\pi}+1=0").move_to((s.get_value(),0,0))))
        self.play(Write(txt))
        self.play(s.animate.set_value(1))
        # self.play(FadeOut(txt), run_time=2) # FadeOut doesn't work
        # self.play(Uncreate(txt), run_time=2) # Uncreate works
        self.play(txt.animate.set_opacity(0), run_time=2) # animate.set_opacity doesn't work
        return super().construct()

**Comment by TonyCrane** [comment]
I noticed that you are using the community version of manim, so please ask this question in their discord channel, or open an issue in ManimCommunity/manim instead of here.
