### ISSUE TITLE
Pip doesn't install a new enough numpy

### ISSUE THREAD

**Issue by thomasahle** [3b1b/manim#1824]
### Describe the bug
I ran
```
$ pip install manimgl
$ manimgl
```
and got the error 
```
    import numpy.typing as npt
ModuleNotFoundError: No module named 'numpy.typing'
```

### Additional context
I have numpy 1.19 and I numpy.typing requires numpy 1.20. I think the pip requirements files need to specify "numpy >= 1.20" rather than just "numpy" as it does now.

**Comment by TonyCrane** [comment]
maybe the version of your python is under 3.7

**Comment by thomasahle** [comment]
My python is 3.9.
The problem was fixed when I force updated my numpy.
I'm just saying the requirements.txt file in manim currently doesn't specify versions for any of the packages, so when people already have old versions installed they won't get updated. This leads to bugs like this.

**Comment by TonyCrane** [comment]
ok, I will specify the version later, thanks :)
