### ISSUE TITLE
manim doesn't support text tag in svg

### ISSUE THREAD

**Issue by daxiangcai** [3b1b/manim#1829]
in file manimlib/mobject/svg/svg_mobject.py line 275:
`def text_to_mobject(self, text: se.Text):
        pass`

**Comment by daxiangcai** [comment]
can anyone fix this? I would appreciate it

**Comment by TonyCrane** [comment]
We haven't implemented the `<text>` tag yet, because implementing it requires many considerations. But we're trying our best to do it.
If you urgently need to use text in svg, it is recommended that you use other software to convert `<text>` tags to `<path>`

**Comment by daxiangcai** [comment]
thanks a lot! I try to use inkscape to convert <text> to <path>, and it works
