### ISSUE TITLE
Program does not run

### ISSUE THREAD

**Issue by meddhiaka** [3b1b/manim#1836]
### Describe the error
I installed Manim  Manimlib modules with pip command, added FFmpeg to the windows path, installed Latex and Sox etc ...
I was passing by the documentation learning how to create a Grid, Then suddenly I got a weird message from the terminal,
I wrote this command :
" manim BasicAnimations.py CoordScreen -p -ql "

### Code and Error
**Code**:
from manim import *

class CoordScreen(Scene):
    def construct(self):
        screen_grid = ScreenGrid()
        dot = Dot([1, 1, 0])
        self.add(screen_grid)
        self.play(FadeIn(dot))
        self.wait()

**Error**:
Media will be written to C:\Users\dhiaakaa\Desktop\media\. You can change this behavior with the --media_dir flag.

   There are no scenes inside that module 

Then when I open that folder i dont find anything

### Environment
**Windows 10**: 
**manim version**: master 
**python version**:
3.9

**Comment by TonyCrane** [comment]
Seems you are using ManimCE, but you have a ManimCairo in your pip environment, please see Manim Community's docs: docs.manim.community
Have nothing to do with 3b1b/manim, so closed.
