### ISSUE TITLE
Couldn't get a file descriptor referring to the console

### ISSUE THREAD

**Issue by pu17** [3b1b/manim#185]
I am encounter with this problem,how can I fix it
![image](https://user-images.githubusercontent.com/22163384/38193523-0bff4508-36a5-11e8-82ad-6c3b1901b184.png)

**Comment by MedNait** [comment]
Try installing SoX "sudo apt-get install sox" and its dependencies "sudo apt-get install libasound2-plugins libasound2-python libsox-fmt-all" (try installing them one by one if necessary)

**Comment by pu17** [comment]
Thanks, after installing, the alsa: under-run problem seems fixed,but problem Couldn't get a file descriptor referring to the console  still persist。

![image](https://user-images.githubusercontent.com/22163384/38227634-b98bd70e-3731-11e8-9abc-1630e01ff96b.png)

**Comment by eulertour** [comment]
Resolved by #193.
