### ISSUE TITLE
LaTeX not being handled properly when MathTex mobject has single brackets in a string ("{" or "}")

### ISSUE THREAD

**Issue by Elektriman** [3b1b/manim#1856]
### Description
The MathTex mobject is not being written correctly by the Write method when there is a bracket alone in a string.
A part of the formula is missing or may even be displayed without animation and with some parenthesis caracters missing.
The resulting mobject is not built properly and the submobjects are mixed up.

### Code to reproduce the error
```python
class example(Scene):
    def construct(self):
        eqn = MathTex("u(x)", "=", "{", "y(x)", r"\over", "cos(x)", "}")
        self.wait()
        self.play(Write(eqn))
        self.wait()
```

https://user-images.githubusercontent.com/71984039/185765731-58a02da5-4217-4596-9198-0755bff535c9.mp4

### Code to show the bad construction of the MathTex mobject
```python
class example(Scene):
    def construct(self):
        eqn = MathTex("u(x)", "=", "{", "y(x)", r"\over", "cos(x)", "}")
        self.wait()
        self.play(Write(eqn))
        self.wait()
        for x in eqn :
            self.play(Indicate(x))
```

https://user-images.githubusercontent.com/71984039/185765669-fc65a3e5-676e-4d11-8638-a2e7cb644f82.mp4

### Environment
Microsoft Windows [version 10.0.19044.1889]
ManimCE v0.15.2
Python 3.10.5

**Comment by TonyCrane** [comment]
You are using the community version of manim, so please ask this question in their discord channel, or open an issue in ManimCommunity/manim, instead of here.
