### ISSUE TITLE
Latex error begginer (Texmaker and MikTex)

### ISSUE THREAD

**Issue by jaynaik159** [3b1b/manim#1861]
### Describe the error

log4cxx: No appender could be found for logger (pdflatex). log4cxx: Please initialize the log4cxx system properly. Sorry, but pdflatex did not succeed. You may want to visit the MiKTeX project page (http://miktex.org), if you need help.

Process exited with error(s)

Could not start the command.
pdflatex -synctex=1 -interaction=nonstopmode %.tex

### Code and Error
Just install Texmaker and MikTex 
and run with very short command
Received such error
*Error*
Could not start the command.
pdflatex -synctex=1 -interaction=nonstopmode %.tex

### Environment
**OS System**: 
**manim version**: master 
**python version**:

**Comment by TonyCrane** [comment]
Has nothing to do with manim, so closing this.
