### ISSUE TITLE
"add_updater" and "Mobject.become"

### ISSUE THREAD

**Issue by HeW3** [3b1b/manim#1877]
### Describe the bug

I use "Mobject.become" function in "add_updater".
But it seems not to work!?("angle'" doesn't follow "l2")
In addition,I use the newest Manimgl on Github(v1.6.1).
WHY???????????????????????????
**Code**:

```python
from manimlib import *
class Test1(Scene):
    def construct(self):
        t=ValueTracker(TAU/6)
        l1=Line(ORIGIN,[2.,0.,0.])
        l2=Line(ORIGIN,[2.,0.,0.]).rotate(t.get_value(),about_point=ORIGIN).add_updater(lambda m:m.set_angle(t.get_value()))
        angle=Arc(angle=l2.get_angle()).add_updater(lambda m:m.become(Arc(angle=l2.get_angle())))
        self.play(ShowCreation(l1),ShowCreation(l2),ShowCreation(angle))
        self.play(t.animate.increment_value(TAU/6))
```
**Wrong display or Error traceback**:

https://user-images.githubusercontent.com/97308223/194323849-162b9b34-d03e-4caf-9f1e-f198839256cb.mp4
![Test1](https://user-images.githubusercontent.com/97308223/194324803-ddc84dd8-e8c2-4081-953f-a7f7f41b63d0.png)

### Additional context

I follow the tutorial on bilibili to code the code on bilibili.It appears in the video(https://www.bilibili.com/video/BV1W4411Z7Zt/?p=23)
Episode 23!!

**Comment by IcyChlorine** [comment]
This is because the updater is removed during mobj.become().
Under the hood, become() change mobj so that is has identical states with param mobj, including points, color attributes, and UPDATERS and so on. That is to say, when being updated for the first time, the original mobj become the newly constructed mobj, which has NO updaters attached to it.

**Comment by IcyChlorine** [comment]
To put it simple, the updater is removed upon the first updating and will not work during subsequent calls.
The correct way to do it should be `add_updater(lambda m: m.set_points(Arc(angle=l2.get_angle()).get_points()))`, which update the shape of mobj only and do not affect its updater list.

**Comment by HeW3** [comment]
> 简而言之，更新程序在第一次更新时被删除，并且在后续调用期间将不起作用。正确的方法应该是 ，它只更新 mobj 的形状，而不会影响它的更新程序列表。`add_updater(lambda m: m.set_points(Arc(angle=l2.get_angle()).get_points()))`

It works!!
II appreciate your help very much!

**Comment by HeW3** [comment]
I even don't know the method called "set_points".

**Comment by 3b1b** [comment]
I've changed it so that by default, Mobject.become will not cause a mobject to adopt the updaters of the argument.

I think it's fair to say the usual case is that you don't want this, e.g. anytime you want to call become in an updater.
