### ISSUE TITLE
Color gradient function outputting only the latter color

### ISSUE THREAD

**Issue by JoosepToom** [3b1b/manim#1882]
Hello!

I'm trying to make the graph of my parametric curve run a gradient across it but when using the set_color_by_gradient() function I get 1 color across the graph. What am I doing wrong? 

#
from cmath import cos
from ctypes import sizeof
from math import sin
from re import X
from tkinter import Y, Scale
from manim import *

class Base(ThreeDScene):
    def construct(self):

        axes = ThreeDAxes(
            x_range=[-3, 3, 1],
            y_range=[-2, 3, 1],
            z_range=[-6, 6, 1],
            x_length=6,
            y_length=5,
            z_length=12,

            axis_config={"include_numbers": True},
        y_axis_config={"scaling": LinearBase(True)},
        x_axis_config={"scaling": LinearBase(True)},
        z_axis_config={"scaling": LinearBase(True)}

        )

        graph = axes.plot_parametric_curve(
            lambda t: np.array([
                
                np.sin(t)*1.3**((1/PI)*t), 
                np.cos(t)*1.3**((1/PI)*t), 
                (1/PI)*t]),
            t_range=[-6 * PI, 5.75 * PI],
            
            
            
        )

        x_label = axes.get_x_axis_label(Tex("Im(y)"))
        y_label = axes.get_y_axis_label(Tex("Re(y)")).shift(DOWN * 1.5, OUT*1.5)
        z_label = axes.get_z_axis_label(Tex("x")).shift(DOWN*0.5, IN*1)
        
        
        # zoom out so we see the axes
        self.set_camera_orientation(phi=-120 * DEGREES, theta=-25 * DEGREES, zoom=0.64, gamma= 90* DEGREES)
        y_label.rotate(120*DEGREES, axis=DOWN)
        y_label.rotate(17*DEGREES, axis=LEFT)
        x_label.rotate(120*DEGREES, axis=DOWN)
        x_label.rotate(15.8*DEGREES, axis=LEFT)
        z_label.rotate(75*DEGREES, axis=LEFT)
        z_label.rotate(20*DEGREES, axis=IN)
        z_label.rotate(27*DEGREES, axis=UP)
        x_label.scale(1.3)
        z_label.scale(1.5)
        sphere=Sphere([0,0.5,0], radius=0.05 , color=WHITE)
        self.add(axes)
        self.add((x_label), (y_label), (z_label))
        self.add(graph, sphere)
        graph.set_color_by_gradient(RED, BLUE)
       

#
OS System: Windows 10
Manim version: 0.16.0 
Python Version: 3.10.7

**Comment by 3b1b** [comment]
It had been defaulting to coloring submobjects according to a gradient, but I've added a line to make the default behavior in cases like this equivalent to graph.set_color([color1, color2])

**Comment by gd247217** [comment]
> It had been defaulting to coloring submobjects according to a gradient, but I've added a line to make the default behavior in cases like this equivalent to graph.set_color([color1, color2])

Even if you use the fixed set_color_by_gradient() method, you still cannot apply gradient color to the square.
```
from manimlib import*
sin=np.sin
cos=np.cos
My_color=[BLUE_E,WHITE]
class MainScene(Scene):
    def construct(self) -> None:
        tex=Tex(r"a^2+b^2=c^2",font_size=200).to_edge(UP)
        sq=Square(fill_opacity=1)
        
        tex.set_color_by_gradient(*My_color)
        sq.set_color_by_gradient(*My_color)
        
        self.add(tex,sq)
```
### Output
<img width="667" alt="Screenshot 2025-01-07 230218" src="https://github.com/user-attachments/assets/ebdabcaf-336d-4d7d-9833-c4b272ff2396" />

**Comment by 3b1b** [comment]
This is true, there's currently no support for gradient in fill. You could play around with Mobjuect.set_color_by_xyz_func, which is a bit hacky. It takes in a string that can be interpreted as glsl code, with reference to variables x, y and z, and which evaluates to a single number. That number, together with the color map, will determine the color of a pixel at those coordinates.

I believe set_color_by_gradient should work well for stroke colors, though.
