### ISSUE TITLE
CoordinateSystem point_to_coords Function Not Working As Expected 

### ISSUE THREAD

**Issue by Fangjun-Zhou** [3b1b/manim#1892]
### Describe the bug

When using point_to_coords to convert scene position to axis coordinate, the wrong results are created.

**Code**:

Create an 2D axis, and run this:

```python
print(axes.point_to_coords(axes.coords_to_point(-1, -1)))
print(axes.point_to_coords(axes.coords_to_point(1, 1)))
print(axes.point_to_coords(axes.coords_to_point(3, 2)))
```

**Wrong display or Error traceback**:

Following results are printed:

```
(-0.8780487804878052, -0.8888888888888891)
(1.1707317073170724, 1.1851851851851851)
(3.219512195121951, 2.222222222222223) 
```

### Additional context

Possible reason in [this commit](https://github.com/3b1b/manim/commit/d88c301622ad877b22e401f7d97abaf4cc29d6a5#r89150263).

When converting from coordinates to points, origin is included, but when converting from points to coordinate, the origin is ignored. Why?

**Comment by 3b1b** [comment]
I believe this is fixed now.
