### ISSUE TITLE
Tikz and Circuitikz does not work anymore

### ISSUE THREAD

**Issue by myzinsky** [3b1b/manim#1894]
I use this example: 

https://www.youtube.com/watch?v=sWSmd3cujK8

**Code**:
https://github.com/sayedul79/m-anim/blob/main/colored-circuit.py

However What I get looks like this: 

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/1970554/201149690-322e3270-5c83-41d5-a867-5489ddb76682.png">

i.e. all components are stuck together at one sigle point... 
Any Ideas what may have changed?

**Comment by TonyCrane** [comment]
This code uses the community version of manim. So please ask this question in their discord channel or open an issue at ManimCommunity/manim instead of here.

**Comment by myzinsky** [comment]
Reference: https://github.com/ManimCommunity/manim/issues/2293#issuecomment-1310786352
