### ISSUE TITLE
I met this error

### ISSUE THREAD

**Issue by dr-jiahaoCHEN** [3b1b/manim#1905]
GLib-GIO-WARNING **: 23:30:36.872: Unexpectedly, UWP app `Clipchamp.Clipchamp_2.5.5.0_neutral__yxz26nhyzhsrt' (AUMId `Clipchamp.Clipchamp_yxz26nhyzhsrt!App') supports 41 extensions but has no verbs

python3.9

**Comment by ospqul** [comment]
Just unistall this app: Clipchamp

**Comment by GjermundOstensvig** [comment]
I had the same error, and like @ospqul said, uninstalling it solved the issue.
