### ISSUE TITLE
Small bug: wrong type of "cube" in drawings.py Laptop class.

### ISSUE THREAD

**Issue by Jesperoka** [3b1b/manim#1912]
##Error message:

  File "C:\manim\manimlib\mobject\svg\drawings.py", line 152, in __init__
      body.set_fill(self.shaded_body_color, opacity=1)
  AttributeError: 'Cube' object has no attribute 'set_fill'

## Expected behavior:

Being able to instantiate the class and use it for whatever

## How to reproduce the issue:

```py
import manimlib
class MyScene(manimlib.Scene):
    def construct(self):
        myLaptop = manimlib.Laptop()
```

## How to fix:
In

C:\manim\manimlib\mobject\svg\drawings.py

Import VCube instead of Cube

drawings.py lines [15, 16]
```py
from manimlib.mobject.three_dimensions import Cube #
from manimlib.mobject.three_dimensions import VCube # Bugfix for set_fill() issue. --> Cube is then no longer accessed, so not needed.
```

and in the class Laptop(VGroup)

drawings.py lines [147, 155]
```py
def __init__(self, **kwargs):
        super().__init__(**kwargs)
        body = VCube(side_length=1) # Changed from Cube() to VCube(), fixed the issue for me ¯\_(ツ)_/¯
        for dim, scale_factor in enumerate(self.body_dimensions):
            body.stretch(scale_factor, dim=dim)
        body.set_width(self.width)
        body.set_fill(self.shaded_body_color, opacity=1)
        body.sort(lambda p: p[2])
        body[-1].set_fill(self.body_color)
```

**Comment by 3b1b** [comment]
Thanks! I believe this is now fixed.
