### ISSUE TITLE
How to get the latest version of manim? I try "git" and "zip" both, but terminal still showed 'manimgl v1.5.0'

### ISSUE THREAD

**Issue by barakasamsara** [3b1b/manim#1916]
How to get the latest version of manim? I try "git" and "zip" both, but terminal still showed 'manimgl v1.5.0'
![Untitled](https://user-images.githubusercontent.com/36161299/203599940-d44e506d-6391-4a2a-b711-ed45772f26c2.jpg)

I just thought maybe I misunderstood something until I saw this image in another issue...
![201511149-d88aa51a-9b81-4cad-bd79-42dff4639777](https://user-images.githubusercontent.com/36161299/203600149-3d91d97a-5545-4671-8d27-4eafa056c91b.png)

**Comment by TonyCrane** [comment]
See the README.md. You should install it locally by `pip install .` or `pip install -e .`.

**Comment by barakasamsara** [comment]
Thanks so much
