### ISSUE TITLE
Different expressions of pi creatures were found. Should we put them in the repository?

### ISSUE THREAD

**Issue by CaftBotti** [3b1b/manim#1925]
Now all pi creatures are able to get:
https://github.com/CaftBotti/manim_pi_creatures
They are from 3blue1brown.com, maybe they are using in 3b1b videos.
That repository also includes pi_creature.py, it is from cairo-backend, but i changed a little to use the different picreatures, you just need to put the picreature svgs in the assets folder, and use the modified pi_creature.py instead of the original one.
Then you can write a piece of code with many picreatures just like 3b1b's code, and the video you get will produce the same effects as in 3b1b's videos.
So should we put the different picreatures in this repository and/or manim-community? If we can use cute pi in our own animations, we will be more glad to use manim.

**Comment by TonyCrane** [comment]
No.
I think pi creatures are copyrighted by 3Blue1Brown (Grant) and they should not exist in this open source engine repo. And Grant probably moved the code about pi creatures that he only wanted to use in his videos out of this repo because of that.
