### ISSUE TITLE
There is something wrong in requirements.txt#L7 

### ISSUE THREAD

**Issue by ExerciseBook** [3b1b/manim#194]
https://github.com/3b1b/manim/blob/master/requirements.txt#L7

https://github.com/scottopell/aggdraw-64bits@c95aac4369038706943fd0effb7d888683860e5a is not found.

**Comment by MedNait** [comment]
Did you try "python -m pip install aggdraw" ?

**Comment by MedNait** [comment]
Correction: after seeing the updated README.md, I recommend not to use "python -m pip install aggdraw" as I suggested in a previous post since it will install a newer version of aggdraw that apparently does not work with manim.

**Comment by Leftier** [comment]
Download the version 1.2a3 from here https://www.lfd.uci.edu/~gohlke/pythonlibs/#aggdraw
And install it like this:

python -m pip install aggdraw‑1.2a3‑cp27‑cp27m‑win32.whl

**Comment by ExerciseBook** [comment]
I edited the file to install the package. XD.
I delete the ```@c95aac4369038706943fd0effb7d888683860e5a``` from the file.

**Comment by eulertour** [comment]
Closing, as this was resolved by 087715e538700e11bbc78e6acb8d1631fa93b182.
