### ISSUE TITLE
Unused Function `digest_mobject_attrs`

### ISSUE THREAD

**Issue by MrDiver** [3b1b/manim#1947]
I'm not quite sure if this function is used anymore. It was last changed about 3 years ago and doesn't seem to be used anymore and has no references either.

https://github.com/3b1b/manim/blob/fcff44a66b58a3af4070381afed0b4fad80768be/manimlib/mobject/mobject.py#L416-L423

(Currently working on updating the CE version to the new state of your repo, so if theres anything i can do for you while i'm looking at the code anyway just leave it here. Always happy to help)

**Comment by MrDiver** [comment]
Thank you for the quick response, that makes sense to keep old scenes from breaking.

**Comment by 3b1b** [comment]
> Currently working on updating the CE version to the new state of your repo, so if theres anything i can do for you while i'm looking at the code anyway just leave it here.

Thanks! On the flip side, if I can be helpful, or explain anything, don't hesitate to ask. I think what stands to be most useful for ManimCE are updates to Tex, allowing for indexing in my strings, and converting substrings into DecimalMobjects in place. The downside is that the code for StringMobject is a bit messy and not the easiest thing in the world to work with.

**Comment by MrDiver** [comment]
> if I can be helpful, or explain anything, don't hesitate to ask.
Currently it seems to go pretty well 🥳. We are at the stage were we are slowly removing cairo (temporarily). Thank you!

The Tex update seems really useful. I haven't looked in to the subclasses as much by now because we first need to get the base system to work again but that seems really useful!

Maybe in a few days there will be more questions 🎉
