### ISSUE TITLE
Typing Issue: Functions explicitly marked as return `None` but returning self

### ISSUE THREAD

**Issue by MrDiver** [3b1b/manim#1949]
Just stumbled upon these two functions and they explicitly return `None` but also return self. Is this intended?

https://github.com/3b1b/manim/blob/a0c46ef3bfbeb5cb0eb46f11431cdb02e133cf49/manimlib/mobject/mobject.py#L676-L684

**Comment by 3b1b** [comment]
Not intended, thanks for the catch.

What's more appropriate is to have the return type for most Mobject methods be "Self", which is I think is new to Python 3.11
