### ISSUE TITLE
Unable to remove a object on the screen when using an updater

### ISSUE THREAD

**Issue by michaelnicol** [3b1b/manim#1954]
I have the following code:

```
class Example2(Scene):
    def construct(self):
        
        step = ValueTracker(1)
        square = Square()
        circle = Circle()

        self.add(circle)
        self.add(square)

        def circleUpdater(m):
            m.shift(LEFT*0.1)
            self.remove(square)

        circle.add_updater(
            lambda m : circleUpdater(m)
        )

        self.play(step.animate.set_value(0.5))
        self.wait(1)
```

It works by creating a circle that has an updater that should remove the square in each frame. The circle is also shifted to the left each frame. However, the square is not removed in each frame that the updater fires. The square only gets removed at the end of the animate.set_value. 

Details

Manim Community v0.17.1
Windows 11

Proof:

In the video, you can see that it takes one second for the square to remove, which signifies it is being removed after the self.play has finished rather then during.

![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/41444983/210154829-e8153a9b-d0a3-4f46-8504-cb66ed6a53ba.gif)

**Comment by 3b1b** [comment]
This issue may be meant for the ManimCommunity repo, the example you listed works fine here.
