### ISSUE TITLE
Misspelled "EventListener" on multiple occasions

### ISSUE THREAD

**Issue by tchoopojcharoen** [3b1b/manim#1961]
### Describe the bug
The word "EventListener" is being spelled as "EventListner". I'm not sure if this is intentional.

### Additional context
https://github.com/3b1b/manim/blob/master/manimlib/event_handler/event_listner.py

**Comment by 3b1b** [comment]
Thanks! Fixed [here](https://github.com/3b1b/manim/pull/1979).
