### ISSUE TITLE
Getting an error: "UserWarning: Could not set COM MTA mode. Unexpected behavior may occur." [Pyglet Error]

### ISSUE THREAD

**Issue by Varniex** [3b1b/manim#1975]
### Describe the error

In any scene that I am running, whether it's in preview mode or not, I am getting the mentioned error. I searched everywhere but nothing closely related I found to resolve it. The problem is the output is really messed up. The rendering is not done properly. It started happen after one of the recent commits [that I am not sure of], before that everything was working fine. Maybe it's the way the rendering is being done.

**Error**:

Error from the package: `pyglet\libs\win32\__init__.py:326`

### Environment
**OS System**: Windows 11
**manim version**: master latest commit. 
**python version**: 3.9.16

Even, I created a fresh environment with python 3.10.6 and installed all the dependencies. Still the same error and same messed up rendered animation.

**Comment by 3b1b** [comment]
Can you share an image showing how the rendering is messed up?  And is there any kind of stack trace, or line number, associated with the warning?

**Comment by Varniex** [comment]
The error I got was just I mentioned: Line 326 from pyglet `libs\win32\__init__.py` package.

**Error**: `..\pyglet\libs\win32\__init__.py:326: UserWarning: Could not set COM MTA mode. Unexpected behavior may occur.
 warnings.warn("Could not set COM MTA mode. Unexpected behavior may occur.")`

There was no stack of error.
For reference, I am attaching both the old and new animations.

Old (this one is when `CONFIG` parameter was still used in manimgl):

https://user-images.githubusercontent.com/41651498/215852781-ccec45ee-c50a-44cd-accc-d010856c4456.mp4

New:

https://user-images.githubusercontent.com/41651498/215852851-771b8a2c-8efa-4891-bed6-b806f3b15876.mp4

**python version**: 3.10.8
**manim version**: Latest manim version

**Comment by 3b1b** [comment]
Are you able to check if [this fix](https://github.com/3b1b/manim/pull/1980) works on your end?  It's not directly related to the window warning but addresses a certain hypothesis about the rendering glitch.

**Comment by Varniex** [comment]
Yup! This fix worked perfectly well.
