### ISSUE TITLE
"Play" is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Leftier** [3b1b/manim#198]
After installing all the dependencies needed and trying to run the following line:

python extract_scene.py example_scenes.py SquareToCircle -pt

or

python extract_scene.py example_scenes.py SquareToCircle

```
Traceback (most recent call last):
  File "extract_scene.py", line 267, in main
    handle_scene(SceneClass(**scene_kwargs), **config)
  File "C:\Users\shai\Desktop\manim-master\scene\scene.py", line 75, in __init__
    self.open_movie_pipe()
  File "C:\Users\shai\Desktop\manim-master\scene\scene.py", line 618, in open_movie_pipe
    self.writing_process = sp.Popen(command, stdin=sp.PIPE)
  File "C:\Python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2] System could not find the file specified

"play" is not recognized as an internal or external command
```

**Comment by Qoutroy** [comment]
Have you installed `sox` properly?
Python can't use the command `play`(most likely because it does not exist, at least not in your $PATH)
Go to the terminal and write `play`
If it can't find sox, you have most likely not installed it correctly.

**Comment by cnrmck** [comment]
Should the play command work inside a docker container?

**Comment by eulertour** [comment]
Closing, as @Qoutroy gave the solution. @cnrmck, the `play` command will only work inside a docker container if it was installed, as it is in the dockerfile included in this repo.
