### ISSUE TITLE
how to commit and complete old_projects folder

### ISSUE THREAD

**Issue by pu17** [3b1b/manim#199]
I want use old_projects folder,but as README said I will have to go back to the commit which complete that project

but how to commit,I found this below ,but what should I do next?
![image](https://user-images.githubusercontent.com/22163384/38463843-abb76622-3b35-11e8-91fe-d1011ee4a22c.png)

**Comment by JoJoDeveloping** [comment]
Pro tip: Use git properly.
When you have found the commit you were looking for (IE by reading through the comment history, or using github to see when some file was moved into old_projects), you can revert back to the commit by running:
git checkout <commit>, where commit is the commit's ID (like 0d1d7fc32)

**Comment by eulertour** [comment]
Closing, as @JoJoDeveloping  gave the solution and this isn't related to manim.
