### ISSUE TITLE
Running Manim

### ISSUE THREAD

**Issue by AhmedSheraky12** [3b1b/manim#1995]
Hello!
So I installed manim successfully (I think) and I have been trying some test runs to see if it works or not. I am still new to programming, so there might be an obvious thing I am missing. It mentions that there are a couple of non-recognized stuff so, I was wondering what went wrong. Any help would be appreciated, and Thank you in advance!

So here is what is says: 
Media will be written to C:\Users\ahmed\Downloads\media\. You can change this behavior with the --media_dir flag.
C:\Users\ahmed\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-72 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\ahmed\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-101 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\ahmed\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-108 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\ahmed\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-111 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\ahmed\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-109 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\ahmed\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-97 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\ahmed\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-110 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\ahmed\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-105 not recognized
  warnings.warn("%s not recognized" % ref)
C:\Users\ahmed\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\manimlib\mobject\svg\svg_mobject.py:125: UserWarning: g0-33 not recognized
  warnings.warn("%s not recognized" % ref)

Traceback (most recent call last):
  File "C:\Users\ahmed\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "C:\Users\ahmed\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\manimlib\scene\scene.py", line 75, in __init__
    self.construct()
  File "C:\Users\ahmed\Downloads\bruh.py", line 5, in construct
    t = TextMobject("Hello manim!")
  File "C:\Users\ahmed\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\manimlib\mobject\svg\tex_mobject.py", line 150, in __init__
    self.break_up_by_substrings()
  File "C:\Users\ahmed\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\manimlib\mobject\svg\tex_mobject.py", line 190, in break_up_by_substrings
    sub_tex_mob.move_to(self.submobjects[last_submob_index], RIGHT)
IndexError: list index out of range

**Comment by Jim707t** [comment]
If you are new to programming, I suggest you use the [Manim community](https://github.com/ManimCommunity/manim) version which is documented, 3b1b manim is not, so it can be a bit tricky to install and use.

**Comment by TonyCrane** [comment]
And you are also not using manimgl. I think the manim you use is very old (i.e. cairo-backend), so please update it.
