### ISSUE TITLE
I had a problem while downloading manim

### ISSUE THREAD

**Issue by level17** [3b1b/manim#2000]
### Describe the bug
When I used pip3 install manim, i run into this error

**Code**:
 fatal error: 'cairo.h' file not found
      #include "cairo.h"
               ^~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for manimpango
  Building wheel for pycairo (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pycairo (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-cpython-310
      creating build/lib.macosx-10.9-universal2-cpython-310/cairo
      copying cairo/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/cairo
      copying cairo/__init__.pyi -> build/lib.macosx-10.9-universal2-cpython-310/cairo
      copying cairo/py.typed -> build/lib.macosx-10.9-universal2-cpython-310/cairo
      running build_ext
      'pkg-config' not found.
      Command ['pkg-config', '--print-errors', '--exists', 'cairo >= 1.15.10']
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycairo
Failed to build manimpango pycairo
ERROR: Could not build wheels for manimpango, pycairo, which is required to install pyproject.toml-based projects
**Wrong display or Error traceback**:

**Comment by TonyCrane** [comment]
I think you are using the community version of manim, so please read README.md in [ManimCommunity/manim](https://github.com/ManimCommunity/manim) or ask this question on their discord channel or open an issue in ManimCommunity/manim instead of here.
