### ISSUE TITLE
Redefine MEDIA_DIR in constants.py to point to a valid directory where movies and images will be written

### ISSUE THREAD

**Issue by dbw5718** [3b1b/manim#206]
`python extract_scene.py example_scenes.py 
Traceback (most recent call last):
  File "extract_scene.py", line 14, in <module>
    from helpers import *
  File "/home/tachyon/manim/helpers.py", line 13, in <module>
    from constants import *
  File "/home/tachyon/manim/constants.py", line 91, in <module>
    """)
Exception: 
        Redefine MEDIA_DIR in constants.py to point to 
        a valid directory where movies and images will 
        be written
    
`
How can I solve this problem?
Is it because docker is not installed?
I checked the previous question and did not understand how to solve it.

**Comment by vors** [comment]
Open the `constants.py` file and replace the `MEDIA_DIR`. Make it point to some existing local folder.

**Comment by dbw5718** [comment]
thank you very much!!!

**Comment by dbw5718** [comment]
I got it, thank you very much

**Comment by Qoutroy** [comment]
Close this issue...?

**Comment by Matemasters** [comment]
> Open the `constants.py` file and replace the `MEDIA_DIR`. Make it point to some existing local folder.

Greetings! 
May sound stupid but, can you describe (maybe with a good example) how do you replace `MEDIA_DIR` within `constants.py` in order to make it point to some existing local folder.
Thank you in advanced,

**Comment by Matemasters** [comment]
> 
> 
> Within the `Manim37` folder, create a folder for your output files -- I called mine `output`. Then open the file `constants.py` and go to line 23, which should look like:
> <img alt="screen shot 2018-09-26 at 8 18 32 am" width="468" src="https://user-images.githubusercontent.com/43263403/46090113-d6d56600-c164-11e8-919b-a421a93d9db8.png">
> 
> Replace `Dropbox (3Blue1Brown)/3Blue1Brown Team Folder` with the location of your output file, for example:
> <img alt="screen shot 2018-09-26 at 8 18 05 am" width="376" src="https://user-images.githubusercontent.com/43263403/46090174-01bfba00-c165-11e8-956b-3f6c5dfcdcdc.png">

Thank you very much, it helped me tons

**Comment by eulertour** [comment]
Closed, as this has been resolved.
