### ISSUE TITLE
Latex error converting to dvi

### ISSUE THREAD

**Issue by dbw5718** [3b1b/manim#207]
```
Traceback (most recent call last):
  File "extract_scene.py", line 253, in main
    handle_scene(SceneClass(**scene_kwargs), **config)
  File "/home/tachyon/manim/scene/scene.py", line 67, in __init__
    self.construct(*self.construct_args)
  File "/home/tachyon/manim/./example_scenes.py", line 62, in construct
    self.play(Write(TextMobject("Stuff").scale(3)))
  File "/home/tachyon/manim/mobject/tex_mobject.py", line 56, in __init__
    self.template_tex_file
  File "/home/tachyon/manim/mobject/tex_mobject.py", line 338, in tex_to_svg_file
    dvi_file = tex_to_dvi(tex_file)
  File "/home/tachyon/manim/mobject/tex_mobject.py", line 383, in tex_to_dvi
    "See log output above or the log file: %s" % log_file)
Exception: Latex error converting to dvi. See log output above or the log file: /home/tachyon/manim/files/Tex/-4565850486120066600.log

```
According to #36 I modified the command configuration
However, it still fails to solve the problem of failure to run other classes.
Can currently only run SquareToCircle class
How can I solve this problem?
Thank you

**Comment by pu17** [comment]
First,you need to check error message:
`cat /home/tachyon/manim/files/Tex/-4565850486120066600.log`
Probability, you have missed some component in Latex,you can uninstall Latex,and try this(in linux)
```
sudo apt-get install texlive-full
sudo apt install texlive-latex-base 
sudo apt install texlive-fonts-extra
```

**Comment by kiranajij** [comment]
If you have those packages installed thats maybe because the TEX HASH function returns negative value and the latex compiler treats it as a command, and also the latex compiler doesnot work all the time, so you need to use the pdflatex compiler. I created a pull request regarding the issue, hopefully it fixed all errors for me. Check out the changes, that might help.

**Comment by GrahamBenHarper** [comment]
@pu17 I read the tex log, and it said I was missing some .sty files. Those were exactly the packages I needed to install for them. Thanks a ton.

**Comment by eulertour** [comment]
Closing, since this issue seems to be resolved.

**Comment by abecus** [comment]
@pu17  
I am facing the same problem with win10.
what about win10 users?
-thankyou in advance

**Comment by jaddoescad** [comment]
facing the same issue

**Comment by dthemg** [comment]
I had the same issue. I had to remove miktex before installing texlive:
`sudo apt remove miktex
sudo apt-get install texlive-full
sudo apt-get install texlive-latex-base
sudo apt-get install texlive-fonts-extra`

**Comment by erfansalavati** [comment]
I had the same problem. After hours of investigation I figured out that there was something wrong with the path that the tex file is written.

The problem was solved by changing
MEDIA_DIR = "./media"
to
MEDIA_DIR = ".\media"
in "tex_file_writing.py"

**Comment by aninska** [comment]
> I had the same problem. After hours of investigation I figured out that there was something wrong with the path that the tex file is written.
> 
> The problem was solved by changing
> MEDIA_DIR = "./media"
> to
> MEDIA_DIR = ".\media"
> in "tex_file_writing.py"


Thanks for the information!! I'll try this! I have the same issue...
