### ISSUE TITLE
Write Chinese words problem!

### ISSUE THREAD

**Issue by pu17** [3b1b/manim#209]
Hi,I am Chinese, so I need to use it to write some Chinese words, I have tried to use template.tex as README.TXT said, and I alse tried to add below codes at the beginning,It still not work in ./example_scenes.py  WriteStuff
```
 #!/usr/bin/python
# -*- coding: UTF-8 -*-
```

here is error message,someone please help
![image](https://user-images.githubusercontent.com/22163384/38716579-0b572a2c-3f14-11e8-9281-e4e62e2a6f99.png)

**Comment by pu17** [comment]
AS I further investigate,I found that maybe it is not python cause this problem,it is Latex unable to compile Chinese, should install CTEX to fix this problem?

**Comment by bhopro** [comment]
Were you ever able to get Chinese characters to print out?

**Comment by icreiuheciijc** [comment]
You can write Chinese with the following changes:

In `tex_template.tex`, change lines 19-20:
```
\DisableLigatures{encoding = *, family = * }
%\usepackage[UTF8]{ctex}
```
to:
```
%\DisableLigatures{encoding = *, family = * }  
\usepackage[UTF8]{ctex}
```

Then, in `utils/tex_file_writing.py`, change lines 46-88:
```
def tex_to_dvi(tex_file):
    result = tex_file.replace(".tex", ".dvi")
    if not os.path.exists(result):
        commands = [
            "latex",
            "-interaction=batchmode",
            "-halt-on-error",
            "-output-directory=" + TEX_DIR,
            tex_file,
            ">",
            get_null()
        ]
        exit_code = os.system(" ".join(commands))
        if exit_code != 0:
            log_file = tex_file.replace(".tex", ".log")
            raise Exception(
                "Latex error converting to dvi. "
                "See log output above or the log file: %s" % log_file)
    return result


def dvi_to_svg(dvi_file, regen_if_exists=False):
    """
    Converts a dvi, which potentially has multiple slides, into a
    directory full of enumerated pngs corresponding with these slides.
    Returns a list of PIL Image objects for these images sorted as they
    where in the dvi
    """
    result = dvi_file.replace(".dvi", ".svg")
    if not os.path.exists(result):
        commands = [
            "dvisvgm",
            dvi_file,
            "-n",
            "-v",
            "0",
            "-o",
            result,
            ">",
            get_null()
        ]
        os.system(" ".join(commands))
    return result
```
to:
```
def tex_to_dvi(tex_file):
    # result = tex_file.replace(".tex", ".dvi")
    result = tex_file.replace(".tex", ".xdv")
    if not os.path.exists(result):
        # commands = [
        #     "latex",
        #     "-interaction=batchmode",
        #     "-halt-on-error",
        #     "-output-directory=" + TEX_DIR,
        #     tex_file,
        #     ">",
        #     get_null()
        # ]
        commands = [
            "xelatex",
            "-no-pdf",
            "-interaction=batchmode",
            "-halt-on-error",
            "-output-directory=" + TEX_DIR,
            tex_file,
            ">",
            get_null()
        ]
        exit_code = os.system(" ".join(commands))
        if exit_code != 0:
            log_file = tex_file.replace(".tex", ".log")
            raise Exception(
                "Latex error converting to dvi. "
                "See log output above or the log file: %s" % log_file)
    return result


def dvi_to_svg(dvi_file, regen_if_exists=False):
    """
    Converts a dvi, which potentially has multiple slides, into a
    directory full of enumerated pngs corresponding with these slides.
    Returns a list of PIL Image objects for these images sorted as they
    where in the dvi
    """
    # result = dvi_file.replace(".dvi", ".svg")
    result = dvi_file.replace(".xdv", ".svg")
    if not os.path.exists(result):
        commands = [
            "dvisvgm",
            dvi_file,
            "-n",
            "-v",
            "0",
            "-o",
            result,
            ">",
            get_null()
        ]
        os.system(" ".join(commands))
    return result
```

Reference: PR #48 Issue #64

**Comment by icreiuheciijc** [comment]
![screen shot 2018-09-16 at 2 15 26 pm](https://user-images.githubusercontent.com/29544653/45593516-fdeca480-b9ba-11e8-9682-b35837125f3d.png)

**Comment by bhopro** [comment]
Thank for your help. I am in need to use Korean (Hangul) characters. For anyone else interested, all I needed to do was add `\usepackage{kotex}` to the `tex_template.tex` and the changes listed above in `tex_file_writing.py`.

<img width="1412" alt="screen shot 2018-09-17 at 12 33 56 pm" src="https://user-images.githubusercontent.com/43263403/45645645-ff2ed780-ba75-11e8-9378-8afd2fe9e937.png">

**Comment by pu17** [comment]
thanks very match for help, I have fixed this problem new

**Comment by pu17** [comment]
hello, I had using your way,but it seems only xdv file been generated echo times,but without svg file,
![image](https://user-images.githubusercontent.com/22163384/45749768-4fa56100-bc3f-11e8-9c61-4fef391713e1.png)

**Comment by icreiuheciijc** [comment]
@pu17  Try changing manim/mobject/svg/svg_mobject.py, lines 50-63:

```
def ensure_valid_file(self):
        if self.file_name is None:
            raise Exception("Must specify file for SVGMobject")
        possible_paths = [
            os.path.join(SVG_IMAGE_DIR, self.file_name),
            os.path.join(SVG_IMAGE_DIR, self.file_name + ".svg"),
            self.file_name,
        ]
        for path in possible_paths:
            if os.path.exists(path):
                self.file_path = path
                return
        raise IOError("No file matching %s in image directory" %
                      self.file_name)
```
to
```
def ensure_valid_file(self):
        if self.file_name is None:
            raise Exception("Must specify file for SVGMobject")
        possible_paths = [
            os.path.join(SVG_IMAGE_DIR, self.file_name),
            os.path.join(SVG_IMAGE_DIR, self.file_name + ".svg"),
            os.path.join(SVG_IMAGE_DIR, self.file_name + ".xdv"),
            self.file_name,
        ]
        for path in possible_paths:
            if os.path.exists(path):
                self.file_path = path
                return
        raise IOError("No file matching %s in image directory" %
                      self.file_name)
```

**Comment by SniperM99** [comment]
> You can write Chinese with the following changes:
> 
> In `tex_template.tex`, change lines 19-20:
> 
> ```
> \DisableLigatures{encoding = *, family = * }
> %\usepackage[UTF8]{ctex}
> ```
> 
> to:
> 
> ```
> %\DisableLigatures{encoding = *, family = * }  
> \usepackage[UTF8]{ctex}
> ```
> 
> Then, in `utils/tex_file_writing.py`, change lines 46-88:
> 
> ```
> def tex_to_dvi(tex_file):
>     result = tex_file.replace(".tex", ".dvi")
>     if not os.path.exists(result):
>         commands = [
>             "latex",
>             "-interaction=batchmode",
>             "-halt-on-error",
>             "-output-directory=" + TEX_DIR,
>             tex_file,
>             ">",
>             get_null()
>         ]
>         exit_code = os.system(" ".join(commands))
>         if exit_code != 0:
>             log_file = tex_file.replace(".tex", ".log")
>             raise Exception(
>                 "Latex error converting to dvi. "
>                 "See log output above or the log file: %s" % log_file)
>     return result
> 
> 
> def dvi_to_svg(dvi_file, regen_if_exists=False):
>     """
>     Converts a dvi, which potentially has multiple slides, into a
>     directory full of enumerated pngs corresponding with these slides.
>     Returns a list of PIL Image objects for these images sorted as they
>     where in the dvi
>     """
>     result = dvi_file.replace(".dvi", ".svg")
>     if not os.path.exists(result):
>         commands = [
>             "dvisvgm",
>             dvi_file,
>             "-n",
>             "-v",
>             "0",
>             "-o",
>             result,
>             ">",
>             get_null()
>         ]
>         os.system(" ".join(commands))
>     return result
> ```
> 
> to:
> 
> ```
> def tex_to_dvi(tex_file):
>     # result = tex_file.replace(".tex", ".dvi")
>     result = tex_file.replace(".tex", ".xdv")
>     if not os.path.exists(result):
>         # commands = [
>         #     "latex",
>         #     "-interaction=batchmode",
>         #     "-halt-on-error",
>         #     "-output-directory=" + TEX_DIR,
>         #     tex_file,
>         #     ">",
>         #     get_null()
>         # ]
>         commands = [
>             "xelatex",
>             "-no-pdf",
>             "-interaction=batchmode",
>             "-halt-on-error",
>             "-output-directory=" + TEX_DIR,
>             tex_file,
>             ">",
>             get_null()
>         ]
>         exit_code = os.system(" ".join(commands))
>         if exit_code != 0:
>             log_file = tex_file.replace(".tex", ".log")
>             raise Exception(
>                 "Latex error converting to dvi. "
>                 "See log output above or the log file: %s" % log_file)
>     return result
> 
> 
> def dvi_to_svg(dvi_file, regen_if_exists=False):
>     """
>     Converts a dvi, which potentially has multiple slides, into a
>     directory full of enumerated pngs corresponding with these slides.
>     Returns a list of PIL Image objects for these images sorted as they
>     where in the dvi
>     """
>     # result = dvi_file.replace(".dvi", ".svg")
>     result = dvi_file.replace(".xdv", ".svg")
>     if not os.path.exists(result):
>         commands = [
>             "dvisvgm",
>             dvi_file,
>             "-n",
>             "-v",
>             "0",
>             "-o",
>             result,
>             ">",
>             get_null()
>         ]
>         os.system(" ".join(commands))
>     return result
> ```
> 
> Reference: PR #48 Issue #64

--------------------------------------------------------------------------
now, we can modify directly in manimlib/constants.py , change line 50, `TEX_USE_CTEX = False`  to `TEX_USE_CTEX = True`

**Comment by baqianxin** [comment]
windows 路径问题 

    os.path.join(consts.TEX_DIR,"xxxx.tex") #会拼接 `\` 到文件路径中，需要做转换
    result = Path(result).as_posix() # 替换 `\` 为 `/`
    tex_file = Path(tex_file).as_posix()
    tex_dir = Path(consts.TEX_DIR).as_posix()

LaTex 中文问题
   修改constants.py line 50
   TEX_USE_CTEX = True 
   对应逻辑：
   1.使用CTEX模板文件 （默认为TEX模板文件）
   2.使用XDV文件生成视频图片 （默认使用DVI）

**Comment by DGideas** [comment]
@SniperM99 Thanks! I'm interested why don't set TEX_USE_CTEX = True as default vaule?

**Comment by hanwenzhu** [comment]
> @SniperM99 Thanks! I'm interested why don't set `TEX_USE_CTEX = True` as default vaule?

@DGideas It was like that a few years ago (see #48, the PR by @Solara570 back in 2017), but CTEX uses XeLaTeX which causes a lot of other problems like #64 or #124 or #142 (these were really old issues). Eventually it was deleted in #200.

**Comment by aaa5890012** [comment]
对上边的“大神”的方法都用了，还是不能显示中文

**Comment by DGideas** [comment]
> ## 中国,如果下载的是最新版本的manim,并且只是想要在manim中显示中文, 对于LaTeX没有中文显示需求的, 可以直接按照如下操作进行.
> 
> 直接修改` manimlib/constants.py` 第50行的 `TEX_USE_CTEX = False` 为 `TEX_USE_CTEX = True`
> 
> now, we can modify directly in manimlib/constants.py , change line 50, `TEX_USE_CTEX = False` to `TEX_USE_CTEX = True`

@aaa5890012 这个你也试了吗？

**Comment by beck0505** [comment]
``` 
title = Text('测试中文字符', font='Weibei SC')
```
Try to set the font that your computer has that support Chinese characters. This way works.

**Comment by shartoo** [comment]
there is no content `TEX_USE_CTEX = False`  in `constants.py`  in the newest version of this repo any more,what can i do?

**Comment by plantinghero** [comment]
> there is no content `TEX_USE_CTEX = False` in `constants.py` in the newest version of this repo any more,what can i do?

我也发现找不到啊，估计是又更新了，请问你解决这个问题了吗？
I have the same problem, have you solved this?

**Comment by TonyCrane** [comment]
是更新了，现在在config文件里面改：
```yaml
tex:
  executable: xelatex -no-pdf
  intermediate_filetype: xdv
  template_file: ctex_template.tex
  text_to_replace: '[tex_expression]'
```
这样和原来`TEX_USE_CTEX = True`的效果是一样的。
或者可以直接运行`manimgl --config`，询问第[6/8]个问题时输入`xelatex`

**Comment by gityaozhenhua** [comment]
> 是更新了，现在在config文件里面改：
> 
> ```yaml
> tex:
>   executable: xelatex -no-pdf
>   intermediate_filetype: xdv
>   template_file: ctex_template.tex
>   text_to_replace: '[tex_expression]'
> ```
> 
> 这样和原来`TEX_USE_CTEX = True`的效果是一样的。
> 或者可以直接运行`manimgl --config`，询问第[6/8]个问题时输入`xelatex`

是直接把代码添加上去就行吗？

**Comment by TonyCrane** [comment]
建议你先看文档：
ZH_CN:
https://docs.manim.org.cn/shaders/getting_started/configuration.html#id5
https://docs.manim.org.cn/shaders/documentation/custom_config.html#tex
EN:
https://3b1b.github.io/manim/getting_started/configuration.html#custom-config
https://3b1b.github.io/manim/documentation/custom_config.html

**Comment by Social-Mean** [comment]
> ```
> title = Text('测试中文字符', font='Weibei SC')
> ```
> 
> Try to set the font that your computer has that support Chinese characters. This way works.

有用, 我把字体改成 微软雅黑就好了. 谢谢! 
It works when I use `font = 'Microsoft Yahei'`. Thanks!
