### ISSUE TITLE
Set the default font type for manim

### ISSUE THREAD

**Issue by fededed56** [3b1b/manim#2100]
When I use the Text() function, I write the text in Chinese, but it see that Manim does not support Chinese,I think manim should set the default font is MSYH

**Comment by pushpankar** [comment]
Manim supports custom font though:
https://github.com/3b1b/manim/blob/4729e44e057fcc4f02b4d6bdb64c010af4a540b3/manimlib/mobject/svg/text_mobject.py#L82

**Comment by fededed56** [comment]
ok,thanks
