### ISSUE TITLE
manim reders "broken" images

### ISSUE THREAD

**Issue by Ray625625** [3b1b/manim#2165]
As I installed manim through **Windows (Direct)** section in [the documentation](https://3b1b.github.io/manim/getting_started/installation.html) and ran ``manimgl example_scenes.py OpeningManimExample`` in the terminal, what manim rendered was a mess, as shown below: 

![屏幕截图 2024-09-12 201329](https://github.com/user-attachments/assets/5bb6d8ad-c431-441a-bb08-68385e35ec33)

Going through the [Quick Start](https://3b1b.github.io/manim/getting_started/quickstart.html) section gives a similar result: 

![屏幕截图 2024-09-12 201232](https://github.com/user-attachments/assets/fb776670-8732-4836-a226-45866e212005)

I am on Windows 11 and Python 3.10.11.

**Comment by mathsvisualization** [comment]
Yes Bro Same Problem 😭

**Comment by Ray625625** [comment]
Just reinstalled windows. The problem consists.

**Comment by mathsvisualization** [comment]
> Just reinstalled windows. The problem consists.



> Just reinstalled windows. The problem consists.

Also these are not errors of windows, this is a mess in the ManimGL library

**Comment by Ray625625** [comment]
> > Just reinstalled windows. The problem consists.
> 
> > Just reinstalled windows. The problem consists.
> 
> Also these are not errors of windows, this is a mess in the ManimGL library

Well, I thought TeX was working properly so it must have been the stuff that renders the images and I dont know :(

**Comment by Ray625625** [comment]
Just tried the [cummunity edition](https://docs.manim.community/en/stable/installation.html), it works perfectly @mathsvisualization

**Comment by mathsvisualization** [comment]
> The issue is likely caused by the update on August 19, 2024. The specific problematic commit ID is [24b160f](https://github.com/3b1b/manim/commit/24b160f9f9c3fde3a6c0f735f75df259173e32c3). You can try using `git reset --hard f9b9cf69fdea86f1d591613131ef7d0d18728300` to resolve this problem.


can you contact me on instagram?
@maths.visualization

**Comment by LJD96** [comment]
https://github.com/3b1b/manim/issues/2165#issuecomment-2354800132

**Comment by 3b1b** [comment]
I've since made a change that (I believe) addresses this. Can you let me know whether the most recent commits to this repo contain the same issue on your machine?

**Comment by Ray625625** [comment]
> I've since made a change that (I believe) addresses this. Can you let me know whether the most recent commits to this repo contain the same issue on your machine?

I seems that manimgl 1.6.1 requires manimpango <0.5.0, >=0.4.0; while manim 0.18.1 requires manimpango <1.0.0, >=0.5.0, so there's no way installing an appropriate version of manimpango. 

The bunch of Chinese basically means manimgl cannot be recognized as a cmdlet, a function, a script or an executable file.

Thank you, Grant @3b1b 

![屏幕截图 2024-10-12 173506](https://github.com/user-attachments/assets/2e47bcd1-c30e-482a-9810-e935568bbe83)

**Comment by 3b1b** [comment]
Do you have any idea why it's listed for <0.5.0? When I run it with later versions of ManimPango it seems fine.

**Comment by CoderXL1** [comment]
> Do you have any idea why it's listed for <0.5.0? When I run it with later versions of ManimPango it seems fine.

Thanks for providing this information. After upgrading to the latest manimpango(which pip reported as incompatible with manimgl), the previous render problem is gone. I suppose someone should update the requirements.txt or whatever.

**Comment by Ray625625** [comment]
> > Do you have any idea why it's listed for <0.5.0? When I run it with later versions of ManimPango it seems fine.
> 
> Thanks for providing this information. After upgrading to the latest manimpango(which pip reported as incompatible with manimgl), the previous render problem is gone. I suppose someone should update the requirements.txt or whatever.

Yes that fixed the problem. Thank you for your work @CoderXL1 @3b1b , manim now works perfectly on my device. Let me close this issue.
