### ISSUE TITLE
ManimGL : Text And Mobject Issues

### ISSUE THREAD

**Issue by mathsvisualization** [3b1b/manim#2166]
https://github.com/user-attachments/assets/eb49ab87-4ebf-4467-a33d-f1ed3ca1ec1f

### Describe the bug

**Code**:

**Wrong display or Error traceback**:

**Comment by lixiangsheng2018** [comment]
I encountered the same problem，It seems that the path of the animation is presented, but has not been cleaned up. Waiting for resolution......

**Comment by lixiangsheng2018** [comment]
commit ：8235607b2a45849bc799b79049678668f091a635 is ok,the newst version is bad

**Comment by mathsvisualization** [comment]
> commit ：8235607b2a45849bc799b79049678668f091a635 is ok,the newst version is bad

How to install ? Can you message me on instagram ?
@maths.visualization

**Comment by lixiangsheng2018** [comment]
git reset --hard 8235607b2a45849bc799b79049678668f091a635

> > commit ：8235607b2a45849bc799b79049678668f091a635 is ok,the newst version is bad
> 
> How to install ? Can you message me on instagram ? @maths.visualization

**Comment by lixiangsheng2018** [comment]
but this mesh line cannot show

**Comment by mathsvisualization** [comment]
Can you message me on instagram ? @maths.visualization

Please Urgent ? Messenge me

**Comment by lixiangsheng2018** [comment]
I have no telegram account> Messenge

**Comment by mathsvisualization** [comment]
> I have no intendgram account> Messenge

Instagram

**Comment by lixiangsheng2018** [comment]
after 24b160f9f9c3fde3a6c0f735f75df259173e32c3  all have problem

commit 24b160f9f9c3fde3a6c0f735f75df259173e32c3 (have issue)
Author: Grant Sanderson <grant@3blue1brown.com>
Date:   Mon Aug 19 08:05:32 2024 -0500

    Update VMobject shader wrapper
    
    Use a combined VBO
    Render with TRIANGLE_STRIP, and ignore every other

commit f9b9cf69fdea86f1d591613131ef7d0d18728300 (normal)
Author: Grant Sanderson <grant@3blue1brown.com>
Date:   Sat Aug 17 07:11:56 2024 -0500

    Update so that vbo is not recreated on each from, but is read into

**Comment by lixiangsheng2018** [comment]
I think the vbo my not cleared during animation @grant@3blue1brown.com can you check and fix this

commit 24b160f9f9c3fde3a6c0f735f75df259173e32c3
Author: Grant Sanderson <grant@3blue1brown.com>
Date:   Mon Aug 19 08:05:32 2024 -0500

    Update VMobject shader wrapper

    Use a combined VBO
    Render with TRIANGLE_STRIP, and ignore every other

**Comment by 3b1b** [comment]
One guess is that the use of gl_VertexID isn't consistent on all GPUs. 

Can you let me know if it works on your machine from this branch?  https://github.com/3b1b/manim/pull/2171

**Comment by germanzhu** [comment]
> One guess is that the use of gl_VertexID isn't consistent on all GPUs.
> 
> Can you let me know if it works on your machine from this branch? #2171

This patch works for me, and the issue has been resolved. `git checkout fix-vert-index-issue`

**Comment by mathsvisualization** [comment]
> > One guess is that the use of gl_VertexID isn't consistent on all GPUs.
> > Can you let me know if it works on your machine from this branch? #2171
> 
> This patch works for me, and the issue has been resolved. `git checkout fix-vert-index-issue`

Bro can you talk to me on Instagram? I talked about something related to manim. I.G @maths.visualization
