### ISSUE TITLE
when i run example by manimgl, circle displayed not coorectly

### ISSUE THREAD

**Issue by hashixuehua** [3b1b/manim#2172]
### Describe the bug
when i run manim, circle displayed not coorectly.it seems has may lines around the circle.
![image](https://github.com/user-attachments/assets/807f1411-6121-4a29-9755-9a4b76d35b67)
![image](https://github.com/user-attachments/assets/4e047f17-b5da-4755-88c6-91c72abeb933)

**Code**:
from manimlib import *

class SquareToCircle(Scene):
    def construct(self):
        circle = Circle()
        circle.set_fill(BLUE, opacity=0.5)
        circle.set_stroke(BLUE_E, width=4)

        self.add(circle)

**Wrong display or Error traceback**:

### Additional context

Windows;Python 3.10,

**Comment by hashixuehua** [comment]
the version of manimgl is latest,clone and compiled at today.
the english letter Text is also occured the same question.
![image](https://github.com/user-attachments/assets/cf3332d3-36df-4b17-b8d7-cfd6e4c15bd9)
![image](https://github.com/user-attachments/assets/0870da75-e112-443e-a1ae-f6d4f9d8c09d)

alternative,when the manimgl is displaying,my GPU's working state is as below picture.
![image](https://github.com/user-attachments/assets/2305a64e-25bb-4ef0-85f9-d913db2f543a)

**Comment by mathsvisualization** [comment]
DM me, I will fix this, it was happening to me too 
Instagram:- @maths.visualization

**Comment by 3b1b** [comment]
Is this still happening for you on the most recently updated version?

**Comment by mathsvisualization** [comment]
> Is this still happening for you on the most recently updated version?

No, this was before the update. Now everything has been fixed but there is still a problem related to MIMCE. Whenever I run any big code, I get an attributes error.
![Screenshot_2024-10-07_134941](https://github.com/user-attachments/assets/d194dfc5-2487-4ef5-a013-e5e33ec2f641)

**Comment by 3b1b** [comment]
Okay, glad to hear it's working.

To your other concern, that sounds like a question for the community edition.
