### ISSUE TITLE
That's important! Why I can't run my manim?

### ISSUE THREAD

**Issue by EgorusAbobus434** [3b1b/manim#2173]
### Discussed in https://github.com/3b1b/manim/discussions/2098

<div type='discussions-op-text'>

<sup>Originally posted by **CharlieGao2009** February 10, 2024</sup>
When I run `manimgl` in command prompt, the following error occurs:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\gao\AppData\Roaming\Python\Python311\Scripts\manimgl.exe\__main__.py", line 4, in <module>
  File "C:\Users\gao\AppData\Roaming\Python\Python311\site-packages\manimlib\__main__.py", line 6, in <module>
    from manimlib import __version__
ImportError: cannot import name '__version__' from 'manimlib' (C:\Users\gao\AppData\Roaming\Python\Python311\site-packages\manimlib\__init__.py)
```
Could anybody help me solve this? Thank you very much :D</div>

**Comment by EgorusAbobus434** [comment]
I just have the same problem and i need help :\

**Comment by MathItYT** [comment]
> I just have the same problem and i need help :\

I'm sorry for replying too late, but you maybe can run `pip install setuptools` (in Windows) or `pip3 install setuptools` (in MacOS/Linux) and that should solve your problem.

**Comment by mitkonikov** [comment]
You're have probably downloaded manimgl from pypi (using pip install manimgl). In that case, you will need Python 3.10 or less. The release of manimgl in pypi is 2+ years old and doesn't support new versions of Python and numpy. If you want the latest, clone the repository and run the commands to install it from the repo. (See Readme.md). But be aware that the repo is not stable.

**Comment by JasonAlbertEinstien** [comment]
I think the best solution for this problem if you are using linux / MacOS is using virtual environment
```
python3 -m venv .env
source .env/bin/activate
pip3 install manim manimlib
```
This should work.

**Comment by EgorusAbobus434** [comment]
I'm using Windows, and thanks to replying me

чт, 17 окт. 2024 г., 14:16 JasonAlbertEinstien ***@***.***>:

**Comment by a20144** [comment]
> ### Discussed in #2098
> Originally posted by **CharlieGao2009** February 10, 2024 When I run `manimgl` in command prompt, the following error occurs:
> 
> ```
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "C:\Users\gao\AppData\Roaming\Python\Python311\Scripts\manimgl.exe\__main__.py", line 4, in <module>
>   File "C:\Users\gao\AppData\Roaming\Python\Python311\site-packages\manimlib\__main__.py", line 6, in <module>
>     from manimlib import __version__
> ImportError: cannot import name '__version__' from 'manimlib' (C:\Users\gao\AppData\Roaming\Python\Python311\site-packages\manimlib\__init__.py)
> ```
> 
> Could anybody help me solve this? Thank you very much :D

Have you solved this issue? I have the same problem . Can you give some info how to solve it? Thanks!

**Comment by mitkonikov** [comment]
Can you tell us which `manimgl` version you have installed?
