### ISSUE TITLE
The problem of black screen.

### ISSUE THREAD

**Issue by ZhaoJianQiu** [3b1b/manim#218]
I am working on Windows.
Yesterday I cloned manim then tried the command "python extract_scene.py example_scenes.py SquareToCircle -pl" and got a file of mp4,but it was full of black when I open it.
On github I found that many people had also met this problem.Then I read some of other issues but useless.
I tried adding the argument "--save_pngs",but got a sequence of black picture,full of black.
I removed a line of code in scene.py(561):
image = image.convert(mode)
Surprisedly I got correct pngs,on which there is a square turning to a circle.
But the video was still in black screen.
Then I found something unbelievable.
As the code in example_scenes.py and mobject/geometry.py,the square on pngs must be in the color of white,but in fact it's black.Something wrong must have happened when the color being initialized.
I think it is the key of this problem,which accounts for the black screen video,just because the video's background is black.If the video's background is white,the graphs should be shown correctly.
Ah,to be honest,I'm not able to solve this problem,so I posted this issue so that someone can help to do this.

**Comment by ExerciseBook** [comment]
我还以为就我一个人黑屏。。。

**Comment by Qoutroy** [comment]
Close the issue...?
