### ISSUE TITLE
Tetrahedron inside sphere

### ISSUE THREAD

**Issue by Cyteriti** [3b1b/manim#226]
Hello, I am a student that is currently working on the Putnam question you showed in the video "hardest question on the hardest test". My question is, what program did you use to animate the sphere and the tetrahedron? As well as, the trials you made on the side to prove the theory, through the probabilty calculations.

**Comment by Jar-win** [comment]
@3b1b Even the topology ones were done using Grapher?

**Comment by eulertour** [comment]
Closing, as this isn't related to manim.
