### ISSUE TITLE
Caching issue during `reload()`

### ISSUE THREAD

**Issue by Splines** [3b1b/manim#2272]
I can reproduce the following issue when the Manimlib itself is not reloaded during `reload()`. Use this example:

```py
from manimlib import *


class MyFirstManimNotebook(Scene):
    def construct(self):
        ## Your first Manim Cell
        circle = Circle()
        circle.set_stroke(BLUE_E, width=4)
        self.play(ShowCreation(circle))

        ## Transform circle to square
        square = Square()
        self.play(ReplacementTransform(circle, square))

        ## Make it red and fly away
        self.play(
            square.animate.set_fill(RED_D, opacity=0.5),
            self.frame.animate.set_width(25),
        )

```

- Start on line 11

```
manimgl "./path/to/file.py" MyFirstManimNotebook -se 11 --log-level DEBUG
```

- `checkpoint_paste()` the part that starts with `## Transform circle to square` (lines 11-13)
- `reload(11)`
- `checkpoint_paste()` again the part that starts with `## Transform circle to square` (lines 11-13)

I end up with this state:

<img src="https://github.com/user-attachments/assets/9f0b37ff-1801-473a-a9cc-b4daa19778ab" width="250px"/>

Now go to the `module_loader.py` and set `ignore_manimlib_modules = False`. Do everything again and end up with the desired state:

<img src="https://github.com/user-attachments/assets/dc02ffb4-f9d9-4768-be49-cb9941620550" width="250px"/>

---

I haven't been able to track this issue down yet. Maybe something with the `CheckpointManager`. Is there any additional cleanup needed in the `except KillEmbedded` block in `run_scenes()`?

What I tried so far (without any luck) is this before the `Reloading...`:

- `self.scene.clear()`
- `self.scene.tear_down()`
- `self.checkpoint_manager.clear_checkpoints()`
- `self.shell.run_line_magic("reset", "-f")`

**Comment by 3b1b** [comment]
Very likely just need to have CheckpointManager clear it's states upon reloading, I'll look into it.

**Comment by Splines** [comment]
A quick-and-dirty solution would be to always reload modules in the `manimlib.scene` namespace as I've done [via this commit](https://github.com/Splines/manim-fork/commit/884d6e8e092ff74ce3d6065fa3a257426f670c9b). At least, this narrows down where the problem could be coming from. Hopefully a quick cleanup in the `CheckpointManager` will do, though.

**Comment by Splines** [comment]
Wow, that was quick ;) Thanks, it works 🎉

**Comment by 3b1b** [comment]
Sure, I can do a release shortly.
