### ISSUE TITLE
LaTeX error converting to DVI

### ISSUE THREAD

**Issue by jyl63** [3b1b/manim#237]
Hello all,
I've been trying to learn how to use manim and have been playing around with `example_scenes.py`
I've managed to get all of the classes working except for WriteStuff. I keep getting what looks to be the now-infamous "Latex error converting to DVI."

I seem to have a number of problems. Most cosmetic of those is that the LaTeX log files isn't saving to my \files\Tex folder (I've since found the .log file mentioned in the command prompt error in C:\Programs of all places; it's also named "texput.log" rather than "<hash>.log"[weird, any thoughts?]).

I think I've nailed down the crux of the problem but don't know how to solve it. Upon running `extract_scene.py example_scenes.py WriteStuff -p` the `tex_file_writing.py` commands[...] in`tex_to_div` are throwing something off. The LaTeX log spits out the following:

`This is pdfTeX, Version 3.14159265-2.6-1.40.18 (MiKTeX 2.9.6500 64-bit) (preloaded format=latex 2018.5.16)  17 MAY 2018 22:32
entering extended mode`
`**Files (x86)\Python27\manim-master\files\Tex C:\Program Files (x86)\Python27\m
anim-master\files\Tex\-755577849.tex`
`! Emergency stop.`
`<*> Files 
          (x86)\Python27\manim-master\files\Tex C:\Program Files (x86)\Pytho...`
I can't figure out why the commands[...] are trying to run "Files (x86) instead of `tex_file`....
If I run each of the LaTeX commands in the command prompt manually everything works fine. Thus, unfortunately the recommendations of #36 haven't really helped... :'( (it also looks like the master has changed recently enough that `tex_to_div` is now in tex_file_writing.py rather than in tex_mobject.py ???)

Any thoughts?? Any help would be much appreciated.
Thanks
-- A failed mathematician, and hopeful manim user

**Comment by rajdakin** [comment]
The log should be named `texput.log` probably because you try to write `texput`. But it seems weird, because you are trying to write `Stuff` instead... Are you sure that you have no local changes (except the one from that issue)? It may cause the problem...
If you have a space in your `commands` stuff, try to esape it by predecessing it with a `\`.

I don't see any other stuff that could cause this mess. Maybe try to put the log if this didn't work?

**Comment by jyl63** [comment]
I've figured it out!
It turns out that it was nowhere near as complicated as I thought it was.
It turns out that the Win10 Command Prompt wasn't playing nice with the LaTeX command options.
Because there was a space in my the the path file "C:\Program<space>Files...", in the `-output-directory=<PATH>` option, the LaTeX command assumed that the path ended at "Program".

This problem can be resolved by wrapping each of the directory and file paths in `tex_file_writing.py` with quotation marks as follows (I sincerely doubt that this is the best way to do this, but for the time being it works):
```python
def tex_to_dvi(tex_file):
     result = tex_file.replace(".tex", ".dvi")
     if not os.path.exists(result):
          commands = [
                "latex",
                "-interaction=batchmode",
                "-halt-on-error",
                "-output-directory=" + '"{}"'.format(TEX_DIR),
                '"{}"'.format(tex_file),
                ">",
                get_null()
          ]
          exit_code = os.system(" ".join(commands))
          if exit_code !=0:
               log_file = tex_file.replace(".tex", ".log")
                    raise Exception(
                         "Latex error converting to dvi."
                         "See log output above or the log file: %s" % log_fil
     return result
```
Quotation marks should be wrapped around each of the required paths in this file as necessary (four times in total: twice in `tex_to_dvi` and twice in `dvi_to_svg`) with `'"{}"'.format()`.

Hopefully this will help someone in the future :)

**Comment by Matemasters** [comment]
> 
> 
> I've figured it out!
> It turns out that it was nowhere near as complicated as I thought it was.
> It turns out that the Win10 Command Prompt wasn't playing nice with the LaTeX command options.
> Because there was a space in my the the path file "C:\ProgramFiles...", in the `-output-directory=<PATH>` option, the LaTeX command assumed that the path ended at "Program".
> 
> This problem can be resolved by wrapping each of the directory and file paths in `tex_file_writing.py` with quotation marks as follows (I sincerely doubt that this is the best way to do this, but for the time being it works):
> 
> ```python
> def tex_to_dvi(tex_file):
>      result = tex_file.replace(".tex", ".dvi")
>      if not os.path.exists(result):
>           commands = [
>                 "latex",
>                 "-interaction=batchmode",
>                 "-halt-on-error",
>                 "-output-directory=" + '"{}"'.format(TEX_DIR),
>                 '"{}"'.format(tex_file),
>                 ">",
>                 get_null()
>           ]
>           exit_code = os.system(" ".join(commands))
>           if exit_code !=0:
>                log_file = tex_file.replace(".tex", ".log")
>                     raise Exception(
>                          "Latex error converting to dvi."
>                          "See log output above or the log file: %s" % log_fil
>      return result
> ```
> 
> Quotation marks should be wrapped around each of the required paths in this file as necessary (four times in total: twice in `tex_to_dvi` and twice in `dvi_to_svg`) with `'"{}"'.format()`.
> 
> Hopefully this will help someone in the future :)

Greetings!

can you give us an example of how it should look like? Thank you in advanced, :)

**Comment by Matemasters** [comment]
Hi!
You mean, for example , instead of  `"-output-directory=" + '"{}"'.format(TEX_DIR),
                '"{}"'.format(tex_file)` I must write `'"C:\Users\....\Output\media_dir.txt"'.format(TEX_DIR),
                '"C:\Users\....\Output\media_dir.txt"'.format(tex_file)"'` Am I right? Thanks for your response
