### ISSUE TITLE
Error after installing requirements

### ISSUE THREAD

**Issue by theasder** [3b1b/manim#244]
Tried installing on OS X 10.13.4 and Ubuntu 16.04

    Installed /tmp/pip-install-rs5cp2h_/colour/.eggs/d2to1-0.2.12.post1-py3.6.egg
        error in setup command: Error parsing /tmp/pip-install-rs5cp2h_/colour/setup.cfg: RecursionError:
    maximum recursion depth exceeded while calling a Python object

**Comment by cnrmck** [comment]
Hmm... this is weird. Have you tried the docker image?

**Comment by eulertour** [comment]
Closing, as this issue is inactive. Feel free to reopen (with more detail) if the problem is still present.
