### ISSUE TITLE
play command not found (docker on OSX)

### ISSUE THREAD

**Issue by tzurs** [3b1b/manim#247]
using the docker build I get things to run (though I cannot find the output .mp4 yet)
I get 
sh: 1: play: not found

what am I missing?
(running play in a terminal does not work -- not found)
UPDATE: installed sox on the host machine and added to the path, clean build the docker image and run again.
RESULT: same

thanks,
-tzurs

**Comment by cnrmck** [comment]
Yeah, I have this issue too, I'll look into it. 

But you definitely need to install sox in the docker image, not on the host machine. The container is the one that needs to run sox

**Comment by eulertour** [comment]
Closing, as @cnrmck gave the solution.
