### ISSUE TITLE
No video, on macOS

### ISSUE THREAD

**Issue by emilienlemaire** [3b1b/manim#248]
When I try the example scenes I can't get the video, my terminal only shows that:

`Writing to /Users/<user>/Desktop/manim-master/example_scenes/480p15/SquareToCircleTemp.mp4
ffmpeg version 4.0.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with Apple LLVM version 9.1.0 (clang-902.0.39.2)
  configuration: --enable-libx264 --enable-gpl --enable-shared
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
  0%|                                                    | 0/15 [00:00<?, ?it/s]`

**Comment by cnrmck** [comment]
I would try using the the docker method. It works for me. Have you tried that yet?

**Comment by eulertour** [comment]
Closing, as this issue is inactive. Feel free to reopen (with the setup and command included) if the issue is still present.
