### ISSUE TITLE
No video getting generated

### ISSUE THREAD

**Issue by vdorbala** [3b1b/manim#258]
Trying to run `python extract_scene.py example_scenes.py SquareToCircle -pl
` or 
`docker run --rm -v "$PWD/files":/app/files manim example_scenes.py WarpSquare
` 
gives me this error.

`Traceback (most recent call last):
  File "extract_scene.py", line 283, in <module>
    main()
  File "extract_scene.py", line 243, in main
    module = get_module(config["file"])
  File "extract_scene.py", line 238, in get_module
    return get_module_posix(file_name)
  File "extract_scene.py", line 231, in get_module_posix
    last_module = imp.load_module(part, *load_args)
  File "/home/me/manim/./example_scenes.py", line 4, in <module>
    from .big_ol_pile_of_manim_imports import *
ValueError: Attempted relative import in non-package
`

I then changed the command to 
`python -m big_ol_pile_of_manim_imports extract_scene.py example_scenes.py SquareToCircle -pl
` to add the module.
This throws no error, but I do not get a preview video, nor does it get stored in the media folder I have specified in MEDIA_DIR. It just creates empty animation and design (svg and rastor) folders.

**Comment by zimmermant** [comment]
Go into `example_scenes.py` and remove the period at the start of the second line `https://github.com/zimmermant/manim.git`.  The period is trying to use a relative import which is causing your problem.

**Comment by vdorbala** [comment]
Oh I cant believe I missed that. Thank you. That solved the problem.
