### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by aryan-02** [3b1b/manim#275]
I installed manim on Anaconda as instructed on [this page](https://talkingphysics.wordpress.com/2018/06/11/installing-manim-and-python-manim-series-part-1/).
However, running this command after installation results in an error.
```
python extract_scene.py example_scenes.py SquareToCircle -pl 
```

The output I see is:

```
Traceback (most recent call last):
  File "extract_scene.py", line 15, in <module>
    from scene.scene import Scene
  File "C:\Users\A\Desktop\stuff\manim_exp\exp1\manim\scene\scene.py", line 11, in <module>
    from tqdm import tqdm as ProgressDisplay
ModuleNotFoundError: No module named 'tqdm'
```

And then I tried again, after which I got this error:
```
Traceback (most recent call last):
  File "extract_scene.py", line 15, in <module>
    from scene.scene import Scene
  File "C:\Users\A\Desktop\stuff\manim_exp\exp1\manim\scene\scene.py", line 15, in <module>
    from animation.animation import Animation
  File "C:\Users\A\Desktop\stuff\manim_exp\exp1\manim\animation\animation.py", line 5, in <module>
    from mobject.mobject import Mobject
  File "C:\Users\A\Desktop\stuff\manim_exp\exp1\manim\mobject\mobject.py", line 14, in <module>
    from utils.color import color_gradient
  File "C:\Users\A\Desktop\stuff\manim_exp\exp1\manim\utils\color.py", line 23
    return np.array([*color_to_rgb(color), alpha])
                     ^
SyntaxError: invalid syntax
```

Please help me fix it asap.

**Comment by 3b1b** [comment]
Did you run "pip install -r requirements.txt" to get all pip requirements?

**Comment by aryan-02** [comment]
Hi
Yes, I did.
The errors occurred when I tried to run it on Anaconda on Windows.
However, when I tried using Windows Subsystem for Linux without any environment like Anaconda, it started working...
Although I still think there are latex issues in WSL, though I think I can fix them...

**Comment by crazymerlyn** [comment]
This is a python version problem. `[*something, another thing]` is valid python3 but not valid python2.

**Comment by aryan-02** [comment]
@crazymerlyn  But isn't Manim written in Python 2?

**Comment by crazymerlyn** [comment]
[Installation instructions](https://github.com/3b1b/manim#install-requirements) mention that python2.7 is no longer supported

**Comment by crazymerlyn** [comment]
On that note, python2 will stop receiving patches in 2020. It's time to upgrade.

**Comment by aryan-02** [comment]
Oh, I see why it wasn't working...
Thanks :)

**Comment by pu17** [comment]
I got this error to , and i use python3.7
