### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by igij** [3b1b/manim#277]
E:\manim-master>python extract_scene.py -p example_scenes.py SquareToCircle
Traceback (most recent call last):
  File "extract_scene.py", line 13, in <module>
    from constants import *
  File "E:\manim-master\constants.py", line 7
    try:
      ^
SyntaxError: invalid syntax

**Comment by NoMod-Programming** [comment]
Which version of python are you using?

**Comment by igij** [comment]
3.7 
i just update it, but it still tells me the same error

> E:\manim-master>python extract_scene.py example_scenes.py SquareToCircle -pl
> Traceback (most recent call last):
>   File "extract_scene.py", line 13, in <module>
>     from constants import *
>   File "E:\manim-master\constants.py", line 7
>     try:
>       ^
> SyntaxError: invalid syntax
> 
> E:\manim-master>python --version
> Python 3.7.0

**Comment by igij** [comment]
also, when i finished to install all the requirements, it said that there's an error in the Microsoft Visual Studio

error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2                                                                                                                                                     ----------------------------------------                                    
Command ""e:\new folder\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-x5bt_o0j\\pycairo\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\admin\AppData\Local\Temp\pip-record-_z978wx5\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\admin\AppData\Local\Temp\pip-install-x5bt_o0j\pycairo\

**Comment by eulertour** [comment]
Are you still seeing this problem?

**Comment by igij** [comment]
Not anymore, thanks guys
