### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by optimistguy** [3b1b/manim#278]
Traceback (most recent call last):
  File "extract_scene.py", line 13, in <module>
    from constants import *
  File "C:\Users\Josh\Desktop\manim-master\constants.py", line 32, in <module>
    """)
Exception:
        Redefine MEDIA_DIR by changing the MEDIA_DIR
        environment constant or by changing
        media_dir.txt to point to a valid directory
        where movies and images will be written

**Comment by chxybin** [comment]
You need create a file named "media_dir.txt" at  the directory "C:\Users\Josh\Desktop\manim-master\", and write the path about output file location, such as "C:\Users\Josh\Desktop\manim-master\output" or "D:\file".

**Comment by optimistguy** [comment]
cool, that fixed it. Thanks @chxybin

**Comment by eulertour** [comment]
Closing, as this issue has been resolved.
