### ISSUE TITLE
link error doing pip install -r requirements.txt

### ISSUE THREAD

**Issue by DanielLiviu** [3b1b/manim#279]
I am trying to use manim but I am getting a link error:

  C:\Users\Owner\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:c:\anaconda2\envs\manim27\libs /LIBPATH:c:\anaconda2\envs\manim27\PCbuild\amd64 /LIBPATH:c:\anaconda2\envs\manim27\PC\VS9.0\amd64 cairo.lib /EXPORT:init_cairo build\temp.win-amd64-2.7\Release\cairo/device.obj build\temp.win-amd64-2.7\Release\cairo/bufferproxy.obj build\temp.win-amd64-2.7\Release\cairo/error.obj build\temp.win-amd64-2.7\Release\cairo/cairomodule.obj build\temp.win-amd64-2.7\Release\cairo/context.obj build\temp.win-amd64-2.7\Release\cairo/font.obj build\temp.win-amd64-2.7\Release\cairo/matrix.obj build\temp.win-amd64-2.7\Release\cairo/path.obj build\temp.win-amd64-2.7\Release\cairo/pattern.obj build\temp.win-amd64-2.7\Release\cairo/region.obj build\temp.win-amd64-2.7\Release\cairo/surface.obj build\temp.win-amd64-2.7\Release\cairo/enums.obj build\temp.win-amd64-2.7\Release\cairo/misc.obj build\temp.win-amd64-2.7\Release\cairo/glyph.obj build\temp.win-amd64-2.7\Release\cairo/rectangle.obj build\temp.win-amd64-2.7\Release\cairo/textcluster.obj build\temp.win-amd64-2.7\Release\cairo/textextents.obj /OUT:build\lib.win-amd64-2.7\cairo\_cairo.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\cairo\_cairo.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\cairo\_cairo.pyd.manifest
  LINK : fatal error LNK1181: cannot open input file 'cairo.lib'
  error: command 'C:\\Users\\Owner\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\link.exe' failed with exit status 1181

Can somebody help? Thank you.

**Comment by belgiancoder** [comment]
install `pkgconfig` first ?

**Comment by icreiuheciijc** [comment]
I don't know if I can help you, but I ran into a problem while doing `pip install -r requirements.txt` on MacOS. When installing pycairo, there also was an error of cairo. I didn't know anything about cairo.

So after googling, it turned out that I'll first have to install cairo onto the system then  pip install pycairo.

**Comment by icreiuheciijc** [comment]
You can find the download link [here](https://cairographics.org/download/). Looks like cairo should also be a dependency for manim besides ffmpeg,sox,latex.

**Comment by icreiuheciijc** [comment]
I noticed that you used `manim27` from the tutorial. Note that now manim is in Python3.7, and the tutorial is a bit outdated. That might also create problems with pycairo...

**Comment by bhopro** [comment]
@icreiuheciijc 
So I have also been having issues with cairo. When attempting to 'pip install pycairo', I end up with the error:

Collecting pycairo
  Using cached https://files.pythonhosted.org/packages/68/76/340ff847897296b2c8174dfa5a5ec3406e3ed783a2abac918cf326abad86/pycairo-1.17.1.tar.gz
Building wheels for collected packages: pycairo
  Running setup.py bdist_wheel for pycairo ... error
  Complete output from command /usr/local/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/j0/j4nx_xvd5v3c_9nrv1cf1kn80000gn/T/pip-install-_4oeuxyq/pycairo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/j0/j4nx_xvd5v3c_9nrv1cf1kn80000gn/T/pip-wheel-cxe2_4yw --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.12-x86_64-3.7
  creating build/lib.macosx-10.12-x86_64-3.7/cairo
  copying cairo/__init__.py -> build/lib.macosx-10.12-x86_64-3.7/cairo
  copying cairo/__init__.pyi -> build/lib.macosx-10.12-x86_64-3.7/cairo
  copying cairo/py.typed -> build/lib.macosx-10.12-x86_64-3.7/cairo
  running build_ext
  'pkg-config' not found.
  Command ['pkg-config', '--print-errors', '--exists', 'cairo >= 1.13.1']
  
  ----------------------------------------
  Failed building wheel for pycairo
  Running setup.py clean for pycairo
Failed to build pycairo
Installing collected packages: pycairo
  Running setup.py install for pycairo ... error
    Complete output from command /usr/local/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/j0/j4nx_xvd5v3c_9nrv1cf1kn80000gn/T/pip-install-_4oeuxyq/pycairo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/j0/j4nx_xvd5v3c_9nrv1cf1kn80000gn/T/pip-record-nfde2ulp/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.12-x86_64-3.7
    creating build/lib.macosx-10.12-x86_64-3.7/cairo
    copying cairo/__init__.py -> build/lib.macosx-10.12-x86_64-3.7/cairo
    copying cairo/__init__.pyi -> build/lib.macosx-10.12-x86_64-3.7/cairo
    copying cairo/py.typed -> build/lib.macosx-10.12-x86_64-3.7/cairo
    running build_ext
    'pkg-config' not found.
    Command ['pkg-config', '--print-errors', '--exists', 'cairo >= 1.13.1']
    
    ----------------------------------------
Command "/usr/local/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/j0/j4nx_xvd5v3c_9nrv1cf1kn80000gn/T/pip-install-_4oeuxyq/pycairo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/j0/j4nx_xvd5v3c_9nrv1cf1kn80000gn/T/pip-record-nfde2ulp/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/j0/j4nx_xvd5v3c_9nrv1cf1kn80000gn/T/pip-install-_4oeuxyq/pycairo/

I have made other attempts at installing with home brew, as well as the replacement library cairocffi. Is there anything else you did to get it to install properly?

**Comment by icreiuheciijc** [comment]
@bhopro Have you tried restarting?

**Comment by icreiuheciijc** [comment]
@bhopro Also seems like you don't have pkg-config...  Installing: [http://macappstore.org/pkg-config/](http://macappstore.org/pkg-config/)

**Comment by bhopro** [comment]
Ah, in a fit of frustration I remade my virtual environment and forgot to reinstall pkg-config. However, installing it did not really fix the problem of getting pycairo. But it seems as though someone has opened a new issue on this, so it might be good to move the conversation there.

**Comment by icreiuheciijc** [comment]
@bhopro I also had about the same problem of pkg-config when I installed. But after I installed pkg-config there was this issue of `PKG_CONFIG_PATH` that I had to manually add some paths to this environment variable in `~/.bash_profile` .... hope that might help

**Comment by eulertour** [comment]
Closing, as this issue seems to be resolved.
