### ISSUE TITLE
Windows 10 - No module named . (period)

### ISSUE THREAD

**Issue by cullenluong** [3b1b/manim#28]
I've tried the python extract_scene.py -p example_scenes.py SquareToCircle example on cmd, and I get the above error. 
*I've looked around and it seems that a few a people have had this problem, but I can't find any one who has a solution. .(period) is syntax for relative import, but I don't know how to fix from there.

**Comment by shahar603** [comment]
Replace the "get_module" (lines 158 I think) in  extract_scene.py with the following code:
```
def get_module(file_name):
   module_name = file_name.replace(".py", "")
   last_module = imp.load_module("__init__", *imp.find_module("__init__", ['.']))
   for part in module_name.split(os.sep):
      load_args = imp.find_module(part, [os.path.dirname(last_module.__file__)])
      last_module = imp.load_module(part, *load_args)
   return last_module
```

I looks like the original code uses Python3's imp.find_module instead of Python2's.

* I tested this on Windows 10 Python 2.7.6 32bit

**Comment by shunzhizhi** [comment]
I get the same error too, I can't find any solution until see the answer of @shahar603 .But only the animation of a squre and a circle when I try the project again with the code above.
The Pyhthon is 2.7 and Windows 7 OS.

**Comment by bhamshu** [comment]
I am also getting this error (windows 10, py2.7) and when I made the made the edit suggested shahar603 it threw many other errors

**Comment by shahar603** [comment]
> ImportError: cannot import name moduleTNC

@bhamshu  I think this is a problem with the `moduleTNC.py` file. It doesn't use capital letters as it should. Change its name to `moduleTNC.py`.

**Comment by bhamshu** [comment]
@shahar603 thanks man! it's working now. btw I don't know what you said in your previous comment but uninstalling and reinstalling scipy fixed it.

**Comment by eulertour** [comment]
Closing, as this issue is old and seems to be resolved.
