### ISSUE TITLE
Suggestion: Add some automated testing like Travis CI, Circle CI, Appveyor

### ISSUE THREAD

**Issue by cclauss** [3b1b/manim#284]
They are all free for Open Source projects like this one.

https://github.com/marketplace/category/continuous-integration

**Comment by eulertour** [comment]
It's pretty clear from [the history of conversations on this topic](https://github.com/3b1b/manim/issues?utf8=✓&q=continuous+integration) that the developers prioritize quick development over the more stable yet slower approach with continuous integration, and the decision makes sense in light of the motivations outlined in the README.

That said, the beauty of open source is that we can make this change ourselves. I've started a fork with Circle CI at https://github.com/eulertour/manim, and I'm going to add more tests and documentation in an effort to make a more stable version of this project that's more accessible to the open source community. Any contributions or suggestions to help with this would be greatly appreciated.

I don't mean to plug myself or anything, but the developers have made it clear that maintaining the software isn't a big priority right now. I just want to see this project get the growth and attention it deserves.

**Comment by cclauss** [comment]
People who want to develop fast use CI.

**Comment by eulertour** [comment]
That may be, but it's clear that there's no interest in adding it to this repository. The beauty of open source is that we can do it on our own.
