### ISSUE TITLE
Unable to install requirements.txt

### ISSUE THREAD

**Issue by wheatly312** [3b1b/manim#292]
whenever i try to use the command pip install -r requirements.txt, i get the error "Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'" ive done every other step, anyone have any ideas?

**Comment by TOMATOFAQ** [comment]
It works well here. Maybe you should add more description or check your environment.

**Comment by icreiuheciijc** [comment]
If you haven't, you have to `cd` to your directory where manim is stored, like `cd C:\some_folder\manim`, because that seems like the only problem that can cause this

**Comment by wheatly312** [comment]
ah thanks, fixed that, now im getting an errot about "Failed building wheel for pycairo"

**Comment by eulertour** [comment]
Can you post the full command output?

**Comment by wheatly312** [comment]
(manim27) Jacks-MBP:manim jackhoneycutt$ pip install -r requirements.txt
Requirement already satisfied: argparse==1.4.0 in /Users/jackhoneycutt/anaconda2/envs/manim27/lib/python2.7/site-packages (from -r requirements.txt (line 1)) (1.4.0)
Requirement already satisfied: colour==0.1.5 in /Users/jackhoneycutt/anaconda2/envs/manim27/lib/python2.7/site-packages (from -r requirements.txt (line 2)) (0.1.5)
Requirement already satisfied: numpy==1.15.0 in /Users/jackhoneycutt/anaconda2/envs/manim27/lib/python2.7/site-packages (from -r requirements.txt (line 3)) (1.15.0)
Requirement already satisfied: Pillow==5.2.0 in /Users/jackhoneycutt/anaconda2/envs/manim27/lib/python2.7/site-packages (from -r requirements.txt (line 4)) (5.2.0)
Requirement already satisfied: progressbar==2.5 in /Users/jackhoneycutt/anaconda2/envs/manim27/lib/python2.7/site-packages (from -r requirements.txt (line 5)) (2.5)
Requirement already satisfied: scipy==1.1.0 in /Users/jackhoneycutt/anaconda2/envs/manim27/lib/python2.7/site-packages (from -r requirements.txt (line 6)) (1.1.0)
Requirement already satisfied: tqdm==4.24.0 in /Users/jackhoneycutt/anaconda2/envs/manim27/lib/python2.7/site-packages (from -r requirements.txt (line 7)) (4.24.0)
Requirement already satisfied: opencv-python==3.4.2.17 in /Users/jackhoneycutt/anaconda2/envs/manim27/lib/python2.7/site-packages (from -r requirements.txt (line 8)) (3.4.2.17)
Collecting pycairo==1.17.1 (from -r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/68/76/340ff847897296b2c8174dfa5a5ec3406e3ed783a2abac918cf326abad86/pycairo-1.17.1.tar.gz
Building wheels for collected packages: pycairo
  Running setup.py bdist_wheel for pycairo ... error
  Complete output from command /Users/jackhoneycutt/anaconda2/envs/manim27/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/2_/v3x23jy16k7_qwpjlq5q8_nh0000gn/T/pip-install-tFozH4/pycairo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/2_/v3x23jy16k7_qwpjlq5q8_nh0000gn/T/pip-wheel-8vJpQO --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.6-x86_64-2.7
  creating build/lib.macosx-10.6-x86_64-2.7/cairo
  copying cairo/__init__.py -> build/lib.macosx-10.6-x86_64-2.7/cairo
  copying cairo/__init__.pyi -> build/lib.macosx-10.6-x86_64-2.7/cairo
  copying cairo/py.typed -> build/lib.macosx-10.6-x86_64-2.7/cairo
  running build_ext
  'pkg-config' not found.
  Command ['pkg-config', '--print-errors', '--exists', 'cairo >= 1.13.1']
  
  ----------------------------------------
  Failed building wheel for pycairo
  Running setup.py clean for pycairo
Failed to build pycairo
Installing collected packages: pycairo
  Running setup.py install for pycairo ... error
    Complete output from command /Users/jackhoneycutt/anaconda2/envs/manim27/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/2_/v3x23jy16k7_qwpjlq5q8_nh0000gn/T/pip-install-tFozH4/pycairo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/2_/v3x23jy16k7_qwpjlq5q8_nh0000gn/T/pip-record-r3IO68/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-x86_64-2.7
    creating build/lib.macosx-10.6-x86_64-2.7/cairo
    copying cairo/__init__.py -> build/lib.macosx-10.6-x86_64-2.7/cairo
    copying cairo/__init__.pyi -> build/lib.macosx-10.6-x86_64-2.7/cairo
    copying cairo/py.typed -> build/lib.macosx-10.6-x86_64-2.7/cairo
    running build_ext
    'pkg-config' not found.
    Command ['pkg-config', '--print-errors', '--exists', 'cairo >= 1.13.1']
    
    ----------------------------------------
Command "/Users/jackhoneycutt/anaconda2/envs/manim27/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/2_/v3x23jy16k7_qwpjlq5q8_nh0000gn/T/pip-install-tFozH4/pycairo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/2_/v3x23jy16k7_qwpjlq5q8_nh0000gn/T/pip-record-r3IO68/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/2_/v3x23jy16k7_qwpjlq5q8_nh0000gn/T/pip-install-tFozH4/pycairo/
(manim27) Jacks-MBP:manim jackhoneycutt$

**Comment by eulertour** [comment]
It'd be helpful to people who encounter this problem in the future if you post your solution in the thread. I assume you installed a package containing `pkg-config`?

**Comment by wheatly312** [comment]
i installed pkg-config using homebrew. Then i used homebrew to install cairo using the command `brew install cairo`after that i used `pip install pycairo` (weird i know im new to this) then i used `pip install -r requirements.txt` that worked

**Comment by icreiuheciijc** [comment]
Refer to issue #279 if anyone needs...
