### ISSUE TITLE
Outdated DockerFile dependencies

### ISSUE THREAD

**Issue by ItsPlantseed** [3b1b/manim#293]
The DockerFile inside the manim-master still contains the python version 2.7.12. Considering that manim had no longer support the python 2. This could lead to a syntax error. Please fix this issue ASAP.

**Comment by eulertour** [comment]
If there is any interest, I've submitted a pull request with the Dockerfile from my fork (#295).

**Comment by ItsPlantseed** [comment]
> If there is any interest, I've submitted a pull request with the Dockerfile from my fork (#295).

Is there a minimum requirement for this? Installing a full texlive seems redundant and unnecessary to me.

**Comment by eulertour** [comment]
Unfortunately, I don't know the minimum tex requirements to run manim. If you're willing to experiment you can always remove those lines and find a more minimal solution. I'd also greatly appreciate it, since the tex packages are rather large.

**Comment by eulertour** [comment]
For reference, I took those packages from [here](https://github.com/3b1b/manim/issues/207#issuecomment-381015481).

**Comment by ItsPlantseed** [comment]
I have removed the full part and the texlive-fonts-extra. In the other case, I'm experiencing this issue:
``docker run --rm -v /` pwd` /files:/app/files manim example_scenes.py WarpSquare``
The output is:
`/bin/bash: example_scenes.py: No such file or directory`
Do you have any idea regarding this?

**Comment by eulertour** [comment]
There are two key differences to take note of here.

First, the new Dockerfile is meant to be used interactively, so it has `/bin/bash` as an entrypoint rather than `python extract_scene.py`. The error you're seeing occurs because the container is trying to run `/bin/bash manim example_scenes.py`.

Second, this Dockerfile doesn't clone or copy a manim repo upon initialization. You have to either bind mount your local repo into the container with a command like `docker run -itv /path/to/your/local/manim/repo:/root/manim`, or just start the container with `docker run -it` and clone a repo afterward.

There's some more context [here](https://github.com/eulertour/manim#docker-method).

**Comment by ItsPlantseed** [comment]
I can't seem to enter both command. It says:
`"docker run" requires at least 1 argument.
See 'docker run --help'.

Usage: docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Run a command in a new container`

**Comment by eulertour** [comment]
You also have to include the image to use, so that should be `docker run -itv /path/to/your/local/manim/repo:/root/manim <image>` and `docker run -it <image>`. You can get a list of the images available to docker with `docker images`.

**Comment by ItsPlantseed** [comment]
How do I output the video exactly, e.g. the example_scenes.py?

**Comment by eulertour** [comment]
Once within the container, you'll have to `cd` into the repo directory and run `python3 extract_scene.py example_scenes.py SquareToCircle -pl`. The image can't play media, so you'll then have to leave the container to watch the video.

**Comment by ItsPlantseed** [comment]
I'm sorry. But how do I enter the repo directory? Or rather the format. I'm certainly new to all of this.

**Comment by eulertour** [comment]
No problem. If the image appears when you run `docker images`, you can start it with [either of the commands mentioned above](https://github.com/3b1b/manim/issues/293#issuecomment-421891364). Once you do, you'll be inside an isolated container which includes all the manim requirements (your prompt should change to something like `root@<hash>:~#` to indicate this). At this point you can use any shell command you normally would like `ls`, `cd`, etc.

If you bind mounted a local repo into the container, you'll be able to see it with `ls`, and can enter it with a simple `cd manim` (or whatever the repo is called). From there, you can use [this command](https://github.com/3b1b/manim/issues/293#issuecomment-421896282) to make a clip. The container doesn't include a media player, so you'll have to go back outside the container to watch the generated video.

Below is the full shell output from when I generated an example clip.
```
etour@instance-1:~$ ls
manim
etour@instance-1:~$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
eulertour/manim     circleci            d163b8006305        2 days ago          4.49GB
eulertour/manim     latest              d163b8006305        2 days ago          4.49GB
ubuntu              18.04               cd6d8154f1e1        11 days ago         84.1MB
ubuntu              latest              cd6d8154f1e1        11 days ago         84.1MB
circleci/picard     latest              1de15f3d2393        5 weeks ago         86.2MB
etour@instance-1:~$ docker run -itv /home/etour/manim:/root/manim eulertour/manim
root@6108733ed68b:~# ls
manim
root@6108733ed68b:~# cd manim
root@6108733ed68b:~/manim# python3 extract_scene.py example_scenes.py SquareToCircle -pl
Writing to media/animations/example_scenes/480p15/SquareToCircleTemp.mp4
Animation 0: ShowCreationCircle: 100%|█████████████████████████| 15/15 [00:02<00:00,  5.68it/s]
Played a total of 1 animations
======================
Finished without error
======================
root@6108733ed68b:~/manim# exit
exit
etour@instance-1:~$ ls manim/media/animations/example_scenes/480p15/SquareToCircle.mp4 
manim/media/animations/example_scenes/480p15/SquareToCircle.mp4
etour@instance-1:~$ 
```

**Comment by eulertour** [comment]
Oh.

Unfortunately I don't have much experience with Windows, so I'll be of limited assistance here. However, I would recommend starting with [this](https://docs.docker.com/v17.09/docker-for-windows/) and [this](https://tutorials.ubuntu.com/tutorial/tutorial-windows-ubuntu-hyperv-containers#0).

**Comment by ItsPlantseed** [comment]
It works now. Thank you so much, I really appreciate all your help getting me through all of this. I was dumb, I thought the directory are supposed to look like that. But apparently we have different OS.

I might close this issue after the DockerFile has already updated.

**Comment by cclauss** [comment]
Can this issue be closed?

**Comment by ItsPlantseed** [comment]
Oh yes, absolutely. Thanks for reminding me.
