### ISSUE TITLE
Not sure how to change the video placement file

### ISSUE THREAD

**Issue by wheatly312** [3b1b/manim#296]
So I'm at that step and I don't understand the directions laid out in the guide. I open constants.py and I am told to change the MEDIA_DIR location, how does one do that? does someone have a screenshot of what they'res looks like?

**Comment by eulertour** [comment]
This is a bit tricky actually. You have to set the `MEDIA_DIR` environment variable by either running `export MEDIA_DIR=<directory>` before `extract_scene.py` or running `MEDIA_DIR=<directory> python extract_scene.py ...`. Alternatively, you could write the name of the desired directory to a file called `media_dir.txt` in the directory. However, none of these will work unless the directory you specify already exists. The program won't create one for you, and will print the same error message as if you hadn't set the environment variable.

**Comment by wheatly312** [comment]
so what im wondering is within constants.py, what do i change?

**Comment by wheatly312** [comment]
<img width="183" alt="screen shot 2018-09-15 at 6 28 31 pm" src="https://user-images.githubusercontent.com/10522459/45591113-a4329e80-b916-11e8-8d85-528bbf5d20a8.png">
this is what im looking at, i understand that i need to put a path for the files to be saved but im not sure how to

**Comment by eulertour** [comment]
You don't have to edit `constants.py` at all. You have to create an empty directory in the repo, then either set the `MEDIA_DIR` environment variable to that directory, write the directory's name to a file called `media_dir.txt`, or (if you want) replace the directory's name where you see `#ERROR#` in the code above. For example, using `media_dir.txt`:
```
mkdir media
echo media > media_dir.txt
python extract_scene.py ...
```

Or using the `MEDIA_DIR` environment variable:
```
mkdir media
export MEDIA_DIR=media
python extract_scene.py ...
```

**Comment by wheatly312** [comment]
makes sense, i used the export MEDIA_DIR=<directory> but changing the directory to a destination, now i get this syntax error

File "/Users/jackhoneycutt/manim/utils/color.py", line 23
return np.array([*color_to_rgb(color), alpha])
                            ^
SyntaxError: invalid syntax

thank you for all the help

**Comment by eulertour** [comment]
This is because you're using python 2, which is no longer supported. You have to install and use python 3.

You should open a new issue for any future problems you encounter, since the problem you stated in this one is solved.

**Comment by wheatly312** [comment]
ahh i thought python 2 still worked

**Comment by kachirogomez** [comment]
I have the same issue, I don't know how tu write my directory
I have this:

env_MEDIA_DIR = None
MEDIA_DIR= "C:\Users\luzai\Documents\3b1b"

Then when I run python extract_scenes.py, it says:

Traceback (most recent call last):
  File "extract_scene.py", line 13, in <module>
    from constants import *
  File "C:\Users\luzai\Desktop\Manim\constants.py", line 32, in <module>
    """)
Exception:
        Redefine MEDIA_DIR by changing the MEDIA_DIR
        environment constant or by changing
        media_dir.txt to point to a valid directory
        where movies and images will be written

What am I doing wrong?
