### ISSUE TITLE
attributeerror

### ISSUE THREAD

**Issue by wheatly312** [3b1b/manim#297]
following step 2 of tutorial, trying to run the first scene, getting this error 
`(manim) Jacks-MBP:manim jackhoneycutt$ python extract_scene.py manim_tutorial_1.py Shapes -pl
Traceback (most recent call last):
  File "extract_scene.py", line 13, in <module>
    from constants import *
  File "/Users/jackhoneycutt/manim/constants.py", line 91, in <module>
    ORIGIN = np.array((0., 0., 0.))
AttributeError: module 'numpy' has no attribute 'array'`

anyone have a fix?

**Comment by eulertour** [comment]
I'm guessing [this](https://stackoverflow.com/questions/36530726/using-numpy-module-object-has-no-attribute-array)?

**Comment by eulertour** [comment]
Closing, as this issue is inactive. Feel free to reopen if you're still seeing this issue.
