### ISSUE TITLE
About Rotate function

### ISSUE THREAD

**Issue by TOMATOFAQ** [3b1b/manim#298]
Hey, it occured to me that the Rotate function doesn't work well. And I work out that the axis it depends to rotate is the center of the image itself. Could somebody render a solution to rotate by absolute coordinate? I don't want to add something other to my model to fix the axis.
![](https://raw.githubusercontent.com/TOMATOFAQ/Calculate-Faulhaber-s-formula-figuratively/master/Pictures/Fifth_2.gif)

**Comment by eulertour** [comment]
Can you post the code used above, and the branch from which you're running it?

**Comment by TOMATOFAQ** [comment]
I just write another function to add some transparent dot which can balance my model. I am going to read the source code to see if I i could find something useful.
