### ISSUE TITLE
Open-sourcing Video "Scripts"

### ISSUE THREAD

**Issue by diego898** [3b1b/manim#3]
Hello! 

Have you ever considered open-sourcing the "script" for your videos? A file that generates all the animations used in your videos?

Thanks!

**Comment by Pear0** [comment]
I'm not sure if it's intentional, but many of @3b1b 's "scripts" are in /eola for the Essence of Linear Algebra series and /old_projects for his other videos.

**Comment by diego898** [comment]
thanks @Pear0! I saw that but it just looks like the declaration of different "scenes" in the videos, as opposed to the some master file chaining all the scenes together. I will check those out if I can get this correctly installed!

**Comment by eulertour** [comment]
I'm closing this issue, since it's very old and seems to be resolved.
