### ISSUE TITLE
Problems with Latex error converting to dvi -- 'standalone.cls' not found

### ISSUE THREAD

**Issue by bhopro** [3b1b/manim#300]
So this issue has been brought up many times before. I have tried making the changes suggested in #36,  #49,  #64,  #110,  #207 and  #209, however none of them seem to be working for me. In fact, I have the same issue that has been raised in #142 where my log points to a `LaTeX Error: File standalone.cls not found`. Did anyone who encountered this problem have a fix? I searched around through many LaTeX forums to no avail. Any help would be greatly appreciated!

My final tweaks to tex_file_writing.py are:

```
def tex_to_dvi(tex_file):
    result = tex_file.replace(".tex", ".xdv")
    if not os.path.exists(result):
        commands = [
            "xelatex",
            "-no-pdf",
            "-interaction=batchmode",
            "-halt-on-error",
            "-output-directory=" + TEX_DIR,
            tex_file,
            ">",
            get_null()
        ]
        exit_code = os.system(" ".join(commands))
        if exit_code != 0:
            log_file = tex_file.replace(".tex", ".log")
            raise Exception(
                "Latex error converting to dvi. "
                "See log output above or the log file: %s" % log_file)
    return result


def dvi_to_svg(dvi_file, regen_if_exists=False):
    """
    Converts a dvi, which potentially has multiple slides, into a
    directory full of enumerated pngs corresponding with these slides.
    Returns a list of PIL Image objects for these images sorted as they
    where in the dvi
    """
    result = dvi_file.replace(".dvi", ".svg")
    if not os.path.exists(result):
        commands = [
            "dvisvgm",
            dvi_file,
            "-n",
            "-v",
            "0",
            "-o",
            result,
            ">",
            get_null()
        ]
        os.system(" ".join(commands))
    return result
```

And my final output log looks like:

```
This is XeTeX, Version 3.14159265-2.6-0.99999 (TeX Live 2018) (preloaded format=xelatex 2018.9.16)  16 SEP 2018 22:42
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**/Users/bhopro/animation/manim37/files/Tex/9d5f7c86eb636190.tex
(/Users/bhopro/animation/manim37/files/Tex/9d5f7c86eb636190.tex
LaTeX2e <2018-04-01> patch level 2
Babel <3.18> and hyphenation patterns for 22 language(s) loaded.

! LaTeX Error: File `standalone.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)

Enter file name: 
! Emergency stop.
<read *> 
         
l.2 ^^M
        
Here is how much of TeX's memory you used:
 10 strings out of 494476
 313 string characters out of 6165662
 57352 words of memory out of 5000000
 4027 multiletter control sequences out of 15000+600000
 3640 words of font info for 14 fonts, out of 8000000 for 9000
 319 hyphenation exceptions out of 8191
 10i,0n,8p,100b,8s stack positions out of 5000i,500n,10000p,200000b,80000s

No pages of output.
```

**Comment by icreiuheciijc** [comment]
since you already replaced .tex with .xdv in `def tex_to_dvi`: `result = tex_file.replace(".tex", ".xdv")`, you should also replace **_.xdv_** with .svg in `def dvi_to_svg`: `result = dvi_file.replace(".xdv", ".svg")`

**Comment by bhopro** [comment]
Ah I missed that -- thanks. However, the log still outputs the same error..

**Comment by icreiuheciijc** [comment]
Which OS are you running?
I personally am using MacOS and uses MacTeX distribution, and there is no problem

**Comment by bhopro** [comment]
I am also using MacOS. Looks like it was an issue with the MacTeX distribution I was using. I reinstalled it and it is now working. Thank you for all of your prompt responses!

**Comment by MingChaoXu** [comment]
> I am also using MacOS. Looks like it was an issue with the MacTeX distribution I was using. I reinstalled it and it is now working. Thank you for all of your prompt responses!

i also have this problem, but after i reinstalled it ,it still doesn't work, can i ask you how to reinstall?
i just reinstall it by click the dmg file download in https://miktex.org/download

**Comment by Wardendyffe** [comment]
i also have the same problem, it had said that 'Xelatex error converting to xdv.' so i compile a tex file, but i can't find any xdv file. my tex is the TeXlive 2018,is that my TeXlive's problem?
