### ISSUE TITLE
Problem with TextMobject

### ISSUE THREAD

**Issue by Elteoremadebeethoven** [3b1b/manim#305]
Hi! 

When I compile from example_scenes.py the scene WriteStuff only shows this:

![sintex](https://user-images.githubusercontent.com/43224662/45817579-d17ba580-bca4-11e8-9aaa-62e51f7a243b.png)

and the rest says error from latex to dvi.

I'm ussing Windows 7 Premium 64 bits, but the same happen in Virtual System (Virtual box) with Lubuntu 18.

Yes, I have miktex on Windows but in the Virtual System (Lubuntu 18 and Ubunto 16.04 lts) I installed TexLive and the same happen. I tried edit the template.tex, tex_template.tex and text_template.tex:

`\usepackage[english]{babel}` 

for

`\usepackage[utf8]{inputenc}`

but don't works, I use another PC where I have Ubuntu 16.04 lts and runs Ok, but en Window's computer not.

**Comment by 3b1b** [comment]
Yeah, not sure why this happened.  It should be fixed now.

**Comment by Elteoremadebeethoven** [comment]
Thank you a lot.

**Comment by epontoni** [comment]
Hi!
I’m trying to print an open question mark “¿”, when I place the characters ¿, “ or \textquestiondown in a TextMobject is printed ?' despite having added in tex_template.tex the line \usepackage[utf8]{inputenc}.

**Comment by Elteoremadebeethoven** [comment]
Add this below of that line:
```latex
\usepackage[T1]{fontenc}
```

**Comment by epontoni** [comment]
> Add this below of that line:
> 
> ```
> \usepackage[T1]{fontenc}
> ```

Thank you very much for your reply!
I really appreciate you taking the time to respond! Your response has solved my problem (I had been trying for hours).
Thank you again!

**Comment by Elteoremadebeethoven** [comment]
Your welcome ;)
