### ISSUE TITLE
Why my progress bar looks so clumsy

### ISSUE THREAD

**Issue by ZipWin** [3b1b/manim#319]
I am using Manim in my Win10 PC. Is there something wrong?

Animation 1: ApplyMethodTextMobjectToTextMobject, etc.:   5%|█▎                         | 3/60 [00:00<00:02, 23.69it/sAnimation 1: ApplyMethodTextMobjectToTextMobject, etc.:  10%|██▋                        | 6/60 [00:00<00:02, 23.23it/Animation 1: ApplyMethodTextMobjectToTextMobject, etc.:  15%|████                       | 9/60 [00:00<00:02, 23.14itAnimation 1: ApplyMethodTextMobjectToTextMobject, etc.:  20%|█████▏                    | 12/60 [00:00<00:02, 23.05Animation 1: ApplyMethodTextMobjectToTextMobject, etc.:  25%|██████▌                   | 15/60 [00:00<00:01, 22.7Animation 1: ApplyMethodTextMobjectToTextMobject, etc.:  30%|███████▊                  | 18/60 [00:00<00:01, 22.Animation 1: ApplyMethodTextMobjectToTextMobject, etc.:  35%|█████████                 | 21/60 [00:00<00:01, 22Animation 1: ApplyMethodTextMobjectToTextMobject, etc.:  40%|██████████▍               | 24/60 [00:01<00:01, Animation 1: ApplyMethodTextMobjectToTextMobject, etc.:  45%|███████████▋              | 27/60 [00:01<00:01,Animation 1: ApplyMethodTextMobjectToTextMobject, etc.:  50%|█████████████             | 30/60 [00:01<00:01Animation 1: ApplyMethodTextMobjectToTextMobject, etc.:  55%|██████████████▎           | 33/60 [00:01<00:Animation 1: ApplyMethodTextMobjectToTextMobject, etc.:  60%|███████████████▌          | 36/60 [00:01<00Animation 1: ApplyMethodTextMobjectToTextMobject, etc.:  65%|████████████████▉         | 39/60 [00:01<0Animation 1: ApplyMethodTextMobjectToTextMobject, etc.:  70%|██████████████████▏       | 42/60 [00:01Animation 1: ApplyMethodTextMobjectToTextMobject, etc.:  75%|███████████████████▌      | 45/60 [00:0Animation 1: ApplyMethodTextMobjectToTextMobject, etc.:  80%|████████████████████▊     | 48/60 [00:Animation 1: ApplyMethodTextMobjectToTextMobject, etc.:  85%|██████████████████████    | 51/60 [00Animation 1: ApplyMethodTextMobjectToTextMobject, etc.:  90%|███████████████████████▍  | 54/60 [Animation 1: ApplyMethodTextMobjectToTextMobject, etc.:  95%|████████████████████████▋ | 57/60 Animation 1: ApplyMethodTextMobjectToTextMobject, etc.: 100%|██████████████████████████| 60/60 [00:02<00:00, 22.95it/s]

**Comment by Elteoremadebeethoven** [comment]
It is normal, that says the progress of the compilation.

**Comment by ZipWin** [comment]
> It is normal, that says the progress of the compilation.

But I learned from other people that one animation only has one process bar

**Comment by Elteoremadebeethoven** [comment]
No, it depends on your animation, the more animations more bars will appear.

**Comment by ZipWin** [comment]
> No, it depends on your animation, the more effects more bars will appear.

Maybe I didn't clearly expressed my meaning, because English is not my mother tongue. I learned from the tutorial written by talkingphysics, whose process bar looks like
![image](https://talkingphysics.files.wordpress.com/2018/06/successful_animation.png)
where one animation only has one process bar. But in my computer, one animation has a lot of process bars, which look like
Animation 1: ApplyMethodTextMobjectToTextMobject, etc.: 5%|█▎ | 3/60 [00:00<00:02, 23.69it/s
Animation 1: ApplyMethodTextMobjectToTextMobject, etc.: 10%|██▋ | 6/60 [00:00<00:02, 23.23it/
Animation 1: ApplyMethodTextMobjectToTextMobject, etc.: 15%|████ | 9/60 [00:00<00:02, 23.14it
Animation 1: ApplyMethodTextMobjectToTextMobject, etc.: 20%|█████▏ | 12/60 [00:00<00:02, 23.05
Animation 1: ApplyMethodTextMobjectToTextMobject, etc.: 25%|██████▌ | 15/60 [00:00<00:01, 22.7
Animation 1: ApplyMethodTextMobjectToTextMobject, etc.: 30%|███████▊ | 18/60 [00:00<00:01, 22.

**Comment by Elteoremadebeethoven** [comment]
Yes, is normal, the same happens with me. Depends of your animation. For example, if I scale a object:
![captura de pantalla de 2018-10-09 02-42-09](https://user-images.githubusercontent.com/43224662/46653990-2f493200-cb6d-11e8-8e6c-60940dc6a82e.png)
