### ISSUE TITLE
Text on white background

### ISSUE THREAD

**Issue by sobuelow** [3b1b/manim#323]
I changed the background color to WHITE to make the animations more compatible with e.g. presentation slides. Now each text has bold black contour lines (irrespective of the color= keyword in the TextMobject definition), which looks quite awful. Changing the color only changes the 'filling' of the text, but not the contours. Is there any way to get of those black contours?
Best,
Soeren

**Comment by 3b1b** [comment]
Change the background_stroke_width attribute of the TextMobject to be 0

**Comment by 3b1b** [comment]
Change the background_stroke_width attribute of the TextMobject to be 0
