### ISSUE TITLE
Dashed line in Matrix of 3 or more rows.

### ISSUE THREAD

**Issue by Elteoremadebeethoven** [3b1b/manim#324]
Hi!

I know it's a little bit exaggerated, but does anyone know how to fix this?

![matrix](https://user-images.githubusercontent.com/43224662/46628953-dc3b9480-cb04-11e8-983f-f574d3fce7c6.png)
![quim1](https://user-images.githubusercontent.com/43224662/46628957-df368500-cb04-11e8-8ff6-1e97176ebd41.png)
![quim2](https://user-images.githubusercontent.com/43224662/46628965-e198df00-cb04-11e8-9a67-5fe89dc08a1b.jpg)

I tried change parameters of tex_mobject.py but I can't find the origin of the problem.

Thanks for read.

**Comment by 3b1b** [comment]
Set background_stroke_width of the TexMobject to be 0

**Comment by Elteoremadebeethoven** [comment]
Thanks you again!
