### ISSUE TITLE
No module named 'colour'

### ISSUE THREAD

**Issue by Sir-Teo** [3b1b/manim#325]
As I run the command ```python extract_scene.py example_scenes.py SquareToCircle -pl.```, the error message said 
```
Traceback (most recent call last):
  File "extract_scene.py", line 15, in <module>
    from scene.scene import Scene
  File "/manim/scene/scene.py", line 15, in <module>
    from animation.animation import Animation
  File "/manim/animation/animation.py", line 5, in <module>
    from mobject.mobject import Mobject
  File "/manim/mobject/mobject.py", line 9, in <module>
    from colour import Color
ModuleNotFoundError: No module named 'colour'
```
But when I check with ```pip install color```, the terminal says that request already satisfied.

**Comment by scrouthtv** [comment]
Did you find a fix because I'm experiencing this problem as well
@Sir-Teo

**Comment by Sir-Teo** [comment]
sorry I haven't find a fix

**Comment by Tarang74** [comment]
Open the module named color, inside "master\utils\color.py".
Then go to line 4 and change;

from color import Color

TO

from colour import Color

**Comment by eulertour** [comment]
You can fix this by installing the `colour` package: `pip install colour`.

**Comment by zarif98sjs** [comment]
@eulertour I tried` pip install colour` but it says `Requirement already satisfied: colour in /usr/local/lib/python3.7/dist-packages (0.1.5)
`

**Comment by dtbulmerJRs** [comment]
im having this problem too.

**Comment by SamarthH** [comment]
Try pip3 install colour

**Comment by akhlak919** [comment]
I trying all the stuffs that are above mentioned by the guys but still I face this problem. Please Help !

**Comment by mohammadian-reza** [comment]
I have a problem with stddraw python file, when I want to import it 
I face module not found error >> no module named 'color'
I tried to install color from pip but it didn't work again!!!

**Comment by mpwolken** [comment]
There are multiple colour packages - I believe the correct one will be this: https://www.colour-science.org/installation-guide/.  Testing now, but the pip install colour installed a colour.py that did not have the requisite functions such as read_LUT.
