### ISSUE TITLE
Live streaming and interactive shell?

### ISSUE THREAD

**Issue by mertyildiran** [3b1b/manim#335]
Can we add a feature to provide live streaming by piping the frames, animation by animation, into a video player like `ffplay`, `mplayer` or `vlc` so that it would be possible to broadcast using [OBS Studio](https://obsproject.com/)?

Also adding an interactive shell mode to give inputs via command-line rather than a scripting system would be necessary for live streaming. The current design of [extract_scene.py](https://github.com/3b1b/manim/blob/master/extract_scene.py) does not allow such feature. So it needs to be reworked I believe.

I'm a bit confused by the architecture of this library because it sits somewhere between being a module and being a script. Like it's both of them at the same time. So if you at least point out the lines and guide me through then maybe in the near future, I can send a PR to add live streaming feature. This library has definitely a great potential on that path.

**Comment by eulertour** [comment]
Firstly, this sounds like an amazing feature and I've love to see it implemented. I'd also be willing to collaborate in writing it if there's any interest, so feel free to get in touch. I don't have time to answer in detail right now, but here's some high-level information.

[The frames are already piped, one by one, into `ffmpeg`](https://github.com/3b1b/manim/blob/31478c523c9febb85d673219c6451ce545b5e319/scene/scene.py#L553). I'm not familiar with how to interface with `ffplay`, `mplayer`, or `vlc`, but it shouldn't be too much work to have them read the frames the same way `ffmpeg` does.

As for an interactive shell, this _might_ already be possible from the python interpreter with some hackery. The frames are currently only written to `ffmpeg` when either `Scene.play()` or `Scene.wait()` is called. It should be possible in theory to replace `ffmpeg` with another live process, pass it (via e.g. a file descriptor for stdin or socket) to python, and then write to it with every call to `Scene.play()`. All other commands would simply run in the python shell as usual.

You're correct that the code here is very rudimentary. We're currently working to improve on it.

**Comment by mertyildiran** [comment]
@eulertour I'm currently trying to implement this feature in [my fork](https://github.com/mertyildiran/manim).

The current state of `ffmpeg` command that I'm using is:
```
ffmpeg -y -f rawvideo -s 1920x1080 -pix_fmt rgba -r 60 -i - -an -loglevel error -vcodec libx264 -pix_fmt yuv420p -f mpegts tcp://127.0.0.1:2000
```

To test my fork, first simply start the `mplayer` listener with:
```
mplayer -cache 8092 ffmpeg://tcp://127.0.0.1:2000?listen
```

then run `python3 test1.py`

### Interactive Shell

Somewhat figured out. You just need to enter three lines of code to start streaming in Python Interactive Shell:

```
from big_ol_pile_of_manim_imports import *
from manim import Manim
manim = Manim()
```

Forcing `mpegts` is the key point in here. I found a lot of information about streaming with `ffmpeg` in [here](https://trac.ffmpeg.org/wiki/StreamingGuide#Pointtopointstreaming). Seems like directly streaming to Twitch for example, does not work. I don't know why. Seems like `udp://`, `rtmp://` protocols don't work but only `tcp://` works. Maybe I'm doing something wrong and you can figure it out.

### Problems in Current State

- `mplayer` does not play the video until you call `close_movie_pipe()`
- `mplayer` does not play animation by animation. But rather plays the whole video. That's **the biggest challenge**.
- `mplayer` closes off when the playback is done.

I don't know where are the fixes for those problems. Either on server-side(manim) or client-side(mplayer).

**Comment by eulertour** [comment]
I was about to start looking into this and saw you got it working. _Very_ impressive!

**Comment by mertyildiran** [comment]
Added with https://github.com/3b1b/manim/pull/336
