### ISSUE TITLE
OSError: dlopen() failed to load a library: cairo / cairo-2 / cairo-gobject-2'`

### ISSUE THREAD

**Issue by liangpu597** [3b1b/manim#337]
I used python3.
I use pip install  pycairo
`
F:\3Blue1Brown\manim-master>python extract_scene.py example_scenes.py SquareToCi
rcle -pl
Traceback (most recent call last):
  File "extract_scene.py", line 15, in <module>
    from scene.scene import Scene
  File "F:\3Blue1Brown\manim-master\scene\scene.py", line 17, in <module>
    from camera.camera import Camera
  File "F:\3Blue1Brown\manim-master\camera\camera.py", line 10, in <module>
    import cairocffi
  File "C:\Users\Tony\AppData\Local\Programs\Python\Python36-32\lib\site-package
s\cairocffi\__init__.py", line 41, in <module>
    cairo = dlopen(ffi, 'cairo', 'cairo-2', 'cairo-gobject-2')
  File "C:\Users\Tony\AppData\Local\Programs\Python\Python36-32\lib\site-package
s\cairocffi\__init__.py", line 38, in dlopen
    raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))
OSError: dlopen() failed to load a library: cairo / cairo-2 / cairo-gobject-2'`

**Comment by scrouthtv** [comment]
Same for me; have you found a fix yet?

**Comment by ishandutta2007** [comment]
I am on mac10.13/python3.7. My error message is slightly different but must be related to the same issue.

>  ImportError: dlopen(/Users/ishandutta2007/.pyenv/versions/3.7.0/lib/python3.7/site-packages/cairo/_cairo.cpython-37m-darwin.so, 2): Symbol not found: _cairo_xcb_surface_set_size

**Comment by ishandutta2007** [comment]
This worked for me(mac10.13/python3.7.), not sure if the first line is required though, now I have pycairo `1.18.0` instead of `1.17.1` as in requirements.txt

```
pip install cairocffi
pip uninstall pycairo
pip install pycairo
```

**Comment by eulertour** [comment]
Closing, as this issue seems to be resolved.

**Comment by SOORAJTS2001** [comment]
pip install cairocffi
pip uninstall pycairo
pip install pycairo

worked for me..
thanks :)
