### ISSUE TITLE
Arabic text objects

### ISSUE THREAD

**Issue by andrewnaguib** [3b1b/manim#342]
How can I get Arabic text to be rendered on my video? It seems that the library doesn't support that? I think I gotta modify something in the Tex configs or something like that, am I correct?

**Comment by Elteoremadebeethoven** [comment]
Try to add
```latex
\usepackage{arabtex}
```
and replace
```latex
\usepackage[english]{babel}
```
to
```latex
\usepackage[utf8]{inputenc}
```

**Comment by eulertour** [comment]
Closing, as this issue seems to have been resolved.

**Comment by AyoubRahbawi** [comment]
hello @Elteoremadebeethoven  i did what you said but the english text turned into random arabic letters and the arabic text is random too plz some help

**Comment by yousif-hag-ahmed** [comment]
Try this 
https://github.com/3b1b/manim/issues/1241#issuecomment-753416291
