### ISSUE TITLE
Gaps in TeX brackets

### ISSUE THREAD

**Issue by sswatson** [3b1b/manim#347]
My matrix delimiters are coming out broken in a few spots. 

```python
class MatrixOfOnes(Scene):
    def construct(self):
        M = matrix_to_mobject(np.ones((4,4)))
        self.play(Write(M))
```

<img width="489" alt="gap" src="https://user-images.githubusercontent.com/8516843/48903550-da663000-ee29-11e8-9f7b-eb03394fbcf2.png">

Inspecting `manim`'s mechanism for handling TeX objects, this behavior makes sense: the different parts of the bracket come out as different strokes in the SVG file that gets parsed and printed to the screen by Cairo. Since Cairo is performing that drawing action with a background stroke, this would result in small gaps between abutting paths. What I don't understand is how this works smoothly in the original videos (see, e.g., EOLA). Also, I tried zeroing out the background stoke, and that didn't make the problem go away. 

(P.S. The code above won't run unless you change 'string' to 'str' in `mobject.matrix.matrix_to_mobject`. See [this PR](https://github.com/3b1b/manim/pull/346).)

**Comment by icreiuheciijc** [comment]
Refer to #324.

**Comment by sswatson** [comment]
Cool, thanks!
