### ISSUE TITLE
Missing "copy()" in camera.py

### ISSUE THREAD

**Issue by Elteoremadebeethoven** [3b1b/manim#350]
Missing to include:

```python3
from mobject.mobject import copy
```
 or

```python3
import copy
```

 In camera.py for ZoomedScene

**Comment by eulertour** [comment]
I'm not sure what the problem is here, since `camera.py` actually contains `import copy` one too many times. Can you clarify what problem you mean to solve?

**Comment by Elteoremadebeethoven** [comment]
Sorry, I'm Wrong, thanks
