### ISSUE TITLE
Error creating scene on Windows 10

### ISSUE THREAD

**Issue by Tarang74** [3b1b/manim#353]
Using the tutorial from talkingphysics.com

Using:

python extract_scene.py example_scenes.py SquareToCircle -p

Traceback (most recent call last):
  File "extract_scene.py", line 15, in <module>
    from scene.scene import Scene
  File "C:\Users\######\manim\scene\scene.py", line 17, in <module>
    from camera.camera import Camera
  File "C:\Users\#######\manim\camera\camera.py", line 10, in <module>
    import cairo
ModuleNotFoundError: No module named 'cairo'

**Comment by eulertour** [comment]
pycairo isn't installed. You should run `pip install -r requirements.txt`.

**Comment by Tarang74** [comment]
> pycairo isn't installed. You should run `pip install -r requirements.txt`.

I have, it says failed to build wheels in the cmd. I’m using windows 10, apparently that’s the problem for many users?

**Comment by eulertour** [comment]
Can you post what you ran and the output?

**Comment by eulertour** [comment]
I don't know a "best" solution for this, but there seem to be two viable options:
1. Verify your installation of MS Visual C++, and that `cl.exe` is added to the `PATH` environment variable [[1]](https://www.quora.com/How-do-I-fix-the-error-command-cl-exe-failed-No-such-file-or-directory-I-got-C++-for-Python-3-6/answer/Ayan-Das-48)[[2]](https://stackoverflow.com/a/39058095)
2. Install from the prebuilt wheels that the University of California Irvine has kindly hosted [[wheels]](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pycairo) [[installation]](https://stackoverflow.com/a/48132109). These wheels aren't the same version that is specified in `requirements.txt`, but hopefully they're similar enough.
Please post here if you manage to figure this out, as I don't have an easy way to test Windows at the moment.

**Comment by Tarang74** [comment]
#1 I didn't understand what you meant.

#2 I tried
I have tried installing it from the UCI website, but it gives me the same result.

The wheels script shows/outputs this message

`pycairo-1.15.4-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform`

**Comment by eulertour** [comment]
It looks like you're trying to install a python 3.6 wheel on python 3.7 (note the cp36 in the name). Try downloading a python 3.7 wheel from [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pycairo) and installing it [like this](https://pip.pypa.io/en/latest/user_guide/#installing-from-wheels).

**Comment by Tarang74** [comment]
Thanks, I'll try it now.

**Comment by Tarang74** [comment]
Should I activate manim, or use base? (anaconda 3)

**Comment by Tarang74** [comment]
Also, the wheel required is pycairo 1.17.1, should I use that version or the latest one (1.18.0)?

**Comment by eulertour** [comment]
I'm not very familiar with anaconda, but I think you have to activate the environment in order for manim to find it. Using 1.18 rather than 1.17 is probably fine.

**Comment by Tarang74** [comment]
What do you use?

**Comment by Tarang74** [comment]
I'm actually just learning python so I'm not too familiar with how it all works yet.

**Comment by Tarang74** [comment]
Well, I think cairo is working now, I downloaded an offline version and installed it from script (it installed successfully).

BUT now there is another error.

`C:\Users\t#####jana\manim>python extract_scene.py example_scenes.py SquareToCircle -pl
Writing to C:\Users\#####\Videos/Manim Animations\animations\example_scenes\480p15\SquareToCircleTemp.mp4



Traceback (most recent call last):
  File "extract_scene.py", line 289, in main
    handle_scene(SceneClass(**scene_kwargs), **config)
  File "C:\Users\#####\manim\scene\scene.py", line 69, in __init__
    self.open_movie_pipe()
  File "C:\Users\#####\manim\scene\scene.py", line 627, in open_movie_pipe
    self.writing_process = sp.Popen(command, stdin=sp.PIPE)
  File "C:\Users\#####\AppData\Local\conda\conda\envs\manim\lib\subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "C:\Users\#####\AppData\Local\conda\conda\envs\manim\lib\subprocess.py", line 1172, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified



The system cannot find the path specified.`

**Comment by eulertour** [comment]
That's a fairly common error with manim and usually means that `ffmpeg` isn't installed or isn't installed correctly. I'd recommend searching the issues in this repo for more context.

**Comment by Tarang74** [comment]
I have installed everything stated in the repo by Grant.

**Comment by Tarang74** [comment]
I can get the -s to save images, but that's all.

**Comment by Tarang74** [comment]
Do you know how I can change what frame of the animation I can save, I think `-s` only does the last frame.

**Comment by eulertour** [comment]
The error is being caused here:
```
File "C:\Users\#####\manim\scene\scene.py", line 627, in open_movie_pipe
    self.writing_process = sp.Popen(command, stdin=sp.PIPE)
```
`Popen()` is meant to take a path to an executable (in this case `ffmpeg`) and execute it. But in this case there's nothing there (`The system cannot find the path specified.`). If you print `command` before it's passed to `Popen`, you can figure out where python is looking and figure out why `ffmpeg` isn't there.

**Comment by liyiliuxingyu** [comment]
http://www.lfd.uci.edu/~gohlke/pythonlibs/#pycairo
intall it, all thing will be done.
