### ISSUE TITLE
Allow rendering Scenes to .gif

### ISSUE THREAD

**Issue by eulertour** [3b1b/manim#354]
manim should have the option to export scenes to .gif. This would make it more convenient to share them online, either to clarify explanations or show an interesting animation.

**Comment by alex-lairan** [comment]
Any news for this issue ?

**Comment by Charlsyy** [comment]
I'm working on it. I think I'll open a pull request in the next few days

**Comment by eulertour** [comment]
Sorry I haven't gotten around to this. My entire life from the moment I opened this has been one long maintenance task.

**Comment by Kolloom** [comment]
Wasn't this done in #529 ?

**Comment by yoshiask** [comment]
@eulertour This issue can be closed now, the feature has now been implemented and pulled into the master branch

**Comment by mahrud** [comment]
In case anyone else finds this thread wondering why "-i" isn't working: it was removed in [this commit](https://github.com/3b1b/manim/commit/61bb4944fad2ee889145bbf8a3253fb07c71bf7d#comments). At least for me reverting that commit works.
