### ISSUE TITLE
Create a default media directory if none is specified

### ISSUE THREAD

**Issue by eulertour** [3b1b/manim#356]
There have been _many_ (#296, #278, #237, #206, #159) issues filed because this isn't done automatically, and the existing solutions (environment variables or manual editing) are rather awkward.

**Comment by icreiuheciijc** [comment]
Or prompt the user for it and store it in media_dir.txt, if not detected or for the first time.

**Comment by eulertour** [comment]
> Or prompt the user for it and store it in media_dir.txt, if not detected or for the first time.

I decided against this in order to keep things streamlined and because [validating a directory can get complicated](https://stackoverflow.com/questions/9532499/check-whether-a-path-is-valid-in-python-without-creating-a-file-at-the-paths-ta/34102855#34102855).

**Comment by eulertour** [comment]
Resolved by #365.
