### ISSUE TITLE
No module named "numpy"

### ISSUE THREAD

**Issue by SushiSalad** [3b1b/manim#363]
When running the example file provided in manim, I am met with a ModuleNotFoundError stating that there is no module named "numpy"

I have installed numpy, but it still returns this error.

**Comment by Elteoremadebeethoven** [comment]
GNU/Linux, Mac or Windows?

**Comment by JacoboGuijar** [comment]
> GNU/Linux, Mac or Windows?

I have the same problem, on windows.

```
File "C:\Manim\Manim_3_feb\big_ol_pile_of_manim_imports.py", line 17, in <module>
    from manimlib.constants import *
  File "C:\Manim\Manim_3_feb\manimlib\constants.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```
