### ISSUE TITLE
Numpy has no attribute 'array'

### ISSUE THREAD

**Issue by SushiSalad** [3b1b/manim#368]
When I run the example code it returns an error: 
https://i.imgur.com/wSCWM3E.png

**Comment by eulertour** [comment]
Have you seen #297?

**Comment by SushiSalad** [comment]
Yes, but the solution did not work for me. There's no numpy.py file anywhere in the directory. Am I supposed to get the files from somewhere else other than numpy's github?

**Comment by eulertour** [comment]
No, that should work. More information would be useful here:
1. The entire error message
2. The output from running `import numpy; numpy.__file__` from a python shell
3. How you installed numpy

**Comment by SushiSalad** [comment]
https://i.imgur.com/UjEx9ml.png
I installed it by downloading numpy's repository to my manim folder through GitHub Desktop.
Running the command you mentioned: 
https://i.imgur.com/28Sv5ZX.png

**Comment by eulertour** [comment]
Downloading the repository is different from installing the library. A google search should produce instructions on how to install numpy.

**Comment by SushiSalad** [comment]
I found where my numpy was and after putting it in the manim directory i got another error for a module that was located in the same place. Is there some way I can set the directory that these modules are in to be accessible from any directory? Sort of how I had to set up the PATH for python.
