### ISSUE TITLE
OSError: No file matching image directory

### ISSUE THREAD

**Issue by SimchaGD** [3b1b/manim#372]
I run on Windows 10

The following error occurs when typing `python extract_scene.py example_scenes.py WriteStuff -p`.

`
ERROR: can't open file 'C:\Users\simcha\Documents\math.dvi' for reading 
`
`
Traceback (most recent call last):
  File "extract_scene.py", line 289, in main
    handle_scene(SceneClass(**scene_kwargs), **config)
  File "C:\Users\simcha\Documents\math animations\manim\scene\scene.py", line 82, in __init__
    self.construct(*self.construct_args)
  File "C:\Users\simcha\Documents\math animations\manim\example_scenes.py", line 41, in construct
    tex_to_color_map={"text": YELLOW}
  File "C:\Users\simcha\Documents\math animations\manim\mobject\svg\tex_mobject.py", line 145, in __init__
    self, self.arg_separator.join(tex_strings), **kwargs
  File "C:\Users\simcha\Documents\math animations\manim\mobject\svg\tex_mobject.py", line 48, in __init__
    SVGMobject.__init__(self, file_name=file_name, **kwargs)
  File "C:\Users\simcha\Documents\math animations\manim\mobject\svg\svg_mobject.py", line 47, in __init__
    self.ensure_valid_file()
  File "C:\Users\simcha\Documents\math animations\manim\mobject\svg\svg_mobject.py", line 67, in ensure_valid_file
    self.file_name)
OSError: No file matching C:\Users\simcha\Documents\math animations\manim\files\Tex\47f78a457bde38f5.svg in image directory `

**Comment by eulertour** [comment]
Is `47f78a457bde38f5.svg` in `manim/files/Tex/`? It should have been written while rendering the scene. I don't know why manim is trying to read `math.dvi` from outside its own directory. Can you explain what that file is?

**Comment by SimchaGD** [comment]
Hi,
Thanks for your reply.
The `.svg` file is not rendered or written in `manim/files/Tex/`. Also, I have no clue what `math.dvi` might be.

**Comment by SimchaGD** [comment]
I tried it again today and the `.dvi` file rendered correctly in the correct directory. Still no `.svg`. The new error I got says. 
`Exception: Latex error converting to dvi. See log output above or the log file: C:\Users\simcha\Documents\math animations\manim\files\Tex\41ed2e2c9545795e.log`

**Comment by Aarif1430** [comment]
Hi,
I am facing similar issue "ERROR: can't open file ... 1b6b75c8b2286ccb.xdv' for reading" in files Tex directory. Also getting OSError: No file matching..../manimlib/files/Tex/1b6b75c8b2286ccb.svg in image directory. Help appreciated.
Thanks,

**Comment by librix** [comment]
look up for your dvisvgm --version. maybe its too old.

**Comment by cszhangbo** [comment]
Hi，I get the same error “No File matching ... xx.svg in image directionary”. I download dvisvgm on this site
https://dvisvgm.de/Downloads/. 
Then set the environment variable of dvisvgm.It worked.

**Comment by cszhangbo** [comment]
> Hi,
> I am facing similar issue "ERROR: can't open file ... 1b6b75c8b2286ccb.xdv' for reading" in files Tex directory. Also getting OSError: No file matching..../manimlib/files/Tex/1b6b75c8b2286ccb.svg in image directory. Help appreciated.
> Thanks,

Just down dvisvgm as librix said. 
https://dvisvgm.de/Downloads/

**Comment by Wulleh** [comment]
I have the same/similar problem, however I'm able to convert it by manually running dvisvgm.

Following Error occures (with example_scenes.py):
```
PS C:MYPATH\manim> python -m manim example_scenes.py WriteStuff -pl
Media will be written to './media\'. You can change this behavior with the --media_dir flag.
File:  media/Tex/e3d47ecc6d1ea954.dvi
FULL COMMAND:  dvisvgm 'media/Tex/e3d47ecc6d1ea954.dvi' -n -v 0 -o 'media/Tex/e3d47ecc6d1ea954.svg'
ERROR: can't open file ''media/Tex/e3d47ecc6d1ea954.dvi'' for reading

Traceback (most recent call last):
  File "C:MYPATH\manim\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "C:MYPATH\manim\manimlib\scene\scene.py", line 53, in __init__
    self.construct()
  File "example_scenes.py", line 102, in construct
    tex_to_color_map={"text": YELLOW}
  File "C:MYPATH\manim\manimlib\mobject\svg\tex_mobject.py", line 144, in __init__
    self, self.arg_separator.join(tex_strings), **kwargs
  File "C:MYPATH\manim\manimlib\mobject\svg\tex_mobject.py", line 46, in __init__
    SVGMobject.__init__(self, file_name=file_name, **kwargs)
  File "C:MYPATH\manim\manimlib\mobject\svg\svg_mobject.py", line 48, in __init__
    self.ensure_valid_file()
  File "C:MYPATH\manim\manimlib\mobject\svg\svg_mobject.py", line 66, in ensure_valid_file
    self.file_name)
OSError: No file matching media/Tex/e3d47ecc6d1ea954.svg in image directory
```

the line starting with "FULL COMMAND" was added by myself to copy/paste the full command directly to the shell. In the python file it looks like this:
```
def dvi_to_svg(dvi_file, regen_if_exists=False):
    """
    Converts a dvi, which potentially has multiple slides, into a
    directory full of enumerated pngs corresponding with these slides.
    Returns a list of PIL Image objects for these images sorted as they
    where in the dvi
    """
    result = dvi_file.replace(".dvi" if not TEX_USE_CTEX else ".xdv", ".svg")
    result = Path(result).as_posix()
    dvi_file = Path(dvi_file).as_posix()
    if not os.path.exists(result):
        commands = [
            "dvisvgm",
            "'{}'".format(dvi_file),
            "-n",
            "-v",
            "0",
            "-o",
            "'{}'".format(result),
            # ">",
            # os.devnull
        ]
        print("FULL COMMAND: ", " ".join(commands)) # Added for debugging
        os.system(" ".join(commands))
    return result
```

Running the commandline manually generates a svg-File as expected, running the manim-program does raise the error. I also changed the tex/dvi-commands according to the suggestions in #734, otherwise it wouldn't even be able to convert the TeX-File. Thanks in advance!

**Comment by Yuz7** [comment]
I had the similar issue "OSError: No file matching media/Tex/20e749dd19b72f20.svg in image directory".I changed the code in `tex_file_writing.py`.Concretly, it looks like this:
```
    def dvi_to_svg(dvi_file, regen_if_exists=False):
    """
    Converts a dvi, which potentially has multiple slides, into a
    directory full of enumerated pngs corresponding with these slides.
    Returns a list of PIL Image objects for these images sorted as they
    where in the dvi
    """
    result = dvi_file.replace(".dvi" if not TEX_USE_CTEX else ".xdv", ".svg")
    result = Path(result).as_posix()
    dvi_file = Path(dvi_file).as_posix()
    if not os.path.exists(result):
        commands = [
            "dvisvgm",
            "D:/manim/manim-master/manim-master/{}".format(dvi_file),      #changed
            "-n",
            "-v",
            "0",
            "-o",
            "D:/manim/manim-master/manim-master/{}".format(result),    #changed
            ">",
            os.devnull
        ]
        os.system(" ".join(commands))
```
But it still not work and I try the command `dvisvgm D:/manim/manim-master/manim-master/media/Tex/20e749dd19b72f20.dvi` in cmd.exe, it reported `ERROR:MiKTeX.Session could not be initialized`.Then i made anthor effort to get it working with the help of the disccusion [https://sourceforge.net/p/miktex/bugs/2376/](url).

Run the following commands with admin rights:
```
 regsvr32 MiKTeX209-core-PS.dll
 regsvr32 MiKTeX209-core.dll
 regsvr32 MiKTeX209-packagemanager-PS.dll
 regsvr32 MiKTeX209-packagemanager.dll
```

Now the dvi file converted svg file successfully and all cases in example_scenes.py can passed.

**Comment by vanshkothari** [comment]
@Yuz7 I had the same problem, I edited the tex_file_writing.py using the your code and it worked!!
Thank you so much!!!!!!
