### ISSUE TITLE
Y labels not displayed left to the y-axe, but down the tick in graphs

### ISSUE THREAD

**Issue by quark67** [3b1b/manim#373]
Here is my code:

```python
from big_ol_pile_of_manim_imports import *

class Graf(GraphScene):
    CONFIG = {
        "y_max" : 1,
        "y_min" : -1,
        "x_max" : 1,
        "x_min" : -1,
        "graph_origin" : ORIGIN,
        "x_labeled_nums" : [-1,1],
        "y_labeled_nums" : [-1,1],
    }
    def construct(self):
        self.setup_axes(animate=False)
        graphique = self.get_graph(lambda x : x**2)
        self.add(graphique)
        self.wait()
```

As you can see in the screenshot, "-1" and "1" for y-axis are displayed below the correspondant tick, not in the left. Why this?

On file `mobject/coordinate_systems.py`, lines 29-31, I read:

```python
        "y_axis_config": {
            "label_direction": LEFT,
        },
```

I tried to add these lines in CONFIG of my code, but this change nothing.

Is there a bug in the code? How can I have my labels for y-axis displayed on left?

![image](https://user-images.githubusercontent.com/9338576/50380778-0700a800-0673-11e9-98f6-5703bf2002ae.png)

**Comment by Elteoremadebeethoven** [comment]
Probably 3b1b missed it by accident.

**Comment by Kamik423** [comment]
I just had the same issue and after an hour of research (but not googling 😬) I got to the same solution. However I think I have nailed down the issue more: `line_to_number_vect` is [only ever set but never used](
https://github.com/3b1b/manim/search?q=line_to_number_vect&unscoped_q=line_to_number_vect), it has probably at some point in the past been partially renamed to `label_direction`. So a more correct solution would be to not add that line, but replace the one before.

**Comment by leotrs** [comment]
This issue can probably be closed now
