### ISSUE TITLE
can't run python extract_scene.py example_scenes.py SquareToCircle -pl

### ISSUE THREAD

**Issue by lkevinzc** [3b1b/manim#376]
Greetings!
Could anyone help me with the implementation of manim?
The problem now I have is that when i run **python extract_scene.py example_scenes.py SquareToCircle -pl**, the Traceback tells me that:
File "extract_scene.py", line 143, in <module>
    main()
TypeError: main() missing 1 required positional argument: 'config'
Just like the screen-shot shows:
![image](https://user-images.githubusercontent.com/38581401/50464180-7d324100-09ca-11e9-8e7a-ba1dafa17475.png)

I use Python3.7.1, and the dependencies should be already installed.
Thanks in advance for your help!!

**Comment by eulertour** [comment]
Try running `python -m manim example_scenes.py SquareToCircle -pl` or `python manim.py example_scenes.py SquareToCircle -pl`.

**Comment by JohnAZoidberg** [comment]
So should `extract_scene` never be manually called?
Then the doc at https://manim.readthedocs.io/en/latest/getting_started/learning_by_example.html is outdated/wrong.

**Comment by harshitgarg22** [comment]
+1. Experienced the same error. Is it a fault in documentation?
