### ISSUE TITLE
requirements installation

### ISSUE THREAD

**Issue by s1291** [3b1b/manim#383]
In the `README` file, to install the library:
```
git clone https://github.com/3b1b/manim.git
cd manim
pip install -r requirements.txt
python3 -m manim example_scenes.py SquareToCircle -pl
```

But in the third command (`pip install -m requirements.txt`) will install to for python2 instead of python3 packages (if python2 is the default) and that what happened to me.
So `pip3` should be called explicitly:
`pip3 install -r requirements.txt`
or
`python3 -m pip install -r requirements.txt`

**Comment by eulertour** [comment]
Closed by 9dafb85bde676485dbff3ecd9f14b5cf347a947f.
