### ISSUE TITLE
Scene Not In Script error if the file is not in root directory

### ISSUE THREAD

**Issue by Jar-win** [3b1b/manim#389]
When I try to render a file which is in a folder, using `python3 -m manim folder/filename.py -p` I get an error stating:
**That scene is not in the script**.
But when I move the same file to manim's root directory, it works.

For Instance:  Consider `active_projects/holomorphic.py` 
```
(manim) [jarwin:~/Documents/manim]$ python3 -m manim active_projects/holomorphic.py -p
  >   That scene is not in the script

```
Similarly, if I go into `active_projects` and then run it, I get another error:
```
(manim) [azazel:...ents/manim/active_projects]$ python3 ../manim.py active_projects/holomorphic.py -p
Media will be stored in media/. You can change this behaviour by writing a different directory to media_dir.txt.

   That scene is not in the script

```

Can anyone please tell me how to render the animation from within a folder?

I am using Ubuntu 18.04 and version of manim is **9dafb85**

**Comment by eulertour** [comment]
This is a problem with how manim import the files you specify. I'll try to get it fixed as soon as possible.

**Comment by eulertour** [comment]
#391 should fix this issue.
