### ISSUE TITLE
Python version problem?

### ISSUE THREAD

**Issue by ahmedahmedov** [3b1b/manim#39]
While running the demo, ( python extract_scene.py -p example_scenes.py SquareToCirclepython extract_scene.py -p example_scenes.py SquareToCircle ) I get the following exception: 

  File "extract_scene.py", line 46
    print str(err)
            ^
SyntaxError: invalid syntax

I believe it is somehow related to python version, right?

**Comment by sramsay64** [comment]
Yes, That particular syntax for `print` only works in python 2 so if you're using python 3 it won't work. Try using python 2.

**Comment by xtipacko** [comment]
Why on earth do you use python 2.7 ? :(

**Comment by theshteves** [comment]
*This issue can be closed.*

If @ahmedahmedov or anyone you know are interested in a Python 3 rewrite, then open a separate issue to raise awareness.  The Python community needs people like you pushing us forward!

**Comment by cclauss** [comment]
See #97

**Comment by kurosh-z** [comment]
I tried to convert all files into pyhon3 using 2to3 so I could use my own liberaries as well. It didn't work successfully for all files. Have anybody a better idea to convert it?

**Comment by cclauss** [comment]
Yes.  97# talks about how to use futurize.  There is another alternative called modernize.

These are both wrappers around 2to3 because 2to3 often breaks backward compatibility with Python 2 and the others try to preserve coexistence.
