### ISSUE TITLE
Latex Error -- Deciphering Log Error

### ISSUE THREAD

**Issue by financialphysician** [3b1b/manim#390]
I'm getting an error that other people have reported but am having a hard time figuring out what's wrong. Here's the error:

sh: latex: command not found

Traceback (most recent call last):
  File "/Users/logan/code/manim/manimlib/extract_scene.py", line 138, in main
    handle_scene(SceneClass(**scene_kwargs), **config)
  File "/Users/logan/code/manim/manimlib/scene/scene.py", line 78, in __init__
    self.construct(*self.construct_args)
  File "/Users/logan/code/manim/manim_tutorial_1.py", line 42, in construct
    my_first_text=TextMobject("Writing with manim is fun")
  File "/Users/logan/code/manim/manimlib/mobject/svg/tex_mobject.py", line 144, in __init__
    self, self.arg_separator.join(tex_strings), **kwargs
  File "/Users/logan/code/manim/manimlib/mobject/svg/tex_mobject.py", line 45, in __init__
    self.template_tex_file_body
  File "/Users/logan/code/manim/manimlib/utils/tex_file_writing.py", line 19, in tex_to_svg_file
    dvi_file = tex_to_dvi(tex_file)
  File "/Users/logan/code/manim/manimlib/utils/tex_file_writing.py", line 67, in tex_to_dvi
    "See log output above or the log file: %s" % log_file)
Exception: Latex error converting to dvi. See log output above or the log file: /Users/logan/code/manim/manimlib/files/Tex/41ed2e2c9545795e.log

So I pulled up the error log and retrieved the following but it's unclear to me what the problem is:

\documentclass[preview]{standalone}

\usepackage[english]{babel}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{dsfont}
\usepackage{setspace}
\usepackage{tipa}
\usepackage{relsize}
\usepackage{textcomp}
\usepackage{mathrsfs}
\usepackage{calligra}
\usepackage{wasysym}
\usepackage{ragged2e}
\usepackage{physics}
\usepackage{xcolor}
\usepackage{textcomp}
\usepackage{microtype}
\DisableLigatures{encoding = *, family = * }
%\usepackage[UTF8]{ctex}
\linespread{1}

\begin{document}
\centering Writing with manim is fun
\end{document}

Sorry if this is stupid simple. I'm still relatively new to programming. The line that looks unique is the "%\usepackage[UTF8]{ctex}" so I'm assuming it has something to do with that but googling isn't helping me much

**Comment by eulertour** [comment]
> sh: latex: command not found

This means manim was unable to find where latex was installed. It may help to run `latex` from the command line in the manim directory.

**Comment by financialphysician** [comment]
> > sh: latex: command not found
> 
> This means manim was unable to find where latex was installed. It may help to run `latex` from the command line in the manim directory.

Okay, I'm in the manim directory. How do I run latex? If I type it into the command line it just says "bash: latex: command not found" but I have installed it

**Comment by financialphysician** [comment]
I got it to work! Maybe I just needed to reload my terminals. Feels so good.
