### ISSUE TITLE
The video doesn't concatenate, I can only get partial videos

### ISSUE THREAD

**Issue by yerovi84** [3b1b/manim#401]
I have only the partial videos with the next error:

"[concat @ 000001ff22102900] Impossible to open '0.mp4'
media\videos\example_scenes\480p15\partial_movie_files\WriteStuff\partial_movie_file_list.txt: No such file or directory
File ready at media\videos\example_scenes\480p15\WriteStuff.mp4"

But I don't have the video WriteStuff.mp4.

Please help me

**Comment by pdcxs** [comment]
Same issue. I use windows platform and get the same problem.

**Comment by DRBrodbeck** [comment]
I also get this error.  What is the mystery text "partial_movie_file_list.txt" (from scene.py) below?

        file_list = os.path.join(
            partial_movie_file_directory,
            "partial_movie_file_list.txt"
        )

**Comment by Elteoremadebeethoven** [comment]
The problem was fixed today in the original repository of 3b1b.
