### ISSUE TITLE
Interpolation error for sqrt(x)

### ISSUE THREAD

**Issue by fukanchik** [3b1b/manim#404]
Graph of square root function has some bump next to zero x. See attached image.
![warpsquare](https://user-images.githubusercontent.com/967289/51141166-7010b100-1816-11e9-8d8b-7a907d65787c.png)
I am also attaching source code. 
[code.zip](https://github.com/3b1b/manim/files/2757059/code.zip)
To reproduce run:
$ python3 -m manim nerav.py WarpSquare -s
I tabulated function call (also attached) and there's gap between 0.0002-0.08.
[tabulated.zip](https://github.com/3b1b/manim/files/2757067/tabulated.zip)
Therefore I conclude next to 0, between 0.0002777777777777778 and 0.08305555555555555 function is interpolated instead of tabulated.

**Comment by Elteoremadebeethoven** [comment]
Yes, it looks like a stranger bug, but I found a little trick to fix it until someone find the solution:

```python3
class Graph(GraphScene):
    CONFIG = {
            "x_min": 0,
            "x_max": 2,
            "x_labeled_nums": range(0,3),
            "y_min": 0,
            "y_max": 3,
    }
    def construct(self):
        self.setup_axes(animate=False)
        sqrt_graph_1 = self.get_graph(lambda x : np.sqrt(x), GREEN,x_min=0.0001,x_max=0.02)
        sqrt_graph_2 = self.get_graph(lambda x : np.sqrt(x), GREEN,x_min=0.02,x_max=2)
        sqrt_graph=VMobject(sqrt_graph_1,sqrt_graph_2)
        self.play(ShowCreation(sqrt_graph))
```

**Comment by eulertour** [comment]
Yeah, this bug is unfortunately pretty deep in the code.
Depending on how hacky you want to be, you could also add `"num_graph_anchor_points": 3000` to `CONFIG`.

**Comment by 3b1b** [comment]
This issue should now be fixed.
