### ISSUE TITLE
Problem with negative DecimalNumber

### ISSUE THREAD

**Issue by Elteoremadebeethoven** [3b1b/manim#411]
Hi, I have a problem with UdatersExample in example_scenes.py on Windows and Linux:

![issue](https://user-images.githubusercontent.com/43224662/51407241-ea944600-1b20-11e9-94ad-8706ce23a9ae.png)

I don't find the way to fix this.

**Comment by 3b1b** [comment]
Apologies for that, I just pushed a change that should fix it.

**Comment by Elteoremadebeethoven** [comment]
Thanks!
