### ISSUE TITLE
Problems with ffmpeg

### ISSUE THREAD

**Issue by achen0325** [3b1b/manim#415]
Dear all,

I am getting following error when running Manim. I've installed ffmpeg. 

![issue](https://user-images.githubusercontent.com/34126639/51433827-873a0f00-1c19-11e9-95eb-156aaa28c2e2.png)

**Comment by eulertour** [comment]
Your user doesn't have execute permission on ffmpeg. You could probably fix this with either the `chmod` or `chown` command.
