### ISSUE TITLE
Docker image: No module named 'pydub'

### ISSUE THREAD

**Issue by LoveDaisy** [3b1b/manim#417]
Dear all

I've pulled the latest docker image and run the `SquareToCircle` example, and it reports that `No module named 'pydub'`. Then I installed the `pydubs` module via `pip3 install pydub` and the problem solved.

I'm not sure whether there are other module issues. 

Can anyone help to update the docker image?

**Comment by eulertour** [comment]
This should just be a matter of updating requirements.txt. I'll get to it soon.

**Comment by LoveDaisy** [comment]
Thanks @eulertour .
I think re-build the docker image on eulertour/manim:latest will help. When I tried building a new image on my local, there wasn't any problem.

**Comment by eulertour** [comment]
I've pushed an updated image, so this problem is resolved.
