### ISSUE TITLE
Attribute Error: module 'cairo' has no attribute 'ImageSurface'

### ISSUE THREAD

**Issue by Zokalyx** [3b1b/manim#420]
Hi, I am trying to run the example in git bash, but I get this error:
`$ python -m manim example_scenes.py SquareToCircle -pl                           Traceback (most recent call last):                                                 File "C:\Users\seba\Desktop\Coding\Forks and Clones\manim\manimlib\extract_sce ne.py", line 153, in main                                                            scene = SceneClass(**scene_kwargs)                                             File "C:\Users\seba\Desktop\Coding\Forks and Clones\manim\manimlib\scene\scene .py", line 54, in __init__                                                           self.construct()                                                               File "example_scenes.py", line 81, in construct                                    self.play(ShowCreation(square))                                                File "C:\Users\seba\Desktop\Coding\Forks and Clones\manim\manimlib\scene\scene .py", line 453, in wrapper                                                           func(self, *args, **kwargs)                                                    File "C:\Users\seba\Desktop\Coding\Forks and Clones\manim\manimlib\scene\scene .py", line 484, in play                                                              self.update_frame(moving_mobjects, static_image)                               File "C:\Users\seba\Desktop\Coding\Forks and Clones\manim\manimlib\scene\scene .py", line 145, in update_frame                                                      self.capture_mobjects_in_camera(mobjects, **kwargs)                            File "C:\Users\seba\Desktop\Coding\Forks and Clones\manim\manimlib\scene\scene .py", line 123, in capture_mobjects_in_camera                                        self.camera.capture_mobjects(mobjects, **kwargs)                               File "C:\Users\seba\Desktop\Coding\Forks and Clones\manim\manimlib\camera\came ra.py", line 271, in capture_mobjects                                                func(batch, self.pixel_array)                                                  File "C:\Users\seba\Desktop\Coding\Forks and Clones\manim\manimlib\camera\came ra.py", line 319, in display_multiple_vectorized_mobjects                            self.display_multiple_non_background_colored_vmobjects(batch, pixel_array)     File "C:\Users\seba\Desktop\Coding\Forks and Clones\manim\manimlib\camera\came ra.py", line 322, in display_multiple_non_background_colored_vmobjects               ctx = self.get_cairo_context(pixel_array)                                      File "C:\Users\seba\Desktop\Coding\Forks and Clones\manim\manimlib\camera\came ra.py", line 292, in get_cairo_context                                               surface = cairo.ImageSurface.create_for_data(                                AttributeError: module 'cairo' has no attribute 'ImageSurface'`
I'm running Windows 10 64bit. I had to install pycairo from this website https://www.lfd.uci.edu/~gohlke/pythonlibs/#pycairo because the regular one would generate a bug that has been adressed in #353, and as a user mentioned, I used that webpage and downloaded "pycairo‑1.18.0‑cp37‑cp37m‑win_amd64.whl". I think this is the right version since I have Python 3.7.2, but I still get this problem.

**Comment by Beinger** [comment]
I'm running Manjaro. I get this error also.

**Comment by inasaaone** [comment]
I am also having the same issue...

**Comment by kolibril13** [comment]
I had a similar problem on Ubunutu, maybe you can try this:
 First, I installed python3.7.
Then I installed pycairo:
`python3.7 -m pip install pycairo`
Afterwards the requirements:
`python3.7 -m pip install -r requirements.txt`

**Comment by abecus** [comment]
@kolibril13 
it worked, thank you!

**Comment by yoshiask** [comment]
@eulertour I think this issue needs to be closed
