### ISSUE TITLE
WinError 2 from subprocess.Popen

### ISSUE THREAD

**Issue by AustereTriceratops** [3b1b/manim#423]
While running `python -m manim example_scenes.py SquareToCircle -pl` in Anaconda2 I get the following error:

> Traceback (most recent call last):
>   File "D:\programming\manim\manimlib\extract_scene.py", line 153, in main
>     scene = SceneClass(**scene_kwargs)
>   File "D:\programming\manim\manimlib\scene\scene.py", line 54, in __init__
>     self.construct()
>   File "example_scenes.py", line 81, in construct
>     self.play(ShowCreation(square))
>   File "D:\programming\manim\manimlib\scene\scene.py", line 452, in wrapper
>     self.file_writer.begin_animation(allow_write)
>   File "D:\programming\manim\manimlib\scene\scene_file_writer.py", line 152, in begin_animation
>     self.open_movie_pipe()
>   File "D:\programming\manim\manimlib\scene\scene_file_writer.py", line 240, in open_movie_pipe
>     self.writing_process = subprocess.Popen(command, stdin=subprocess.PIPE)
>   File "C:\Users\gatew\PyMOL\envs\py36\lib\subprocess.py", line 729, in __init__
>     restore_signals, start_new_session)
>   File "C:\Users\gatew\PyMOL\envs\py36\lib\subprocess.py", line 1017, in _execute_child
>     startupinfo)
> FileNotFoundError: [WinError 2] The system cannot find the file specified

I've done some looking around and it seems that other people are having trouble with this module. I've tried setting `shell=True` in extract_scene.py and running this command as an administrator, but the problem still persists.

**Comment by Elteoremadebeethoven** [comment]
Don't use anaconda. Install python with the original sourse: 
https://www.python.org/downloads/

**Comment by AustereTriceratops** [comment]
The error is the same regardless of which command line I use - I was just used to Anaconda so that was the first one I tried.

**Comment by AustereTriceratops** [comment]
I did some more testing and found the error: the location of ffmpeg was wrong in the path system variable.

**Comment by Jaimath** [comment]
Hello @AustereTriceratops, can you tell me the path you used for ffmpeg? I have the same error than you, the path I have is C:\ffmpeg\bin, I checked this path in other sites but I am not sure if is correct or  not.

This is what I got:

Traceback (most recent call last):
  File "c:\manim-master\manimlib\extract_scene.py", line 146, in main
    handle_scene(SceneClass(**scene_kwargs), **config)
  File "c:\manim-master\manimlib\scene\scene.py", line 73, in __init__
    self.construct(*self.construct_args)
  File "example_scenes.py", line 108, in construct
    self.play(Write(example_text))
  File "c:\manim-master\manimlib\scene\scene.py", line 86, in wrapper
    self.open_movie_pipe()
  File "c:\manim-master\manimlib\scene\scene.py", line 689, in open_movie_pipe
    self.writing_process = subprocess.Popen(command, stdin=subprocess.PIPE)
  File "C:\Users\Jamath\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Jamath\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado

Thanks!

**Comment by yoshiask** [comment]
@Jaimath Did you add that ffmpeg path to the PATH environment variable?

**Comment by Jaimath** [comment]
Hello Yoshi, the ffmpeg was correct, my problem was (I think) that I had
installed a 32bit version of the Pycairo module while I have a 64bit Python
installation (and system). Anyway I removed all and installed all again
paying more attention to the 64bit modules when neeeded and now I can
finally work with Manim for the sake of my students!!

Many thanks for your attention!
