### ISSUE TITLE
ImportError undefined symbol: cairo_tee_surface_index

### ISSUE THREAD

**Issue by kolibril13** [3b1b/manim#430]
I installed the manim package as described (Ubuntu 18.04):

`git clone https://github.com/3b1b/manim.git`
`cd manim`
`python3 -m pip install -r requirements.txt`
But when I run the line 
`python3 -m manim example_scenes.py SquareToCircle -pl`
I receive the following error:
![screenshot from 2019-02-08 21-31-25](https://user-images.githubusercontent.com/44469195/52504484-ef608d00-2be8-11e9-80fb-538b437f419a.png)

Thank you for any ideas how to solve this.

**Comment by eulertour** [comment]
You probably didn't have cairo installed before you installed the requirements.

**Comment by kolibril13** [comment]
Tank you for this hint.
Normally I am using anaconda, however I did not manage to install cairo in anaconda properly.
I got it now working with the following procedure:
First, I installed python3.7.
Then I installed pycairo:
`python3.7 -m pip install pycairo`
Afterwards the requirements:
`python3.7 -m pip install -r requirements.txt`
and now it is working!

**Comment by Rodroro** [comment]
I am trying to solve the problem trying to do what is suggested, I uninstall pycairo and requirements.txt and then install them correctly (with the suggested order) but the error continues to appear and continue to appear, any help?

**Comment by Czechball** [comment]
I'm having the same issue:
```
sudo pip2 install pycairo
Requirement already satisfied: pycairo in /usr/lib/python2.7/site-packages (1.18.2)
```
```
file /usr/lib/python2.7/site-packages/cairo/_cairo.so
/usr/lib/python2.7/site-packages/cairo/_cairo.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=6cb1ed19ad648f925b18d567bc0c8e35c86cc778, stripped
```
```
zenmap
Could not import the zenmapGUI.App module: '/usr/lib/python2.7/site-packages/cairo/_cairo.so: undefined symbol: cairo_tee_surface_index'.
I checked in these directories:
    /usr/bin
    /usr/lib/python27.zip
    /usr/lib/python2.7
    /usr/lib/python2.7/plat-linux2
    /usr/lib/python2.7/lib-tk
    /usr/lib/python2.7/lib-old
    /usr/lib/python2.7/lib-dynload
    /home/czechball/.local/lib/python2.7/site-packages
    /usr/lib/python2.7/site-packages
    /usr/lib/python2.7/site-packages/gtk-2.0
    /usr/lib/python2.7/site-packages
If you installed Zenmap in another directory, you may have to add the
modules directory to the PYTHONPATH environment variable.
```
