### ISSUE TITLE
Problem with add sound on Windows

### ISSUE THREAD

**Issue by Elteoremadebeethoven** [3b1b/manim#433]
Hi, in Linux if a run this:

```python3
class SoundTest(Scene):
	CONFIG = {"include_sound": True}
	def construct(self):
		title=TextMobject("Sound Test").to_edge(UP)
		self.play(Write(title))
		self.wait()
		self.add_sound("sound.wav")
		self.wait()
```
With "sound.wav" in media/designs/sounds/sound.wav works fine, but in Windows if I run the same I get:

```sh
[aac @ 02f5c0c0] The encoder 'aac' is experimental but experimental codecs are not enabled, add '-strict -2' if you want to use it.
[aac @ 02f5c0c0] Alternatively use the non experimental encoder 'libvo_aacenc'.
```

If I modify the file manimlib\scene\scene_file_writer.py in the line 334:

```python3
'-loglevel', 'error',
```
you add '-strict','-2', just like:

```python3
'-loglevel', 'error','-strict','-2',
```

The problem is solved. But I do not know if this is a bug to consider, or if it can be resolved differently for Windows users.

**Comment by 3b1b** [comment]
Hmm, according to [this page](https://trac.ffmpeg.org/wiki/Encode/AAC), under "Native FFmpeg AAC Encoder", aac is no longer experimental.

**Comment by Elteoremadebeethoven** [comment]
That's weird, I'm using the latest version of FFmpeg.

I saw that it also serves to replace 'aac' with 'libvo_aacenc' (on line 328). But in the same way I do not know what this is due to. Probably the FFmpeg enconders on Windows are less updated than those of Linux or Mac.

**Comment by Elteoremadebeethoven** [comment]
This problem don't occur in W10
