### ISSUE TITLE
can't find script that generate (Euler's Formula Poem)

### ISSUE THREAD

**Issue by FathyEltanany** [3b1b/manim#435]
i can't find script that generate (Euler's Formula Poem) video in that link:  https://www.youtube.com/watch?v=zLzLxVeqdQg

**Comment by 3b1b** [comment]
Oh man, that would be extremely old.  Certainly whatever code generated that would not work with the current version of manim.  Is there some functionality you're looking for specifically?

**Comment by FathyEltanany** [comment]
yeah , iam looking for functions that control the plane such as moving and rotating and scaling
