### ISSUE TITLE
i cant run manim successfully

### ISSUE THREAD

**Issue by awaqawaq** [3b1b/manim#444]
i think i've successful installed all module what manim need,but when i run 'python -m manim example_scenes.py SquareToCircle -pl' there were some error i cant solve ...
![image](https://user-images.githubusercontent.com/43958583/52912655-54a23580-32ef-11e9-899f-bb2a5e8b1e0c.png)
how can i solve them thank you very much

**Comment by Elteoremadebeethoven** [comment]
Install readline:
```sh
python3 -m pip install pyreadline
```

**Comment by awaqawaq** [comment]
thanks your reply.
after i installing pyreadline ,i try to run SquareToCircle ,luckily it worked. but when i run other function such as WriteStuff : 
 

![image](https://user-images.githubusercontent.com/43958583/52949228-acf03a80-33b6-11e9-98b9-d98ab65ae4e0.png)


why??

**Comment by eulertour** [comment]
There's a problem with your latex installation, although it's hard to know exactly what it is. You could try reinstalling it.

As for the pyreadline problem, there should be a way to skip the check on Windows. I don't want to install it by default because it seems to be unsupported.
