### ISSUE TITLE
self.setup_axes returns an error

### ISSUE THREAD

**Issue by SushiSalad** [3b1b/manim#448]
when attempting to run a code that plots a graph it returns an error upon reaching "self.setup_axes()"

"AttributeError: 'PlottingFunctions" object has no attribute 'setup_axes' "

I'm clueless. Has this function changed in an update recently?

Current code: https://i.imgur.com/UGwAhlZ.png

**Comment by rkcosner** [comment]
Just in case other people run into this issue: 
You were inheriting from "Scene" when you should've been inheriting from "GraphScene"
