### ISSUE TITLE
Change Interpolation for ImageMobject

### ISSUE THREAD

**Issue by kolibril13** [3b1b/manim#451]
I want to graph an matrix array without interpolation (just rectangular boxes for each matrix element).
However, when I run my script manim interpolates the matrix.
```
class Images(Scene):
    def construct(self):
        matrix= np.uint8([[ 0, 0 , 200],
                          [255,0 , 33]])
        img= ImageMobject(matrix)
        img.scale(3)
        self.add(img)
        self.wait(2)
````
And what I get looks like this:
![img](https://user-images.githubusercontent.com/44469195/53189462-dbb11f80-3607-11e9-9df8-a79ee793231a.png)

Does someone know where to change the interpolation settings?

**Comment by adamryczkowski** [comment]
I wonder how to do it myself. Did you get the answer elsewhere?

**Comment by kolibril13** [comment]
I just saw you pr, thanks for that! :)
