### ISSUE TITLE
Latex error converting to dvi

### ISSUE THREAD

**Issue by SushiSalad** [3b1b/manim#452]
When I attempt to export a scene using some form of Latex text it returns the error "Latex error converting to dvi"
I've scanned through most of the related issues but none of them seem to apply since the block of text they generally suggest to replace is in a completely different file than where they found it (in tex_file_writing.py rather than in tex_mobject.py).
I tried replacing the block of text in the new file but it would return a new error that "get_null" is not defined and after I removed it, it would just return the same error as before.
The issue I'm refering to is https://github.com/3b1b/manim/issues/64

> Traceback (most recent call last):
  File "/home/quentin/manim/manimlib/extract_scene.py", line 153, in main
    scene = SceneClass(**scene_kwargs)
  File "/home/quentin/manim/manimlib/scene/scene.py", line 52, in __init__
    self.construct()
  File "plotting.py", line 185, in construct
    self.setup_axes(animate = True)
  File "/home/quentin/manim/manimlib/scene/graph_scene.py", line 87, in setup_axes
    x_label = TextMobject(self.x_axis_label)
  File "/home/quentin/manim/manimlib/mobject/svg/tex_mobject.py", line 143, in __init__
    self, self.arg_separator.join(tex_strings), **kwargs
  File "/home/quentin/manim/manimlib/mobject/svg/tex_mobject.py", line 44, in __init__
    self.template_tex_file_body
  File "/home/quentin/manim/manimlib/utils/tex_file_writing.py", line 20, in tex_to_svg_file
    dvi_file = tex_to_dvi(tex_file)
  File "/home/quentin/manim/manimlib/utils/tex_file_writing.py", line 62, in tex_to_dvi
    "See log output above or the log file: %s" % log_file)
Exception: Latex error converting to dvi. See log output above or the log file: /home/quentin/manim/manimlib/files/Tex/4f3c7493cee28c13.log

This is what the error looks like and
[4f3c7493cee28c13.log](https://github.com/3b1b/manim/files/2892241/4f3c7493cee28c13.log)
this is the log it makes.

I have installed all texlive packages, I'm unsure what I can do now?

**Comment by Elteoremadebeethoven** [comment]
Please, show us the code to help you.

**Comment by kolibril13** [comment]
Try to install this package:
`sudo apt-get install texlive-fonts-extra `
and it should work

**Comment by SushiSalad** [comment]
> Please, show us the code to help you.
> 
> I think you're using the method `TextMobject` with formulas. For example, if you wanna write:
> 
> ```
> \frac{x}{y}
> ```
> 
> You have to write it in `TextMobject` like:
> 
> ```python
> TextMobject("$\\frac{x}{y}$")
> ```
> 
> With the $$ symbols and double backslash. But, if you wanna write the formula like `$$formula$$`, you have to use:
> 
> ```python
> TexMobject("\\frac{x}{y}")
> ```
> 
> TextMobject for normal text, and TexMobject for formulas.

This didn't work, it still returns the same error using both methods.

**Comment by eulertour** [comment]
Change this line:
```
(manim) > diff sushi_orig.py sushi.py
40c40
<         graphl = self.get_graph_label(func_graph, label = "$\\x^{2}$")
---
>         graphl = self.get_graph_label(func_graph, label = "x^{2}")
```
Though I admit this is weird, since latex won't typeset the axis labels in `CONFIG` unless they're surrounded by $$.

Also, it's much easier to debug your scenes when they run as pasted, so please make sure all of it is formatted properly in the future.
