### ISSUE TITLE
get_area places rectangles in middle of screen?

### ISSUE THREAD

**Issue by SushiSalad** [3b1b/manim#455]
class AreaTest(GraphScene, Scene):
    CONFIG = {
        "x_min": -10,
        "x_max": 10,
        "x_axis_width": 15,
        "x_tick_frequency": 0.5,
        "x_leftmost_tick": None,  # Change if different from x_min
        "x_labeled_nums": None,
        "x_axis_label": "$time$",
        "y_min": -10,
        "y_max": 10,
        "y_axis_height": 6,
        "y_tick_frequency": 1,
        "y_bottom_tick": None,  # Change if different from y_min
        "y_labeled_nums": None,
        "y_axis_label": "$velocity$",
        "axes_color": BLUE,
        "graph_origin": ORIGIN,
        "exclude_zero_label": True,
        "default_graph_colors": [BLUE, GREEN, YELLOW],
        "default_derivative_color": GREEN,
        "default_input_color": YELLOW,
        "default_riemann_start_color": BLUE,
        "default_riemann_end_color": GREEN,
        "area_opacity": 0.8,
        "num_rects": 50,
        "num_graph_anchor_points" : 3000,
        "function_color" : WHITE,
	}

    def func1(self, x):
        return (x)

    def construct(self):
        self.setup_axes(animate = True)
        func_graph = self.get_graph(self.func1, self.function_color)
        graph_area = self.get_area(func_graph, 0, 10)

        self.play(ShowCreation(func_graph))
        self.play(ShowCreation(graph_area))
        self.wait(1)

In this code I attempt to create a graph with a function then show the area underneath, but when I show the creation of the area, rectangles just appear in the center of the screen .

I searched through Essence of Calculus Chap. 1 to see how it work in there and he seemed to use some kind of lists when placing them but I couldn't figure out how it worked. Is this what I am doing wrong?

Also I can't get all the code to properly format into code on this post please forgive me

**Comment by Elteoremadebeethoven** [comment]
I don't know what you wanna do, but if you wanna see all area, in the possitive and negative you have tu use:

```python3
graph_area = self.get_area(func_graph, -10, 10) #<--- change de '0' for '-10'
```

Or if you wanna put the origin in another place you have to change ""graph_origin": ORIGIN":

```python3
class AreaTest(GraphScene, Scene):
    CONFIG = {
    "x_min": 0,
    "x_max": 10,
    "x_axis_width": 10, #change the width of the step in x
    "x_tick_frequency": 1,
    "x_axis_label": "$time$",
    "y_min": 0,
    "y_max": 10,
    "y_axis_height": 6,
    "y_tick_frequency": 1,
    "y_bottom_tick": None,
    "y_labeled_nums": None,
    "y_axis_label": "$velocity$",
    "axes_color": BLUE,
    "graph_origin": LEFT*6+DOWN*3, #Change the position of the origin
    "exclude_zero_label": True,
    "default_graph_colors": [BLUE, GREEN, YELLOW],
    "default_derivative_color": GREEN,
    "default_input_color": YELLOW,
    "default_riemann_start_color": BLUE,
    "default_riemann_end_color": GREEN,
    "area_opacity": 0.8,
    "num_rects": 50,
    "num_graph_anchor_points" : 3000,
    "function_color" : WHITE,
    }

    def func1(self, x):
        return (x)

    def construct(self):
        self.setup_axes(animate = True)
        func_graph = self.get_graph(self.func1, self.function_color)
        graph_area = self.get_area(func_graph, 0, 10)

        self.play(ShowCreation(func_graph))
        self.play(ShowCreation(graph_area))
        self.wait(1)
```

![areatest](https://user-images.githubusercontent.com/43224662/53310232-a0198e00-3871-11e9-998d-75f2cca267a9.png)

**Comment by SushiSalad** [comment]
Sorry, I wasn't clear on what my issue is. When I say it places all the rectangles in the middle I mean this...
![areatest](https://user-images.githubusercontent.com/29654673/53310307-508b9000-387a-11e9-84ab-8f2362b6cb9c.png)

The rectangles don't pan out underneath the line.

**Comment by Elteoremadebeethoven** [comment]
Yes, it is a bug, do not worry, you just have to see the code of graph_scene.py, but I do not have time to look at it, you can use this version and wait until it is solved.

https://github.com/3b1b/manim/tree/3b088b12843b7a4459fe71eba96b70edafb7aa78

**Comment by eulertour** [comment]
8e0fae4663dfe0d963d67f7dfbabf8a865332607 caused this problem, and reverting the commit solves it. However, I'm not sure what the motivation for that change is, so I don't know what side effects that would cause. 

The bug is triggered when a `VMobject` which contains `VectorizedPoint`s in its boundary is passed to `VMobject.get_points_defining_boundary()`. A `VectorizedPoint` contains only a single point, and `get_start_anchors()` will return it. But `get_end_anchors()` returns an empty array. This causes the call to `zip()` in `get_anchors()` to return an empty zip object, which in turn makes `get_anchors()` return an empty array. As a result, no `VectorizedPoints` are considered part of the `VMobject`s boundary.

I'm not sure what an "anchor" is meant to be in this context, so I'm not sure if `get_anchors()` or `get_points_defining_boundary()` is wrong, but it's definitely one of them. Perhaps @3b1b can shed some light on the problem. The relevant code is below.

https://github.com/3b1b/manim/blob/5b1f54a89ec5564d12c4086c859f72e192b37741/manimlib/mobject/types/vectorized_mobject.py#L653-L670

**Comment by eulertour** [comment]
Since the bug is still there, this issue shouldn't be closed yet.

**Comment by zonxin** [comment]
@eulertour   In `manim`, a `VMobject` is made up of cubic [Bézier curves](https://en.wikipedia.org/wiki/Composite_B%C3%A9zier_curve), even if it is a `Polygon` which is made up of lines.  Each cubic curve is determined by 4 points,  2 endpoints  and 2 control points. The endpoints are called anchors in thousands applications. 
(Thus, for a `VMobject`,  `len(self.points) % 4 == 0` and `VMobject.n_points_per_cubic_curve` is 4).

**Comment by eulertour** [comment]
> In manim, a VMobject is made up of cubic Bézier curves, even if it is a Polygon which is made up of straight lines. Each cubic curve is determined by 4 points, 2 endpoints and 2 control points.

Each `VectorizedPoint` has only one point, which is what was confusing me. That said, the other context you gave makes it pretty clear that calling `get_anchors()` on a `VectorizedPoint` should return its only point.

**Comment by zonxin** [comment]
Very sorry for my misunderstanding.  `manim`  is very charming. I were reading the source codes in last two days hoping to provide some help.
