### ISSUE TITLE
Changing y domain of a graph

### ISSUE THREAD

**Issue by SushiSalad** [3b1b/manim#457]
I'm trying to place a graph beneath words depicting what is on the graph, but when I draw the functions onto it they bleed out of the graph's area and up into where the wording is. I can't find an argument allowing me to cut off the functions before they leave the graph.

![intro](https://user-images.githubusercontent.com/29654673/53379958-ad9a4b00-3939-11e9-8746-0b0d0b299e73.png)

This is how it looks at the end.

`class Intro(GraphScene, Scene):
    CONFIG = {
        "x_min": -10,
        "x_max": 10,
        "x_axis_width": 15,
        "x_tick_frequency": 0.5,
        "x_leftmost_tick": None,  # Change if different from x_min
        "x_labeled_nums": None,
        "x_axis_label": None,
        "y_min": -10,
        "y_max": 10,
        "y_axis_height": 6,
        "y_tick_frequency": 1,
        "y_bottom_tick": None,  # Change if different from y_min
        "y_labeled_nums": None,
        "y_axis_label": None,
        "axes_color": BLUE,
        "graph_origin": 3*DOWN,
        "exclude_zero_label": True,
        "default_graph_colors": [BLUE, GREEN, YELLOW],
        "default_derivative_color": GREEN,
        "default_input_color": YELLOW,
        "default_riemann_start_color": BLUE,
        "default_riemann_end_color": GREEN,
        "area_opacity": 0.8,
        "num_rects": 50,
        "num_graph_anchor_points" : 3000,
        "function_color" : WHITE,
	}

    def func1(self, x):
        return (x**3+2*x**2+3)

    def func1der(self, x):
        return (3*x**2+4*x)

    def func1int(self, x):
        return ((x**4)/(4)+(2*x**3)/(3)+3*x)

    def construct(self):
        self.setup_axes(animate = True)
        intext = TextMobject("Integration")
        dertext = TextMobject("Differentiation")
        caltext = TextMobject("Calculus")
        caltext.set_color_by_tex("Calculus", BLUE)
        intext.set_color_by_tex("Integration", PURPLE)
        dertext.set_color_by_tex("Differentiation", RED)

        func1g = self.get_graph(self.func1, self.function_color)
        func1g2 = self.get_graph(self.func1, self.function_color)
        func1derg = self.get_graph(self.func1der, color = RED)
        func1intg = self.get_graph(self.func1int, color = PURPLE)

        equa1 = TexMobject("f(x) = x^{3}+2x^{2}+3")
        equa1der = TexMobject("f'(x) = 3x^{2}+4x")
        equa2 = TexMobject("f(x) = x^{3}+2x^{2}+3")
        equa2int = TexMobject("F(x) = \\frac{x^{4}}{4}+\\frac{2x^{3}}{3}+3x+C")
        
        caltext.move_to(3*UP)
        intext.move_to(2*UP + 4.5*RIGHT)
        dertext.move_to(2*UP + 5*LEFT)
        equa1.move_to(5*LEFT)
        equa1der.move_to(5*LEFT)
        equa2.move_to(4.5*RIGHT)
        equa2int.move_to(4.5*RIGHT)

        self.play(ShowCreation(caltext))
        self.wait(1)
        self.play(ShowCreation(intext), ShowCreation(dertext))
        self.play(ShowCreation(equa1), ShowCreation(equa2), ShowCreation(func1g), ShowCreation(func1g2))
        self.wait(1)
        self.play(Transform(equa1, equa1der), Transform(equa2, equa2int), Transform(func1g, func1derg), Transform(func1g2, func1intg))
        self.wait(1)
        self.play(FadeOut(dertext), FadeOut(equa1), FadeOut(caltext), FadeOut(func1g))
        self.wait(1)
        self.play(ApplyMethod(intext.move_to, 3*UP), FadeOut(equa2), FadeOut(caltext))
        self.wait(1)`

And this is my code. Sorry if it looks messy, I'm very new and I'm sort of rushing to have this finished as a project.

**Comment by SushiSalad** [comment]
Nevermind, I'm an idiot. I just changed the x domain and it worked fine.

**Comment by 3b1b** [comment]
As a note, I view GraphScene right now as generally being a mess in need of fixing.
