### ISSUE TITLE
how to move an end point of a line and animate

### ISSUE THREAD

**Issue by chuck1** [3b1b/manim#46]
What are the different ways you could move one end point of a Line and animate it?
The only way I know of so far is to construct a new Line object with the desired points and Transform between them. But is there a proper way to do this without constructing a new Line object?

**Comment by 3b1b** [comment]
I typically use the Line.put_start_and_end_on method.  So you could write
self.play(line.put_start_and_end_on, line.get_start(), DESIRED_END_POINT)

**Comment by chuck1** [comment]
excellent! thank you!
