### ISSUE TITLE
I want to use \textsf{} but failed

### ISSUE THREAD

**Issue by xy-23** [3b1b/manim#461]
from big_ol_pile_of_manim_imports import *

class WriteStuff(Scene):
    def construct(self):
        example_tex = TexMobject(
            "\\textsf{print(`Hello, world!')}",
            tex_to_color_map={"print": YELLOW, "`Hello, world!'": ORANGE}
        )

        self.play(Write(example_tex))
        self.wait()

Traceback (most recent call last):
  File "C:\Users\xy\Desktop\manim\manimlib\extract_scene.py", line 153, in main
    scene = SceneClass(**scene_kwargs)
  File "C:\Users\xy\Desktop\manim\manimlib\scene\scene.py", line 52, in __init__
    self.construct()
  File "c:\Users\xy\Desktop\manim\test_text.py", line 18, in construct
    self.play(Write(example_tex))
  File "C:\Users\xy\Desktop\manim\manimlib\scene\scene.py", line 404, in wrapper
    func(self, *args, **kwargs)
  File "C:\Users\xy\Desktop\manim\manimlib\scene\scene.py", line 460, in play
    self.begin_animations(animations)
  File "C:\Users\xy\Desktop\manim\manimlib\scene\scene.py", line 413, in begin_animations
    animation.begin()
  File "C:\Users\xy\Desktop\manim\manimlib\animation\creation.py", line 62, in begin
    super().begin()
  File "C:\Users\xy\Desktop\manim\manimlib\animation\animation.py", line 54, in begin
    self.interpolate(0)
  File "C:\Users\xy\Desktop\manim\manimlib\animation\animation.py", line 111, in interpolate
    self.interpolate_mobject(self.rate_func(alpha))
  File "C:\Users\xy\Desktop\manim\manimlib\animation\animation.py", line 124, in interpolate_mobject
    self.interpolate_submobject(*mobs, sub_alpha)
  File "C:\Users\xy\Desktop\manim\manimlib\animation\creation.py", line 87, in interpolate_submobject
    outline, 0, subalpha
  File "C:\Users\xy\Desktop\manim\manimlib\mobject\types\vectorized_mobject.py", line 835, in pointwise_become_partial
    bezier_quads[lower_index],
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by xy-23** [comment]
Oops
`from big_ol_pile_of_manim_imports import *


class WriteStuff(Scene):
    def construct(self):
        example_tex = TexMobject(
            "\\textsf{print(`Hello, world!')}",
            tex_to_color_map={"print": YELLOW, "`Hello, world!'": ORANGE}
        )

        self.play(Write(example_tex))
        self.wait()`

**Comment by xy-23** [comment]
`from big_ol_pile_of_manim_imports import *


class WriteStuff(Scene):
    def construct(self):
        example_tex = TexMobject(
            "\\textsf{print(`Hello, world!')}",
            tex_to_color_map={"print": YELLOW, "`Hello, world!'": ORANGE}
        )

        self.play(Write(example_tex))
        self.wait()`

**Comment by xy-23** [comment]
Oops
```
from big_ol_pile_of_manim_imports import *


class WriteStuff(Scene):
    def construct(self):
        example_tex = TexMobject(
            "\\textsf{print(`Hello, world!')}",
            tex_to_color_map={"print": YELLOW, "`Hello, world!'": ORANGE}
        )

        self.play(Write(example_tex))
        self.wait()
```

**Comment by xy-23** [comment]
Seems like the problem is `tex_to_color_map={"print": YELLOW, "`Hello, world!'": ORANGE}`.
If I comment out it , it will works.

**Comment by xy-23** [comment]
Seems like the problem is ```tex_to_color_map={"print": YELLOW, "`Hello, world!'": ORANGE}```.
If I comment out it , it will works

**Comment by Elteoremadebeethoven** [comment]
Manim is going through an update process, so many of its functions are not longer as they were before and therefore should be rewritten.
The version:
https://github.com/3b1b/manim/tree/3b088b12843b7a4459fe71eba96b70edafb7aa78
Is the most stable.

I proved your code and it works in it:
![writestuff2](https://user-images.githubusercontent.com/43224662/53681853-d5304100-3cb4-11e9-84a4-9677800e9879.png)

Or if you want to use the most recent version you can prove:
```python3
class WriteStuff(Scene):
    def construct(self):
        example_tex = TexMobject(
            "{\\sf print}{\\sf (}\\textsf{`Hello, world!'}{\\sf )}",
            tex_to_color_map={"{\\sf print}": YELLOW, "\\textsf{`Hello, world!'}": ORANGE}
        )

        self.play(Write(example_tex))
        self.wait()
```
![writestuff2](https://user-images.githubusercontent.com/43224662/53681884-4c65d500-3cb5-11e9-9604-f7f5ab2e75a4.png)

**Comment by xy-23** [comment]
> Manim is going through an update process, so many of its functions are not longer as they were before and therefore should be rewritten.
> The version:
> https://github.com/3b1b/manim/tree/3b088b12843b7a4459fe71eba96b70edafb7aa78
> Is the most stable.
> 
> I proved your code and it works in it:
> ![writestuff2](https://user-images.githubusercontent.com/43224662/53681853-d5304100-3cb4-11e9-84a4-9677800e9879.png)
> 
> Or if you want to use the most recent version you can prove:
> 
> ```python
> class WriteStuff(Scene):
>     def construct(self):
>         example_tex = TexMobject(
>             "{\\sf print}{\\sf (}\\textsf{`Hello, world!'}{\\sf )}",
>             tex_to_color_map={"{\\sf print}": YELLOW, "\\textsf{`Hello, world!'}": ORANGE}
>         )
> 
>         self.play(Write(example_tex))
>         self.wait()
> ```
> 
> ![writestuff2](https://user-images.githubusercontent.com/43224662/53681884-4c65d500-3cb5-11e9-9604-f7f5ab2e75a4.png)
It works, thanks.
