### ISSUE TITLE
Cannot open include file io.h

### ISSUE THREAD

**Issue by FireChaos** [3b1b/manim#462]
Greetings,

I've been getting other errors before, and they told me to install Visual Studio 14 C++ tools, and I did.
Then I also installed Win10SDK and Python for Visual Studio as well, but nothing worked. 
Mentioning this because I see mentions of VS in the error message

I am trying the Direct install method from Git, on Windows 10. I am not certain if I have installed the cairo library as well.

Thanks in advance.

> Collecting pycairo==1.17.1 (from -r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/68/76/340ff847897296b2c8174dfa5a5ec3406e3ed783a2abac918cf326abad86/pycairo-1.17.1.tar.gz
Collecting pydub==0.23.0 (from -r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/2f/73/bb9c093882d647437a9e6e87c7e6592d2df852f83ffac6f348b878979be0/pydub-0.23.0-py2.py3-none-any.whl
Installing collected packages: pycairo, pydub
  Running setup.py install for pycairo: started
    Running setup.py install for pycairo: finished with status 'error'
    Complete output from command C:\Users\Entropy\AppData\Local\Programs\Python\Python37\python3.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Entropy\\AppData\\Local\\Temp\\pip-install-vsjln7hx\\pycairo\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Entropy\AppData\Local\Temp\pip-record-l6ol5dez\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\cairo
    copying cairo\__init__.py -> build\lib.win-amd64-3.7\cairo
    copying cairo\__init__.pyi -> build\lib.win-amd64-3.7\cairo
    copying cairo\py.typed -> build\lib.win-amd64-3.7\cairo
    running build_ext
    building 'cairo._cairo' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\cairo
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPYCAIRO_VERSION_MAJOR=1 -DPYCAIRO_VERSION_MINOR=17 -DPYCAIRO_VERSION_MICRO=1 -IC:\Users\Entropy\AppData\Local\Programs\Python\Python37\include -IC:\Users\Entropy\AppData\Local\Programs\Python\Python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include" /Tccairo/device.c /Fobuild\temp.win-amd64-3.7\Release\cairo/device.obj
    device.c
    c:\users\entropy\appdata\local\programs\python\python37\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
Command "C:\Users\Entropy\AppData\Local\Programs\Python\Python37\python3.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Entropy\\AppData\\Local\\Temp\\pip-install-vsjln7hx\\pycairo\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Entropy\AppData\Local\Temp\pip-record-l6ol5dez\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Entropy\AppData\Local\Temp\pip-install-vsjln7hx\pycairo\

**Comment by FireChaos** [comment]
I'm getting a similar error but this time it mentions how the cairo.h file is missing. It seems that I haven't installed it correctly, what should I do?

Error:

> Collecting pycairo==1.17.1 (from -r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/68/76/340ff847897296b2c8174dfa5a5ec3406e3ed783a2abac918cf326abad86/pycairo-1.17.1.tar.gz
Collecting pydub==0.23.0 (from -r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/2f/73/bb9c093882d647437a9e6e87c7e6592d2df852f83ffac6f348b878979be0/pydub-0.23.0-py2.py3-none-any.whl
Installing collected packages: pycairo, pydub
  Running setup.py install for pycairo: started
    Running setup.py install for pycairo: finished with status 'error'
    Complete output from command C:\Users\Entropy\AppData\Local\Programs\Python\Python37\python3.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Entropy\\AppData\\Local\\Temp\\pip-install-4kglqdbi\\pycairo\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Entropy\AppData\Local\Temp\pip-record-3xiet1x1\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\cairo
    copying cairo\__init__.py -> build\lib.win-amd64-3.7\cairo
    copying cairo\__init__.pyi -> build\lib.win-amd64-3.7\cairo
    copying cairo\py.typed -> build\lib.win-amd64-3.7\cairo
    running build_ext
    building 'cairo._cairo' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\cairo
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPYCAIRO_VERSION_MAJOR=1 -DPYCAIRO_VERSION_MINOR=17 -DPYCAIRO_VERSION_MICRO=1 -IC:\Users\Entropy\AppData\Local\Programs\Python\Python37\include -IC:\Users\Entropy\AppData\Local\Programs\Python\Python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /Tccairo/device.c /Fobuild\temp.win-amd64-3.7\Release\cairo/device.obj
    device.c
    c:\users\entropy\appdata\local\temp\pip-install-4kglqdbi\pycairo\cairo\pycairo.h(37): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
Command "C:\Users\Entropy\AppData\Local\Programs\Python\Python37\python3.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Entropy\\AppData\\Local\\Temp\\pip-install-4kglqdbi\\pycairo\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Entropy\AppData\Local\Temp\pip-record-3xiet1x1\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Entropy\AppData\Local\Temp\pip-install-4kglqdbi\pycairo\

**Comment by liyiliuxingyu** [comment]
http://www.lfd.uci.edu/~gohlke/pythonlibs/#pycairo
install it. all things will be done.

**Comment by FireChaos** [comment]
Good workaround. Thanks!
