### ISSUE TITLE
Docker example run: No module named 'deprecated'

### ISSUE THREAD

**Issue by FireChaos** [3b1b/manim#463]
Hello. I tried installing manim using Docker, but when running the example I'm getting this error:

![screenshot_1](https://user-images.githubusercontent.com/7671689/53698900-46721000-3deb-11e9-8077-5c827f69ecf1.png)

I've pulled and cloned a remote repo, and no errors showed up. Am I doing something wrong?

**Comment by eulertour** [comment]
Sorry about this, the docker instructions specified an old version of manim before 03e832af45e16bd0f6d7d8d45739384c22044f3f was committed.

**Comment by FireChaos** [comment]
> 
> 
> Sorry about this, the docker instructions specified an old version of manim before [03e832a](https://github.com/3b1b/manim/commit/03e832af45e16bd0f6d7d8d45739384c22044f3f) was committed.

So, what does this mean? What do I have to do to get it working? Will the module be included in the docker image soon?

**Comment by FireChaos** [comment]
For now, using `pip3 install deprecated` fixed the issue.

**Comment by eulertour** [comment]
Sorry I missed this, I meant that the instructions pointed to an old version of manim, and that one required the deprecated module. I've updated the instructions now.
