### ISSUE TITLE
Does anyone know if its possible to use different fonts and how to do it?

### ISSUE THREAD

**Issue by jaddoescad** [3b1b/manim#471]

**Comment by Elteoremadebeethoven** [comment]
In manimlib/tex_template.tex you can add new fonts of LaTeX, browse [here](http://www.tug.dk/FontCatalogue/), or you can add a personalize font like [this[(https://github.com/3b1b/manim/issues/329).

**Comment by jaddoescad** [comment]
Thank you!

**Comment by Elteoremadebeethoven** [comment]
#471
