### ISSUE TITLE
Error on create Matrix()

### ISSUE THREAD

**Issue by Incubator4th** [3b1b/manim#472]
Cannot create Matrix Object
This is the code:
```
class test(Scene):
    def construct(self):
        matrix = Matrix(["1","0"])
        self.play(ShowCreation(matrix))
        self.wait()
```
Then run the script and get output:
```
Traceback (most recent call last):
  File "E:\manim-master\manimlib\extract_scene.py", line 153, in main
    scene = SceneClass(**scene_kwargs)
  File "E:\manim-master\manimlib\scene\scene.py", line 52, in __init__
    self.construct()
  File "example_scenes.py", line 94, in construct
    matrix = Matrix(["1","0"])
  File "E:\manim-master\manimlib\mobject\matrix.py", line 77, in __init__
    self.add_brackets()
  File "E:\manim-master\manimlib\mobject\matrix.py", line 105, in add_brackets
    l_bracket, r_bracket = bracket_pair.split()
ValueError: not enough values to unpack (expected 2, got 1)
```
Specially，I saw the source code
file on matrix.py
```
    def add_brackets(self):
        bracket_pair = TexMobject("\\big[ \\big]")
        bracket_pair.scale(2)
        bracket_pair.stretch_to_fit_height(self.get_height() + 0.5)
        l_bracket, r_bracket = bracket_pair.split()
        l_bracket.next_to(self, LEFT)
        r_bracket.next_to(self, RIGHT)
        self.add(l_bracket, r_bracket)
        self.brackets = VGroup(l_bracket, r_bracket)
        return self
```
file on mobject.py
```
    def split(self):
        result = [self] if len(self.points + 1) > 0 else []
        return result + self.submobjects
```
Maybe these has some problem,but I cannot fix it.

**Comment by 3b1b** [comment]
Ah, I think it assumes the input will be a 2d array, e.g. Matrix([["1","0"]]).

This seems fixable with the right "reshape" statement somewhere...

**Comment by Incubator4th** [comment]
> Ah, I think it assumes the input will be a 2d array, e.g. Matrix([["1","0"]]).
> 
> This seems fixable with the right "reshape" statement somewhere...

Thanks for you reply.But in that case,the error happens again.I tried some ways to show the matrix,and only write the text in latex such as `r"\begin{pmatrix} a&b\\c&d \end{pmatrix}\quad"`, it could display the matrix.
And i saw that in examples,they were also defined by you,like
```
v = Matrix(["v_1", "v_2", "v_3"])
w = Matrix(["w_1", "w_2", "w_3"])
```
in example8p2.py

And I try different OS(windows 10 and linux),the error would still happen

**Comment by 3b1b** [comment]
Ah, sorry, the problem was with a recent change to TexMobject.  I just pushed a fix.

**Comment by Incubator4th** [comment]
> Ah, sorry, the problem was with a recent change to TexMobject. I just pushed a fix.

No need for apologize,I am happy to find  bug and be a volunteer tester.

**Comment by niyiyu2316** [comment]
> > Ah, sorry, the problem was with a recent change to TexMobject. I just pushed a fix.
> 
> No need for apologize,I am happy to find bug and be a volunteer tester.

I've solved this problem~ There is just a problem to map the strip to split_list with numpy.int64.
In file /manim/manimlib/mobject/svg/tex_mobject.py, about line 159 I think,
change
`split_list = list(map(str.strip, split_list)) 
`
to
`split_list = [str(x).strip() for x in split_list]
`
