### ISSUE TITLE
Problem installing manim : Pycairo wheel

### ISSUE THREAD

**Issue by Pyke75** [3b1b/manim#476]
Hello to all, 

I have tried to follow the steps proposed by bhowell4 to install Manim for Mac users (http://bhowell4.com/manic-install-tutorial-for-mac/) but I have a problem installing Pycairo. 

I have the following error message : 
Collecting pycairo
Using cached https://files.pythonhosted.org/packages/a6/54/23d6cf3e8d8f1eb30e0e58f171b6f62b2ea75c024935492373639a1a08e4/pycairo-1.18.0.tar.gz
Building wheels for collected packages: pycairo
Building wheel for pycairo (setup.py) … error
Complete output from command /Users/cusset/Animation/manim/venv/bin/python -u -c “import setuptools, tokenize;__file__=’/private/var/folders/2s/v1d3n29s77db0590732lvcgr0000gn/T/pip-install-e0qeh4zm/pycairo/setup.py’;f=getattr(tokenize, ‘open’, open)(__file__);code=f.read().replace(‘\r\n’, ‘\n’);f.close();exec(compile(code, __file__, ‘exec’))” bdist_wheel -d /private/var/folders/2s/v1d3n29s77db0590732lvcgr0000gn/T/pip-wheel-96i_cait –python-tag cp37:
running bdist_wheel
running build
running build_py
creating build
creating build/lib.macosx-10.7-x86_64-3.7
creating build/lib.macosx-10.7-x86_64-3.7/cairo
copying cairo/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/cairo
copying cairo/__init__.pyi -> build/lib.macosx-10.7-x86_64-3.7/cairo
copying cairo/py.typed -> build/lib.macosx-10.7-x86_64-3.7/cairo
running build_ext
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc’
to the PKG_CONFIG_PATH environment variable
Package ‘libffi’, required by ‘gobject-2.0’, not found
Command ‘[‘pkg-config’, ‘–print-errors’, ‘–exists’, ‘cairo >= 1.13.1′]’ returned non-zero exit status 1._

The error message suggests the I add the directory containing `libffi.pc’
to the PKG_CONFIG_PATH environment variable, but I don't know how to to that (where is this variable ?)

Thanks in advance for any help !

**Comment by Kirkmanamos** [comment]
https://github.com/lovell/sharp/issues/1603#issuecomment-471767376

This worked for me.

**Comment by Pyke75** [comment]
It wooooorked ! Thank you sooo much !!
