### ISSUE TITLE
cairo.h not installing correctly on windows 10 64-bit anaconda

### ISSUE THREAD

**Issue by tjf801** [3b1b/manim#480]
Hi, I am trying to install the requirements.txt but it keeps coming back with an error "Failed building wheel for pycairo". if anyone could help that would be great.

Here is the log:
(manim37) C:\Users\Tyler\Desktop\manim>pip install -r requirements.txt
Requirement already satisfied: argparse==1.4.0 in c:\users\tyler\anaconda3\envs\manim37\lib\site-packages (from -r requirements.txt (line 1)) (1.4.0)
Requirement already satisfied: colour==0.1.5 in c:\users\tyler\anaconda3\envs\manim37\lib\site-packages (from -r requirements.txt (line 2)) (0.1.5)
Requirement already satisfied: numpy==1.15.0 in c:\users\tyler\anaconda3\envs\manim37\lib\site-packages (from -r requirements.txt (line 3)) (1.15.0)
Requirement already satisfied: Pillow==5.2.0 in c:\users\tyler\anaconda3\envs\manim37\lib\site-packages (from -r requirements.txt (line 4)) (5.2.0)
Requirement already satisfied: progressbar==2.5 in c:\users\tyler\anaconda3\envs\manim37\lib\site-packages (from -r requirements.txt (line 5)) (2.5)
Requirement already satisfied: scipy==1.1.0 in c:\users\tyler\anaconda3\envs\manim37\lib\site-packages (from -r requirements.txt (line 6)) (1.1.0)
Requirement already satisfied: tqdm==4.24.0 in c:\users\tyler\anaconda3\envs\manim37\lib\site-packages (from -r requirements.txt (line 7)) (4.24.0)
Requirement already satisfied: opencv-python==3.4.2.17 in c:\users\tyler\anaconda3\envs\manim37\lib\site-packages (from -r requirements.txt (line 8)) (3.4.2.17)
Collecting pycairo==1.17.1 (from -r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/68/76/340ff847897296b2c8174dfa5a5ec3406e3ed783a2abac918cf326abad86/pycairo-1.17.1.tar.gz
Collecting pydub==0.23.0 (from -r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/2f/73/bb9c093882d647437a9e6e87c7e6592d2df852f83ffac6f348b878979be0/pydub-0.23.0-py2.py3-none-any.whl
Building wheels for collected packages: pycairo
  Building wheel for pycairo (setup.py) ... error
  Complete output from command C:\Users\Tyler\Anaconda3\envs\manim37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Tyler\\AppData\\Local\\Temp\\pip-install-qpkhwnw5\\pycairo\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\Tyler\AppData\Local\Temp\pip-wheel-2nurtyqi --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\cairo
  copying cairo\__init__.py -> build\lib.win-amd64-3.7\cairo
  copying cairo\__init__.pyi -> build\lib.win-amd64-3.7\cairo
  copying cairo\py.typed -> build\lib.win-amd64-3.7\cairo
  running build_ext
  building 'cairo._cairo' extension
  creating build\temp.win-amd64-3.7
  creating build\temp.win-amd64-3.7\Release
  creating build\temp.win-amd64-3.7\Release\cairo
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPYCAIRO_VERSION_MAJOR=1 -DPYCAIRO_VERSION_MINOR=17 -DPYCAIRO_VERSION_MICRO=1 -IC:\Users\Tyler\Anaconda3\envs\manim37\include -IC:\Users\Tyler\Anaconda3\envs\manim37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /Tccairo/device.c /Fobuild\temp.win-amd64-3.7\Release\cairo/device.obj
  device.c
  c:\users\tyler\appdata\local\temp\pip-install-qpkhwnw5\pycairo\cairo\pycairo.h(37): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for pycairo
  Running setup.py clean for pycairo
Failed to build pycairo
Installing collected packages: pycairo, pydub
  Found existing installation: pycairo 1.18.0
    Uninstalling pycairo-1.18.0:
      Successfully uninstalled pycairo-1.18.0
  Running setup.py install for pycairo ... error
    Complete output from command C:\Users\Tyler\Anaconda3\envs\manim37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Tyler\\AppData\\Local\\Temp\\pip-install-qpkhwnw5\\pycairo\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Tyler\AppData\Local\Temp\pip-record-r0sd1t7n\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\cairo
    copying cairo\__init__.py -> build\lib.win-amd64-3.7\cairo
    copying cairo\__init__.pyi -> build\lib.win-amd64-3.7\cairo
    copying cairo\py.typed -> build\lib.win-amd64-3.7\cairo
    running build_ext
    building 'cairo._cairo' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\cairo
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPYCAIRO_VERSION_MAJOR=1 -DPYCAIRO_VERSION_MINOR=17 -DPYCAIRO_VERSION_MICRO=1 -IC:\Users\Tyler\Anaconda3\envs\manim37\include -IC:\Users\Tyler\Anaconda3\envs\manim37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /Tccairo/device.c /Fobuild\temp.win-amd64-3.7\Release\cairo/device.obj
    device.c
    c:\users\tyler\appdata\local\temp\pip-install-qpkhwnw5\pycairo\cairo\pycairo.h(37): fatal error C1083: Cannot open include file: 'cairo.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

    ----------------------------------------
  Rolling back uninstall of pycairo
  Moving to c:\users\tyler\anaconda3\envs\manim37\lib\site-packages\cairo\
   from c:\users\tyler\anaconda3\envs\manim37\lib\site-packages\~airo
  Moving to c:\users\tyler\anaconda3\envs\manim37\lib\site-packages\pycairo-1.18.0.dist-info\
   from c:\users\tyler\anaconda3\envs\manim37\lib\site-packages\~ycairo-1.18.0.dist-info
Command "C:\Users\Tyler\Anaconda3\envs\manim37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Tyler\\AppData\\Local\\Temp\\pip-install-qpkhwnw5\\pycairo\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Tyler\AppData\Local\Temp\pip-record-r0sd1t7n\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Tyler\AppData\Local\Temp\pip-install-qpkhwnw5\pycairo\

**Comment by Elteoremadebeethoven** [comment]
https://www.reddit.com/r/3Blue1Brown/comments/b1porr/how_to_run_manim_on_windowsguide/

**Comment by tjf801** [comment]
I just tried that, still saying "no module named cairo"…

log:

(manim37) C:\Users\Tyler\Desktop\manim>py -m manim example_scenes.py SquareToCircle.py -pl
Media will be stored in media\. You can change this behavior by writing a different directory to media_dir.txt.
Traceback (most recent call last):
  File "C:\Users\Tyler\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Tyler\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Tyler\Desktop\manim\manim.py", line 3, in <module>
    import manimlib.extract_scene
  File "C:\Users\Tyler\Desktop\manim\manimlib\extract_scene.py", line 9, in <module>
    from manimlib.scene.scene import Scene
  File "C:\Users\Tyler\Desktop\manim\manimlib\scene\scene.py", line 11, in <module>
    from manimlib.camera.camera import Camera
  File "C:\Users\Tyler\Desktop\manim\manimlib\camera\camera.py", line 9, in <module>
    import cairo
ModuleNotFoundError: No module named 'cairo'

**Comment by Elteoremadebeethoven** [comment]
Don't use virtualenv (manim37)

**Comment by tjf801** [comment]
kind of a noob talking here, but what is that, and how would I not use it?

**Comment by Elteoremadebeethoven** [comment]
Disable the manim37 and install pycairo with .whl like here
https://www.reddit.com/r/3Blue1Brown/comments/b1porr/how_to_run_manim_on_windowsguide/

**Comment by tjf801** [comment]
yeah. that's what I tried to do.

**Comment by Elteoremadebeethoven** [comment]
Show the images please.

**Comment by tjf801** [comment]
actually, just fixed it. it worked when I used "pip install [filename]" instead of "py -m pip install [filename]". Don't ask me why that works though.
