### ISSUE TITLE
Is there a method for creating an arrow between 2 mobjects ? 

### ISSUE THREAD

**Issue by BenBausch** [3b1b/manim#482]
I tried using set_start_and_end_attrs(mobject1, mobject2), but it did not work ? Is there an other method for achieving this ? Thanks.

**Comment by 3b1b** [comment]
If you write Arrow(mobject1, mobject2), that should give what you want.

**Comment by BenBausch** [comment]
Okay, thank you very much for the fast answer.

**Comment by vikramsingh111** [comment]
ya Ben but arrow tip is not meeting to the exact point.
        dot1 = Dot(RIGHT+UP)
        self.add(dot1)
        dot2 = Dot(ORIGIN)
        self.add(dot2)
        line = Arrow(dot1,dot2)
        self.play(ShowCreation(line)

**Comment by Tony031218** [comment]
@vikramsingh111 `buff=0`
that is `line = Arrow(dot1, dot2, buff=0)`

**Comment by vikramsingh111** [comment]
Wow! It's work.  Thanks Tony.

**Comment by vikramsingh111** [comment]
from manimlib.imports import *

class ThreeDObjects(SpecialThreeDScene):
    def construct(self):
        axes = ThreeDAxes()
        circle=Arrow((0,0,0),(0,0,1),buff=0,color=BLUE)
        self.set_camera_orientation(phi=45 * DEGREES)
        #self.set_camera_orientation(phi=0 * DEGREES)
        self.play(ShowCreation(axes))
        self.wait()
        self.play(GrowArrow(circle))
        self.wait(3)
Arrow tip on z-axis is not showing properly. However it works for x and y axis.
