### ISSUE TITLE
How to write a question mixed with TextMobject and TexMobject

### ISSUE THREAD

**Issue by quoyon** [3b1b/manim#484]
Hi, I am new to manim.
I met with a problem when trying to write a loooooooong description of a question, mixed with TextMobject and TexMobject. If it is a long question with a TextMobject, it can change lines automatically and properly. But if I put the description into a VGroup, it will not change lines. I tried "arrange(DOWN)", and it did change lines when had written a TextMobject or TexMobject, but looked fragmented. 
So I had to cut off the sentences manually then made a VGroup of each line. It was solved but in a complicated way. Is there any simple solutions?

**Comment by 3b1b** [comment]
Make it a TextMobect, but use "$" inline as needed.

For example, TextMobject("What is $x^2 - 1$ in this case?").

Or if you want them treated as separate parts, TextMobject("What is", "$x^2 - 1$", "in this case?")

**Comment by quoyon** [comment]
thanks! It helps a lot!
