### ISSUE TITLE
Trouble installing manim(Unknown encoder 'libx264' & BrokenPipeError: [Errno 32])

### ISSUE THREAD

**Issue by soyeb-jim285** [3b1b/manim#492]
I am new to Linux. Currently using Ubuntu 18.04.2 in my system. after installing  cairo,
ffmpeg and sox. i copied this code in may terminal. 
`~$ sh`
`$ sh`
`git clone https://github.com/3b1b/manim.git`
`cd manim`
`python3 -m pip install -r requirements.txt
python3 -m manim example_scenes.py 
 SquareToCircle -pl`

but it isn't working work. It is giving BrokenPipeError:[Error 32] broken pipe and also unknown encoder 'libx264'
![Screenshot from 2019-04-07 23-14-31](https://user-images.githubusercontent.com/38866970/55687115-10e0b980-598b-11e9-9473-e19d873831aa.png)
![Screenshot from 2019-04-07 23-14-54](https://user-images.githubusercontent.com/38866970/55687116-15a56d80-598b-11e9-8486-5b961c500417.png)
![Screenshot from 2019-04-07 11-09-34](https://user-images.githubusercontent.com/38866970/55679039-c5e08b00-5925-11e9-8d78-b79f10a012d6.png)

**Comment by Skirmsiher** [comment]
I had the same issue, and could not resolve it.
However, I had a different issue with ffmpeg on another project, reinstalling ffmpeg with the following command resolved both issues.

`conda install -c conda-forge ffmpeg`

Hope this will help :)

**Comment by soyeb-jim285** [comment]
Thank you very much!the issue is now fixed :D

**Comment by Skirmsiher** [comment]
Next to the "comment" button, you have "Close issue", just click on it

**Comment by jsuarez314** [comment]
It works for me

`conda install x264=='1!152.20180717' ffmpeg=4.0.2 -c conda-forge`

**Comment by Dowlatabadi** [comment]
you need to compile ffmpeg whith appropriate header along side other needed headers for example:
./configure --enable-nonfree --enable-gpl  --enable-libnpp --enable-libx264 
Then you can make and install
gl

**Comment by Diraw** [comment]
I successfully solved the problem until using this code
`conda install x264 ffmpeg -c conda-forge`
