### ISSUE TITLE
Specify center of a circle

### ISSUE THREAD

**Issue by soyeb-jim285** [3b1b/manim#499]
I want to specify the center point of a circle. but unable to. Here is a the code. I want to include another circle with radius=1.25 and center at [0.75,-0.5,0].   
How can I do this? 
Or if I can draw a circle with three non-linear points?
Thanks in advance :) 

       from big_ol_pile_of_manim_imports import *
       class Shapes(Scene):
       def construct(self):
        circle = Circle(
            radius = 2.5,
        )

        triangle = Polygon(
            np.array([1.5, 2, 0]),
            np.array([-2, -1.5, 0]),
            np.array([2, -1.5, 0]),
        )

        altitutea = Line(
            np.array([1.5, 2, 0]),
            np.array([1.5, -1.5, 0]),
        )

        altituteb = Line(
            np.array([2, -1.5, 0]),
            np.array([0, 0.5, 0]),
        )
        altitutec = Line(
            np.array([-2, -1.5, 0]),
            np.array([1.92, -0.94, 0]),
        )
        pointa = Dot(
            [1.5, 2, 0],
        )
        pointb = Dot(
            [-2, -1.5, 0],
        )
        pointc = Dot(
            [2, -1.5, 0],
        )
        self.play(ShowCreation(triangle))
        self.play(FadeIn(circle))
        self.play(ShowCreation(altitutea), ShowCreation(altituteb), ShowCreation(altitutec))
        self.play(FadeIn(pointa),FadeIn(pointb),FadeIn(pointc))
`

**Comment by 3b1b** [comment]
You can call circle.move_to(point) to put it at a given place.

Or, on initialization, you could add a parameter "arc_center"

**Comment by 3b1b** [comment]
You can call circle.move_to(point) to put it at a given place.

Or, on initialization, you could add a parameter "arc_center"

**Comment by 3b1b** [comment]
You can call circle.move_to(point) to put it at a given place.

Or, on initialization, you could add a parameter "arc_center"

**Comment by soyeb-jim285** [comment]
Thank you very much:)

**Comment by soyeb-jim285** [comment]
How can I draw circumcircle of a triangle ? Is there any dedicated command?

**Comment by 3b1b** [comment]
No such command exists right now.  You could implement it yourself, doing the math to write the inradius and the center

**Comment by soyeb-jim285** [comment]
Thanks for the help & manim is really awesome! <3
