### ISSUE TITLE
Permission Denied to aggdraw.so

### ISSUE THREAD

**Issue by kellybrower** [3b1b/manim#5]
Here was the text in Terminal

`~``kbrower$ cd $TMPDIR
T kbrower$ git clone https://github.com/scottopell/aggdraw-64bits
fatal: destination path 'aggdraw-64bits' already exists and is not an empty directory.
T kbrower$ cd aggdraw-64bits
aggdraw-64bits kbrower$ /usr/local/bin/python setup.py build_ext -i
-bash: /usr/local/bin/python: No such file or directory
aggdraw-64bits kbrower$ python setup.py build_ext -i
=== freetype support disabled
running build_ext
Kellys-MacBook-Pro:aggdraw-64bits kbrower$ python setup.py install
=== freetype support disabled
running install
running build
running build_ext
running install_lib
copying build/lib.macosx-10.11-intel-2.7/aggdraw.so -> /Library/Python/2.7/site-packages
error: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/aggdraw.so'
aggdraw-64bits``kbrower$`

Please help?

**Comment by shantanu69** [comment]
I think you just have to do `sudo python setup.py install` at the last line :smiley:

**Comment by kellybeach** [comment]
@shantanu69 

Thanks!

Not exactly sure what this does, but it certainly yielded a different result, loading the content with many `warning` written.

Now my issue is getting `pip -r requirements.txt` to install.

**Comment by shantanu69** [comment]
@kellybeach What are the errors and warnings?
and you might need to `sudo` here as well, also remove the first line of `requirements.txt`

**Comment by eulertour** [comment]
Closing, as this issue is very old and inactive.
