### ISSUE TITLE
Aggdraw Installation not working

### ISSUE THREAD

**Issue by aagarwal1999** [3b1b/manim#50]
Hey, so I'm trying to install the manim engine requirements but whenever I try, it always throws the following error for the aggdraw package: 

Collecting aggdraw from git+https://github.com/scottopell/aggdraw-64bits@c95aac4369038706943fd0effb7d888683860e5a#egg=aggdraw (from -r requirements.txt (line 7))
  Cloning https://github.com/scottopell/aggdraw-64bits (to c95aac4369038706943fd0effb7d888683860e5a) to c:\users\user\appdata\local\temp\pip-build-erhnfr\aggdraw
  Error [Error 2] The system cannot find the file specified while executing command git clone -q https://github.com/scottopell/aggdraw-64bits c:\users\user\appdata\local\temp\pip-build-erhnfr\aggdraw
Cannot find command 'git'

**Comment by ddxtanx** [comment]
You have git installed on your local machine, right?

**Comment by eulertour** [comment]
Closing, since this issue seems to be resolved.
