### ISSUE TITLE
Objects overlapping text 

### ISSUE THREAD

**Issue by giovablackops98** [3b1b/manim#503]
How do I set the "level" of an object, so that it always stays in front?
I have a title on a black background (here red to highlight the effect) that is written before the numberplane is generated:

```
        title = TextMobject("Applying the cartesian product to two points of a R2 plane")
        title.add_background_rectangle(color=RED, opacity=1)
        title.to_edge(UP)

        grid = NumberPlane()
        grid.scale(0.5)

        self.play(
            Write(title),
            ShowCreation(grid, run_time=3, lag_ratio=0.1)
        )
        self.wait()
```

When run, the numberplane overlaps with the text, but i would like for it to stay in the background.
![Capture](https://user-images.githubusercontent.com/49610943/56092332-37d34a00-5ebb-11e9-9277-5a48ff35481d.PNG)
If the text is generated after the plane, then the text is in front (like for the A and B text). Is there a "send_to_back" kind of function?
Thanks, and sorry if this is a stupid question

**Comment by Elteoremadebeethoven** [comment]
Check manimlib/scene/scene.py
There are 4 methods:
```python3
self.bring_to_front(mobject) 
self.bring_to_back(mobject)
```
If you wanna put a mobject always in front use:
```python3
self.add_foreground_mobjects(mobjects)
```
And to remove this property use:
```python3
self.remove_foreground_mobjects(mobjects)
```

**Comment by giovablackops98** [comment]
Thanks, I couldn't find the commands. I'll be closing the issue
