### ISSUE TITLE
Exception: Latex error converting to dvi. 

### ISSUE THREAD

**Issue by 562245918** [3b1b/manim#511]
i have some trouble in run WriteStuff . i want to use "TexMobject("Life梦马") " but fail to ...

This is pdfTeX, Version 3.14159265-2.6-1.40.20 (MiKTeX 2.9.7000) (preloaded format=latex 2019.4.26)  26 APR 2019 12:45
entering extended mode
**C:/Users/lenovo/manim/manimlib/files/Tex/84ce4b55d61dc0c1.tex
(C:/Users/lenovo/manim/manimlib/files/Tex/84ce4b55d61dc0c1.tex
LaTeX2e <2018-12-01>
(E:\CTEX\MiKTeX\tex/latex/standalone\standalone.cls
Document Class: standalone 2018/03/26 v1.3a Class to compile TeX sub-files stan
dalone
(E:\CTEX\MiKTeX\tex/latex/tools\shellesc.sty
Package: shellesc 2016/06/07 v0.02a unified shell escape interface for LaTeX
Package shellesc Info: Restricted shell escape enabled on input line 69.
) (E:\CTEX\MiKTeX\tex/generic/oberdiek\ifluatex.sty
Package: ifluatex 2016/05/16 v1.4 Provides the ifluatex switch (HO)
Package ifluatex Info: LuaTeX not detected.
) (E:\CTEX\MiKTeX\tex/generic/oberdiek\ifpdf.sty
Package: ifpdf 2018/09/07 v3.3 Provides the ifpdf switch
) (E:\CTEX\MiKTeX\tex/generic/ifxetex\ifxetex.sty
Package: ifxetex 2010/09/12 v0.6 Provides ifxetex conditional
) (E:\CTEX\MiKTeX\tex/latex/xkeyval\xkeyval.sty
Package: xkeyval 2014/12/03 v2.7a package option processing (HA)
(E:\CTEX\MiKTeX\tex/generic/xkeyval\xkeyval.tex (E:\CTEX\MiKTeX\tex/generic/xke
yval\xkvutils.tex
\XKV@toks=\toks14
\XKV@tempa@toks=\toks15
(E:\CTEX\MiKTeX\tex/generic/xkeyval\keyval.tex))
\XKV@depth=\count80
File: xkeyval.tex 2014/12/03 v2.7a key=value parser (HA)
))
\sa@internal=\count81
\c@sapage=\count82
(E:\CTEX\MiKTeX\tex/latex/standalone\standalone.cfg
File: standalone.cfg 2018/03/26 v1.3a Default configuration file for 'standalon
e' class
) (E:\CTEX\MiKTeX\tex/latex/base\article.cls
Document Class: article 2018/09/03 v1.4i Standard LaTeX document class
(E:\CTEX\MiKTeX\tex/latex/base\size10.clo
File: size10.clo 2018/09/03 v1.4i Standard LaTeX file (size option)
)
\c@part=\count83
\c@section=\count84
\c@subsection=\count85
\c@subsubsection=\count86
\c@paragraph=\count87
\c@subparagraph=\count88
\c@figure=\count89
\c@table=\count90
\abovecaptionskip=\skip41
\belowcaptionskip=\skip42
\bibindent=\dimen102
) (E:\CTEX\MiKTeX\tex/latex/preview\preview.sty
Package: preview 2017/04/24 11.91 (AUCTeX/preview-latex)
(E:\CTEX\MiKTeX\tex/generic/luatex85\luatex85.sty
Package: luatex85 2016/06/15 v1.4 pdftex aliases for luatex
) (E:\CTEX\MiKTeX\tex/latex/preview\prtightpage.def
\PreviewBorder=\dimen103
)
\pr@snippet=\count91
\pr@box=\box27
\pr@output=\toks16
)) (E:\CTEX\MiKTeX\tex/latex/base\inputenc.sty
Package: inputenc 2018/08/11 v1.3c Input encoding file
\inpenc@prehook=\toks17
\inpenc@posthook=\toks18
) (E:\CTEX\MiKTeX\tex/latex/amsmath\amsmath.sty
Package: amsmath 2018/12/01 v2.17b AMS math features
\@mathmargin=\skip43
For additional information on amsmath, use the `?' option.
(E:\CTEX\MiKTeX\tex/latex/amsmath\amstext.sty
Package: amstext 2000/06/29 v2.01 AMS text
(E:\CTEX\MiKTeX\tex/latex/amsmath\amsgen.sty
File: amsgen.sty 1999/11/30 v2.0 generic functions
\@emptytoks=\toks19
\ex@=\dimen104
)) (E:\CTEX\MiKTeX\tex/latex/amsmath\amsbsy.sty
Package: amsbsy 1999/11/29 v1.2d Bold Symbols
\pmbraise@=\dimen105
) (E:\CTEX\MiKTeX\tex/latex/amsmath\amsopn.sty
Package: amsopn 2016/03/08 v2.02 operator names
)
\inf@bad=\count92
LaTeX Info: Redefining \frac on input line 223.
\uproot@=\count93
\leftroot@=\count94
LaTeX Info: Redefining \overline on input line 385.
\classnum@=\count95
\DOTSCASE@=\count96
LaTeX Info: Redefining \ldots on input line 482.
LaTeX Info: Redefining \dots on input line 485.
LaTeX Info: Redefining \cdots on input line 606.
\Mathstrutbox@=\box28
\strutbox@=\box29
\big@size=\dimen106
LaTeX Font Info:    Redeclaring font encoding OML on input line 729.
LaTeX Font Info:    Redeclaring font encoding OMS on input line 730.
\macc@depth=\count97
\c@MaxMatrixCols=\count98
\dotsspace@=\muskip10
\c@parentequation=\count99
\dspbrk@lvl=\count100
\tag@help=\toks20
\row@=\count101
\column@=\count102
\maxfields@=\count103
\andhelp@=\toks21
\eqnshift@=\dimen107
\alignsep@=\dimen108
\tagshift@=\dimen109
\tagwidth@=\dimen110
\totwidth@=\dimen111
\lineht@=\dimen112
\@envbody=\toks22
\multlinegap=\skip44
\multlinetaggap=\skip45
\mathdisplay@stack=\toks23
LaTeX Info: Redefining \[ on input line 2844.
LaTeX Info: Redefining \] on input line 2845.
) (E:\CTEX\MiKTeX\tex/latex/amsfonts\amssymb.sty
Package: amssymb 2013/01/14 v3.01 AMS font symbols
(E:\CTEX\MiKTeX\tex/latex/amsfonts\amsfonts.sty
Package: amsfonts 2013/01/14 v3.01 Basic AMSFonts support
\symAMSa=\mathgroup4
\symAMSb=\mathgroup5
LaTeX Font Info:    Overwriting math alphabet `\mathfrak' in version `bold'
(Font)                  U/euf/m/n --> U/euf/b/n on input line 106.
)) (E:\CTEX\MiKTeX\tex/latex/doublestroke\dsfont.sty
Package: dsfont 1995/08/01 v0.1 Double stroke roman fonts
) (E:\CTEX\MiKTeX\tex/latex/setspace\setspace.sty
Package: setspace 2011/12/19 v6.7a set line spacing
) (E:\CTEX\MiKTeX\tex/latex/tipa\tipa.sty
Package: tipa 2002/08/08 TIPA version 1.1
(E:\CTEX\MiKTeX\tex/latex/base\fontenc.sty
Package: fontenc 2018/08/11 v2.0j Standard LaTeX package
(E:\CTEX\MiKTeX\tex/latex/tipa\t3enc.def
File: t3enc.def 2001/12/31 T3 encoding
Now handling font encoding T3 ...
... no UTF-8 mapping file for font encoding T3
) (E:\CTEX\MiKTeX\tex/latex/base\ot1enc.def
File: ot1enc.def 2018/08/11 v2.0j Standard LaTeX file
LaTeX Font Info:    Redeclaring font encoding OT1 on input line 48.
))) (E:\CTEX\MiKTeX\tex/latex/relsize\relsize.sty
Package: relsize 2013/03/29 ver 4.1
) (E:\CTEX\MiKTeX\tex/latex/base\textcomp.sty
Package: textcomp 2018/08/11 v2.0j Standard LaTeX package
Package textcomp Info: Sub-encoding information:
(textcomp)               5 = only ISO-Adobe without \textcurrency
(textcomp)               4 = 5 + \texteuro
(textcomp)               3 = 4 + \textohm
(textcomp)               2 = 3 + \textestimated + \textcurrency
(textcomp)               1 = TS1 - \textcircled - \t
(textcomp)               0 = TS1 (full)
(textcomp)             Font families with sub-encoding setting implement
(textcomp)             only a restricted character set as indicated.
(textcomp)             Family '?' is the default used for unknown fonts.
(textcomp)             See the documentation for details.
Package textcomp Info: Setting ? sub-encoding to TS1/1 on input line 79.
(E:\CTEX\MiKTeX\tex/latex/base\ts1enc.def
File: ts1enc.def 2001/06/05 v3.0e (jk/car/fm) Standard LaTeX file
Now handling font encoding TS1 ...
... processing UTF-8 mapping file for font encoding TS1
(E:\CTEX\MiKTeX\tex/latex/base\ts1enc.dfu
File: ts1enc.dfu 2018/10/05 v1.2f UTF-8 support for inputenc
   defining Unicode char U+00A2 (decimal 162)
   defining Unicode char U+00A3 (decimal 163)
   defining Unicode char U+00A4 (decimal 164)
   defining Unicode char U+00A5 (decimal 165)
   defining Unicode char U+00A6 (decimal 166)
   defining Unicode char U+00A7 (decimal 167)
   defining Unicode char U+00A8 (decimal 168)
   defining Unicode char U+00A9 (decimal 169)
   defining Unicode char U+00AA (decimal 170)
   defining Unicode char U+00AC (decimal 172)
   defining Unicode char U+00AE (decimal 174)
   defining Unicode char U+00AF (decimal 175)
   defining Unicode char U+00B0 (decimal 176)
   defining Unicode char U+00B1 (decimal 177)
   defining Unicode char U+00B2 (decimal 178)
   defining Unicode char U+00B3 (decimal 179)
   defining Unicode char U+00B4 (decimal 180)
   defining Unicode char U+00B5 (decimal 181)
   defining Unicode char U+00B6 (decimal 182)
   defining Unicode char U+00B7 (decimal 183)
   defining Unicode char U+00B9 (decimal 185)
   defining Unicode char U+00BA (decimal 186)
   defining Unicode char U+00BC (decimal 188)
   defining Unicode char U+00BD (decimal 189)
   defining Unicode char U+00BE (decimal 190)
   defining Unicode char U+00D7 (decimal 215)
   defining Unicode char U+00F7 (decimal 247)
   defining Unicode char U+0192 (decimal 402)
   defining Unicode char U+02C7 (decimal 711)
   defining Unicode char U+02D8 (decimal 728)
   defining Unicode char U+02DD (decimal 733)
   defining Unicode char U+0E3F (decimal 3647)
   defining Unicode char U+2016 (decimal 8214)
   defining Unicode char U+2020 (decimal 8224)
   defining Unicode char U+2021 (decimal 8225)
   defining Unicode char U+2022 (decimal 8226)
   defining Unicode char U+2030 (decimal 8240)
   defining Unicode char U+2031 (decimal 8241)
   defining Unicode char U+203B (decimal 8251)
   defining Unicode char U+203D (decimal 8253)
   defining Unicode char U+2044 (decimal 8260)
   defining Unicode char U+204E (decimal 8270)
   defining Unicode char U+2052 (decimal 8274)
   defining Unicode char U+20A1 (decimal 8353)
   defining Unicode char U+20A4 (decimal 8356)
   defining Unicode char U+20A6 (decimal 8358)
   defining Unicode char U+20A9 (decimal 8361)
   defining Unicode char U+20AB (decimal 8363)
   defining Unicode char U+20AC (decimal 8364)
   defining Unicode char U+20B1 (decimal 8369)
   defining Unicode char U+2103 (decimal 8451)
   defining Unicode char U+2116 (decimal 8470)
   defining Unicode char U+2117 (decimal 8471)
   defining Unicode char U+211E (decimal 8478)
   defining Unicode char U+2120 (decimal 8480)
   defining Unicode char U+2122 (decimal 8482)
   defining Unicode char U+2126 (decimal 8486)
   defining Unicode char U+2127 (decimal 8487)
   defining Unicode char U+212E (decimal 8494)
   defining Unicode char U+2190 (decimal 8592)
   defining Unicode char U+2191 (decimal 8593)
   defining Unicode char U+2192 (decimal 8594)
   defining Unicode char U+2193 (decimal 8595)
   defining Unicode char U+2329 (decimal 9001)
   defining Unicode char U+232A (decimal 9002)
   defining Unicode char U+2422 (decimal 9250)
   defining Unicode char U+25E6 (decimal 9702)
   defining Unicode char U+25EF (decimal 9711)
   defining Unicode char U+266A (decimal 9834)
   defining Unicode char U+FEFF (decimal 65279)
))
LaTeX Info: Redefining \oldstylenums on input line 334.
Package textcomp Info: Setting cmr sub-encoding to TS1/0 on input line 349.
Package textcomp Info: Setting cmss sub-encoding to TS1/0 on input line 350.
Package textcomp Info: Setting cmtt sub-encoding to TS1/0 on input line 351.
Package textcomp Info: Setting cmvtt sub-encoding to TS1/0 on input line 352.
Package textcomp Info: Setting cmbr sub-encoding to TS1/0 on input line 353.
Package textcomp Info: Setting cmtl sub-encoding to TS1/0 on input line 354.
Package textcomp Info: Setting ccr sub-encoding to TS1/0 on input line 355.
Package textcomp Info: Setting ptm sub-encoding to TS1/4 on input line 356.
Package textcomp Info: Setting pcr sub-encoding to TS1/4 on input line 357.
Package textcomp Info: Setting phv sub-encoding to TS1/4 on input line 358.
Package textcomp Info: Setting ppl sub-encoding to TS1/3 on input line 359.
Package textcomp Info: Setting pag sub-encoding to TS1/4 on input line 360.
Package textcomp Info: Setting pbk sub-encoding to TS1/4 on input line 361.
Package textcomp Info: Setting pnc sub-encoding to TS1/4 on input line 362.
Package textcomp Info: Setting pzc sub-encoding to TS1/4 on input line 363.
Package textcomp Info: Setting bch sub-encoding to TS1/4 on input line 364.
Package textcomp Info: Setting put sub-encoding to TS1/5 on input line 365.
Package textcomp Info: Setting uag sub-encoding to TS1/5 on input line 366.
Package textcomp Info: Setting ugq sub-encoding to TS1/5 on input line 367.
Package textcomp Info: Setting ul8 sub-encoding to TS1/4 on input line 368.
Package textcomp Info: Setting ul9 sub-encoding to TS1/4 on input line 369.
Package textcomp Info: Setting augie sub-encoding to TS1/5 on input line 370.
Package textcomp Info: Setting dayrom sub-encoding to TS1/3 on input line 371.
Package textcomp Info: Setting dayroms sub-encoding to TS1/3 on input line 372.

Package textcomp Info: Setting pxr sub-encoding to TS1/0 on input line 373.
Package textcomp Info: Setting pxss sub-encoding to TS1/0 on input line 374.
Package textcomp Info: Setting pxtt sub-encoding to TS1/0 on input line 375.
Package textcomp Info: Setting txr sub-encoding to TS1/0 on input line 376.
Package textcomp Info: Setting txss sub-encoding to TS1/0 on input line 377.
Package textcomp Info: Setting txtt sub-encoding to TS1/0 on input line 378.
Package textcomp Info: Setting lmr sub-encoding to TS1/0 on input line 379.
Package textcomp Info: Setting lmdh sub-encoding to TS1/0 on input line 380.
Package textcomp Info: Setting lmss sub-encoding to TS1/0 on input line 381.
Package textcomp Info: Setting lmssq sub-encoding to TS1/0 on input line 382.
Package textcomp Info: Setting lmvtt sub-encoding to TS1/0 on input line 383.
Package textcomp Info: Setting lmtt sub-encoding to TS1/0 on input line 384.
Package textcomp Info: Setting qhv sub-encoding to TS1/0 on input line 385.
Package textcomp Info: Setting qag sub-encoding to TS1/0 on input line 386.
Package textcomp Info: Setting qbk sub-encoding to TS1/0 on input line 387.
Package textcomp Info: Setting qcr sub-encoding to TS1/0 on input line 388.
Package textcomp Info: Setting qcs sub-encoding to TS1/0 on input line 389.
Package textcomp Info: Setting qpl sub-encoding to TS1/0 on input line 390.
Package textcomp Info: Setting qtm sub-encoding to TS1/0 on input line 391.
Package textcomp Info: Setting qzc sub-encoding to TS1/0 on input line 392.
Package textcomp Info: Setting qhvc sub-encoding to TS1/0 on input line 393.
Package textcomp Info: Setting futs sub-encoding to TS1/4 on input line 394.
Package textcomp Info: Setting futx sub-encoding to TS1/4 on input line 395.
Package textcomp Info: Setting futj sub-encoding to TS1/4 on input line 396.
Package textcomp Info: Setting hlh sub-encoding to TS1/3 on input line 397.
Package textcomp Info: Setting hls sub-encoding to TS1/3 on input line 398.
Package textcomp Info: Setting hlst sub-encoding to TS1/3 on input line 399.
Package textcomp Info: Setting hlct sub-encoding to TS1/5 on input line 400.
Package textcomp Info: Setting hlx sub-encoding to TS1/5 on input line 401.
Package textcomp Info: Setting hlce sub-encoding to TS1/5 on input line 402.
Package textcomp Info: Setting hlcn sub-encoding to TS1/5 on input line 403.
Package textcomp Info: Setting hlcw sub-encoding to TS1/5 on input line 404.
Package textcomp Info: Setting hlcf sub-encoding to TS1/5 on input line 405.
Package textcomp Info: Setting pplx sub-encoding to TS1/3 on input line 406.
Package textcomp Info: Setting pplj sub-encoding to TS1/3 on input line 407.
Package textcomp Info: Setting ptmx sub-encoding to TS1/4 on input line 408.
Package textcomp Info: Setting ptmj sub-encoding to TS1/4 on input line 409.
) (E:\CTEX\MiKTeX\tex/latex/jknappen\mathrsfs.sty
Package: mathrsfs 1996/01/01 Math RSFS package v1.0 (jk)
\symrsfs=\mathgroup6
) (E:\CTEX\MiKTeX\tex/latex/fundus-calligra\calligra.sty
Package: calligra 2012/04/10 v1.9 LaTeX package calligra
) (E:\CTEX\MiKTeX\tex/latex/wasysym\wasysym.sty
Package: wasysym 2003/10/30 v2.0 Wasy-2 symbol support package
\symwasy=\mathgroup7
LaTeX Font Info:    Overwriting symbol font `wasy' in version `bold'
(Font)                  U/wasy/m/n --> U/wasy/b/n on input line 90.
) (E:\CTEX\MiKTeX\tex/latex/ms\ragged2e.sty
Package: ragged2e 2009/05/21 v2.1 ragged2e Package (MS)
(E:\CTEX\MiKTeX\tex/latex/ms\everysel.sty
Package: everysel 2011/10/28 v1.2 EverySelectfont Package (MS)
)
\CenteringLeftskip=\skip46
\RaggedLeftLeftskip=\skip47
\RaggedRightLeftskip=\skip48
\CenteringRightskip=\skip49
\RaggedLeftRightskip=\skip50
\RaggedRightRightskip=\skip51
\CenteringParfillskip=\skip52
\RaggedLeftParfillskip=\skip53
\RaggedRightParfillskip=\skip54
\JustifyingParfillskip=\skip55
\CenteringParindent=\skip56
\RaggedLeftParindent=\skip57
\RaggedRightParindent=\skip58
\JustifyingParindent=\skip59
) (E:\CTEX\MiKTeX\tex/latex/physics\physics.sty
Package: physics 
(E:\CTEX\MiKTeX\tex/latex/l3packages/xparse\xparse.sty (E:\CTEX\MiKTeX\tex/late
x/l3kernel\expl3.sty
Package: expl3 2019-04-21 L3 programming layer (loader) 
(E:\CTEX\MiKTeX\tex/latex/l3kernel\expl3-code.tex
Package: expl3 2019-04-21 L3 programming layer (code)
\c_max_int=\count104
\l_tmpa_int=\count105
\l_tmpb_int=\count106
\g_tmpa_int=\count107
\g_tmpb_int=\count108
\g__kernel_prg_map_int=\count109
\c__ior_term_ior=\count110
\c_log_iow=\count111
\l_iow_line_count_int=\count112
\l__iow_line_target_int=\count113
\l__iow_one_indent_int=\count114
\l__iow_indent_int=\count115
\c_zero_dim=\dimen113
\c_max_dim=\dimen114
\l_tmpa_dim=\dimen115
\l_tmpb_dim=\dimen116
\g_tmpa_dim=\dimen117
\g_tmpb_dim=\dimen118
\c_zero_skip=\skip60
\c_max_skip=\skip61
\l_tmpa_skip=\skip62
\l_tmpb_skip=\skip63
\g_tmpa_skip=\skip64
\g_tmpb_skip=\skip65
\c_zero_muskip=\muskip11
\c_max_muskip=\muskip12
\l_tmpa_muskip=\muskip13
\l_tmpb_muskip=\muskip14
\g_tmpa_muskip=\muskip15
\g_tmpb_muskip=\muskip16
\l_keys_choice_int=\count116
\l__intarray_loop_int=\count117
\c__intarray_sp_dim=\dimen119
\g__intarray_font_int=\count118
\c__fp_leading_shift_int=\count119
\c__fp_middle_shift_int=\count120
\c__fp_trailing_shift_int=\count121
\c__fp_big_leading_shift_int=\count122
\c__fp_big_middle_shift_int=\count123
\c__fp_big_trailing_shift_int=\count124
\c__fp_Bigg_leading_shift_int=\count125
\c__fp_Bigg_middle_shift_int=\count126
\c__fp_Bigg_trailing_shift_int=\count127
\c__kernel_randint_max_int=\count128
\g__fp_array_int=\count129
\l__fp_array_loop_int=\count130
\l__sort_length_int=\count131
\l__sort_min_int=\count132
\l__sort_top_int=\count133
\l__sort_max_int=\count134
\l__sort_true_max_int=\count135
\l__sort_block_int=\count136
\l__sort_begin_int=\count137
\l__sort_end_int=\count138
\l__sort_A_int=\count139
\l__sort_B_int=\count140
\l__sort_C_int=\count141
\l__tl_analysis_normal_int=\count142
\l__tl_analysis_index_int=\count143
\l__tl_analysis_nesting_int=\count144
\l__tl_analysis_type_int=\count145
\l__regex_internal_a_int=\count146
\l__regex_internal_b_int=\count147
\l__regex_internal_c_int=\count148
\l__regex_balance_int=\count149
\l__regex_group_level_int=\count150
\l__regex_mode_int=\count151
\c__regex_cs_in_class_mode_int=\count152
\c__regex_cs_mode_int=\count153
\l__regex_catcodes_int=\count154
\l__regex_default_catcodes_int=\count155
\c__regex_catcode_D_int=\count156
\c__regex_catcode_S_int=\count157
\c__regex_catcode_L_int=\count158
\c__regex_catcode_O_int=\count159
\c__regex_catcode_A_int=\count160
\c__regex_all_catcodes_int=\count161
\l__regex_show_lines_int=\count162
\l__regex_min_state_int=\count163
\l__regex_max_state_int=\count164
\l__regex_left_state_int=\count165
\l__regex_right_state_int=\count166
\l__regex_capturing_group_int=\count167
\l__regex_min_pos_int=\count168
\l__regex_max_pos_int=\count169
\l__regex_curr_pos_int=\count170
\l__regex_start_pos_int=\count171
\l__regex_success_pos_int=\count172
\l__regex_curr_char_int=\count173
\l__regex_curr_catcode_int=\count174
\l__regex_last_char_int=\count175
\l__regex_case_changed_char_int=\count176
\l__regex_curr_state_int=\count177
\l__regex_step_int=\count178
\l__regex_min_active_int=\count179
\l__regex_max_active_int=\count180
\l__regex_replacement_csnames_int=\count181
\l__regex_match_count_int=\count182
\l__regex_min_submatch_int=\count183
\l__regex_submatch_int=\count184
\l__regex_zeroth_submatch_int=\count185
\g__regex_trace_regex_int=\count186
\c_empty_box=\box30
\l_tmpa_box=\box31
\l_tmpb_box=\box32
\g_tmpa_box=\box33
\g_tmpb_box=\box34
\l__box_top_dim=\dimen120
\l__box_bottom_dim=\dimen121
\l__box_left_dim=\dimen122
\l__box_right_dim=\dimen123
\l__box_top_new_dim=\dimen124
\l__box_bottom_new_dim=\dimen125
\l__box_left_new_dim=\dimen126
\l__box_right_new_dim=\dimen127
\l__box_internal_box=\box35
\l__coffin_internal_box=\box36
\l__coffin_internal_dim=\dimen128
\l__coffin_offset_x_dim=\dimen129
\l__coffin_offset_y_dim=\dimen130
\l__coffin_x_dim=\dimen131
\l__coffin_y_dim=\dimen132
\l__coffin_x_prime_dim=\dimen133
\l__coffin_y_prime_dim=\dimen134
\c_empty_coffin=\box37
\l__coffin_aligned_coffin=\box38
\l__coffin_aligned_internal_coffin=\box39
\l_tmpa_coffin=\box40
\l_tmpb_coffin=\box41
\g_tmpa_coffin=\box42
\g_tmpb_coffin=\box43
\l__coffin_bounding_shift_dim=\dimen135
\l__coffin_left_corner_dim=\dimen136
\l__coffin_right_corner_dim=\dimen137
\l__coffin_bottom_corner_dim=\dimen138
\l__coffin_top_corner_dim=\dimen139
\l__coffin_scaled_total_height_dim=\dimen140
\l__coffin_scaled_width_dim=\dimen141
\c__coffin_empty_coffin=\box44
\l__coffin_display_coffin=\box45
\l__coffin_display_coord_coffin=\box46
\l__coffin_display_pole_coffin=\box47
\l__coffin_display_offset_dim=\dimen142
\l__coffin_display_x_dim=\dimen143
\l__coffin_display_y_dim=\dimen144
\g__file_internal_ior=\read1
\l__seq_internal_a_int=\count187
\l__seq_internal_b_int=\count188
\c__deprecation_minus_one=\count189
) (E:\CTEX\MiKTeX\tex/latex/l3kernel\l3dvips.def
File: l3dvips.def 2019-04-06 v L3 Experimental driver: dvips
\g__driver_pdf_object_int=\count190
\l__driver_pdf_content_box=\box48
\l__driver_pdf_model_box=\box49
\g__driver_pdf_annotation_int=\count191
\g__driver_pdf_link_int=\count192
\g__driver_pdf_link_sf_int=\count193
))
Package: xparse 2019-03-05 L3 Experimental document command parser
\l__xparse_current_arg_int=\count194
\g__xparse_grabber_int=\count195
\l__xparse_m_args_int=\count196
\l__xparse_v_nesting_int=\count197
)) (E:\CTEX\MiKTeX\tex/latex/xcolor\xcolor.sty
Package: xcolor 2016/05/11 v2.12 LaTeX color extensions (UK)
(E:\CTEX\MiKTeX\tex/latex/graphics-cfg\color.cfg
File: color.cfg 2016/01/02 v1.6 sample color configuration
)
Package xcolor Info: Driver file: dvips.def on input line 225.
(E:\CTEX\MiKTeX\tex/latex/graphics-def\dvips.def
File: dvips.def 2017/06/20 v3.1d Graphics/color driver for dvips
)
Package xcolor Info: Model `cmy' substituted by `cmy0' on input line 1348.
Package xcolor Info: Model `RGB' extended on input line 1364.
Package xcolor Info: Model `HTML' substituted by `rgb' on input line 1366.
Package xcolor Info: Model `Hsb' substituted by `hsb' on input line 1367.
Package xcolor Info: Model `tHsb' substituted by `hsb' on input line 1368.
Package xcolor Info: Model `HSB' substituted by `hsb' on input line 1369.
Package xcolor Info: Model `Gray' substituted by `gray' on input line 1370.
Package xcolor Info: Model `wave' substituted by `hsb' on input line 1371.
) (E:\CTEX\MiKTeX\tex/latex/microtype\microtype.sty
Package: microtype 2019/02/28 v2.7b Micro-typographical refinements (RS)
\MT@toks=\toks24
\MT@count=\count198
LaTeX Info: Redefining \textls on input line 790.
\MT@outer@kern=\dimen145
LaTeX Info: Redefining \textmicrotypecontext on input line 1336.
\MT@listname@count=\count199
(E:\CTEX\MiKTeX\tex/latex/microtype\microtype-pdftex.def
File: microtype-pdftex.def 2019/02/28 v2.7b Definitions specific to pdftex (RS)

LaTeX Info: Redefining \lsstyle on input line 914.
LaTeX Info: Redefining \lslig on input line 914.
\MT@outer@space=\skip66
)
Package microtype Info: Loading configuration file microtype.cfg.
(E:\CTEX\MiKTeX\tex/latex/microtype\microtype.cfg
File: microtype.cfg 2019/02/28 v2.7b microtype main configuration file (RS)
)) (C:\Users\lenovo\manim\manimlib\files\Tex\84ce4b55d61dc0c1.aux)
\openout1 = `84ce4b55d61dc0c1.aux'.

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 23.
LaTeX Font Info:    ... okay on input line 23.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 23.
LaTeX Font Info:    ... okay on input line 23.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 23.
LaTeX Font Info:    ... okay on input line 23.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 23.
LaTeX Font Info:    ... okay on input line 23.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 23.
LaTeX Font Info:    ... okay on input line 23.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 23.
LaTeX Font Info:    ... okay on input line 23.
LaTeX Font Info:    Checking defaults for T3/cmr/m/n on input line 23.
LaTeX Font Info:    Try loading font information for T3+cmr on input line 23.
(E:\CTEX\MiKTeX\tex/latex/tipa\t3cmr.fd
File: t3cmr.fd 2001/12/31 TIPA font definitions
)
LaTeX Font Info:    ... okay on input line 23.
LaTeX Font Info:    Checking defaults for TS1/cmr/m/n on input line 23.
LaTeX Font Info:    Try loading font information for TS1+cmr on input line 23.
(E:\CTEX\MiKTeX\tex/latex/base\ts1cmr.fd
File: ts1cmr.fd 2014/09/29 v2.5h Standard LaTeX font definitions
)
LaTeX Font Info:    ... okay on input line 23.
Preview: Fontsize 10pt
ABD: EverySelectfont initializing macros
LaTeX Info: Redefining \selectfont on input line 23.
LaTeX Info: Redefining \microtypecontext on input line 23.
Package microtype Info: Generating DVI output.
Package microtype Info: Character protrusion enabled (level 2).
Package microtype Info: Using default protrusion set `alltext'.
Package microtype Info: No font expansion.
Package microtype Info: No adjustment of tracking.
Package microtype Info: No adjustment of interword spacing.
Package microtype Info: No adjustment of character kerning.
(E:\CTEX\MiKTeX\tex/latex/microtype\mt-cmr.cfg
File: mt-cmr.cfg 2013/05/19 v2.2 microtype config. file: Computer Modern Roman 
(RS)
)
LaTeX Font Info:    Try loading font information for U+msa on input line 25.
(E:\CTEX\MiKTeX\tex/latex/amsfonts\umsa.fd
File: umsa.fd 2013/01/14 v3.01 AMS symbols A
) (E:\CTEX\MiKTeX\tex/latex/microtype\mt-msa.cfg
File: mt-msa.cfg 2006/02/04 v1.1 microtype config. file: AMS symbols (a) (RS)
)
LaTeX Font Info:    Try loading font information for U+msb on input line 25.
(E:\CTEX\MiKTeX\tex/latex/amsfonts\umsb.fd
File: umsb.fd 2013/01/14 v3.01 AMS symbols B
) (E:\CTEX\MiKTeX\tex/latex/microtype\mt-msb.cfg
File: mt-msb.cfg 2005/06/01 v1.0 microtype config. file: AMS symbols (b) (RS)
)
LaTeX Font Info:    Try loading font information for U+rsfs on input line 25.
(E:\CTEX\MiKTeX\tex/latex/jknappen\ursfs.fd
File: ursfs.fd 1998/03/24 rsfs font definition file (jk)
)
LaTeX Font Info:    Try loading font information for U+wasy on input line 25.
(E:\CTEX\MiKTeX\tex/latex/wasysym\uwasy.fd
File: uwasy.fd 2003/10/30 v2.0 Wasy-2 symbol font definitions
)

! Package inputenc Error: Unicode character 梦 (U+68A6)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.27 \end{align*}
                  
Here is how much of TeX's memory you used:
 15836 strings out of 492898
 274476 string characters out of 3139585
 341305 words of memory out of 3000000
 19624 multiletter control sequences out of 15000+200000
 536485 words of font info for 42 fonts, out of 3000000 for 9000
 1141 hyphenation exceptions out of 8191
 47i,8n,65p,383b,317s stack positions out of 5000i,500n,10000p,200000b,50000s

No pages of output.

**Comment by nullp0tr** [comment]
post what's in the log file `C:\Users\lenovo\manim\manimlib\files\Tex\905c0559e4af4e80.log`

**Comment by 562245918** [comment]
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (MiKTeX 2.9.7000 64-bit) (preloaded format=latex 2019.4.18)  25 APR 2019 23:59
entering extended mode
**C:/Users/lenovo/manim/manimlib/files/Tex/905c0559e4af4e80.tex
(C:/Users/lenovo/manim/manimlib/files/Tex/905c0559e4af4e80.tex
LaTeX2e <2018-12-01>

! LaTeX Error: File `standalone.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)

Enter file name: 
! Emergency stop.
<read *> 
         
l.2 

      
Here is how much of TeX's memory you used:
 14 strings out of 492946
 447 string characters out of 3143504
 56746 words of memory out of 3000000
 4008 multiletter control sequences out of 15000+200000
 3640 words of font info for 14 fonts, out of 3000000 for 9000
 1141 hyphenation exceptions out of 8191
 10i,0n,8p,100b,8s stack positions out of 5000i,500n,10000p,200000b,50000s

No pages of output.

**Comment by conradolandia** [comment]
Your MikTeX probably doesn't have the "standalone" class installed. You need to search "standalone" in the MikTeX package manager and install it. In [here](https://www.youtube.com/watch?v=OD15rZO_rD8) you'll find a video tutorial to help you out with that.
