### ISSUE TITLE
Error while trying to continually update an mobject

### ISSUE THREAD

**Issue by AamodJ** [3b1b/manim#514]
I wanted to create an animation wherein there's a moving point. 
This is the code for the animation: 

[moving_point.txt](https://github.com/3b1b/manim/files/3124389/moving_point.copy.txt)

But when I run the file, it gives me an Attribute Error. 

`Traceback (most recent call last):
  File "/Users/aamodj/manim/manimlib/extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "/Users/aamodj/manim/manimlib/scene/scene.py", line 52, in __init__
    self.construct()
  File "My_Projects/moving_point.py", line 12, in construct
    self.add(ContinuallyMove(point))
  File "/Users/aamodj/manim/manimlib/scene/scene.py", line 190, in add
    self.restructure_mobjects(to_remove=mobjects)
  File "/Users/aamodj/manim/manimlib/scene/scene.py", line 221, in restructure_mobjects
    to_remove = self.camera.extract_mobject_family_members(to_remove)
  File "/Users/aamodj/manim/manimlib/camera/camera.py", line 211, in extract_mobject_family_members
    it.chain(*[method(m) for m in mobjects])
  File "/Users/aamodj/manim/manimlib/camera/camera.py", line 211, in <listcomp>
    it.chain(*[method(m) for m in mobjects])
  File "/Users/aamodj/manim/manimlib/mobject/mobject.py", line 916, in get_family
    sub_families = list(map(Mobject.get_family, self.submobjects))
AttributeError: 'ContinuallyMove' object has no attribute 'submobjects'`

How do I fix this?

**Comment by eulertour** [comment]
I think you're trying to use the old `ContinualAnimation` class, which has be removed. This should be done with updaters instead.

**Comment by AamodJ** [comment]
> I think you're trying to use the old `ContinualAnimation` class, which has be removed. This should be done with updaters instead.

How would one go about using updaters for animating?

**Comment by jjenzano** [comment]
Did you ever get a reply? I am trying to do the same thing.

**Comment by AamodJ** [comment]
> Did you ever get a reply? I am trying to do the same thing.

Not yet man :(
Still don't know how to make it work

**Comment by jjenzano** [comment]
I’ve been tinkering with it all morning. I have made some progress. Here is my most recent code that moves a circle to the right at a rate that depends on its x-coordinate.

 

I am a Python noob. I have been reverse-engineering everything. Trying to use manim to illustrate sime math concepts for high-school math.

 

from manimlib.imports import *

class Animate (GraphScene):
    CONFIG = {

    "plane_kwargs" : {
        "color" : RED_B,
        },

        "axis_config": {
            "stroke_color": WHITE,
            "stroke_width": 2,
            "include_ticks": False,
            "include_tip": False,
            "line_to_number_buff": SMALL_BUFF,
            "label_direction": DR,
            "number_scale_val": 0.5,
        },
        "y_axis_config": {
            "label_direction": DR,
        },
        "background_line_style": {
            "stroke_color": BLUE_D,
            "stroke_width": 5,
            "stroke_opacity": 1,
        },
    "point_charge_loc" : 0.5*RIGHT-1.5*UP,
    }

    def construct (self):
        plane = NumberPlane(**self.plane_kwargs)
        plane.add(plane.get_axis_labels())
        self.add(plane)
        circle=Circle(radius=0.5)
        self.add(circle)
        self.wait(1)




        def update_circle(circle,dt):
            dt = 0.01
            circle.velocity=circle.get_x(RIGHT)

            circle.shift(dt*circle.velocity*RIGHT)


        self.add(circle.add_updater(update_circle))
        self.wait(15)

**Comment by AamodJ** [comment]
@jjenzano Thanks! That helped me out!
