### ISSUE TITLE
Conda environment for installing manim on Windows

### ISSUE THREAD

**Issue by napsternxg** [3b1b/manim#519]
### Feature request

It would be nice to install manim using anaconda environment for windows. The anaconda environment file can be used to automatically install most of the external packages, e.g. cairo, ffmpeg, and other pip dependencies. 

Only sox, and latex need to be installed separately.

**Comment by LexCode74** [comment]
What does it mean napsternxg? Can we install most of the dependencies within anaconda and the remaining ones apart and it istill works?
