### ISSUE TITLE
Broken pipe error after installing via conda in an Anaconda environment and running the example

### ISSUE THREAD

**Issue by PaawanSharma** [3b1b/manim#536]
When I input `python3 -m manim example_scenes.py SquareToCircle -pl` into Terminal, I get the following error:

> Media will be stored in ./media/. You can change this behavior by writing a different directory to media_dir.txt.
> Animation 0: ShowCreationSquare:   0%|                   | 0/15 [00:00<?, ?it/s]Unknown encoder 'libx264'
>                                                                                 
> 
> 
> Traceback (most recent call last):
>   File "/Users/paawansharma/manim/manimlib/extract_scene.py", line 150, in main
>     scene = SceneClass(**scene_kwargs)
>   File "/Users/paawansharma/manim/manimlib/scene/scene.py", line 52, in __init__
>     self.construct()
>   File "example_scenes.py", line 81, in construct
>     self.play(ShowCreation(square))
>   File "/Users/paawansharma/manim/manimlib/scene/scene.py", line 404, in wrapper
>     func(self, *args, **kwargs)
>   File "/Users/paawansharma/manim/manimlib/scene/scene.py", line 461, in play
>     self.progress_through_animations(animations)
>   File "/Users/paawansharma/manim/manimlib/scene/scene.py", line 437, in progress_through_animations
>     self.add_frames(self.get_frame())
>   File "/Users/paawansharma/manim/manimlib/scene/scene.py", line 541, in add_frames
>     self.file_writer.write_frame(frame)
>   File "/Users/paawansharma/manim/manimlib/scene/scene_file_writer.py", line 172, in write_frame
>     self.writing_process.stdin.write(frame.tostring())
> BrokenPipeError: [Errno 32] Broken pipe
>

**Comment by Elteoremadebeethoven** [comment]
Check #492
