### ISSUE TITLE
Jupyter notebook integration?

### ISSUE THREAD

**Issue by krassowski** [3b1b/manim#545]
I would really love to see some proper integration with the Jupyter notebooks. I could not find anything so I went ahead and published my work-in-progress and not-ideal solution based on cell magics (see https://github.com/krassowski/jupyter-manim) and I would love to hear more from the community around the excellent @3b1b's toolkit:

- is there any other way to get that working smoothly?
- has anyone tried doing so before?
- is the jupyter-manim integration that I wrote any use to anyone else?

**Comment by zimmermant** [comment]
I'll definitely give it a try and give feedback.

**Comment by xkortex** [comment]
This is great! I would love to see this continue using traction. 

Just tried and failed miserably to generate some animated graphs for a presentation, first with Matplotlib (resolution was terrible), then with Bokeh (phantomjs refused to run properly). Using manim as a plotting engine in Jupyter would revolutionize data science visualization.

**Comment by krassowski** [comment]
Version 1.0 is now released and features much-anticipated namespace export. Hope you will enjoy it!
