### ISSUE TITLE
Exception: Latex error converting to dvi

### ISSUE THREAD

**Issue by Michael-Tulskikh** [3b1b/manim#548]
I have recently come across an issue with TexMobjects that I cannot seem to fix. I have tried looking through the many other issues created by others, and none of the solutions seemed to help. To briefly describe my goal, I am trying to create a simple animation, briefly going over implicit differentiation, so that I can get used to working with manim. 

I have already created the LaTeX equation , which seems to work when put together as one long string, but it fails when I attempt to separate it, which has confused me for quite some time now, as I used an identical method in an earlier animation, and there were no problems: 

`text = TexMobject(r"\frac{\text{d}", r"\text{y}}", r"{\text{d}", r"\text{x}}")
`

I am separating the `\text{x}` and `\text{y}`, so that I can eventually recolor them, using set_color_by_tex_to_color_map; however, I am confident that the recoloring is not my issue, as I have successfully used it before, and the animation still refuses to render, even when I remove the command to color the equation and just try to get it to appear on the screen. In an attempt to troubleshoot my problems, I created a separate class intended only to get this specific part of my animation working, which I will paste below. The issue remains the same.

```
class test (Scene):
    def construct(self):
        text = TexMobject(r"\frac{\text{d}", r"\text{y}}", r"{\text{d}", r"\text{x}}")

        self.play(Write(text))
```

After trying to play this animation, with `python -m manim anim.py test -pl`, I get the following error:

```
Media will be stored in ./media\. You can change this behavior by writing a different directory to media_dir.txt.



Traceback (most recent call last):
  File "C:\Users\tulsk\Documents\manim\manimlib\extract_scene.py", line 150, in main
    scene = SceneClass(**scene_kwargs)
  File "C:\Users\tulsk\Documents\manim\manimlib\scene\scene.py", line 52, in __init__
    self.construct()
  File "anim.py", line 405, in construct
    text = TexMobject(r"\frac{\text{d}", r"\text{y}}", r"{\text{d}", r"\text{x}}")
  File "C:\Users\tulsk\Documents\manim\manimlib\mobject\svg\tex_mobject.py", line 146, in __init__
    self.break_up_by_substrings()
  File "C:\Users\tulsk\Documents\manim\manimlib\mobject\svg\tex_mobject.py", line 174, in break_up_by_substrings
    sub_tex_mob = SingleStringTexMobject(tex_string, **self.CONFIG)
  File "C:\Users\tulsk\Documents\manim\manimlib\mobject\svg\tex_mobject.py", line 44, in __init__
    self.template_tex_file_body
  File "C:\Users\tulsk\Documents\manim\manimlib\utils\tex_file_writing.py", line 19, in tex_to_svg_file
    dvi_file = tex_to_dvi(tex_file)
  File "C:\Users\tulsk\Documents\manim\manimlib\utils\tex_file_writing.py", line 67, in tex_to_dvi
    "See log output above or the log file: %s" % log_file)
Exception: Latex error converting to dvi. See log output above or the log file: .\files\Tex\280909e253fde66a.log

```

I would think that my method of separation should work perfectly fine, as replacing the code with the following works without any errors. I am using the exact same method in this attempt, as I am in the previous one, yet this is the only one that successfully produces an animation:

```
class test1 (Scene):
    def construct(self):
        text2 = TexMobject(r"\frac{\partial}{\partial", r"\text{x}", r"}")

        self.play(Write(text2))
```
Command Used: `python -m manim anim.py test1 -pl`

Other Information:

- Python 3.7
- Latest version of manim
- Windows 10
- I am using PyCharm as my editor
- I am using MiKTeX, as suggested by the installation tutorial

I am comparatively new to Python; however, I would consider myself knowledgeable enough to understand the basics, but am not quite sure how to fix this issue, or what else I should look for, as I have already tried some of the suggested fixes found in other resolved issues, but nothing seemed to work. It is also entirely possible that I am missing something quite obvious; however, I have tried everything that I can think of and have not yet found a solution.

If anyone could help me solve my issue, and figure out why the first scene is giving me an error, it would be greatly appreciated. Please feel free to let me know if I need to provide any additional information.

**Comment by Elteoremadebeethoven** [comment]
Manim works better with `"{a","\over","b}"`

**Comment by Michael-Tulskikh** [comment]
Thank you so much! After switching to using \over instead of \frac it seems that I am not longer getting any issues, and it is working fine.
