### ISSUE TITLE
Concatenate Multiple Scenes

### ISSUE THREAD

**Issue by FedeClaudi** [3b1b/manim#550]
Hi, 

Amazing work with Manim, loving it. 
I was just wondering if there is a way to automatically concatenate multiple scenes into a single video. 

I've seen that there are scripts like this: 'active_projects/ode/all_part1_scenes.py' which list a number of scenes:
`SCENES_IN_ORDER = [
    WhenChangeIsEasier,
    VectorFieldTest,
    IntroducePendulum,
    MultiplePendulumsOverlayed,
    ...`

And if you running it allows you to select which scenes to run in order, but then the output of these scenes is single video files. Is there a way to specify that I want the scenes I selected to appear in order in a single movie?

Thank you,
Federico

**Comment by Elteoremadebeethoven** [comment]
Not at the moment, but you can use [ffmpeg](https://trac.ffmpeg.org/wiki/Concatenate)

**Comment by kolibril13** [comment]
I can really recomend the new release of the videosoftweare kdenlive:
https://kdenlive.org/en/2019/04/kdenlive-19-04-released/
I use it to put scenes together and the best: when you have a microphone it is super easy to do voice dubbing

**Comment by FedeClaudi** [comment]
That's great, thank you both!

**Comment by kolibril13** [comment]
I also wrote a jupyter tool to connect scenes:
The best of it: 
You can go from video scene to video scene with mouse clicks:
![clicks](https://user-images.githubusercontent.com/44469195/58812560-6bf8fa80-8622-11e9-8b6c-e30c41e54235.gif)
Here is the code:
https://github.com/kolibril13/jupyter_video_presentation
