### ISSUE TITLE
\usepackage{textcomp} declared twice in ctex_template.tex

### ISSUE THREAD

**Issue by Kolloom** [3b1b/manim#552]
`\documentclass[preview]{standalone}

\usepackage[english]{babel}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{dsfont}
\usepackage{setspace}
\usepackage{tipa}
\usepackage{relsize}
\usepackage{textcomp} <<<
\usepackage{mathrsfs}
\usepackage{calligra}
\usepackage{wasysym}
\usepackage{ragged2e}
\usepackage{physics}
\usepackage{xcolor}
\usepackage{textcomp} <<<
\usepackage{microtype}
%\DisableLigatures{encoding = *, family = * }
\usepackage[UTF8]{ctex}
\linespread{1}

\begin{document}

YourTextHere

\end{document}`

**Comment by yoshiask** [comment]
Fixed in #554
