### ISSUE TITLE
How to delay a single animation among all parameters passed to Scene.play

### ISSUE THREAD

**Issue by Krantz-XRF** [3b1b/manim#559]
All parameters passed to `Scene.play` is played simultaneously. And separate calls to `Scene.play` makes the second animation happen after the first one finishes. If I want 2 animations A and B, with B played some time (say `t`) after A starts but still before A finishes, how can I achieve that?

By searching the repository, I found some code in `old_projects` used a class called `DelayByOrder`, but no code seems to provide that. I guess it is already removed. So how can I delay an animation, so that it is played after other animations passed to `Scene.play`?

**Comment by Krantz-XRF** [comment]
All of a sudden I found the `AnimationGroup` class. I guess this would be the correct method. I will close this issue, sorry for disturbing.

**Comment by daem-on** [comment]
Thank you for the info!

For anyone wondering how to use this, you can replace
`self.play(*animations)`, which runs all at once with `self.play(AnimationGroup(*animations, lag_ratio=0.04))`, which runs with lag ratio of 0.04.
