### ISSUE TITLE
"ImportError: No module named PIL" even after "pip install -r requirements.txt" and Pillow installed

### ISSUE THREAD

**Issue by JoeyKL** [3b1b/manim#56]
Hi,

To test out the library, I downloaded & opened the zip, navigated into the directory, installed dependency, and executed `pip install -r requirements.txt` and then `python extract_scene.py -p example_scenes.py SquareToCircle`, yielding the following.

    Traceback (most recent call last):
      File "extract_scene.py", line 12, in <module>
        from helpers import *
      File "/Users/joeykellison-linn/Desktop/manim-master/helpers.py", line 4, in <module>
        from PIL import Image
    ImportError: No module named PIL

This confuses me greatly. Pillow is definitely installed. I'm on a Mac running python installed by homewbrew. Thoughts?

**Comment by theshteves** [comment]
Which exact version of Python are you running?
Are you able to open up the intended Python version's console and do that import manually without running the module?

You probably installed PIL for a wrong 2/3 version of python,
...or if you installed it properly, you might be trying to run it with the wrong python interpreter version.

**Comment by vors** [comment]
Related
https://stackoverflow.com/questions/8863917/importerror-no-module-named-pil

**Comment by eulertour** [comment]
Closing, as this issue seems to be resolved.
