### ISSUE TITLE
AnimationGroup does not play the same animation twice

### ISSUE THREAD

**Issue by epicycloids** [3b1b/manim#560]
AnimationGroup seems not to play the same animation twice, as demonstrated with the following example:

```class Testing5(Scene):
    def construct(self):
        text=TextMobject("start")
        text.to_corner(RIGHT + UP)
        squares = VGroup()
        for i in range(9):
            squares.add(Square())
        squares.arrange_in_grid(n_rows=3, n_cols=3)
        self.add(squares)
        anims=[]
        for i in range(18):
            anims.append(FadeToColor(squares[i%9],RED,rate_func=there_and_back))
        self.play(Write(text))
        self.play(AnimationGroup(
            *anims,
            lag_ratio=0.1,
            group=Group(*[anim.mobject for anim in anims])))
        self.play(Transform(text,TextMobject("end").to_corner(RIGHT + UP)))
        self.wait()
```
One might expect that this would show the squares changing color in a cascading pattern _twice_, however as seen in the actual rendered animation, this does not happen. Rather, it only plays the second instance of each animation. (I added the start/end text to denote the relative time of the animation since gifs loop):

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/51128420/58492418-e1565e00-813e-11e9-89b4-ffe1fb1ea457.gif)

Note that I tried to fix this by specifying the group to include all the anim.mobjects, since I thought the problem was stemming from the definition of AnimationGroup assigning group to the list of anim.mobjects without redundancies. I have also tried going through and changing the definition of get_family() and remove_updater() so that they don't remove redundancies but nothing seemed to work.

I apologize if this is an easy fix; this is my first time actually coding anything so I am still rather inexperienced.

**Comment by 3b1b** [comment]
If you want an animation to apply to a given mobject two times in a row like this, use Succession.  So in this case, you'd want to do an AnimationGroup of 9 different Succession's.

When a given animation begins, it starts to mess with the state of its underlying mobject, so trying to run multiple animations with the same mobject, as is happening here, may result in these animations fighting over which one controls that mobject's state.  Using Succession should, at least in principle, take care of the hand-off of state control from one animation to the next.

**Comment by epicycloids** [comment]
D'oh, I tried doing Succession of AnimationGroups but for some reason did not try the other way around. Thanks!
