### ISSUE TITLE
Latex error converting to dvi.

### ISSUE THREAD

**Issue by michel9092** [3b1b/manim#564]
'latex' is not recognized as an internal or external command,
operable program or batch file.

Traceback (most recent call last):
  File "C:\Manim\manimlib\extract_scene.py", line 150, in main
    scene = SceneClass(**scene_kwargs)
  File "C:\Manim\manimlib\scene\scene.py", line 52, in __init__
    self.construct()
  File "example_scenes.py", line 213, in construct
    tex_to_color_map={"text": YELLOW}
  File "C:\Manim\manimlib\mobject\svg\tex_mobject.py", line 144, in __init__
    self, self.arg_separator.join(tex_strings), **kwargs
  File "C:\Manim\manimlib\mobject\svg\tex_mobject.py", line 44, in __init__
    self.template_tex_file_body
  File "C:\Manim\manimlib\utils\tex_file_writing.py", line 19, in tex_to_svg_file
    dvi_file = tex_to_dvi(tex_file)
  File "C:\Manim\manimlib\utils\tex_file_writing.py", line 67, in tex_to_dvi
    "See log output above or the log file: %s" % log_file)
Exception: Latex error converting to dvi. See log output above or the log file: .\files\Tex\34b95eca9f7c5b73.log

Hello everyone, I know this is an old problem, but all the solutions mentioned before doesn't seem to work for me ( I am using Windows 10, the newest version of python3.7, miktex, FFmpeg, Cairo, and Sox).
I was trying to run the "WriteStuff" code in "example_scenes.py" when this happened.
If Latex not being recognized is the problem, how can i change it? ( I'm new, so if you can post a step by step solution i would be very greatful)

**Comment by Elteoremadebeethoven** [comment]
Full MikTeX?

**Comment by michel9092** [comment]
Yes full MikTex, here are some photos that might help with the problem

![Screenshot (4)](https://user-images.githubusercontent.com/38926044/58568814-c2f96c80-81e9-11e9-88bd-fd5dd21e7e80.png)
![Screenshot (5)](https://user-images.githubusercontent.com/38926044/58568816-c2f96c80-81e9-11e9-85a2-8ef214831caf.png)
![Screenshot (6)](https://user-images.githubusercontent.com/38926044/58568817-c3920300-81e9-11e9-8527-81f94759a38d.png)

**Comment by michel9092** [comment]
Yes full MikTeX, here are some photos that might help
![InkedScreenshot (6)_LI](https://user-images.githubusercontent.com/38926044/58569705-7e6ed080-81eb-11e9-9fd6-0f8014f6b014.jpg)
![InkedScreenshot (5)_LI](https://user-images.githubusercontent.com/38926044/58569716-83338480-81eb-11e9-90c2-452e252fa24f.jpg)
![Inked _LI](https://user-images.githubusercontent.com/38926044/58569724-84fd4800-81eb-11e9-8cbd-03f910b19445.jpg)

**Comment by Kolloom** [comment]
there should be another folder ``x64`` under the bin directory, where the ``latex.exe`` resides. add that folder instead.

**Comment by michel9092** [comment]
@Kolloom 
I will check it during the night, internet would be faster to download these things, Thanks!

**Comment by michel9092** [comment]
So my problem was that miktex setup was missing alot of files,i dont loaded the portable edition and it did the trick, so now latex was identified by cmd. Now this was not enough since the error converting to dvi was still there, so i copied the code from issue #36 and everything worked.
@Kolloom @Elteoremadebeethoven  Thanks guys

**Comment by girishgargcool** [comment]
> So my problem was that miktex setup was missing alot of files,i downoaded the portable edition and it did the trick, so now latex is identified by cmd. Now this was not enough since the error converting to dvi was still there, so i copied the code from issue #36 and everything worked.
> @Kolloom @Elteoremadebeethoven Thanks guys

I think I have the same issue. Many files are missing. Please tell me how you installed those
