### ISSUE TITLE
Update graph_scene.py

### ISSUE THREAD

**Issue by Elteoremadebeethoven** [3b1b/manim#568]
Change the lines [520-522](https://github.com/3b1b/manim/blob/master/manimlib/scene/graph_scene.py#L520)
```python3
            Transform(area, new_area).update(1)
            Transform(left_v_line, new_left_v_line).update(1)
            Transform(right_v_line, new_right_v_line).update(1)
```
To
```python3
            area.become(new_area)
            left_v_line.become(new_left_v_line)
            right_v_line.become(new_right_v_line)
```

**Comment by Kolloom** [comment]
why

**Comment by Elteoremadebeethoven** [comment]
Nevermind, all the code needs to be update.

**Comment by Kolloom** [comment]
3b1b mentioned that the graph_scene is quite outdated compare to the rest of the codebase, but its low on priority.

**Comment by Elteoremadebeethoven** [comment]
Yes, what happens is that I used an old version without realizing it, and I thought that they had already solved it. My mistake
