### ISSUE TITLE
docker, starting container process caused "exec: \"manim\ ": executable file not found in $PATH": unknown 

### ISSUE THREAD

**Issue by quinn-dougherty** [3b1b/manim#579]
I'm new to Docker and Compose. Once I grok this, I'd really like to write tutorials on Docker and Manim. 

I've been wrestling with this. 
```
ERROR: Cannot start service manim: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"manim\
": executable file not found in $PATH": unknown 
```
it comes up almost every command and configuration I can think of.

I git cloned my fork of the repo, have Docker and Compose installed, and the image is cached. 

I have env vars in my shell, because I ran 
```export MANIM_PATH=$(pwd)```

And the following commands all seem equivalent: 
```
//// omitting it because the var is set in the shell context. 
docker-compose run manim example_scenes.py SquareToCircle -l

//// exactly what it says in README.md#Using Docker
MANIM_PATH=$(pwd) docker-compose run manim example_scenes.py SquareToCircle -l

//// using Compose command line arg for environment
docker-compose run -e MANIM_PATH=$(pwd) manim example_scenes.py SquareToCircle -l
```

they all give the same error: `OCI runtime create failed`, `/manim/ executable file not found in $PATH`, etc.

I also attempted this 
`docker-compose run -e PATH=$(pwd):$PATH ... `, to no avail. 

I'm not messing with any [`.env` file in docker-compose.yml](https://docs.docker.com/compose/env-file/) until i figure this out. 

I've also attempted different things with the volumes. I don't know if that's related, but the instructions weren't straightforward. Most of what I tried was either setting `INPUT_DIR` and `OUTPUT_DIR` to `$(pwd)`, or just commenting out the volumes section entirely. --- no effect on this error unless I try to use the `volumes:` part exactly as it looks in the repo, resulting in the error `ERROR: Invalid interpolation format for "volumes" option in service "manim": `

OS: Ubuntu 18.04.2 LTS

**Comment by Kolloom** [comment]
I don't use the docker version. Can @eulertour comment on this?

**Comment by eulertour** [comment]
The current compose file doesn't use `MANIM_PATH`, so you don't need to set that. @quinn-dougherty it seems like you're using an older version of the compose file, and possibly an old version of `docker-compose`. That said, I actually need to update the current compose file after f81c275631b02d0914c3c83f26d2709dd770089d. The `/manim/ executable file not found in $PATH` error means the `manim` command can't be run in the container.

For debugging purposes, it may be helpful to run the container interactively with `docker run -it manim`, which will work as long as the Dockerfile contains `ENTRYPOINT ["/bin/bash"]`. This will allow you to test the effects of different flags individually before moving to `docker-compose`.

It's important to understand that using docker is essentially the same as running commands on a new install of the image os, and that bind mounting is just a way to map directories from the host (your computer) into the container that's spawned. For example, in `docker-compose run -e MANIM_PATH=$(pwd) manim example_scenes.py SquareToCircle -l` you're setting the `MANIM_PATH` environment variable in the _container_ to a path on the _host_, which is bound to cause errors.

**Comment by eulertour** [comment]
I updated the Compose file and README.md entry in f6dc1cb50fd6caa2fa7961f1395a11d586ca81c4. Post again if you have more questions.

**Comment by quinn-dougherty** [comment]
Thank you for those updates!
