### ISSUE TITLE
How can the quality be so high using ffmpeg?

### ISSUE THREAD

**Issue by jeffx99** [3b1b/manim#59]
No explicit settings have been set for the bitrate or quality. How is it that the videos produced have such a high quality to them? I have tried using the same exact settings and get very poor video quality.

**Comment by anthonynorthrup314** [comment]
There is a guide [here](https://trac.ffmpeg.org/wiki/Encode/H.264#LosslessH.264) for modifying the ffmpeg parameters to create a better quality video. You can specify the Constant Rate Factor (CRF) to change the quality of the video. Below is a snippet of the page linked:

> Tip: If you're looking for an output that is roughly "visually lossless" but not technically lossless, use a -crf value of around 17 or 18 (you'll have to experiment to see which value is acceptable for you). It will likely be indistinguishable from the source and not result in a huge, possibly incompatible file like true lossless mode.

You can modify command array in the `open_movie_pipe` method in `manim/scene/scene.py` to have `"-crf", "17",` just before log level.

**Comment by eulertour** [comment]
Closing, as this issue seems to be resolved.
