### ISSUE TITLE
Image Import Error

### ISSUE THREAD

**Issue by kellybrower** [3b1b/manim#6]
Also` I went through the README and it looks like line 5 of selftest.py leads to there being a problem with the image it's trying to import.

See here:

`aggdraw-64bits kbrower$ python selftest.py
Traceback (most recent call last):
File "selftest.py", line 5, in 
import Image
ImportError: No module named Image`

**Comment by jbaldus** [comment]
Did you run the command `pip -r requirements.txt` in the original manim directory?  The Image module is provided by PIL, which should be installed when you you run that command.

**Comment by diego898** [comment]
I also received this error when trying to install using pip, as I described in #4

**Comment by kellybeach** [comment]
@jbaldus 

Which is the original manim directory?

Could you kindly instruct me on how to run the command `pip -r requirements.txt` in the original manim?

**Comment by diego898** [comment]
@kellybeach once you clone this repository as: 

`git clone https://github.com/3b1b/manim.git`

That should create a directory called `manim` . You then `cd` (change directory) into as: 

`cd manim`

Once there, you can type:

`pip -r requirements.txt` 

to install all of the missing requirements.

**Comment by kellybeach** [comment]
@diego898 

Well Diego, thank you, but this is what came about:

`Kellys-MacBook-Pro:~ kbrower$ cd $TMPDIR
Kellys-MacBook-Pro:T kbrower$ git clone https://github.com/3b1b/manim.git
Cloning into 'manim'...
remote: Counting objects: 2194, done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 2194 (delta 25), reused 0 (delta 0), pack-reused 2149
Receiving objects: 100% (2194/2194), 1.11 MiB | 1.21 MiB/s, done.
Resolving deltas: 100% (1627/1627), done.
Checking connectivity... done.
Kellys-MacBook-Pro:T kbrower$ cd manim
Kellys-MacBook-Pro:manim kbrower$ pip -r requirements.txt
-bash: pip: command not found`

**Comment by jbaldus** [comment]
@kellybeach 

`sudo easy_install pip` should install pip for you.

**Comment by kellybeach** [comment]
@jbaldus 

Here were are now, same ending results.

`Kellys-MacBook-Pro:manim kbrower$ sudo easy_install pip
Password:
Searching for pip
Reading https://pypi.python.org/simple/pip/
Best match: pip 8.1.2
Downloading https://pypi.python.org/packages/e7/a8/7556133689add8d1a54c0b14aeff0acb03c64707ce100ecd53934da1aa13/pip-8.1.2.tar.gz#md5=87083c0b9867963b29f7aba3613e8f4a
Processing pip-8.1.2.tar.gz
Writing /tmp/easy_install-hPFkjh/pip-8.1.2/setup.cfg
Running pip-8.1.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-hPFkjh/pip-8.1.2/egg-dist-tmp-ILRlb_
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching '.mailmap'
warning: no previously-included files found matching '.travis.yml'
warning: no previously-included files found matching '.landscape.yml'
warning: no previously-included files found matching 'pip/_vendor/Makefile'
warning: no previously-included files found matching 'tox.ini'
warning: no previously-included files found matching 'dev-requirements.txt'
warning: no previously-included files found matching 'appveyor.yml'
no previously-included directories found matching '.github'
no previously-included directories found matching '.travis'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'contrib'
no previously-included directories found matching 'tasks'
no previously-included directories found matching 'tests'
Adding pip 8.1.2 to easy-install.pth file
Installing pip script to /usr/local/bin
Installing pip2.7 script to /usr/local/bin
Installing pip2 script to /usr/local/bin

Installed /Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg
Processing dependencies for pip
Finished processing dependencies for pip
Kellys-MacBook-Pro:manim kbrower$ cd aggdraw_64bits
-bash: cd: aggdraw_64bits: No such file or directory
Kellys-MacBook-Pro:manim kbrower$ cd aggdraw64_bits
-bash: cd: aggdraw64_bits: No such file or directory
Kellys-MacBook-Pro:manim kbrower$ cd aggdraw
-bash: cd: aggdraw: No such file or directory
Kellys-MacBook-Pro:manim kbrower$ cd $TMPDIR
Kellys-MacBook-Pro:T kbrower$ git cd aggdraw-64bits
git: 'cd' is not a git command. See 'git --help'.

Did you mean this?
	add
Kellys-MacBook-Pro:T kbrower$ cd aggdraw-64bits
-bash: cd: aggdraw-64bits: No such file or directory
Kellys-MacBook-Pro:T kbrower$ git clone https://github.com/scottopell/aggdraw-64bits
Cloning into 'aggdraw-64bits'...
remote: Counting objects: 219, done.
remote: Total 219 (delta 0), reused 0 (delta 0), pack-reused 219
Receiving objects: 100% (219/219), 309.41 KiB | 105.00 KiB/s, done.
Resolving deltas: 100% (107/107), done.
Checking connectivity... done.
Kellys-MacBook-Pro:T kbrower$ cd aggdraw-64bits
Kellys-MacBook-Pro:aggdraw-64bits kbrower$ python setup build_ext -i
python: can't open file 'setup': [Errno 2] No such file or directory
Kellys-MacBook-Pro:aggdraw-64bits kbrower$ python setup.py install
=== freetype support disabled
running install
running build
running build_ext
building 'aggdraw' extension
creating build
creating build/temp.macosx-10.11-intel-2.7
creating build/temp.macosx-10.11-intel-2.7/agg2
creating build/temp.macosx-10.11-intel-2.7/agg2/src
cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -Iagg2/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c aggdraw.cxx -o build/temp.macosx-10.11-intel-2.7/aggdraw.o
aggdraw.cxx:1122:5: warning: delete called on 'draw_adaptor_base' that is
      abstract but has non-virtual destructor [-Wdelete-non-virtual-dtor]
    delete self->draw;
    ^
aggdraw.cxx:169:21: warning: unused variable 'FontType' [-Wunused-variable]
static PyTypeObject FontType = {
                    ^
2 warnings generated.
aggdraw.cxx:518:25: warning: implicit conversion loses integer precision:
      'Py_ssize_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
        int data_size = PyString_GET_SIZE(buffer);
            ~~~~~~~~~   ^~~~~~~~~~~~~~~~~~~~~~~~~
/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/stringobject.h:92:32: note: 
      expanded from macro 'PyString_GET_SIZE'
#define PyString_GET_SIZE(op)  Py_SIZE(op)
                               ^~~~~~~~~~~
/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/object.h:116:56: note: 
      expanded from macro 'Py_SIZE'
#define Py_SIZE(ob)             (((PyVarObject*)(ob))->ob_size)
                                 ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
aggdraw.cxx:576:9: warning: implicit conversion loses integer precision:
      'Py_ssize_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
    n = PyObject_Length(xyIn);
      ~ ^~~~~~~~~~~~~~~~~~~~~
/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/abstract.h:434:25: note: 
      expanded from macro 'PyObject_Length'
#define PyObject_Length PyObject_Size
                        ^
aggdraw.cxx:627:19: warning: implicit conversion loses integer precision: 'long'
      to 'int' [-Wshorten-64-to-32]
        int ink = PyInt_AsLong(color);
            ~~~   ^~~~~~~~~~~~~~~~~~~
aggdraw.cxx:634:21: warning: implicit conversion loses integer precision: 'long'
      to 'int' [-Wshorten-64-to-32]
            int i = strtol(ink+1, NULL, 16); /* FIXME: rough parsing */
                ~   ^~~~~~~~~~~~~~~~~~~~~~~
aggdraw.cxx:1122:5: warning: delete called on 'draw_adaptor_base' that is
      abstract but has non-virtual destructor [-Wdelete-non-virtual-dtor]
    delete self->draw;
    ^
aggdraw.cxx:169:21: warning: unused variable 'FontType' [-Wunused-variable]
static PyTypeObject FontType = {
                    ^
6 warnings generated.
cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -Iagg2/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c agg2/src/agg_arc.cpp -o build/temp.macosx-10.11-intel-2.7/agg2/src/agg_arc.o
cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -Iagg2/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c agg2/src/agg_bezier_arc.cpp -o build/temp.macosx-10.11-intel-2.7/agg2/src/agg_bezier_arc.o
cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -Iagg2/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c agg2/src/agg_curves.cpp -o build/temp.macosx-10.11-intel-2.7/agg2/src/agg_curves.o
cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -Iagg2/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c agg2/src/agg_path_storage.cpp -o build/temp.macosx-10.11-intel-2.7/agg2/src/agg_path_storage.o
cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -Iagg2/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c agg2/src/agg_rasterizer_scanline_aa.cpp -o build/temp.macosx-10.11-intel-2.7/agg2/src/agg_rasterizer_scanline_aa.o
cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -Iagg2/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c agg2/src/agg_trans_affine.cpp -o build/temp.macosx-10.11-intel-2.7/agg2/src/agg_trans_affine.o
cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -Iagg2/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c agg2/src/agg_vcgen_contour.cpp -o build/temp.macosx-10.11-intel-2.7/agg2/src/agg_vcgen_contour.o
cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -Iagg2/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c agg2/src/agg_vcgen_stroke.cpp -o build/temp.macosx-10.11-intel-2.7/agg2/src/agg_vcgen_stroke.o
creating build/lib.macosx-10.11-intel-2.7
c++ -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -Wl,-F. build/temp.macosx-10.11-intel-2.7/aggdraw.o build/temp.macosx-10.11-intel-2.7/agg2/src/agg_arc.o build/temp.macosx-10.11-intel-2.7/agg2/src/agg_bezier_arc.o build/temp.macosx-10.11-intel-2.7/agg2/src/agg_curves.o build/temp.macosx-10.11-intel-2.7/agg2/src/agg_path_storage.o build/temp.macosx-10.11-intel-2.7/agg2/src/agg_rasterizer_scanline_aa.o build/temp.macosx-10.11-intel-2.7/agg2/src/agg_trans_affine.o build/temp.macosx-10.11-intel-2.7/agg2/src/agg_vcgen_contour.o build/temp.macosx-10.11-intel-2.7/agg2/src/agg_vcgen_stroke.o -o build/lib.macosx-10.11-intel-2.7/aggdraw.so
running install_lib
copying build/lib.macosx-10.11-intel-2.7/aggdraw.so -> /Library/Python/2.7/site-packages
error: could not delete '/Library/Python/2.7/site-packages/aggdraw.so': Permission denied
Kellys-MacBook-Pro:aggdraw-64bits kbrower$ python setup.py build_ext -i
=== freetype support disabled
running build_ext
building 'aggdraw' extension
cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -Iagg2/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c aggdraw.cxx -o build/temp.macosx-10.11-intel-2.7/aggdraw.o
aggdraw.cxx:1122:5: warning: delete called on 'draw_adaptor_base' that is
      abstract but has non-virtual destructor [-Wdelete-non-virtual-dtor]
    delete self->draw;
    ^
aggdraw.cxx:169:21: warning: unused variable 'FontType' [-Wunused-variable]
static PyTypeObject FontType = {
                    ^
2 warnings generated.
aggdraw.cxx:518:25: warning: implicit conversion loses integer precision:
      'Py_ssize_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
        int data_size = PyString_GET_SIZE(buffer);
            ~~~~~~~~~   ^~~~~~~~~~~~~~~~~~~~~~~~~
/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/stringobject.h:92:32: note: 
      expanded from macro 'PyString_GET_SIZE'
#define PyString_GET_SIZE(op)  Py_SIZE(op)
                               ^~~~~~~~~~~
/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/object.h:116:56: note: 
      expanded from macro 'Py_SIZE'
#define Py_SIZE(ob)             (((PyVarObject*)(ob))->ob_size)
                                 ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
aggdraw.cxx:576:9: warning: implicit conversion loses integer precision:
      'Py_ssize_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
    n = PyObject_Length(xyIn);
      ~ ^~~~~~~~~~~~~~~~~~~~~
/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/abstract.h:434:25: note: 
      expanded from macro 'PyObject_Length'
#define PyObject_Length PyObject_Size
                        ^
aggdraw.cxx:627:19: warning: implicit conversion loses integer precision: 'long'
      to 'int' [-Wshorten-64-to-32]
        int ink = PyInt_AsLong(color);
            ~~~   ^~~~~~~~~~~~~~~~~~~
aggdraw.cxx:634:21: warning: implicit conversion loses integer precision: 'long'
      to 'int' [-Wshorten-64-to-32]
            int i = strtol(ink+1, NULL, 16); /* FIXME: rough parsing */
                ~   ^~~~~~~~~~~~~~~~~~~~~~~
aggdraw.cxx:1122:5: warning: delete called on 'draw_adaptor_base' that is
      abstract but has non-virtual destructor [-Wdelete-non-virtual-dtor]
    delete self->draw;
    ^
aggdraw.cxx:169:21: warning: unused variable 'FontType' [-Wunused-variable]
static PyTypeObject FontType = {
                    ^
6 warnings generated.
cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -Iagg2/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c agg2/src/agg_arc.cpp -o build/temp.macosx-10.11-intel-2.7/agg2/src/agg_arc.o
cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -Iagg2/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c agg2/src/agg_bezier_arc.cpp -o build/temp.macosx-10.11-intel-2.7/agg2/src/agg_bezier_arc.o
cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -Iagg2/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c agg2/src/agg_curves.cpp -o build/temp.macosx-10.11-intel-2.7/agg2/src/agg_curves.o
cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -Iagg2/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c agg2/src/agg_path_storage.cpp -o build/temp.macosx-10.11-intel-2.7/agg2/src/agg_path_storage.o
cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -Iagg2/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c agg2/src/agg_rasterizer_scanline_aa.cpp -o build/temp.macosx-10.11-intel-2.7/agg2/src/agg_rasterizer_scanline_aa.o
cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -Iagg2/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c agg2/src/agg_trans_affine.cpp -o build/temp.macosx-10.11-intel-2.7/agg2/src/agg_trans_affine.o
cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -Iagg2/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c agg2/src/agg_vcgen_contour.cpp -o build/temp.macosx-10.11-intel-2.7/agg2/src/agg_vcgen_contour.o
cc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -Iagg2/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c agg2/src/agg_vcgen_stroke.cpp -o build/temp.macosx-10.11-intel-2.7/agg2/src/agg_vcgen_stroke.o
c++ -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -Wl,-F. build/temp.macosx-10.11-intel-2.7/aggdraw.o build/temp.macosx-10.11-intel-2.7/agg2/src/agg_arc.o build/temp.macosx-10.11-intel-2.7/agg2/src/agg_bezier_arc.o build/temp.macosx-10.11-intel-2.7/agg2/src/agg_curves.o build/temp.macosx-10.11-intel-2.7/agg2/src/agg_path_storage.o build/temp.macosx-10.11-intel-2.7/agg2/src/agg_rasterizer_scanline_aa.o build/temp.macosx-10.11-intel-2.7/agg2/src/agg_trans_affine.o build/temp.macosx-10.11-intel-2.7/agg2/src/agg_vcgen_contour.o build/temp.macosx-10.11-intel-2.7/agg2/src/agg_vcgen_stroke.o -o /private/var/folders/22/tc_89dvs4373xjq58vb_9dl40000gn/T/aggdraw-64bits/aggdraw.so
Kellys-MacBook-Pro:aggdraw-64bits kbrower$ python extract_scene.py -p example_scenes.py SquareToCircle
python: can't open file 'extract_scene.py': [Errno 2] No such file or directory
Kellys-MacBook-Pro:aggdraw-64bits kbrower$ python example_scenes.py SquareToCircle
python: can't open file 'example_scenes.py': [Errno 2] No such file or directory
Kellys-MacBook-Pro:aggdraw-64bits kbrower$ `

**Comment by Spstolar** [comment]
I've had similar issues with aggdraw--using Python2.7 on Windows 10. I've tried redownloading PIL, and didn't really get anything. One thing I ran into was replacing disutils.core in line 15 of aggdraw's setup.py with setuptools. This got rid of the 'No module named Image' error, but still gave me issues when I ran the selftest.py

Then I tried uninstalling PIL and instead using pillow. That gave the same trouble, but cleared up a bit when I used the https://github.com/jakul/aggdraw clone instead. That allowed the selftest to finally run, but 6 of the tests failed. It seems like its having trouble identifying PIL im structures. 

Googling around showed that there might bit something amiss with _imaging.pyd. The file is in my libraries folder, but does not run when I call the Image module inside of 'python -v'.

**Comment by jbaldus** [comment]
@kellybeach 
It looks like you got aggdraw installed, but you ran in to trouble trying to run `python extract_scene.py` in a directory that is not the same as your manim file.  Try running it in the manim directory.

**Comment by themangokid** [comment]
What am I doing wrong?

vm@ubuntu:~/manim-master$ python extract_scene.py -p example_scenes.py SquareToCircle

Traceback (most recent call last):
  File "extract_scene.py", line 208, in main
    handle_scene(SceneClass(**scene_kwargs), **config)
  File "/home/vm/manim-master/scene/scene.py", line 36, in __init__
    self.construct(*self.construct_args)
  File "/home/vm/manim-master/./example_scenes.py", line 34, in construct
    self.play(ShowCreation(square))
  File "/home/vm/manim-master/scene/scene.py", line 228, in play
    self.update_frame(static_mobjects)
  File "/home/vm/manim-master/scene/scene.py", line 69, in update_frame
    self.camera.capture_mobjects(mobjects, **kwargs)
  File "/home/vm/manim-master/camera.py", line 83, in capture_mobjects
    canvas = aggdraw.Draw(image)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 510, in __getattr__
    raise AttributeError(name)
AttributeError: tobytes


sh: 1: play: not found

**Comment by 3b1b** [comment]
So, as a general answer, I have to admit that I've not been tracking dependencies well when I change libraries, use new ones, etc.  For this specific issue, aggdraw for some reason only works with an older version of PIL, so uninstall Pillow, then reinstall with "pip install Pillow==1.7.8".

**Comment by kellybeach** [comment]
Hey Grant,

Thanks for the update.

Keep up the good work, but I don't think I'll be un/installing at this
time, as I'm still working my way through learning python in general.

It's a bummer I can't play with it yet, but if it becomes compatible with
the current version let me know.

And my guess is that aggdraw was last updated almost a decade ago if i
remember correctly, so it's natural that it couldn't be easily accessed by
the latest PIL.

Anyways, hope it comes around, I'll be following your progress as a
disruptor of the math education industry. Best of luck.

-Kelly

**Comment by eulertour** [comment]
Closing, as this issue is very old and inactive.
