### ISSUE TITLE
Error related to ffmpeg

### ISSUE THREAD

**Issue by Planeuge** [3b1b/manim#603]
So, my issue is literally the same as the #415 (see screenshot), but I'm not very familiar with UNIX commands, so I tried a few things like `$ chmod 777 example_scenes.py` but I still get the same message:

![Capture d’écran 2019-06-18 à 14 11 52](https://user-images.githubusercontent.com/51932153/59681129-6deebc00-91d3-11e9-8e24-4919047052ec.png)

So I guess I might not be using the `chmod` command correctly ?

**Comment by Kolloom** [comment]
is this osx? 

Did you install ffmpeg? https://github.com/3b1b/manim/blob/master/docs/source/installation/mac.rst

Check it by running ffmpeg from command line.

**Comment by Planeuge** [comment]
Yes, it is OSX

Yes, I even tried re-installing it

**Comment by Kolloom** [comment]
apologies I didn't see that on the first time. please run it like so 
`python3 ./manim.py example_scenes.py SquareToCircle -pl`

**Comment by Planeuge** [comment]
Well, I reinstalled everything from the beginning, ran your command and it work perfectly, thanks ! But may I ask why yours work ? I mean, what means every part of it ? If you don't bother explaining :)

**Comment by Kolloom** [comment]
The rendering is done in `extract_scene.py` which is called by `manim.py`. There is some discussion on improve this workflow. 

Please close the issue.
