### ISSUE TITLE
PROBLEM IN INSTALLING PYCAIRO      

### ISSUE THREAD

**Issue by girishgargcool** [3b1b/manim#618]
Ref Youtube video: Manim Tutorial Installation on Windows by Theorem of Beethoven
https://www.youtube.com/watch?v=ZltiKHFWmv8
Check 8:46 of the video

I was going through this video about installing manim and was trying to do the same on my PC. I was stuck at 8:46 where pycairo is being installed.

![pycairo problem](https://user-images.githubusercontent.com/52619530/60765120-a981f500-a0b2-11e9-86af-ef667fcc1069.png)
 
PLEASE HELP

**Comment by Elteoremadebeethoven** [comment]
Try with version of 32 bits:
![Captura de pantalla 2019-07-07 a la(s) 02 02 19](https://user-images.githubusercontent.com/43224662/60765158-4fa21080-a05b-11e9-9851-a996b69929a6.png)
Or the another:
![Captura de pantalla 2019-07-07 a la(s) 02 02 19](https://user-images.githubusercontent.com/43224662/60765161-63e60d80-a05b-11e9-9577-77c554a71280.png)

**Comment by girishgargcool** [comment]
I did. Same issue

**Comment by Elteoremadebeethoven** [comment]
Send the ScreenShots of every one.

**Comment by girishgargcool** [comment]
I just restarted my PC and again tried to install the 32 bit version. Voila!
![Screenshot (12)](https://user-images.githubusercontent.com/52619530/60765240-a1c35000-a0b4-11e9-8f06-c4f50a394f2d.png)

**Comment by Elteoremadebeethoven** [comment]
Perfect
