### ISSUE TITLE
WHICH TEXT TO DELETE FROM requirements.txt ?

### ISSUE THREAD

**Issue by girishgargcool** [3b1b/manim#619]
Ref Youtube video: Manim Tutorial Installation on Windows by Theorem of Beethoven
https://www.youtube.com/watch?v=ZltiKHFWmv8
Check 10:18 of the video

Please tell me which pycairo text should I delete? In the video Alexander shows to delete pycairo, but I have got two texts. Please help

![Screenshot (13)](https://user-images.githubusercontent.com/52619530/60765276-b227fa80-a0b5-11e9-8ff0-ac04318e59d0.png)

**Comment by Elteoremadebeethoven** [comment]
For my tutorials you have to use [this version](https://github.com/3b1b/manim/tree/3b088b12843b7a4459fe71eba96b70edafb7aa78).

That version that you donwloaded is the most recent, if you have use that version you have to remove this:
```
pycairo==1.17.1; sys_platform == 'linux'
pycairo==1.18.0; sys_platform == 'win32'
```

**Comment by Elteoremadebeethoven** [comment]
One more thing, if you have problems with Manim you have to post your problems here, but if you have problems with the codes or procedures of my tutorials (from topic 1.1) you have to do it on my [GitHub page](https://github.com/Elteoremadebeethoven/AnimationsWithManim/issues).

**Comment by girishgargcool** [comment]
got it.

**Comment by Elteoremadebeethoven** [comment]
Please close the issue if it works.
