### ISSUE TITLE
Color undefined

### ISSUE THREAD

**Issue by xy-23** [3b1b/manim#626]
The command I ran like
```
from manimlib.imports import *

class Playground(Scene):
    def construct(self):
        squ = Square(fill_opacity=1, color=RED)
        self.play(FadeIn(squ))
```
Although it can run successfully, vscode keeps on warning me 
`Undefined variable 'RED'`

But if I run command like
```
from manimlib.imports import *

class Playground(Scene):
    def construct(self):
        squ = Square(fill_opacity=1, color=COLOR_MAP["RED_C"])
        self.play(FadeIn(squ))
```
It would not pop out the warning.

**Comment by Elteoremadebeethoven** [comment]
Thats weird, the purpose of [this code](https://github.com/3b1b/manim/blob/master/manimlib/constants.py#L236) is to convert the COLORS_C to COLORS, verify that nothing has been modified.

**Comment by xy-23** [comment]
I didn't change those codes, the warning is given by the ide(vscode pylint), actually it can run successfully.

I think the reason why it pops out warning is that it only defined when running the code, not defined at the very beginning, so the ide can't recognize before running it.

I think the more porper way is to define it clearly instead of implicit statement(generate).
like `RED = '#FC6255'`

Although it is a not very import problem, it is very annoying to me.

**Comment by Elteoremadebeethoven** [comment]
Most likely that's it, I compiled it with a terminal (I'm quite traditional) and it does not give any warning. IDEs usually have their problems.

**Comment by xy-23** [comment]
In other word, I think it is a little bit complicated than define it directly.

**Comment by eulertour** [comment]
This is the IDE warning you that `import *` isn't a good practice. It's right, but it's fine for small scripts.
