### ISSUE TITLE
Text rendering problem

### ISSUE THREAD

**Issue by xy-23** [3b1b/manim#627]
### Steps to reproduce
```
from manimlib.imports import *

class Playground(Scene):
    def construct(self):
        text = TextMobject("print('Hello, world!')",
                           tex_to_color_map={'print': YELLOW})
        self.play(FadeIn(text))
```
### The unexpected behavior that occurred
Notice between the 'print' and the '(' there is no space.

Wrong
![wrong](https://user-images.githubusercontent.com/47266984/60874808-2fe13700-a26b-11e9-8042-85041a680656.png)

Right
![right](https://user-images.githubusercontent.com/47266984/60874825-35d71800-a26b-11e9-9d20-2dcc2fe515d5.png)
### Solution
I changed [here](https://github.com/3b1b/manim/blob/master/manimlib/mobject/svg/tex_mobject.py) in line 134

`"arg_separator": " ", --> "arg_separator": "",`

and also commented out [here](https://github.com/3b1b/manim/blob/master/manimlib/mobject/svg/tex_mobject.py) in line 160
```
split_list = [str(x).strip() for x in split_list] --> 
#split_list = [str(x).strip() for x in split_list]
```
I also find some interesting in TexMobject(), no matter how many space I enter, like

`text = TexMobject("print    ('Hello, world!')")`

it always ignored those space.

**Comment by Elteoremadebeethoven** [comment]
Thanks for this!! The reason why TexMobject ignores spaces is because inside the quotes you are writing TeX code, and the TeX code ignores the spaces.

**Comment by sidhanta1989** [comment]
Still i am facing the same problem. Not able to generate spaces between the words.
![SpaceIssue](https://user-images.githubusercontent.com/49337352/101286459-a7c0e180-3810-11eb-88b6-d207e68dbad7.jpg)
