### ISSUE TITLE
Can't Get Example Scene To Run

### ISSUE THREAD

**Issue by ThisPi** [3b1b/manim#639]
I'm new to python (and coding in general) and I'm trying to get Manim to run on my Mac. I've been following the directions on http://bhowell4.com/manic-install-tutorial-for-mac/

I got to the point of trying to test the animations by running:

> python3 extract_scene.py example_scenes.py SquareToCircle -pl

Here is the error message I receive:

> /Users/rdownie/animations/manim/venv/lib/python3.7/site-packages/pydub/utils.py:165: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Traceback (most recent call last):
  File "extract_scene.py", line 163, in <module>
    main()
TypeError: main() missing 1 required positional argument: 'config'

Any help is much appreciated!

**Comment by xy-23** [comment]
It seems like that you didn't download [ffmpeg](https://www.ffmpeg.org/).
The python package of ffmpeg (pip install ffmpeg) requires ffmpeg.

**Comment by ThisPi** [comment]
So I entered 

> pip3 install ffmpeg

and got:

> Requirement already satisfied: ffmpeg in ./venv/lib/python3.7/site-packages (1.4)

**Comment by Elteoremadebeethoven** [comment]
It is 
```
python3 -m manim extract_scene.py example_scenes.py SquareToCircle -pl
```
Or
```
python3 manim.py extract_scene.py example_scenes.py SquareToCircle -pl
```
If you install manim via pip (`pip install manimlib`) then:
```
manim extract_scene.py example_scenes.py SquareToCircle -pl
```

**Comment by ThisPi** [comment]
Okay, I tried what you suggested and here is what it gave me:

>/Users/rdownie/animations/manim/venv/lib/python3.7/site-packages/pydub/utils.py:165: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Media will be written to /Users/rdownie/animations/manim/output/. You can change this behavior with the --media_dir flag.

   There are no scenes inside that module

**Comment by xy-23** [comment]
You need to go to the website https://www.ffmpeg.org/ to download.

**Comment by ThisPi** [comment]
Once I do, does the file need to be anywhere specific?

**Comment by xy-23** [comment]
I'm not sure whether mac need add  ffmpeg to path like windows

**Comment by ThisPi** [comment]
Well, I went to the site and downloaded it but didn't move the file location. I then tried running the test scene again and got:

/Users/rdownie/animations/manim/venv/lib/python3.7/site-packages/pydub/utils.py:165: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Media will be written to /Users/rdownie/animations/manim/output/. You can change this behavior with the --media_dir flag.

   There are no scenes inside that module

**Comment by xy-23** [comment]
You have to add ffmpeg to path

**Comment by ThisPi** [comment]
Okay, super dumb question, but how do I do that?

**Comment by xy-23** [comment]
You can see this video https://www.youtube.com/watch?v=8nbuqYw2OCw

**Comment by ThisPi** [comment]
Thanks! I think I'm making progress, but now when I run it, it gives:

Media will be written to /Users/rdownie/animations/manim/output/. You can change this behavior with the --media_dir flag.

   There are no scenes inside that module

**Comment by xy-23** [comment]
Try to run this
`python3 example_scenes.py SquareToCircle -pl`

**Comment by xy-23** [comment]
Try to run this:
`python3 -m manim example_scenes.py SquareToCircle -pl`

**Comment by ThisPi** [comment]
The last one did it!!!! Thank you for your help and patience!
