### ISSUE TITLE
What is opencv for?

### ISSUE THREAD

**Issue by xy-23** [3b1b/manim#640]
At first I guessed that it was opencv that generated the video, then I found it was ffmpeg that generated the video.
So is opencv being used in manim?

**Comment by Kolloom** [comment]
opencv2 is defined here: https://github.com/3b1b/manim/blob/master/manimlib/scene/scene_from_video.py#L8 and not used anywhere else

**Comment by Kolloom** [comment]
Seem to be some sort of post processing effects.

**Comment by xy-23** [comment]
Thanks! Some old projects rely on it.
