### ISSUE TITLE
ModuleNotFoundError: No module named 'manimlib.continual_animation'

### ISSUE THREAD

**Issue by AlessandroInnocenti95** [3b1b/manim#642]
Hello everyone!
I'm trying to run manim. However, I'm encountering this issue and I don't know how to go on. I verified and "continual_animation" exists in my manim folder.
Can you tell me how to go on?
![Cattura](https://user-images.githubusercontent.com/18037902/61579961-7147d100-ab0c-11e9-83e4-daabc279f4d9.PNG)

**Comment by Elteoremadebeethoven** [comment]
Did you install manim with pip or just download the repository files?

**Comment by AlessandroInnocenti95** [comment]
Well, actually I did both. First only with pip, but It didn't work at all. After, I downloaded the files (following your video :) ) and I made some step forward, but I'm stuck here.

**Comment by Elteoremadebeethoven** [comment]
Uninstall the pip version with: 

`python -m pip uninstall manimlib`

then restart your pc, download the repository again in another folder and try to run that command again.

**Comment by AlessandroInnocenti95** [comment]
Ok, thanks, I'll try It!

**Comment by Rajveer221099** [comment]
I am facing the same issue, but reinstalling is not working for me.
`E:\Software\Manim\manim_3_feb>python -m manim example_scenes.py WriteStuff -pl
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Software\Manim\manim_3_feb\manim.py", line 4, in <module>
    import manimlib.stream_starter
ModuleNotFoundError: No module named 'manimlib.stream_starter'`

how do I fix ModuleNotFoundError: No module named 'manim.stream_starter'??

**Comment by titai1999** [comment]
Hello I am using windows 10 and I am getting the same problem like no module named manim
