### ISSUE TITLE
Is circle `filter_out` function deprecated?

### ISSUE THREAD

**Issue by chiangqiqi** [3b1b/manim#643]
I'm trying to create a semicircle in manim, After digging into the code, I find a `semicircle` definition in `old_projects/music_and_measure.py`.

```
class PianoTuning(Scene):
    def construct(self):
        piano = self.piano = Piano()
        jump = piano.half_note_jump
        semicircle = Circle().filter_out(lambda p : p[1] < 0)
        semicircle.scale(jump/semicircle.get_width())
```

After I tried to use `semicircle = Circle().filter_out(lambda p : p[1] < 0)` , got this error:

`AttributeError: 'Circle' object has no attribute 'filter_out'`

So my question is is this function deprecated? How should I create a `semicircle` now?

**Comment by xy-23** [comment]
I guess it is deprecated.
You can try this:
```
from manimlib.imports import *

class Playground(Scene):
    def construct(self):
        semicircle = Arc(fill_opacity=1, angle=TAU / 2)
        self.add(semicircle)
```

**Comment by chiangqiqi** [comment]
@xy-23 thx for your kind replay,
another question is how `segment` in a circle can be defined? with `filter_out` I can think of a segment is an Arc `filter_out` the other side the line connects it's two end points.
