### ISSUE TITLE
How to make scandinavian letters like ‘æ’, ‘ø’ and ‘å’ in manim?

### ISSUE THREAD

**Issue by mscharling** [3b1b/manim#645]
When I render out a text with one of above mentioned letters it just vanishes.

Example
In: mængde
Out: mngde

**Comment by mscharling** [comment]
When I render out a text with one of above mentioned letters it just vanishes.

Example
In: mængde 
Out: mngde

**Comment by Elteoremadebeethoven** [comment]
You need to install the `siunitx` package to latex, you can easily install it if you use TeXMaker or TeXStudio, when you do it then you need to replace the line (from manimlib/tex_template.tex):

```latex
\usepackage[english]{babel}
```

with

```latex
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{siunitx}
```
Here an example:

```python
class Scandinavian(Scene):
    def construct(self):
        text=TextMobject("""
        mængde,å, ä, ö, ø, æ
        """)
        text.scale(3)
        self.add(text)
```

Result:
![Scandinavian](https://user-images.githubusercontent.com/43224662/61671750-98d69f00-acae-11e9-9d89-7e4afe428f1f.png)

**Comment by mscharling** [comment]
I guess that will do it! Thanks :-)

**Comment by Elteoremadebeethoven** [comment]
If it works please close the issue.
