### ISSUE TITLE
How to make a wavy wave

### ISSUE THREAD

**Issue by jaddoescad** [3b1b/manim#646]
Hello everyone, Im not the smartest tool in the shed and I can't seem to figure this out. I'm trying to create an animated sine wave but it never turns out smooth, it's very choppy, and I'm sure theres a more effective way of doing this.

here is the animation that i get:

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/12466304/61660073-0ecf0c00-ac97-11e9-9527-a0862fd1e359.gif)

and here is the code i used:
```
class fifteenth(GraphScene):
    CONFIG = {
        "x_min": -20,
        "x_max": 20,
        "y_min": -20,
        "y_max": 20,
    }
    def construct(self):
        self.setup_axes()
        self.axes.rotate(180*DEGREES).scale(1).shift(UP*2+RIGHT*2)
        func_graph=self.get_graph(lambda x: np.sin(x), x_min = -20, x_max = 20).set_color(RED)

        wave = VGroup()
        for i in range (1000):
            wave.add(self.get_graph(lambda x: np.sin(x+np.pi*(0.05*i)), x_min = -20, x_max = 20).set_color(RED))

        self.play(ShowCreation(func_graph, run_time=0.2))
        self.play(Succession(*[Transform(func_graph, wave[i]) for i in range(len(wave))],lag_ratio=-1, run_time=10, rate_func=smooth))
        
```

**Comment by Elteoremadebeethoven** [comment]
Check this:

```python
class SineWave(Scene):
    def get_sine_wave(señf,dx=0):
        return FunctionGraph(
            lambda x: np.sin((x+dx)),
            x_min=-4,x_max=4
        )

    def construct(self):
        sine_function=self.get_sine_wave()
        d_theta=ValueTracker(0)
        def update_wave(func):
            func.become(
                self.get_sine_wave(dx=d_theta.get_value())
            )
            return func
        sine_function.add_updater(update_wave)
        self.play(ShowCreation(sine_function))
        self.play(d_theta.increment_value,PI)
        self.wait()
```

More examples [here](https://github.com/Elteoremadebeethoven/AnimationsWithManim/blob/master/English/update_successions/update_successions.py).

**Comment by jaddoescad** [comment]
thank you 
thank you
thank you

**Comment by varunpenumudi** [comment]
@Elteoremadebeethoven, I am getting this error `Object <function _AnimationBuilder.__getattr__.<locals>.update_target at 
 0x000001A9F73C0C20> cannot be converted to an animation` while running your animation and this error originates from the line:

```py
self.play(d_theta.increment_value,2*PI,rate_func=linear)
```

So, i changed this line of code to be like this, now it's working.

```py
self.play(d_theta.animate.increment_value(6*PI), rate_func=linear, run_time=3)
```



> Check this:
> 
> class SineWave(Scene):
>     def get_sine_wave(self,dx=0):
>         return FunctionGraph(
>             lambda x: np.sin((x+dx)),
>             x_min=-4,x_max=4
>         )
> 
>     def construct(self):
>         sine_function=self.get_sine_wave()
>         d_theta=ValueTracker(0)
>         def update_wave(func):
>             func.become(
>                 self.get_sine_wave(dx=d_theta.get_value())
>             )
>             return func
>         sine_function.add_updater(update_wave)
>         self.play(ShowCreation(sine_function))
>         self.play(d_theta.increment_value,2*PI,rate_func=linear)
>         self.wait()
> Result: ![SineWave2](https://user-images.githubusercontent.com/43224662/61672379-fe2b8f80-acb0-11e9-97ed-603512ce096e.gif) 
> 
> More examples [here](https://github.com/Elteoremadebeethoven/AnimationsWithManim/blob/master/English/update_successions/update_successions.py).
