### ISSUE TITLE
Zooming in manim

### ISSUE THREAD

**Issue by mscharling** [3b1b/manim#649]
I've been trying to figure out how to zoom in on a specific point in manim on my own without success. How do I make some kind of zoom animation? It's about settheory and I want to zoom in on one of the more centered points in the set in the picture below and then zoom out to continue in the same scene. How can I make that happen? :-)
![sets](https://user-images.githubusercontent.com/53175715/61910919-3c85b080-af36-11e9-8fde-205f0f087412.png)

**Comment by Elteoremadebeethoven** [comment]
Check [this](https://github.com/Elteoremadebeethoven/AnimationsWithManim/blob/master/English/extra/faqs/faqs.md#change-position-and-size-of-the-camera) and [this](https://github.com/Elteoremadebeethoven/AnimationsWithManim/blob/master/English/extra/faqs/faqs.md#zoomed-scene-example).

**Comment by mscharling** [comment]
But I keep on getting this attribute error: 
self.camera_frame.save_state()
AttributeError: 'introset' object has no attribute 'camera_frame'
How do I fix that?

**Comment by ayano-kagurazaka** [comment]
> Check [this](https://github.com/Elteoremadebeethoven/AnimationsWithManim/blob/master/English/extra/faqs/faqs.md#change-position-and-size-of-the-camera) and [this](https://github.com/Elteoremadebeethoven/AnimationsWithManim/blob/master/English/extra/faqs/faqs.md#zoomed-scene-example).

These examples were deprecated

**Comment by botcs** [comment]
what about 3D animation?
