### ISSUE TITLE
Highlighting part of text

### ISSUE THREAD

**Issue by mscharling** [3b1b/manim#653]
Back with a new question...
If I want to hightlight `$\in$` in the text by making an animation so the symbol gets bigger, how can I do that? 
![xinA](https://user-images.githubusercontent.com/53175715/62000423-d97f4f80-b0d6-11e9-8c16-77c0081563e5.PNG)

**Comment by Elteoremadebeethoven** [comment]
Use `Indicate`, example [here](https://manim-tb-manual.000webhostapp.com/tree/animations/indication.html#indicate)

**Comment by mscharling** [comment]
Once again, thanks!
