### ISSUE TITLE
How to insert a picture in a math video

### ISSUE THREAD

**Issue by xianfengting** [3b1b/manim#656]
Hello everyone, I have some questions about using this math library. Are there any ways to insert a picture into a math video? If so, can I add some animations to the pictures that I inserted?

**Comment by zavden** [comment]
Use [`ImageMobject`](https://github.com/3b1b/manim/blob/master/manimlib/mobject/types/image_mobject.py#L46), You can make animations that are not specialized for VMobjects.

**Comment by xianfengting** [comment]
@zavden Thanks.

**Comment by Elteoremadebeethoven** [comment]
Close the issue if it works please.

**Comment by xianfengting** [comment]
@Elteoremadebeethoven Sorry, I forgot.
