### ISSUE TITLE
How to transform only a part of formula?

### ISSUE THREAD

**Issue by girishgargcool** [3b1b/manim#657]
formula2=TexMobject(r"\frac { d }{ dx } f(x)\quad =\quad \underset { h\rightarrow 0 }{ lim } \frac { f(x+h)\quad -\quad f(x) }{ (x+h)\quad -\quad (x) } ")
		formula2.set_color(BLUE)
		self.play(Write(formula2), run_time=5)
		self.wait(3)
		#
		formula3=TexMobject(r"\frac { d }{ dx } f(x)\quad =\quad \underset { h\rightarrow 0 }{ lim } \frac { f(x+h)\quad -\quad f(x) }{ h } ")
		formula3.set_color(BLUE)
		self.play(ReplacementTransform(formula2, formula3))
		self.wait(5)

**Comment by zavden** [comment]
With arrays, but it usually causes problems if you use the radical symbol.
```python
        f1=TexMobject(
            r"\frac{d}{dx}f(x)\quad =\quad\lim_{h\to 0}{f(x+h)\quad-\quad f(x) \over ",
            r"(x+h)\quad-\quad(x)",
            "}"
            )
        f2=TexMobject(
            r"\frac{d}{dx}f(x)\quad =\quad\lim_{h\to 0}{f(x+h)\quad-\quad f(x) \over ",
            r"h",
            "}"
            )
        self.add(f1)
        self.play(ReplacementTransform(f1[1],f2[1]))
        self.wait()
```

**Comment by girishgargcool** [comment]
@zavden The code you gave is not working

**Comment by girishgargcool** [comment]
My earlier code: (Screenshot since the code feature on github is crappy)

![Screenshot (60)](https://user-images.githubusercontent.com/52619530/62102496-d478f680-b2b6-11e9-9002-f00b3ff60fed.png)

`class test6(Scene):
	def construct(self):
		formula1=TexMobject("y\quad =\quad f(x)")
		formula2=TexMobject(r"\frac { d }{ dx } f(x)\quad =\quad \underset { h\rightarrow 0 }{ lim } \frac { f(x+h)\quad -\quad f(x) }{ (x+h)\quad -\quad (x) } ")
		formula3=TexMobject(r"\frac { d }{ dx } f(x)\quad =\quad \underset { h\rightarrow 0 }{ lim } \frac { f(x+h)\quad -\quad f(x) }{ h } ")


		formula1.set_color(RED)
		formula2.set_color(BLUE)
		formula3.set_color(BLUE)

		self.play(Write(formula1), run_time=3)
		self.play(ApplyMethod(formula1.shift, 3*LEFT + 3*UP))
		self.wait()
		#
		self.play(Write(formula2), run_time=5)
		self.wait(3)
		#
		self.play(Transform(formula2, formula3))
		self.wait(5)
		

		

`

**Comment by zavden** [comment]
What is the error?
```python
class Help1(Scene):
    def construct(self):
        f1=TexMobject(
            r"\frac{d}{dx}f(x)\quad =\quad\lim_{h\to 0}{f(x+h)\quad-\quad f(x) \over ",
            r"(x+h)\quad-\quad(x)",
            "}"
            )
        f2=TexMobject(
            r"\frac{d}{dx}f(x)\quad =\quad\lim_{h\to 0}{f(x+h)\quad-\quad f(x) \over ",
            "h",
            "}"
            )
        self.add(f1)
        self.play(ReplacementTransform(f1[1],f2[1]))
        self.wait()
```
![Help1](https://user-images.githubusercontent.com/51290473/62103838-44f62800-b263-11e9-8e5b-4a11df01ddb0.gif)

**Comment by girishgargcool** [comment]
Would you mind sending the .py file to my email girishgargcool@gmail.com

**Comment by girishgargcool** [comment]
done. thank you
