### ISSUE TITLE
How to add sound to video?

### ISSUE THREAD

**Issue by girishgargcool** [3b1b/manim#658]

**Comment by NicolasCaous** [comment]
Hi @girishgargcool, I hope you are doing well.

Unfortunately, there is no such feature in manim as it is a tool intended only for animation. A quote from the creator: 
> [I also get worried when I hear people ask things like “how do I sync up narration into manim”.  This is just a tool for spitting out the individual mathematical animations, not the whole video.  For goodness sake, use traditional video editing software for as much as you can!](https://www.3blue1brown.com/faq#manim)

I get that you want to just add some audio to your recently made animation, so I would recommend you to use a proper video editing software. :)

**Comment by zavden** [comment]
Use `.add_sound(file_name)`.

Create a folder called assets, and inside create another folder called sounds. In the sounds folder, place the .wav or .mp3 tracks. It is only recommended to use short sounds. [Here](https://github.com/3b1b/manim/blob/master/old_projects/clacks/solution2/simple_scenes.py#L340) an example.

**Comment by girishgargcool** [comment]
assets folder has to be created in the manim folder itself or any sub-folders?

**Comment by zavden** [comment]
In the manim folder itself.

**Comment by girishgargcool** [comment]
doesnot work
![Screenshot (61)](https://user-images.githubusercontent.com/52619530/62105886-49e9c480-b2c1-11e9-9f35-53151a0280fc.png)

**Comment by girishgargcool** [comment]
self.add_sound("audio")

**Comment by girishgargcool** [comment]
class test6(Scene):
	def construct(self):
		formula1=TexMobject("y\quad =\quad f(x)")
		formula2=TexMobject(r"\frac{d}{dx}f(x)\quad =\quad\lim_{h\to 0}{f(x+h)\quad-\quad f(x) \over ", r"(x+h)\quad-\quad(x)","}")
		formula3=TexMobject(r"\frac{d}{dx}f(x)\quad =\quad\lim_{h\to 0}{f(x+h)\quad-\quad f(x) \over ","h","}")


		formula1.set_color(RED)
		formula2.set_color(BLUE)
		formula3.set_color(BLUE)
		self.add_sound("audio")

		self.play(Write(formula1), run_time=3)
		self.play(ApplyMethod(formula1.shift, 3*LEFT + 3*UP))
		self.wait()
		#
		self.play(Write(formula2), run_time=5)
		self.wait(3)
		#
		self.play(Transform(formula2[1], formula3[1]))
		self.wait(5)

**Comment by zavden** [comment]
I think you need to learn how to write on Markdown to express yourself better, [here is a quick tutorial](https://guides.github.com/features/mastering-markdown/).

Technically it does work, the problem is the shell used by Windows 8 and 10. You have to learn to read the terminal, it is telling you that on line [363 in manimlib/scene/scene_file_writer.py](https://github.com/3b1b/manim/blob/3cee3de94f2872a5b700d8b27b227f35e13a9cc7/manimlib/scene/scene_file_writer.py#L363) (In the current version it is [354](https://github.com/3b1b/manim/blob/master/manimlib/scene/scene_file_writer.py#L354), so I guess you are using a backward version), the process `subprocess.call ([" rm ", sound_file_path])` is not recognized, so you must replace it with a command compatible with the shell you use, it worked for me `os.remove (sound_file_path)`, so replace the line 363 of that file with `os.remove (sound_file_path)`.

**Comment by Elteoremadebeethoven** [comment]
If you have [this error](https://github.com/3b1b/manim/issues/433) you can solve it with [this](https://www.youtube.com/watch?v=vzyzqv8Sp8Y&t=12m).

**Comment by girishgargcool** [comment]
Thank you so much

**Comment by girishgargcool** [comment]
Please suggest a free video and audio editor

**Comment by Elteoremadebeethoven** [comment]
Video: [Blender](https://www.blender.org/)
[Some tutorials](https://www.youtube.com/watch?v=Zcj4onvP06w)

Audio: Reaper

**Comment by xy-23** [comment]
> I think you need to learn how to write on Markdown to express yourself better, [here is a quick tutorial](https://guides.github.com/features/mastering-markdown/).
> 
> Technically it does work, the problem is the shell used by Windows 8 and 10. You have to learn to read the terminal, it is telling you that on line [363 in manimlib/scene/scene_file_writer.py](https://github.com/3b1b/manim/blob/3cee3de94f2872a5b700d8b27b227f35e13a9cc7/manimlib/scene/scene_file_writer.py#L363) (In the current version it is [354](https://github.com/3b1b/manim/blob/master/manimlib/scene/scene_file_writer.py#L354), so I guess you are using a backward version), the process `subprocess.call([" rm ", sound_file_path])` is not recognized, so you must replace it with a command compatible with the shell you use, it worked for me `os.remove(sound_file_path)`, so replace the line 363 of that file with `os.remove(sound_file_path)`.

@zavden 
If `subprocess.call([" rm ", sound_file_path])` doesn't work for win10, 
why don't push a Pr replace it with 'os.remove(sound_file_path)

**Comment by zavden** [comment]
[Sended](https://github.com/3b1b/manim/pull/665).

**Comment by pedroslrey** [comment]
You can use as an audio/video editor OpenShot Video Editor, free and functional
