### ISSUE TITLE
Problem with FadeOutAndShift

### ISSUE THREAD

**Issue by girishgargcool** [3b1b/manim#659]
t3 text is not going through FadeOutAndShift.
Also tell me how I can FadeOutAndShift t1 and t3 together

```# python -m manim try3.py test1 -pm

from manimlib.imports import *

class test1(Scene):
	def construct(self):
		t1=TextMobject("Hi!")
		t2=TextMobject("My name is")
		t3=TextMobject("Girish")

		t1.set_color(RED)
		t3.set_color(BLUE)

		self.play(Write(t1), run_time=2)
		self.play(ApplyMethod(t1.shift, 1*UP))
		self.play(FadeIn(t2))
		self.play(Transform(t2, t3), run_time=2)
		self.wait(2)
		self.play(FadeOutAndShift(t1))
                self.play(FadeOutAndShift(t3))
		

		
```

**Comment by Elteoremadebeethoven** [comment]
Solution [here](https://github.com/3b1b/manim/issues/528#issuecomment-490042954).

**Comment by Elteoremadebeethoven** [comment]
Explication of that [here](https://www.youtube.com/watch?v=HKPm8FZYaq). 
You are asking very basic questions, first read all the information that is already available, both from my tutorials and those made by [other people](https://www.reddit.com/r/manim/comments/chd0k5/ask_your_questions_in_stackoverflow_using_the/). This way you will learn faster without having to ask every time.

**Comment by girishgargcool** [comment]
> Explication of that [here](https://www.youtube.com/watch?v=HKPm8FZYaq).

Video unavailable

**Comment by girishgargcool** [comment]
Also how do I fade multiple texts together?

PS: I already searched about it on github and google, but could not find any results

Refer last two lines of code: 

````class test1(Scene):
	def construct(self):
		t1=TextMobject("Hi!")
		t2=TextMobject("My name is")
		t3=TextMobject("Girish")

		t1.set_color(RED)
		t3.set_color(BLUE)

		self.play(Write(t1), run_time=2)
		self.play(ApplyMethod(t1.shift, 1*UP))
		self.play(FadeIn(t2))
		self.play(ReplacementTransform(t2, t3), run_time=2)
		self.wait(2)
		self.play(FadeOutAndShift(t1))
		self.play(FadeOutAndShift(t3))

**Comment by Elteoremadebeethoven** [comment]
Sorry, my mistake, [here](https://www.youtube.com/watch?v=HKPm8FZYaqI&t=2m) the video
