### ISSUE TITLE
ColorByCaracter help 

### ISSUE THREAD

**Issue by girishgargcool** [3b1b/manim#660]
I want to color only theta of ```{ e }^{ i\theta  }```

I was going through ColorByCaracter in 3_text_like_arrays.py . 
But I fail to understand how you people separate the tex formula into arrays. I know about arrays but I can only copy the tex code from [Daum Equation Editor](http://s1.daumcdn.net/editor/fp/service_nc/pencil/Pencil_chromestore.html) and paste it. I don't know how to divide them into arrays.

Please help me.

**Comment by Elteoremadebeethoven** [comment]
It's a bit complicated I must admit, but you must experiment for yourself to learn more.

```python
class ColorByText(Scene):
    def construct(self):
        #                    0    1       2     3
        formula=TexMobject("e^{","i","\\theta","}")
        formula[0].set_color(RED)
        formula[1].set_color(BLUE)
        formula[2].set_color(PURPLE)
        self.add(formula.scale(5))
```
![ColorByText](https://user-images.githubusercontent.com/43224662/62170917-ccd74300-b2f2-11e9-8841-8d67febfba5a.png)

**Comment by girishgargcool** [comment]
Where can I learn it?

**Comment by girishgargcool** [comment]
>         #                    0    1       2     3
>         formula=TexMobject("e^{","i","\\theta","}")

don't understand no. 3

**Comment by Elteoremadebeethoven** [comment]
LaTeX uses the brackets as grouping symbols, so you should always close them. For that reason you must experience to learn more about latex.
