### ISSUE TITLE
Manim is recieving Tex Error. 

### ISSUE THREAD

**Issue by pedroslrey** [3b1b/manim#664]
I am trying to use manim in my linux computer, but I always recive the same error.

`Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pedro/manim/manim.py", line 5, in <module>
    manimlib.main()
  File "/home/pedro/manim/manimlib/__init__.py", line 11, in main
    config = manimlib.config.get_configuration(args)
  File "/home/pedro/manim/manimlib/config.py", line 185, in get_configuration
    module = get_module(args.file)
  File "/home/pedro/manim/manimlib/config.py", line 180, in get_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "active_projects/inducao.py", line 3, in <module>
    class Inducao(Scene):
  File "active_projects/inducao.py", line 6, in Inducao
    text = TextMobject("Indução Matemática")
  File "/home/pedro/manim/manimlib/mobject/svg/tex_mobject.py", line 144, in __init__
    self, self.arg_separator.join(tex_strings), **kwargs
  File "/home/pedro/manim/manimlib/mobject/svg/tex_mobject.py", line 44, in __init__
    self.template_tex_file_body
  File "/home/pedro/manim/manimlib/utils/tex_file_writing.py", line 19, in tex_to_svg_file
    dvi_file = tex_to_dvi(tex_file)
  File "/home/pedro/manim/manimlib/utils/tex_file_writing.py", line 67, in tex_to_dvi
    "See log output above or the log file: %s" % log_file)
Exception: Latex error converting to dvi. See log output above or the log file: 0befe074291b4316.log
`

And there's another problem, there is no log file but there is a .tex file in the principal directory. My code seem to be write:

`
    
    from manimlib.imports import *

    class Inducao(Scene):
         #TITLE

        text = TextMobject("Indução Matemática")
    
        subtitle = TextMobject("Parte 2")
        subtitle.next_to(text, DOWN)

        self.play(Write(text))
        self.play(FadeIn(subtitle))
        self.wait(3)
        self.play(FadeOut(text), FadeOut(subtitle))
`

**Comment by Elteoremadebeethoven** [comment]
You lack the construct method. To solve the problem go to manimlib/tex_template.tex and replace [line 3](https://github.com/3b1b/manim/blob/master/manimlib/tex_template.tex#L3) with this two lines:
```
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
```

**Comment by pedroslrey** [comment]
Thank you! But still I have a problem with manim. I saw that the .tex file generated by manim gets on the repository of manim! When I compile the .tex file i recive a "no file .aux" error. See the .tex file below:

    \documentclass[preview]{standalone}

    \usepackage[brazil]{babel}  
    \usepackage[T1]{fontenc} % para ``ç'' em textsc
    \usepackage{amsmath}
    \usepackage{amssymb}
    \usepackage{dsfont}
    \usepackage{setspace}
    \usepackage{tipa}
    \usepackage{relsize}
    \usepackage{textcomp}
    \usepackage{mathrsfs}
    \usepackage{calligra}
    \usepackage{wasysym}
    \usepackage{ragged2e}
    \usepackage{physics}
    \usepackage{xcolor}
    \usepackage{microtype}
    \DisableLigatures{encoding = *, family = * }
    %\usepackage[UTF8]{ctex}
    \linespread{1}

    \begin{document}

    \centering Indução Matemática

    \end{document}

**Comment by Elteoremadebeethoven** [comment]
I don't know why that error is due, are you sure you have the `\usepackage[brazil]{babel}` package installed? I think it is better to use uft8, since it is more general and you can write more symbols. I also hope you know you can't change the text
```latex
\begin{document}

\centering Indução Matemática

\end{document}
```

In the tex_template.tex file to use it in Manim, you can test that the packages work, but once you have done the test you have to return it to the original form.
```latex
\begin{document}

YourTextHere

\end{document}
```

In my case, I have this configuration in my tex_template.tex file:

```latex
\documentclass[preview]{standalone}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{dsfont}
\usepackage{setspace}
\usepackage{tipa}
\usepackage{relsize}
\usepackage{textcomp}
\usepackage{mathrsfs}
\usepackage{calligra}
\usepackage{wasysym}
\usepackage{ragged2e}
\usepackage{physics}
\usepackage{xcolor}
\usepackage{microtype}
\DisableLigatures{encoding = *, family = * }
%\usepackage[UTF8]{ctex}
\linespread{1}

\begin{document}

YourTextHere

\end{document}
```

And I can render this scene:
```python
class BrazilText(Scene):
    def construct(self):
        text = TextMobject("\\textsc{Indução Matemática}")
        text.set_width(FRAME_WIDTH)
        self.add(text)
```
Result:
![BrazilText](https://user-images.githubusercontent.com/43224662/62578950-1205f280-b868-11e9-8fea-66a6644d30f0.png)

If I build the tex_template.tex file with latex I get:
```
manimlib $ latex tex_template.tex
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Arch Linux) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode
(./tex_template.tex
LaTeX2e <2018-12-01>
(/usr/share/texmf-dist/tex/latex/standalone/standalone.cls
Document Class: standalone 2018/03/26 v1.3a Class to compile TeX sub-files stan
dalone
(/usr/share/texmf-dist/tex/latex/tools/shellesc.sty)
(/usr/share/texmf-dist/tex/generic/oberdiek/ifluatex.sty)
(/usr/share/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(/usr/share/texmf-dist/tex/generic/ifxetex/ifxetex.sty)
(/usr/share/texmf-dist/tex/latex/xkeyval/xkeyval.sty
(/usr/share/texmf-dist/tex/generic/xkeyval/xkeyval.tex
(/usr/share/texmf-dist/tex/generic/xkeyval/xkvutils.tex
(/usr/share/texmf-dist/tex/generic/xkeyval/keyval.tex))))
(/usr/share/texmf-dist/tex/latex/standalone/standalone.cfg)
(/usr/share/texmf-dist/tex/latex/base/article.cls
Document Class: article 2018/09/03 v1.4i Standard LaTeX document class
(/usr/share/texmf-dist/tex/latex/base/size10.clo))
(/usr/share/texmf-dist/tex/latex/preview/preview.sty
(/usr/share/texmf-dist/tex/generic/luatex85/luatex85.sty)
(/usr/share/texmf-dist/tex/latex/preview/prtightpage.def)))
(/usr/share/texmf-dist/tex/latex/base/inputenc.sty)
(/usr/share/texmf-dist/tex/latex/base/fontenc.sty
(/usr/share/texmf-dist/tex/latex/base/t1enc.def))
(/usr/share/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/usr/share/texmf-dist/tex/latex/amsmath/amstext.sty
(/usr/share/texmf-dist/tex/latex/amsmath/amsgen.sty))
(/usr/share/texmf-dist/tex/latex/amsmath/amsbsy.sty)
(/usr/share/texmf-dist/tex/latex/amsmath/amsopn.sty))
(/usr/share/texmf-dist/tex/latex/amsfonts/amssymb.sty
(/usr/share/texmf-dist/tex/latex/amsfonts/amsfonts.sty))
(/usr/share/texmf-dist/tex/latex/doublestroke/dsfont.sty)
(/usr/share/texmf-dist/tex/latex/setspace/setspace.sty)
(/usr/share/texmf-dist/tex/latex/tipa/tipa.sty
(/usr/share/texmf-dist/tex/latex/base/fontenc.sty
(/usr/share/texmf-dist/tex/latex/tipa/t3enc.def
(/usr/share/texmf-dist/tex/latex/base/t1cmss.fd))
(/usr/share/texmf-dist/tex/latex/base/t1enc.def)))
(/usr/share/texmf-dist/tex/latex/relsize/relsize.sty)
(/usr/share/texmf-dist/tex/latex/base/textcomp.sty
(/usr/share/texmf-dist/tex/latex/base/ts1enc.def
(/usr/share/texmf-dist/tex/latex/base/ts1enc.dfu)))
(/usr/share/texmf-dist/tex/latex/jknapltx/mathrsfs.sty)
(/usr/share/texmf-dist/tex/latex/fundus-calligra/calligra.sty)
(/usr/share/texmf-dist/tex/latex/wasysym/wasysym.sty)
(/usr/share/texmf-dist/tex/latex/ms/ragged2e.sty
(/usr/share/texmf-dist/tex/latex/ms/everysel.sty))
(/usr/share/texmf-dist/tex/latex/physics/physics.sty
(/usr/share/texmf-dist/tex/latex/l3packages/xparse/xparse.sty
(/usr/share/texmf-dist/tex/latex/l3kernel/expl3.sty
(/usr/share/texmf-dist/tex/latex/l3kernel/expl3-code.tex)
(/usr/share/texmf-dist/tex/latex/l3kernel/l3dvips.def))))
(/usr/share/texmf-dist/tex/latex/xcolor/xcolor.sty
(/usr/share/texmf-dist/tex/latex/graphics-cfg/color.cfg)
(/usr/share/texmf-dist/tex/latex/graphics-def/dvips.def))
(/usr/share/texmf-dist/tex/latex/microtype/microtype.sty
(/usr/share/texmf-dist/tex/latex/microtype/microtype-pdftex.def)
(/usr/share/texmf-dist/tex/latex/microtype/microtype.cfg)) (./tex_template.aux)
(/usr/share/texmf-dist/tex/latex/tipa/t3cmr.fd)
(/usr/share/texmf-dist/tex/latex/base/ts1cmr.fd)
Preview: Fontsize 10pt
ABD: EverySelectfont initializing macros
(/usr/share/texmf-dist/tex/latex/microtype/mt-cmr.cfg)
Preview: Tightpage 0 0 0 0
[1] (./tex_template.aux) )
Output written on tex_template.dvi (1 page, 1620 bytes).
Transcript written on tex_template.log.
```

So, check that you have the packages installed, if not, install them, I recommend you install the full version of TeXLive.

**Comment by chaoxiaosu** [comment]
I faced the same problem on my Win 10 and found a workaround. I changed the L29 of _manimlib/constants.py_ to ` MEDIA_DIR = os.path.join(os.getcwd(), "media")`, then I passed. 

You can see [here](https://github.com/3b1b/manim/pull/689#issuecomment-522333581) for details.

**Comment by pedroslrey** [comment]
I found out what was the error: a part of the LaTeX enviorment wasn't installed, and alsso I forgot to add "def construct" thanks for all the help!
