### ISSUE TITLE
"\{" and "\}"

### ISSUE THREAD

**Issue by mscharling** [3b1b/manim#667]
Is it possible to make curved brackets one at a time? I get an error if I make a TextMobject with seperated brackets.
<img width="177" alt="sepcurvbrac" src="https://user-images.githubusercontent.com/53175715/62383546-4cae1900-b550-11e9-9449-ee803d48efd4.PNG">

**Comment by zavden** [comment]
```python
TextMobject("Y=\\{a,b,c\\}")
# or
TextMobject(r"Y=\{a,b,c\}")
```

**Comment by zavden** [comment]
I had the same problem, maybe this can help you until someone else can solve it:
```python
class TextTest(Scene):
    def construct(self):
        text=TextMobject("Y=\\{\\}","a,b,c","\\{\\}")
        lb=text[0][-1].fade(1)
        rb=text[2][-2].fade(1)
        text[1:].shift(lb.get_width()*LEFT)
        text[2].shift(rb.get_width()*LEFT)
        self.add(text)
```
