### ISSUE TITLE
New Text Mobject

### ISSUE THREAD

**Issue by xy-23** [3b1b/manim#681]
# Motivation

Because the `TextMobject` is the subclass of `TexMobject`,

so it requires some latex-style behaviours in order to add some changes.

(e.g. other languages, font, slant and weight)

So I create `Text` mobject but you can still use `TextMobject`.

# Introduction

`Text` is a subclass of `SVGMobject`.

It uses `cairo` to generate text svgs.

It has a better UTF-8 support, multi-line support, and various options. 

It doesn't support mathematical formula(latex), 

you can use `TextMobject` or `TexMobject`.

You can create a text in manim like:
```
from manimlib.imports import *

class Demo(Scene):
    def construct(self):
        text = Text('Hello, world!')
        self.play(Write(text))
```

![introduction](https://user-images.githubusercontent.com/47266984/62842441-e742f080-bce4-11e9-867f-df340d4351a0.png)

# Features

### text
Unlike `TextMobject`, `Text` only receive one `str`.

When there is only one line, the space(`' '`) in front or back will be ignored.

`'\t'` is not supported.

### color
`text = Text('Hello', color=BLUE)`

![color](https://user-images.githubusercontent.com/47266984/62842460-0a6da000-bce5-11e9-9f88-6d8d74ad8041.png)

`color` defined in constants.py or a `str` like `'#FFFFFF'`, default is `WHITE`

### t2c (text2color)
`text = Text('Hello, world!', t2c={'world':BLUE})`

![t2c](https://user-images.githubusercontent.com/47266984/62842523-5d475780-bce5-11e9-9b8d-31168ba27f65.png)

a `dict` like `{'text':color}` or Accurate mode

### gradient
`text = Text('Hello', gradient=(BLUE, GREEN))`

![gradient](https://user-images.githubusercontent.com/47266984/62842527-659f9280-bce5-11e9-8aaa-79560690d633.png)

a `tuple` like `(color1, color2, color3, ...)`

### t2g (text2gradient)
`text = Text('Hello, world!', t2g={'world':(BLUE, GREEN)})`

![t2g](https://user-images.githubusercontent.com/47266984/62842552-8c5dc900-bce5-11e9-87e5-8ea5c4d3448f.png)

a `dict` like `{'text':gradient}` or Accurate mode

### font
`text = Text('Hello', font='Source Han Sans')`

![font](https://user-images.githubusercontent.com/47266984/62842559-98e22180-bce5-11e9-9b5c-a41b04efcc7f.png)

a `str`, the name of font like `'Source Han Sans'`, default is `CONFIG['font']`, defined in constants.py

Be sure you have the font installed!

### t2f (text2font)
`text = Text('Hello, world!', t2f={'world':'Forte'})`

![t2f](https://user-images.githubusercontent.com/47266984/62842574-a8fa0100-bce5-11e9-9980-32332e3f6e92.png)

a `dict` like `{'text':font}` or Accurate mode

Be sure you have the font installed!

### slant
`text = Text('Hello', slant=ITALIC)`

![slant](https://user-images.githubusercontent.com/47266984/62842580-b0b9a580-bce5-11e9-8bd3-06ad0c7a9bbc.png)

`NORMAL` or `ITALIC`, default is `NORMAL`, defined in constants.py(a `str` actually)

### t2s (text2slant)
`text = Text('Hello, world!', t2s={'world':ITALIC})`

![t2s](https://user-images.githubusercontent.com/47266984/62842584-b616f000-bce5-11e9-84cf-9aaeb2188a87.png)

a `dict` like `{'text':slant}` or Accurate mode

### weight
`text = Text('Hello', weight=BOLD)`

![weight](https://user-images.githubusercontent.com/47266984/62842593-be6f2b00-bce5-11e9-9c01-4bd7637b65a4.png)

`NORMAL` or `BOLD`, default is `NORMAL`, defined in constants.py(a `str` actually)

other...

### t2w (text2weight)
`text = Text('Hello, world!', t2w={'world':BOLD})`

![t2w](https://user-images.githubusercontent.com/47266984/62842598-c4fda280-bce5-11e9-8259-402b71b78dab.png)

a `dict` like `{'text':weight}` or Accurate mode

### size
`text = Text('Hello', size=5)`

![size](https://user-images.githubusercontent.com/47266984/62842605-c929c000-bce5-11e9-8ae6-7542d129165b.png)

a number, better larger than 0.1(due to anti-aliasing), irrelevant with MUnit, default is `CONFIG['size']` 

### lsh (line_spacing_height)
`text = Text('Hello\nWorld', lsh=1.5)`

![lsh](https://user-images.githubusercontent.com/47266984/62842611-cf1fa100-bce5-11e9-9831-dcf23a5021b3.png)

a number, better larger than 0.1(due to anti-aliasing), irrelevant with MUnit, default is equal with size

### Accurate mode
```
text = Text(
    'Google', 
    t2c={
        '[:1]':'#3174f0', '[1:2]':'#e53125', 
        '[2:3]':'#fbb003', '[3:4]':'#3174f0', 
        '[4:5]':'#269a43', '[5:]':'#e53125',
    }
)
```

![accurate_mode](https://user-images.githubusercontent.com/47266984/62842622-e3639e00-bce5-11e9-9eae-e9c775bf94b3.png)

This will help you to choose a specific text just like slicing

### Mobject params:
like fill_color, fill_opacity, stroke_color, stroke_width

## Functions
`text = Text('Hello, world!')`

### set_color (Mobject function)

`text.set_color(BLUE)`

![set_color_1](https://user-images.githubusercontent.com/47266984/62842630-eced0600-bce5-11e9-872d-d0d7101e0abe.png)

or

`text[7:12].set_color(BLUE)`

![set_color_2](https://user-images.githubusercontent.com/47266984/62842634-f24a5080-bce5-11e9-97bd-bc91ba9221c7.png)

### set_color_by_gradient (Mobject function)

`text.set_color_by_gradient(BLUE, GREEN)`

![set_color_by_gradient_1](https://user-images.githubusercontent.com/47266984/62842640-fc6c4f00-bce5-11e9-9166-636cd28ccf1f.png)

or

`text[7:12].set_color_by_gradient(BLUE, GREEN)`

![set_color_by_gradient_2](https://user-images.githubusercontent.com/47266984/62842641-00986c80-bce6-11e9-816b-9a2b31336a41.png)

### set_color_by_t2c
`text.set_color_by_t2c({'world':BLUE})`

![set_color_by_t2c](https://user-images.githubusercontent.com/47266984/62842646-05f5b700-bce6-11e9-9255-0f427ade8269.png)

### set_color_by_t2g
`text.set_color_by_t2g({'world':(BLUE, GREEN)})`
![set_color_by_t2g](https://user-images.githubusercontent.com/47266984/62842650-0c842e80-bce6-11e9-8073-53e5bf27c6fe.png)

## UTF-8
```
from manimlib.imports import *

script = '''
Hello
你好
こんにちは
안녕하세요
'''

class Demo(Scene):
    def construct(self):
        text = Text(script, font='Source Han Sans')
        self.play(Write(text))
```
![utf-8](https://user-images.githubusercontent.com/47266984/62842747-ddba8800-bce6-11e9-84bd-c633ad1d7c4d.png)

Be sure you have the font that supports those languages!

**Comment by qubitbok** [comment]
Its a great! I tried it, really well done! 👍 

Only, two things make me struggle. 

1) **from manimlib.imports import *.** // Always raise an error, even me i don't know where this module. 
2) **utf-8. (RTL)  (Arabic Language)** // I spent fair time to figure out how can I  render the output with Arabic font RTL. 

Do you know how can I fix it? I'm using MAC.

**Comment by xy-23** [comment]
> 1. *_from manimlib.imports import _.__ // Always raise an error, even me i don't know where this module.

What the error is ? Plase give more details.
Did you install manim via pip?

> 2. **utf-8. (RTL)  (Arabic Language)** // I spent fair time to figure out how can I  render the output with Arabic font RTL.

Currently, it  probably can't display Arabic Language due to the package it uesd only provied a toy api. 
I will make it support later but it takes time...(about July, 2021)
Because achieving this goal needs huge changments in manim...

> Do you know how can I fix it? I'm using MAC.

My suggestion is using Adobe Illustrator or other software to generate the svg file that contains the proper text and use `SVGMobject('filename.svg')` to display it in manim. Or you can try to change the configration of template.tex and use `TextMobject`.

**Comment by xy-23** [comment]
Ops, accidentally reopened this issue

**Comment by pipetovarh** [comment]
Is anyone having trouble using the slant argument with fonts other than the default for the Text mobject?

**Comment by msmel01** [comment]
@xy-23 Is there a way you could specify which instances of the same word you want the stylistic properties, like BOLD or ITALIC,  to be applied to? The find_index method returns the the start and end index methods of all occurrences of the word and t2w automatically applies the property to all of those... For example, we want the second 'money'  in 'time is money. money is power' to be bold rather than both.

**Comment by jason-c-kwan** [comment]
Just wanted to leave a note here that if you want a `Text` object to have the same default font as a `TextMobject` you can set `font = "Latin Modern Roman"`. This took me a bit of figuring out (tested on the manim docker image).

**Comment by zamirkhan** [comment]
Is there a way to add a background color to just the text? As in, the text would be draw on top of a filled rectangle that only took up slightly more space than the text itself, rather than the entire screen?

I'm not sure how I would accomplish this with shapes, for a variable length/size of text.
