### ISSUE TITLE
Linux Chinese Charactor Unable to 'WRITE'

### ISSUE THREAD

**Issue by JasonVenn** [3b1b/manim#682]
(Manjaro Linux, Python3.7.3, Texlive)

I've read this issue:
[https://github.com/3b1b/manim/issues/209](https://github.com/3b1b/manim/issues/209)

But by doing as what it told, I still cannot 'WRITE' Chinese charactors.

Here is what the .log file says:

> ! Package inputenc Error: Unicode character 者 (U+8005)
> (inputenc)                not set up for use with LaTeX.

It seem that there are some problems with LaTeX.

I've not got too much practice on Python, so now I'm getting into a annoying position.

Somebody help me?

**Comment by Elteoremadebeethoven** [comment]
You have to modify the file manimlib/tex_template.tex, like [this](https://github.com/3b1b/manim/issues/525).

**Comment by JasonVenn** [comment]
> You have to modify the file manimlib/tex_template.tex, like [this](https://github.com/3b1b/manim/issues/525).

Great thanks.
