### ISSUE TITLE
Color a shape progressively from one side?  Centrally align a text inside a shape? 

### ISSUE THREAD

**Issue by girishgargcool** [3b1b/manim#685]
How to color a shape progressively from one side?
How to centrally align a text inside a shape?

**Comment by zavden** [comment]
I will only answer the first question, the second one is very easy to solve if you see the documentation or tutorials on YT:
```python
class ColorExample(Scene):
    def construct(self):
        c=Circle(fill_opacity=1,vect=[0,1,0])
        c.set_color(color=[RED,BLUE])
        color_direction=[0,1,0]
        c.set_sheen_direction(color_direction)
        self.add(c)
```
![ColorExample](https://user-images.githubusercontent.com/51290473/63142893-6704df80-bfb1-11e9-9e56-c9ce50ae99b5.png)
