### ISSUE TITLE
References to an object in submobjects breaks across a copy

### ISSUE THREAD

**Issue by hexagonal-sun** [3b1b/manim#688]
Suppose we have the following code:

```python
class Video(Scene):
        a = VGroup()
        a.foo = Circle()
        a.bar = Rectangle()
        a.digest_mobject_attrs()
        a.print_family()
        print(id(a.foo), id(a.bar))
        self.add(a)
        self.wait()

        a.generate_target()
        a.target.remove(a.target.foo)
        a.target.print_family()
        print(id(a.target.foo), id(a.target.bar))

        self.play(MoveToTarget(a))
        self.wait()

```

which results in:

```
 VGroup 139926527884496
	 Circle 139926858136272
	 Rectangle 139926527884688
139926858136272 139926527884688
```
Everying is all good at this point, however after the copy, `a.target.foo` and `a.target.bar` are no longer the same objects on `a.target`'s submobject array
```
 VGroup 139926527885136
	 Circle 139926527885264
	 Rectangle 139926621818128
139926527967696 139926527967632
```
and therefore, the removal of a.target.foo doesn't work.

I think this is a problem [here](https://github.com/3b1b/manim/blob/master/manimlib/mobject/mobject.py#L130), the `value.copy()` results in two objects.

Expected behaviour: the circle should be removed in the animation.

**Comment by Elteoremadebeethoven** [comment]
Sorry, I don't know what you are trying to prove, `MoveToTarget` was not thought that way, if you want to make that animation it is much easier to do it this way (by the way, you forgot to include the `construct` method).

```python
class Video(Scene):
    def construct(self):
            a = VGroup()
            foo = Circle()
            bar = Rectangle()
            a.add(foo,bar)
            self.add(a)
            self.wait()

            self.play(FadeOut(foo))
            self.wait()
```

If you plan to apply this code in a more complex animation I ask you to explain more.

**Comment by hexagonal-sun** [comment]
Apologies, my example wasn't very clear on how I came across this problem.  This is mainly an issue when you are trying to implement a subclass.  I'm creating videos about programming in C and I've subclassed VGroup into a new object, `CObject`.  The example below should hopefully highlight the problem:

```python
from manimlib.imports import *

class CObject(VGroup):
    CONFIG = {
        "label": "CObject",
        "attrs": {}
    }

    def __init__(self, **kwargs):
        super(CObject, self).__init__(**kwargs)
        digest_config(self, kwargs)
        self.label = TextMobject("\\texttt{" + self.label + "}",
                                 **kwargs)
        self.add(self.label)
        self.attr_texts = []
        self.set_attrs(self.attrs)

        self.box = SurroundingRectangle(self, **kwargs)
        self.add(self.box)

    def set_attrs(self, attrs):
        self.remove(*self.attr_texts)
        self.attr_texts.clear()

        last_text = self.label

        for k, v in attrs.items():
            attr_text = TextMobject("\\scriptsize\\texttt{" + str(k) +
                                    ": " + str(v) + "}")
            attr_text.next_to(last_text, DOWN)
            last_text = attr_text
            self.attr_texts.append(attr_text)
            self.add(attr_text)

        if (hasattr(self, 'box')):
            self.remove(self.box)
            self.box = SurroundingRectangle(self)
            self.add(self.box)

        return self

class Video(Scene):
    def construct(self):
        obj = CObject(label="Working")
        self.add(obj)
        self.wait()
        obj.set_attrs({"foo": "bar", "baz": "tan"})
        self.wait()
        obj.set_attrs({"a": "b", "c": "d", "e": "f"})
        self.wait()
        self.remove(obj)

        obj = CObject(label="Broken")
        self.add(obj)
        self.wait()
        obj.set_attrs({"foo": "bar", "baz": "tan"})
        self.wait()
        obj.generate_target()
        obj.target.set_attrs({"a": "b", "c": "d", "e": "f"})
        self.play(MoveToTarget(obj))
        self.wait()
```
Now this works great for the `working` object.  However, notice that when the `broken` object tries to animate the `set_attrs` via `MoveToTarget` the references to the box and the attr_text is lost meaning they're not removed from the `submobjects` array.

You can see instances of this being worked around [here](https://github.com/3b1b/manim/blob/master/manimlib/for_3b1b_videos/pi_creature.py#L141) which calls [this](https://github.com/3b1b/manim/blob/master/manimlib/for_3b1b_videos/pi_creature.py#L84) to restore the references.

**Comment by hexagonal-sun** [comment]
I've managed to fix this by using `deepcopy`.  For anyone else experiencing this, use:

```python
obj.generate_target(True)
```
to ensure `deepcopy` is used.
