### ISSUE TITLE
What should I do if I want to use the color undefined yet in constant.py? 

### ISSUE THREAD

**Issue by barakasamsara** [3b1b/manim#690]
I'm sorry , I make a stupid mistake....

**Comment by Elteoremadebeethoven** [comment]
Use hexadecimal format:
```python
object.set_color("#FFFFFF")
```
See other ways [here](https://github.com/3b1b/manim/blob/master/manimlib/utils/color.py).

**Comment by barakasamsara** [comment]
> here

Thanks very much...It's so nice of you

**Comment by Elteoremadebeethoven** [comment]
No problem, please close the issue.
