### ISSUE TITLE
I'm shocked ...:Played 0 animations...

### ISSUE THREAD

**Issue by barakasamsara** [3b1b/manim#695]
source code:
class DrawAnAxis(Scene):
    CONFIG = { "plane_kwargs" :
        {
        "x_line_frequency" : 2,
        "y_line_frequency" :2
        }
    }

    def construct(self):
        my_plane = NumberPlane(**self.plane_kwargs)
        my_plane.add(my_plane.get_axis_labels())

        self.add(my_plane)
        #self.wait()

........
$ python3 -m manim ********.py DrawAnAxis -pl
Media will be written to ./media/. You can change this behavior with the --media_dir flag.
No animations in this scene
Played 0 animations

**Comment by eulertour** [comment]
Well, that Scene doesn't contain any animations.

**Comment by zavden** [comment]
Of course, you never use the play method, you only use add. Try this:
```
    my_plane = NumberPlane(**self.plane_kwargs)
    my_plane.add(my_plane.get_axis_labels())

    self.play(ShowCreation(my_plane))
    self.wait()
```

**Comment by barakasamsara** [comment]
> Well, that Scene doesn't contain any animations.

Thanks very much...

**Comment by barakasamsara** [comment]
> Of course, you never use the play method, you only use add. Try this:
> 
> ```
>     my_plane = NumberPlane(**self.plane_kwargs)
>     my_plane.add(my_plane.get_axis_labels())
> 
>     self.play(ShowCreation(my_plane))
>     self.wait()
> ```

I got it ,Thanks very much...
