### ISSUE TITLE
Failed to create `TextMobject` with " " as content

### ISSUE THREAD

**Issue by cpud36** [3b1b/manim#707]
# Steps to reproduce
This is the code inside `Scene::construct`
```python
txt = TextMobject(" ")
self.play(Write(txt))
```
Compiled with:
```sh
python3 -m manim test.py Test -lp
```
Has the following traceback:
```
Writing "\centering" to ./media/Tex/bf704a9c70f0a573.tex



Traceback (most recent call last):
  File "/home/cpud36/workspace/manim/manimlib/extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "/home/cpud36/workspace/manim/manimlib/scene/scene.py", line 53, in __init__
    self.construct()
  File "test.py", line 6, in construct
    txt = TextMobject(" ")
  File "/home/cpud36/workspace/manim/manimlib/mobject/svg/tex_mobject.py", line 146, in __init__
    self.break_up_by_substrings()
  File "/home/cpud36/workspace/manim/manimlib/mobject/svg/tex_mobject.py", line 184, in break_up_by_substrings
    sub_tex_mob.move_to(self.submobjects[last_submob_index], RIGHT)
IndexError: list index out of range
```

# Additional info
The problem is that `self.submobjects` is empty, so `last_submob_index` is `-1`

# Environment
Manim: b74e5ca2 commit
OS: Arch linux-4.19.66-1-lts 
Python Version: Python 3.7.4

**Comment by qo4on** [comment]
Did you find how to fix this? I have [similar error](https://github.com/3b1b/manim/issues/1234).

**Comment by naveen521kk** [comment]
Can you make an issue in community repo? https://github.com/ManimCommunity/manim/issues
I confirm it exists there also. We can find a fix for this there. @cpud36

**Comment by lucalista** [comment]
Is there any update about this issue? I have just installed manim + jupyter support, and I have the same problem with TextMobject. I'm using python 3.7.3 on Linux and manim 0.5.0.

**Comment by TonyCrane** [comment]
There is no this problem in the new version of manim (manimgl), so I'm closing this.
