### ISSUE TITLE
what should i do if I want to show the trace of the circle moving from bottom to top to form a cylinder

### ISSUE THREAD

**Issue by barakasamsara** [3b1b/manim#714]
this is the pic of bottom..
![image](https://user-images.githubusercontent.com/36161299/63994459-5616ab00-cb27-11e9-8f98-0369d6908a8b.png)
this is the pic of top..
![image](https://user-images.githubusercontent.com/36161299/63994526-75add380-cb27-11e9-947a-23123fdec488.png)

**Comment by Elteoremadebeethoven** [comment]
With a update function, like:
```python
def update_cylinder(cylinder):
```

**Comment by barakasamsara** [comment]
> With a update function, like:
> 
> ```python
> def update_cylinder(cylinder):
> ```
> 
> See my tutorial 8.1
> 
> ```python
> class Cylinder(ParametricSurface):
>     CONFIG = {
>         "resolution": (12, 12),
>         "radius": 1,
>         "length": 2,
>         "u_min": 0,
>         "u_max": 2*PI,
>         "v_min": 0,
>         "v_max": 1,
>         "shade_in_3d":True
>     }
> 
>     def __init__(self, **kwargs):
>         ParametricSurface.__init__(
>             self, self.func, **kwargs
>         )
>         self.scale(self.radius)
> 
>     def func(self, u, v):
>         return np.array([
>             self.radius*np.cos(u),
>             self.radius*np.sin(u),
>             self.length*v
>         ])
> 
> 
> class ShowCylinder(ThreeDScene):
>     def construct(self):
>         axes = NumberPlane()
>         axes.set_shade_in_3d(True)
>         circle = Circle()
>         circle.set_shade_in_3d(True)
>         cylinder = Cylinder(radius=1,length=0)
>         self.set_camera_orientation(phi=70 * DEGREES,theta=45*DEGREES)
>         self.add(axes,circle,cylinder)
> 
>         def update_cylinder(mob):
>             new_length = circle.get_center()[2]
>             new_mob = Cylinder(radius=1,length=new_length)
>             mob.become(new_mob)
> 
>         cylinder.add_updater(update_cylinder)
>         self.add(cylinder)
>         self.play(circle.shift,OUT)
>         self.wait()
> ```

Thanks a looooot!
