### ISSUE TITLE
How to input absolute value...I try abs()/[]/{},but it doesn't work

### ISSUE THREAD

**Issue by barakasamsara** [3b1b/manim#715]
How to input absolute value...I try abs()/[]/{},but it doesn't work

**Comment by Elteoremadebeethoven** [comment]
As a text or operator in python?

**Comment by barakasamsara** [comment]
> As a TeX formula or operator in python?

TeX formula...

**Comment by zavden** [comment]
See a LaTeX documentation. Example: [Brackets and parentheses](https://www.overleaf.com/learn/latex/Brackets_and_Parentheses)

**Comment by barakasamsara** [comment]
> See a LaTeX documentation. Example: [Brackets and parentheses](https://www.overleaf.com/learn/latex/Brackets_and_Parentheses)

thanks a loooot!
