### ISSUE TITLE
questions about svg - from the tutorial "Working with SVG Files – manim Series: Part 12"

### ISSUE THREAD

**Issue by barakasamsara** [3b1b/manim#717]
https://talkingphysics.wordpress.com/2018/08/14/working-with-svg-files-manim-series-part-12/
https://github.com/zimmermant/manim_tutorial/blob/master/manim_tutorial_P37.py
code：
class StickMan(SVGMobject):
    CONFIG = {
        "color" : BLUE_E,
        "file_name_prefix": "stick_man",
        "stroke_width" : 2,
        "stroke_color" : WHITE,
        "fill_opacity" : 1.0,
        "height" : 3,
    }
    def __init__(self, mode = "plain", **kwargs):
        digest_config(self, kwargs)
        self.mode = mode
        self.parts_named = False
        try:
            svg_file = os.path.join(
                SVG_IMAGE_DIR,
                "%s_%s.svg" % (self.file_name_prefix, mode)
            )
            SVGMobject.__init__(self, file_name=svg_file, **kwargs)
        except:
            warnings.warn("No %s design with mode %s" %
                            (self.file_name_prefix, mode))
            svg_file = os.path.join(
                SVG_IMAGE_DIR,
                "stick_man_plain.svg",
            )
            SVGMobject.__init__(self, mode="plain", file_name=svg_file, **kwargs)

    def name_parts(self):
        self.head = self.submobjects[HEAD_INDEX]
        self.body = self.submobjects[BODY_INDEX]
        self.arms = self.submobjects[ARMS_INDEX]
        self.legs = self.submobjects[LEGS_INDEX]
        self.parts_named = True

    def init_colors(self):
        SVGMobject.init_colors(self)
        if not self.parts_named:
            self.name_parts()
        self.head.set_fill(self.color, opacity = 1)
        self.body.set_fill(RED, opacity = 1)
        self.arms.set_fill(YELLOW, opacity = 1)
        self.legs.set_fill(BLUE, opacity = 1)
        return self

class Waving(Scene):
    def construct(self):
        start_man = StickMan()
        plain_man = StickMan()
        waving_man = StickMan("wave")

        self.add(start_man)
        self.wait()
        self.play(Transform(start_man,waving_man))
        self.play(Transform(start_man,plain_man))

        self.wait()
and i have put svg files here:
![image](https://user-images.githubusercontent.com/36161299/64354579-4a008100-d032-11e9-9a7d-c997d5de1a2d.png)
![image](https://user-images.githubusercontent.com/36161299/64355382-b29c2d80-d033-11e9-9e0a-ba059974fee0.png)

**Comment by Elteoremadebeethoven** [comment]
That only works in the old version, I have a video (the 7) that I show how to use it in the new one.

**Comment by barakasamsara** [comment]
> That only works in the old version, I have a video (the 7) that I show how to use it in the new one.
> The `assets` folder goes in the manim main folder, not in `docs/source`

Thanks a lot, i'll go to the video right now
