### ISSUE TITLE
how to show an angel mark？

### ISSUE THREAD

**Issue by barakasamsara** [3b1b/manim#718]
like this:
![image](https://user-images.githubusercontent.com/36161299/64361216-c305d580-d03e-11e9-9b62-d2e57bdb33fd.png)

and if i want to highlight the area formed by the sides of the angel and the mark, what should i do...

**Comment by Elteoremadebeethoven** [comment]
See [this](https://github.com/Elteoremadebeethoven/AnimationsWithManim/blob/master/English/update_successions/update_successions.py#L126)

**Comment by barakasamsara** [comment]
> ```python
> angle.set_fill(GREEN,0.7)
> angle.set_stroke(GREEN,4)
> ```
> 
> Play with the numbers

Thanks a lot
