### ISSUE TITLE
How to show an angle mark?

### ISSUE THREAD

**Issue by ManimBigFan** [3b1b/manim#724]
I saw below answer, but I can't understand.

angle.set_fill(GREEN,0.7)
angle.set_stroke(GREEN,4)

What does this angle mean? It comes from arc class?
Please, show me some example what it used?

**Comment by Elteoremadebeethoven** [comment]
It comes from VMobject class, see manimlib/mobjext/types/vectorized_mobject.py

**Comment by ManimBigFan** [comment]
Thanks
