### ISSUE TITLE
Syntax Error: invalid syntax

### ISSUE THREAD

**Issue by girishgargcool** [3b1b/manim#729]
@Elteoremadebeethoven
Hey Alex, I hope you are doing fine. With your help I had successfully set up manim on my pc. Two math videos were also published on youtube. I now need your help again.
I uninstalled sublime text on which I used to write code. Now, when I try using vs code for the same purpose it just doesnot render. I then again installed sublime text, but even now the problem persists
![Screenshot (64)](https://user-images.githubusercontent.com/52619530/65158541-300e6780-da50-11e9-81bf-287ccc2ff438.png)

**Comment by Elteoremadebeethoven** [comment]
The problem is not the code editor, but you edited poorly graph_scene, please read what the terminal says and solve it yourself. You are missing `{}` symbols.

**Comment by girishgargcool** [comment]
But I never edited anything in the manimlib folder. How come it worked fine previously but not now

**Comment by girishgargcool** [comment]
But I never edited anything in the manimlib folder. How come it worked fine previously but not now

**Comment by Elteoremadebeethoven** [comment]
Surely you don't remember, but I can assure you that you did edit it. Line 85 in manimlib / scene / graph_scene.py that your terminal shows is not in the original version of manim, it is a line that I add in my video 6.

**Comment by girishgargcool** [comment]
How come it worked fine previously but not now

**Comment by girishgargcool** [comment]
line 85 of graph scene

```            
decimal_number_config="num_decimal_places": self.x_label_decimal},
        }
```

**Comment by Elteoremadebeethoven** [comment]
I have no idea, but it shouldn't have worked since the first time. if you fix that line it should work, unless you have made other mistakes in other files.

**Comment by Elteoremadebeethoven** [comment]
Yes, you are missing {} symbols, see my video again. The 6 one

**Comment by girishgargcool** [comment]
okay!

**Comment by girishgargcool** [comment]
Can you pls tell the name of the video

**Comment by Elteoremadebeethoven** [comment]
https://youtu.be/YVxhhi14Ha0

**Comment by girishgargcool** [comment]
Done! Thank you
