### ISSUE TITLE
How can I change orders of rendering?

### ISSUE THREAD

**Issue by ManimBigFan** [3b1b/manim#731]
How can I change orders of rendering?
I want to circle A in front of circle B
but I don't know how can I change this
Please help

**Comment by ManimBigFan** [comment]
How can I change orders of rendering?
I want to circle A in front of circle B
but I don't know how can I change this
Please help

**Comment by zavden** [comment]
Use `self.bring_to_back(...)` or `self.bring_to_front(...)`.

**Comment by ManimBigFan** [comment]
Thanks !
