### ISSUE TITLE
No Module Named color

### ISSUE THREAD

**Issue by Kai-Beast223** [3b1b/manim#733]
### If this is a support request:

**Please attempt to solve the problem on your own before opening an issue.**
Between old issues, StackOverflow, and Google, you should be able to find
solutions to most of the common problems.

Include at least:
1. Steps to reproduce the issue (e.g. the command you ran)
./manim.py example_scenes.py SquareToCircle -pl
2. The unexpected behavior that occurred (e.g. error messages or screenshots)
  File "./manim.py", line 2, in <module>
    import manimlib
  File "/Users/<REDACTED>/Desktop/math/manim/manimlib/__init__.py", line 2, in <module>
    import manimlib.config
  File "/Users/<RECACTED>/Desktop/math/manim/manimlib/config.py", line 2, in <module>
    import colour
ImportError: No module named colour
3. The environment (e.g. operating system and version of manim)
Mac OS 10.15 developer beta v8 and latest Manim

**Comment by MonkeyBiz** [comment]
I am also having this issue. I tried the "old" fix of  "pip install colour" without success. I am using Anaconda 3 as my python distribution.

**Comment by Kai-Beast223** [comment]
I ended up fixing my wrapping my encoding in side of a VENV
