### ISSUE TITLE
How can i trick the intersection points

### ISSUE THREAD

**Issue by wsx9999** [3b1b/manim#737]
How can I trick the intersection points of lines or circles, and get the points' coordinate, and make a dot or a text follow the intersection points. 
In addition, how can I make the  common part of the two circles full a color.

```
class wsx(Scene):
    def construct(self):
        radius=ValueTracker(1)
        circle_1=Circle(radius=1).move_to(np.array([-1,0,0]))
        circle_2=Circle(radius=1).move_to(np.array([1,0,0]))
        self.add(circle_1,circle_2)        
        self.wait()
        circle_2.initial=circle_2.copy()
        def updater_circle(obj):
            obj.become(obj.initial)
            obj.scale(radius.get_value())
        circle_2.add_updater(updater_circle)
        self.add(circle_1,circle_2)
        self.play(radius.increment_value,2,run_time=2)
        self.wait()
```
https://youtu.be/agDZhIZPYz4

![Snipaste_2019-09-28_13-08-11](https://user-images.githubusercontent.com/17780777/65811888-0b558500-e1f2-11e9-9dbc-fe3b79d95c5d.png)

**Comment by zavden** [comment]
There is no way to do that with the pre-existing functions of Manim, but you can create some method to solve it, like [this](https://github.com/Elteoremadebeethoven/Manim-community/tree/master/Tools/Intersection).

**Comment by wsx9999** [comment]
@zavden Thank you. But your example is to hard for me now. I can't understand the codes. That's not your problem, it's my problem. I will keep learning hard and try to understand it. 
And it cannot run on my computer. My computer os is windows 7. But the code's based on linux. 

```
Traceback (most recent call last):
  File "c:\manim\manimlib\extract_scene.py", line 156, in main
    open_file_if_needed(scene.file_writer, **config)
  File "c:\manim\manimlib\extract_scene.py", line 35, in open_file_if_needed
    os.startfile(file_path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'c:\\manim\\media\\videos\\wsx\\480p15\\IntersectionScene.mp4'
```
This is the information when I try to run the code and the cmd terminal show.

**Comment by zavden** [comment]
What happens is that you are trying to render it as a video, but the scene that I sent you has no duration, so you have to render it as an image, use `-ps` instead `-pl`.

**Comment by wsx9999** [comment]
Got it~~ thank you!!! ^_^

**Comment by zavden** [comment]
Perfect, please close your issues.
