### ISSUE TITLE
Can Manim import PNG files with transparency channel?

### ISSUE THREAD

**Issue by q2apro** [3b1b/manim#739]
I have not tried Manim yet, because the installation and the learning curve seems like a few days of work. Before starting, I would like to make sure an essential feature I need: 

Can Manim import PNG files with transparency channel?

I only found https://github.com/malhotra5/Manim-Tutorial under "Images" this code:

```
from manimlib.imports import *

class Images(Scene):
    def construct(self):
        img = ImageMobject('pathToIm.png')
        img.scale(2)  # Resize to be twice as big
        img.shift(2 * UP)  # Move the image

        self.play(ShowCreation(img))  # Display the image
```

So I suppose that Manim can import PNG files. However, the open question, does transparency channels are transparent? Especially when it comes to overlays with manim objects.

**Comment by Elteoremadebeethoven** [comment]
Yes, it supports PNG with transparency, SVG, and audio fragments. And you can export videos in alpha channel (.mov). The only part taken is the installation of LaTeX, but the rest is simple. If you want to try the Manim code you can do it online: https://www.eulertour.com/

**Comment by q2apro** [comment]
Thanks for pointing out the website!
