### ISSUE TITLE
Passing arguments via command line. 

### ISSUE THREAD

**Issue by CadenScharpf** [3b1b/manim#742]
Having some trouble trying to pass some data to the scene through the command line. Id like to be able to dynamically render the videos server side by just tacking on some text at the end of the shell command, like maybe:   " manim file.py Scene -pl data "  , but Im not entirely sure what mechanisms orchestrate the manim command, or how everything is parsed to python. If anyone could provide some insight here or point out some applicable functionality I may have missed that would be much appreciated!

**Comment by DzyubSpirit** [comment]
I'm not an expert on this library, but it'll help.

I think you need to add a new flag --data here:
https://github.com/3b1b/manim/blob/master/manimlib/config.py#L25-L29

Then add a new dictionary entry "data" here:
https://github.com/3b1b/manim/blob/master/manimlib/extract_scene.py#L140-L150

Then any Scene can use this in the constructor :)
Can you tell more about what scene are you trying to use with dynamic data?

**Comment by CadenScharpf** [comment]
Thanks just what I needed! Im working on a web app that will generate animation's of the different sorting processes on the fly (with user inputted array), mainly to visualize whats going on during each pass.
