### ISSUE TITLE
Custom tex_template.tex?

### ISSUE THREAD

**Issue by PhilippImhof** [3b1b/manim#743]
While discovering the power of `manim`, I was wondering whether we could easily specify a custom `tex_template.tex` for a certain project. I sometimes use custom packages, but I would rather not want to modify the system-wide file, mostly because it would be overwritten with the next update. 

An easy solution would be the possibility of an additional command line argument. Also, it might be possible to redefine `TEX_DIR` and/or `TEMPLATE_TEX_FILE` inside the python script that is used to generate the scenes. However, I did not succeed in doing so.

**Comment by Elteoremadebeethoven** [comment]
I did something similar in [my manim version](https://github.com/Elteoremadebeethoven/Manim-TB). 

1. First you have to locate the [folder](https://github.com/Elteoremadebeethoven/Manim-TB/tree/master/manimlib/tex_files) where the tex_templates will be. 
2. Then, in [manimlib/constants.py](https://github.com/Elteoremadebeethoven/Manim-TB/blob/master/manimlib/constants.py#L43) you can set each TEX_TEMPLATE_FILE_BODY.
3. And, in [manimlib/mobject/svg/tex_mobject.py](https://github.com/Elteoremadebeethoven/Manim-TB/blob/master/manimlib/mobject/svg/tex_mobject.py#L328) you can create your own `TexMobject` sublcasses.
