### ISSUE TITLE
How to blur the entire backgroud (even the text if present) except some text (rather a single word)

### ISSUE THREAD

**Issue by GSri30** [3b1b/manim#750]
I have some text
now i want it to get blur except one word (which i want it to fade in later)
im not able to understand if at all we can can achieve it or not..
so if such a feature is in implementing stage, we are highly contended

**Comment by GSri30** [comment]
i have the following scene:
class definition(Scene):
    def construct(self):
        definition_text_1=TextMobject("A sequence, $(x_n)$ is said to be a" ,"Cauchy", "Sequence if ","for all", "$\\epsilon > 0$")
        definition_text_2=TextMobject("$\\exists$ \\ K($\\epsilon$) such that ","for all m,n $\geq$ $ K(\\epsilon)$,","$|x_m-x_n|<\\epsilon$")
        definition_text_1.shift(UP)
        definition_text_1.set_color_by_tex_to_color_map({"Cauchy": YELLOW,"$\\epsilon > 0$": BLUE,"for all":RED})
        definition_text_2.set_color_by_tex_to_color_map({"$|x_m-x_n|<\\epsilon$": YELLOW," \\ K($\\epsilon$) ":BLUE,"for all m,n $\geq$ $ K(\\epsilon)$,":BLUE})

        self.play(Write(definition_text_1))
        self.play(Write(definition_text_2))
	#self.play(Applymethod())
        self.wait(3)

here i want to blur the entire screen and only highlight (fade in) the word "for all"
is there any way to do so?

**Comment by Elteoremadebeethoven** [comment]
@kolibril13

**Comment by kolibril13** [comment]
Yes, there is.
Actually I made a whole video in manim in explaining how to blur an image.
https://www.youtube.com/watch?v=frJXybMDlpc
The code is here:
https://github.com/kolibril13/manim/tree/master/hendrik_active/Image_Processing/FourierIdea

What you want to do is not easy, but in a few ours doable.
(sorry, i dont have the time to do that for you, but here a draft of what I would do):
1. Render the scene and save the image with -s  as an argument in the console.
2. Load this image into your scene and apply an image filter to this image.
You can use my blurring filter, in the class FourierMathJuggling, or any other (probably better) implementation from PIL or scit-image etc, and create lot of image arrays with different blurring factors.
3. For a smooth transition, I wrote the function (kind of hacky):
```python
from manimlib.imports import *

class VideoLoader():
    def __init__(self):
        self.all_frames=np.random.random((30,100,100))*250 # 30 images with shape 100x100

    def get_frames(self):
        return self.all_frames

class VideoScene(Scene):
    def construct(self):
        videoframes=VideoLoader()
        all_frames=videoframes.get_frames()
        dot = Dot()
        video=ImageMobject(np.zeros((100,100)))

        def update_frame(video):
            frame_pos=np.int(dot.get_x()*len(all_frames-1))
            print(frame_pos)
            frame = all_frames[frame_pos, :, :]
            frame=np.uint8(frame)
            video.become(ImageMobject(frame))

        video.add_updater(update_frame)
        dot.next_to(video,DOWN)
        self.add(video, dot)
        self.play(dot.shift, RIGHT, rate_func=linear)
```
4. On top on this you place a box(kind of the next layer) in the same Color as the background
5. Even more on top you have the word "for all".

Its a lot of work, but I think it would look very cool!!
And maybe you are also able to automate this process, so everyone can use it.

But if you dont want to spent to much time with that:
Probably the better way to do it is to use an blurring effect not in manim, but for example in [kdenlive](https://kdenlive.org/en/features/) when you finished your video.
I also made a lot of post processing in mine.

**Comment by GSri30** [comment]
oh..nice!
I got what i want
thanks..

**Comment by AB1908** [comment]
@GSri30 any chance you could share your stuff in a gist?

**Comment by AB1908** [comment]
@kolibril13 I'm having a hard time finding the snippet where you've applied the filter to the image in your repo as forks are not searchable. Could you point me in the right direction?
