### ISSUE TITLE
How can I type ① and △ using TextMobject or TexMobject...

### ISSUE THREAD

**Issue by barakasamsara** [3b1b/manim#766]
I type a sentence with Chinese characters and these symbols but these two symbols didn't appear in the video...

**Comment by xy-23** [comment]
You can use it in `Text()`
e.g. `text = Text('①△', font='Microsoft YaHei Mono')`
Make sure you have the font installed.
For more information about `Text`, please look at https://github.com/3b1b/manim/pull/680

**Comment by barakasamsara** [comment]
> You can use it in `Text()`
> e.g. `text = Text('①△', font='Microsoft YaHei Mono')`
> Make sure you have the font installed.
> For more information about `Text`, please look at #680

太感谢了哈哈
