### ISSUE TITLE
What's the difference between TextMobject and TexMobject

### ISSUE THREAD

**Issue by xianfengting** [3b1b/manim#769]
What's the difference between ```TextMobject``` and ```TexMobject```? Are they the same?

**Comment by PhilippImhof** [comment]
The main difference between `TextMobject` and `TexMobject` is the text math object assumes everything is plain text unless you specify an equation with dollar signs while the Tex math object assumes everything is an equation unless you specify something is plain text using `\\text{}`.

Source: https://talkingphysics.wordpress.com/

Note that you do not need the double backslash if you use raw strings like `r"\text{bla}"`

**Comment by Ananyapam7** [comment]
Hey thanks a lot! I had to modify some lines in the code, the first was the imports at the top where I had to change it to 
`from manimlib.imports import *`

and the Tex objects, I replaced them by TextMobjects, which did the rendering in rendering. Thank you very much good sir!
