### ISSUE TITLE
 opencv-python==3.4.2.17 (from -r requirements.txt 

### ISSUE THREAD

**Issue by Mo1802** [3b1b/manim#772]
Hey everyone,

I followed this tutorial: http://bhowell4.com/manic-install-tutorial-for-mac/

I am running macOS Catalina 10.15 (19A602) on my MacMini (Late 2012)

When in step 7 I try pip3 install -r requirements.txt I get the following error:
Ignoring pycairo: markers ‘sys_platform == “linux”‘ don’t match your environment
Ignoring pycairo: markers ‘sys_platform == “win32″‘ don’t match your environment
Ignoring pyreadline: markers ‘sys_platform == “win32″‘ don’t match your environment
Collecting argparse==1.4.0
Using cached https://files.pythonhosted.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl
Collecting colour==0.1.5
Using cached https://files.pythonhosted.org/packages/74/46/e81907704ab203206769dee1385dc77e1407576ff8f50a0681d0a6b541be/colour-0.1.5-py2.py3-none-any.whl
Collecting numpy==1.16.4
Using cached https://files.pythonhosted.org/packages/d3/4b/f9f4b96c0b1ba43d28a5bdc4b64f0b9d3fbcf31313a51bc766942866a7c7/numpy-1.16.4.zip
Collecting Pillow==5.2.0
Using cached https://files.pythonhosted.org/packages/d3/c4/b45b9c0d549f482dd072055e2d3ced88f3b977f7b87c7a990228b20e7da1/Pillow-5.2.0.tar.gz
Collecting progressbar==2.5
Using cached https://files.pythonhosted.org/packages/a3/a6/b8e451f6cff1c99b4747a2f7235aa904d2d49e8e1464e0b798272aa84358/progressbar-2.5.tar.gz
Collecting scipy==1.3.0
Using cached https://files.pythonhosted.org/packages/cb/97/361c8c6ceb3eb765371a702ea873ff2fe112fa40073e7d2b8199db8eb56e/scipy-1.3.0.tar.gz
Installing build dependencies … done
Getting requirements to build wheel … done
Preparing wheel metadata … done
Collecting tqdm==4.24.0
Using cached https://files.pythonhosted.org/packages/7d/e6/19dfaff08fcbee7f3453e5b537e65a8364f1945f921a36d08be1e2ff3475/tqdm-4.24.0-py2.py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement opencv-python==3.4.2.17 (from -r requirements.txt (line 8)) (from versions: none)
ERROR: No matching distribution found for opencv-python==3.4.2.17 (from -r requirements.txt (line 8))

At first, I simply ignored this, but when I tried to run a test I got the following error: python3 manim.py example_scenes.py SquareToCircle -l
Traceback (most recent call last):
File “manim.py”, line 2, in
import manimlib
File “/Users/moritz/Documents/Animationen/manim37/manimlib/__init__.py”, line 2, in
import manimlib.config
File “/Users/moritz/Documents/Animationen/manim37/manimlib/config.py”, line 2, in
import colour
ModuleNotFoundError: No module named ‘colour’

Thank you in advance

**Comment by Elteoremadebeethoven** [comment]
`python3 -m pip install colour`

**Comment by Mo1802** [comment]
Thank you @Elteoremadebeethoven 
I did a reinstall of Manim since I ran into multiple errors.
It now works just fine.
I really appreciate your help
