### ISSUE TITLE
 RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work   warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)

### ISSUE THREAD

**Issue by javari99** [3b1b/manim#781]
I have been following [this](https://www.youtube.com/watch?v=ZltiKHFWmv8&list=PL2B6OzTsMUrwo4hA3BBfS7ZR34K361Z8F&index=4) tutorial attempting to intall manim on my computer. Im using a venv provided by pycharm when creating a new project and followed all steps until it has given me an error when trying to execute the SquareToCircle scene. The error is the following:

```
(venv) E:\Programacion\Python\manim>python -m manim example_scenes.py SquareToCircle -pl
E:\Programacion\Python\manim\venv\lib\site-packages\pydub\utils.py:165: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
Media will be written to ./media\. You can change this behavior with the --media_dir flag.



Traceback (most recent call last):
  File "E:\Programacion\Python\manim\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "E:\Programacion\Python\manim\manimlib\scene\scene.py", line 53, in __init__
    self.construct()
  File "example_scenes.py", line 83, in construct
    self.play(ShowCreation(square))
  File "E:\Programacion\Python\manim\manimlib\scene\scene.py", line 405, in wrapper
    self.file_writer.begin_animation(allow_write)
  File "E:\Programacion\Python\manim\manimlib\scene\scene_file_writer.py", line 172, in begin_animation
    self.open_movie_pipe()
  File "E:\Programacion\Python\manim\manimlib\scene\scene_file_writer.py", line 258, in open_movie_pipe
    self.writing_process = subprocess.Popen(command, stdin=subprocess.PIPE)
  File "E:\Program Files\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "E:\Program Files\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado
```

I have ffmpeg installed and added to the path 
![da17f83a399a960462397ce653b3811d](https://user-images.githubusercontent.com/24279958/68086423-42036880-fe4c-11e9-9cdd-881111798c79.png)

As additional information i will add the path where it is installed and the actual env variable.

![c5f2e666ad4c1d42ac0fd09c900ae35d](https://user-images.githubusercontent.com/24279958/68086457-94dd2000-fe4c-11e9-8d8d-53b1afe646d3.png)

![f4bbb58ae660285b4603eef835e369b9](https://user-images.githubusercontent.com/24279958/68086458-973f7a00-fe4c-11e9-8444-208b116a4eea.png)

I would really appreciate it if someone could help me out!

**Comment by javari99** [comment]
For anyone wondering, changed my ffmpeg version whick seemed to be incompatible to another version and it works alright now.

**Comment by agelas** [comment]
Can I ask which ffmpeg version you switched to? I have this exact same problem.
