### ISSUE TITLE
How can I graph number axes and functions with arrow using Manim?

### ISSUE THREAD

**Issue by barakasamsara** [3b1b/manim#791]
How can I graph number axes and functions with arrow using Manim?

**Comment by Elteoremadebeethoven** [comment]
Share an example.

**Comment by barakasamsara** [comment]
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/36161299/68913035-f67a8400-0794-11ea-925e-d1d8505a119b.png">

**Comment by barakasamsara** [comment]
> Share an example.


![](https://user-images.githubusercontent.com/36161299/68913035-f67a8400-0794-11ea-925e-d1d8505a119b.png)

**Comment by Elteoremadebeethoven** [comment]
You can create the axes with [NumberLine](https://github.com/3b1b/manim/blob/master/manimlib/mobject/number_line.py#L14), it has an option to include the [arrow](https://github.com/3b1b/manim/blob/master/manimlib/mobject/number_line.py#L35) (`NumberLine(...,include_tip=True)`). As for the functions, there is no predefined method in Manim to do that, so you will have to do it yourself. What you can do is get the derivative from the ends of the functions using [ParametricFunction](https://github.com/3b1b/manim/blob/master/manimlib/mobject/functions.py#L7) or [FunctionGraph](https://github.com/3b1b/manim/blob/master/manimlib/mobject/functions.py#L80), numerically, and add the arrow (a triangle) to that position.
If something does not exist in Manim you can create it.

**Comment by barakasamsara** [comment]
> You can create the axes with [NumberLine](https://github.com/3b1b/manim/blob/master/manimlib/mobject/number_line.py#L14), it has an option to include the [arrow](https://github.com/3b1b/manim/blob/master/manimlib/mobject/number_line.py#L35) (`NumberLine(...,include_tip=True)`). As for the functions, there is no predefined method in Manim to do that, so you will have to do it yourself. What you can do is get the derivative from the ends of the functions using [ParametricFunction](https://github.com/3b1b/manim/blob/master/manimlib/mobject/functions.py#L7) or [FunctionGraph](https://github.com/3b1b/manim/blob/master/manimlib/mobject/functions.py#L80), numerically, and add the arrow (a triangle) to that position, and rotate the arrow according to the derivative.
> **If something does not exist in Manim you can create it.**

Thanks a lot, you're so sweet, it really helpful!
