### ISSUE TITLE
How to graph the overlap of two or more circles and fill color?

### ISSUE THREAD

**Issue by barakasamsara** [3b1b/manim#792]
almost like this:
<img width="476" alt="image" src="https://user-images.githubusercontent.com/36161299/68855788-f4bfaa80-0719-11ea-8e95-bb4033de60d6.png">

**Comment by barakasamsara** [comment]
<img width="517" alt="image" src="https://user-images.githubusercontent.com/36161299/68856419-69471900-071b-11ea-8183-4a774238e874.png">

**Comment by Elteoremadebeethoven** [comment]
There are no methods to do that in Manim, the only way is using math, but that depends of you.

**Comment by barakasamsara** [comment]
> There are no methods to do that in Manim, the only way is using math, but that depends of you.

thanks a lot=-=
