### ISSUE TITLE
How to fill different colour to different parts of a svg graph...

### ISSUE THREAD

**Issue by barakasamsara** [3b1b/manim#793]
I have a picture(svg fomart), which I want to split into several sections. Is it possible to independently color these sections using Manim?

**Comment by Elteoremadebeethoven** [comment]
SVGMobject is an array of vmobjects, so, you can select each one using something like:

```python
svg = SVGMobject("file")
legs = svg[0:2]
arms  = svg[2:4]
```

**Comment by barakasamsara** [comment]
> SVGMobject is an array of vmobjects, so, you can select each one using something like:
> 
> ```python
> svg = SVGMobject("file")
> legs = svg[0:2]
> arms  = svg[2:4]
> ```

Thanks a lot!...but it's too difficult for me ... is there more details about some example...=-=
