### ISSUE TITLE
Can I change the stroke_color of a letter in a TexMobject?

### ISSUE THREAD

**Issue by barakasamsara** [3b1b/manim#794]
not in a TextMobject...

**Comment by Elteoremadebeethoven** [comment]
If you see the [source code of TexMobject](https://github.com/3b1b/manim/blob/master/manimlib/mobject/svg/tex_mobject.py#L28) you will be able to realize that it has no thickness, so, in the particular case of a text you must select the letter you want to change, for example:
```python
        #                  0   1   2 
        text = TexMobject("x","^","2")
        # text[0] == "x"
        # text[1] == "^" # This is not a symbol
        # text[2] == "2"
        text[2].set_stroke(width=4,color=RED)
```
![Help60](https://user-images.githubusercontent.com/43224662/69001188-295d6e80-08a0-11ea-8444-1e0d2b243de9.png)

**Comment by barakasamsara** [comment]
Thanks a lot ... but I don't know why the result like this:
<img width="95" alt="image" src="https://user-images.githubusercontent.com/36161299/69004124-d25fa400-0948-11ea-810c-8b25d51d1f05.png">
...
So I have to change the color of the letter to black and then the color of the letter will be the same as the stroke color...

**Comment by barakasamsara** [comment]
> If you see the [source code of TexMobject](https://github.com/3b1b/manim/blob/master/manimlib/mobject/svg/tex_mobject.py#L28) you will be able to realize that it has no thickness, so, in the particular case of a text you must select the letter you want to change, for example:
> 
> ```python
>         #                  0   1   2 
>         text = TexMobject("x","^","2")
>         # text[0] == "x"
>         # text[1] == "^" # This is not a symbol
>         # text[2] == "2"
>         text[2].set_stroke(width=4,color=RED)
> ```
> 
> ![Help60](https://user-images.githubusercontent.com/43224662/69001188-295d6e80-08a0-11ea-8444-1e0d2b243de9.png)

Thanks a lot, I just saw the source code of TexMobject ,and I found I just  made a mistake, 
it's         
"background_stroke_width": 1,
not
"stroke_width": 0,
