### ISSUE TITLE
Can I arrange a TexMobject and a ImageMobject as a group?

### ISSUE THREAD

**Issue by barakasamsara** [3b1b/manim#795]
Can I arrange a TexMobject and a ImageMobject as a group?
=-=

File "*****.py", line 871, in __init__
    raise Exception("All submobjects must be of type VMobject")
Exception: All submobjects must be of type VMobject

How To Solve this problem?

**Comment by Elteoremadebeethoven** [comment]
Yes
```python
group = Group(image,text).arrange(DOWN)
```

**Comment by barakasamsara** [comment]
> Yes
> 
> ```python
> group = Group(image,text).arrange(DOWN)
> ```

also the same with  TexMobject? It doesn't work...and the reminder like that...

**Comment by barakasamsara** [comment]
code:
   a = ImageMobject(self.a)
    a.set_height(7.95)
    self.play(FadeInFromLarge(a), run_time=1.5)

    text1 = TexMobject("a",color=Black).scale(2).move_to(np.array([-4,-1.25,0]))
    self.add(text1)
    self.wait(1)

    group1 = VGroup(a, text1).scale(.5)
    self.play(ApplyMethod(group1.copy().shift, (0,3.5,0)))

terminal reminder:
raise Exception("All submobjects must be of type VMobject")
Exception: All submobjects must be of type VMobject
...

**Comment by zavden** [comment]
Can you please pay attention to the answers? It's `Group` not` VGroup`.

**Comment by barakasamsara** [comment]
> Can you please pay attention to the answers? It's `Group` not` VGroup`.

Thanks a lot, I'll try it again=-=

**Comment by barakasamsara** [comment]
> Can you please pay attention to the answers? It's `Group` not` VGroup`.

It works, THANKS!

**Comment by barakasamsara** [comment]
> Yes
> 
> ```python
> group = Group(image,text).arrange(DOWN)
> ```

Thanks a lot! It works
