### ISSUE TITLE
'latex' is not recognized as an internal or external command, operable program or batch file. Exception: Latex error converting to dvi.

### ISSUE THREAD

**Issue by Weirdguyz** [3b1b/manim#799]
I am having the common issue of `'latex' is not recognized as an internal or external command,
operable program or batch file.` I have attempted many times (several hours) to solve this problem, including several restarts of my laptop (Win10), and a complete reinstall of Manim and other required components. 
![image](https://user-images.githubusercontent.com/40163448/69188658-e2f06400-0b6c-11ea-8304-1890812cd2cf.png)
I have installed according to [this](https://www.youtube.com/watch?v=ZltiKHFWmv8&list=PL2B6OzTsMUrwo4hA3BBfS7ZR34K361Z8F&index=4) tutorial. 

My path variable is as follows.
```C:\Manim\manim_3_feb>path PATH="C:\MikTeX_pack\miktex\bin\x64\;C:\FFmpeg\bin\;C:\sox-14-4-2\;C:\Manim\manim_3_feb\;";"C:\MikTeX_pack\miktex\bin\x64\;C:\FFmpeg\bin\;C:\sox-14-4-2\;C:\Manim\manim_3_feb\;";C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;"C:\Windows\system32;C:\MikTeX_pack\miktex\bin\x64\;C:\FFmpeg\bin\;C:\sox-14-4-2\;C:\Manim\manim_3_feb\;";C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\(name)\AppData\Local\Microsoft\WindowsApps;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\(name)\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\(name)\AppData\Local\Programs\Python\Python37-32\;C:\Users\(name)\AppData\Local\Microsoft\WindowsApps;"C:\MikTeX_pack\miktex\bin\x64\;C:\FFmpeg\bin\;C:\sox-14-4-2\;C:\Manim\manim_3_feb\;";```

I did attempt fixes listed in other issues, namely [Issue 623](https://github.com/3b1b/manim/issues/623), but nothing has worked thus far. I am at my wits end at this point.

Related stuff:
![image](https://user-images.githubusercontent.com/40163448/69188968-76c23000-0b6d-11ea-9e9a-a84bde0b339d.png)
![image](https://user-images.githubusercontent.com/40163448/69189056-9e18fd00-0b6d-11ea-8747-b78049dca754.png)
https://pastebin.com/wCcEpZb1

**Comment by Elteoremadebeethoven** [comment]
You did not follow the instructions correctly, in minute [2:10](https://www.youtube.com/watch?v=ZltiKHFWmv8&t=2m10s) I specify that, *the folder in which the packages are downloaded **is different from** that of the installation*. In the video, I **download** the packages in `C:\MikTeX_Pack`, but the **installation** is done in `C:\Program_Files\MikTeX2.9`. 

I don't know where you installed MikTeX, I hope it was in that same direction (`C:\Program_Files\MikTeX2.9)`. In your PATH variable I can see that **you did not enter the installation folder, but the download folder**, so, look for the folder where you installed MikTeX and add it to your PATH. 

Once you have done it you should be able to execute the `latex` command on any terminal and it must be recognized, as Python, SoX and FFmpeg, if not, the problem will surely be your PATH variable, so be careful when time to modify it.

**Comment by Weirdguyz** [comment]
The `"` symbols were an artifact of generating the whole path through the command prompt, as is the `C:\Manim\manim_3_feb>path PATH="`. Miktex is **installed** in C:\MikTeX_pack\miktex\bin\x64\ (Which I changed to C:\miktex\miktex\bin\x64). 

I just cleaned up the duplicates and got this ```C:\miktex\miktex\bin\x64;C:\FFmpeg\bin;C:\sox-14-4-2;C:\Manim\manim_3_feb\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\nitsc\AppData\Local\Microsoft\WindowsApps;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;``` 

I can now run FFmpeg and latex in `C:\Manim\manim-master>` in the command prompt, and they both work. However, the issue remains, except without `'latex' is not recognized as an internal or external command, operable program or batch file.`

**Comment by Elteoremadebeethoven** [comment]
What do you mean with:
>Which I changed to C:\miktex\miktex\bin\x64

You installed it again or moved the files?, I hope you installed it again, because you can't modify the name or location of the programs just like that.

Remove the `C:\Manim\manim_3_feb\` from your path, that can bring you trouble when rendering scenes.

If you have done the steps correctly then this error may be due to the fact that the full version was not installed, since LaTeX needs certain packages to work, it is a mess to install one by one, so I recommend the full version. If it does not work again, uninstall MikTeX, remove everything that has to do with MikTeX and reinstall it. You generally don't have to add MikTeX to the path since the installer does it automatically.

If the error persist then there are only two options left. Or you learn to configure MikTeX correctly, which is not easy if you do not have previous knowledge, or install a light Linux distribution (such as Lubuntu) in a virtual machine (with VirtualBoX for example, watch videos on YouTube) and follow the tutorial Linux on my channel.

**Comment by Elteoremadebeethoven** [comment]
If you are reinstalling miktex follow the instructions in my video to the letter. At the end of the installation you can confirm that, in the PATH, the directory where the executables are located has been correctly added. Do not modify it unless you confirm that the path directory does not contain the executables. Note, Manim works with python3.7 so don't install the latest version 3.8

**Comment by Weirdguyz** [comment]
After a reinstall, `python -m manim example_scenes.py WriteStuff -pl` now works. Thank you for your help, and I'm sorry if I was a nuisance.
