### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement opencv-python==3.4.2.17 (from manimlib) (from versions: 3.4.8.29, 4.1.2.30)

### ISSUE THREAD

**Issue by HylianAdventurer** [3b1b/manim#802]
I am working on installing manim on my computer but when I run the pip command I receive this error:

**ERROR: Could not find a version that satisfies the requirement opencv-python==3.4.2.17 (from manimlib) (from versions: 3.4.8.29, 4.1.2.30)**

It would appear to me that the opencv-python version that manim requires is no longer available though I might be wrong about that. Is there a way around this?
(BTW, for clarification I am using the command `pip3 install manimlib`, I have also tried to specifically download the opencv version 3.4.2.17 with the command `pip install opencv-python==3.4.2.17` but I receive the exact same error)

**Comment by airqualityanthony** [comment]
How did you solve this?
