### ISSUE TITLE
Typo in "WriteStuff" Example Scene

### ISSUE THREAD

**Issue by blgobler** [3b1b/manim#806]
Just wanted to point this out...
The WriteStuff example scene says "This is **a some** text". Shouldn't it read "This is some text" instead?

<img width="1128" alt="WriteStuff" src="https://user-images.githubusercontent.com/58131742/69491649-ea15bb80-0e65-11ea-84ab-a1720cae56a4.png">

**Comment by Micoael** [comment]
Sounds like true...
