### ISSUE TITLE
Square to circle is working fine and Write stuff is giving no error except this 

### ISSUE THREAD

**Issue by SoutrikDas** [3b1b/manim#812]
![1575055261031618833581](https://user-images.githubusercontent.com/56778179/69887144-83801a00-130b-11ea-99a0-cce71ec9ac65.jpg)

**Comment by mithem** [comment]
Are you sure you have LaTeX installed (https://www.latex-project.org/get/) as WriteStuff does use it and SquareToCircle doesn't

**Comment by Elteoremadebeethoven** [comment]
Click on **INSTALL**
