### ISSUE TITLE
File "/manim/manimlib/mobject/mobject.py", line 9, in <module>     from colour import Color ImportError: cannot import name 'Color' from 'colour' (unknown location)

### ISSUE THREAD

**Issue by dtbulmerJRs** [3b1b/manim#824]
I tried to run (in several manim files)
python3 ./manim.py '/manim/3b1b_projects/old/windmill.py' ShowTest -pl

but it give error involving the colour lib in python.

Traceback (most recent call last):
  File "./manim.py", line 2, in <module>
    import manimlib
  File "/manim/manimlib/__init__.py", line 4, in <module>
    import manimlib.extract_scene
  File "/manim/manimlib/extract_scene.py", line 9, in <module>
    from manimlib.scene.scene import Scene
  File "/manim/manimlib/scene/scene.py", line 9, in <module>
    from manimlib.animation.animation import Animation
  File "/manim/manimlib/animation/animation.py", line 5, in <module>
    from manimlib.mobject.mobject import Mobject
  File "/manim/manimlib/mobject/mobject.py", line 9, in <module>
    from colour import Color
ImportError: cannot import name 'Color' from 'colour' (unknown location)

**Comment by Aathish04** [comment]
Check if `colour` is installed using pip. If it isn't, then install it. If it is, then reinstall it.

**Comment by dtbulmerJRs** [comment]
i tried reinstalling it.  why does everything that requires:
from colour import Color 
fails?

**Comment by dtbulmerJRs** [comment]
I solved it by copying the module colour.py from the python2 directory to the python3 directory?  took me weeks of trying things out to fix it

'''
sudo cp /usr/local/lib/python2.7/dist-packages/colour.py /usr/local/lib/python3.7/dist-packages/colour.py
'''

**Comment by Aathish04** [comment]
I see. The actual mistake that was made was installing color as a Python2.7
package instead of a python3.7 package. In your systems case, try using
'pip3' instead of 'pip' command.
