### ISSUE TITLE
cant use group in group? because self.play() doesnt perfect well

### ISSUE THREAD

**Issue by sexyzeky** [3b1b/manim#825]
I just wanna make this animation that fade in flower of life. I'm sure that shape code is not incorrect. Because when ı use self.add(flower) it works perfectly. But when ı make group and put in the self.play(FadeIn(flower)), shape does not appear perfect (ı showed  with red). I'm gonna mad.. And big_circle doesnt appear too. What is wrong there? Can't use groups belong another groups? ıf it is true, what should ı do?

class YaşamÇiçeği(Scene):

    def construct(self):
        rad = TAU / 6
        x = RIGHT
        y = UP / 2
        ÇY = RIGHT * .866 + UP * .5
        ÇA = RIGHT * .866 + DOWN * .5

        yay1 = ArcBetweenPoints(ORIGIN, UP, rad)
        yay2 = ArcBetweenPoints(UP, ORIGIN, rad)
        yaprak1 = Group(yay1, yay2)

        yay3 = ArcBetweenPoints(ORIGIN, ÇY, rad)
        yay4 = ArcBetweenPoints(ÇY, ORIGIN, rad)
        yaprak2 = Group(yay3, yay4)

        yay5 = ArcBetweenPoints(ORIGIN, ÇA, rad)
        yay6 = ArcBetweenPoints(ÇA, ORIGIN, rad)
        yaprak3 = Group(yay5, yay6)

        yay7 = ArcBetweenPoints(ORIGIN, DOWN, rad)
        yay8 = ArcBetweenPoints(DOWN, ORIGIN, rad)
        yaprak4 = Group(yay7, yay8)

        yay9 = ArcBetweenPoints(ORIGIN, -ÇY, rad)
        yay10 = ArcBetweenPoints(-ÇY, ORIGIN, rad)
        yaprak5 = Group(yay9, yay10)

        yay11 = ArcBetweenPoints(ORIGIN, -ÇA, rad)
        yay12 = ArcBetweenPoints(-ÇA, ORIGIN, rad)
        yaprak6 = Group(yay11, yay12)

        çiçek1 = Group(yaprak1, yaprak2, yaprak3, yaprak4, yaprak5, yaprak6)
        çiçek1.set_color([PURPLE_E, BLUE_D, YENİ_RENK], False)
        çiçek1.set_color([BLUE_C, WHITE], False)
        çiçek1.set_color([DARK_BLUE, WHITE], False)
        çiçek1.set_color([PURPLE_E, WHITE], False)

        çiçek21 = çiçek1.copy().move_to(UP)
        çiçek22 = çiçek21.copy().move_to(ÇY)
        çiçek23 = çiçek21.copy().move_to(ÇA)
        çiçek24 = çiçek21.copy().move_to(DOWN)
        çiçek25 = çiçek21.copy().move_to(-ÇY)
        çiçek26 = çiçek21.copy().move_to(-ÇA)
        orta = Group(çiçek21, çiçek22, çiçek23, çiçek24, çiçek25, çiçek26)

        çiçek31 = çiçek1.copy().move_to(2 * UP)
        çiçek32 = çiçek31.copy().move_to(UP + ÇY)
        çiçek33 = çiçek31.copy().move_to(2 * ÇY)
        çiçek34 = çiçek31.copy().move_to(1.732 * RIGHT)
        çiçek35 = çiçek31.copy().move_to(2 * ÇA)
        çiçek36 = çiçek31.copy().move_to(DOWN + ÇA)
        çiçek37 = çiçek31.copy().move_to(2 * DOWN)
        çiçek38 = çiçek31.copy().move_to(DOWN - ÇY)
        çiçek39 = çiçek31.copy().move_to(2 * -ÇY)
        çiçek310 = çiçek31.copy().move_to(1.732 * LEFT)
        çiçek311 = çiçek31.copy().move_to(2 * -ÇA)
        çiçek312 = çiçek31.copy().move_to(UP - ÇA)
        dış = Group(çiçek31, çiçek32, çiçek33, çiçek34, çiçek35, çiçek36, çiçek37, çiçek38, çiçek39, çiçek310, çiçek311,
                    çiçek312)

        hat1 = yaprak3.copy().move_to(UP * 3 + ÇA * .5)
        hat2 = yaprak3.copy().move_to(UP * 3 + ÇA * 1.5)
        hat3 = yaprak3.copy().move_to(UP * 3 + ÇA * 2.5)
        hat4 = yaprak4.copy().move_to(DOWN / 2 + 3 * ÇY)
        hat5 = hat4.copy().move_to(3 * ÇY + DOWN * 1.5)
        hat6 = hat4.copy().move_to(DOWN * 2.5 + 3 * ÇY)
        hat7 = yaprak5.copy().move_to(3 * ÇA - ÇY / 2)
        hat8 = hat7.copy().move_to(-1.5 * ÇY + 3 * ÇA)
        hat9 = hat7.copy().move_to(-2.5 * ÇY + 3 * ÇA)
        hat10 = yaprak6.copy().move_to(DOWN * 3 - .5 * ÇA)
        hat11 = hat10.copy().move_to(DOWN * 3 - 1.5 * ÇA)
        hat12 = hat10.copy().move_to(DOWN * 3 - 2.5 * ÇA)
        hat13 = yaprak1.copy().move_to(.5 * UP + 3 * -ÇY)
        hat14 = hat13.copy().move_to(1.5 * UP - 3 * ÇY)
        hat15 = hat13.copy().move_to(2.5 * UP - 3 * ÇY)
        hat16 = yaprak2.copy().move_to(3 * -ÇA + .5 * ÇY)
        hat17 = yaprak2.copy().move_to(1.5 * ÇY - 3 * ÇA)
        hat18 = yaprak2.copy().move_to(2.5 * ÇY - 3 * ÇA)

        hat_a = Group(hat1, hat2, hat3, hat4, hat4, hat5, hat6, hat7, hat8)
        hat_b = Group(hat9, hat10, hat11, hat12, hat13, hat14, hat15, hat16, hat17, hat18, )
        hat = Group(hat_a, hat_b)

        big_circle = Circle(radius=3)

        flower = Group(çiçek1, orta, dış, hat, big_circle)
        flower.set_color([PURPLE_E,DARK_BLUE,YENİ_RENK])
        self.play(FadeIn(flower), run_time=3)
        self.wait(2)

This is when ı use self.play(FadeIn(flower):

![Adsız](https://user-images.githubusercontent.com/58697394/70448141-faa67280-1ab0-11ea-8402-ec5fc722f5aa.png)

And this is when ı use self.add(flower) 
![Adsız](https://user-images.githubusercontent.com/58697394/70448835-fa5aa700-1ab1-11ea-930c-2b01fa1982e0.jpg)

**Comment by sexyzeky** [comment]
> I just wanna make this animation that fade in flower of life. I'm sure that shape code is not incorrect. Because when ı use self.add(flower) it works perfectly. But when ı make group and put in the self.play(FadeIn(flower)), shape does not appear perfect (ı showed with red). I'm gonna mad.. And big_circle doesnt appear too. What is wrong there? Can't use groups belong another groups? ıf it is true, what should ı do?
> 
> class YaşamÇiçeği(Scene):
> 
> ```
> def construct(self):
>     rad = TAU / 6
>     x = RIGHT
>     y = UP / 2
>     ÇY = RIGHT * .866 + UP * .5
>     ÇA = RIGHT * .866 + DOWN * .5
> 
>     yay1 = ArcBetweenPoints(ORIGIN, UP, rad)
>     yay2 = ArcBetweenPoints(UP, ORIGIN, rad)
>     yaprak1 = Group(yay1, yay2)
> 
>     yay3 = ArcBetweenPoints(ORIGIN, ÇY, rad)
>     yay4 = ArcBetweenPoints(ÇY, ORIGIN, rad)
>     yaprak2 = Group(yay3, yay4)
> 
>     yay5 = ArcBetweenPoints(ORIGIN, ÇA, rad)
>     yay6 = ArcBetweenPoints(ÇA, ORIGIN, rad)
>     yaprak3 = Group(yay5, yay6)
> 
>     yay7 = ArcBetweenPoints(ORIGIN, DOWN, rad)
>     yay8 = ArcBetweenPoints(DOWN, ORIGIN, rad)
>     yaprak4 = Group(yay7, yay8)
> 
>     yay9 = ArcBetweenPoints(ORIGIN, -ÇY, rad)
>     yay10 = ArcBetweenPoints(-ÇY, ORIGIN, rad)
>     yaprak5 = Group(yay9, yay10)
> 
>     yay11 = ArcBetweenPoints(ORIGIN, -ÇA, rad)
>     yay12 = ArcBetweenPoints(-ÇA, ORIGIN, rad)
>     yaprak6 = Group(yay11, yay12)
> 
>     çiçek1 = Group(yaprak1, yaprak2, yaprak3, yaprak4, yaprak5, yaprak6)
>     çiçek1.set_color([PURPLE_E, BLUE_D, YENİ_RENK], False)
>     çiçek1.set_color([BLUE_C, WHITE], False)
>     çiçek1.set_color([DARK_BLUE, WHITE], False)
>     çiçek1.set_color([PURPLE_E, WHITE], False)
> 
>     çiçek21 = çiçek1.copy().move_to(UP)
>     çiçek22 = çiçek21.copy().move_to(ÇY)
>     çiçek23 = çiçek21.copy().move_to(ÇA)
>     çiçek24 = çiçek21.copy().move_to(DOWN)
>     çiçek25 = çiçek21.copy().move_to(-ÇY)
>     çiçek26 = çiçek21.copy().move_to(-ÇA)
>     orta = Group(çiçek21, çiçek22, çiçek23, çiçek24, çiçek25, çiçek26)
> 
>     çiçek31 = çiçek1.copy().move_to(2 * UP)
>     çiçek32 = çiçek31.copy().move_to(UP + ÇY)
>     çiçek33 = çiçek31.copy().move_to(2 * ÇY)
>     çiçek34 = çiçek31.copy().move_to(1.732 * RIGHT)
>     çiçek35 = çiçek31.copy().move_to(2 * ÇA)
>     çiçek36 = çiçek31.copy().move_to(DOWN + ÇA)
>     çiçek37 = çiçek31.copy().move_to(2 * DOWN)
>     çiçek38 = çiçek31.copy().move_to(DOWN - ÇY)
>     çiçek39 = çiçek31.copy().move_to(2 * -ÇY)
>     çiçek310 = çiçek31.copy().move_to(1.732 * LEFT)
>     çiçek311 = çiçek31.copy().move_to(2 * -ÇA)
>     çiçek312 = çiçek31.copy().move_to(UP - ÇA)
>     dış = Group(çiçek31, çiçek32, çiçek33, çiçek34, çiçek35, çiçek36, çiçek37, çiçek38, çiçek39, çiçek310, çiçek311,
>                 çiçek312)
> 
>     hat1 = yaprak3.copy().move_to(UP * 3 + ÇA * .5)
>     hat2 = yaprak3.copy().move_to(UP * 3 + ÇA * 1.5)
>     hat3 = yaprak3.copy().move_to(UP * 3 + ÇA * 2.5)
>     hat4 = yaprak4.copy().move_to(DOWN / 2 + 3 * ÇY)
>     hat5 = hat4.copy().move_to(3 * ÇY + DOWN * 1.5)
>     hat6 = hat4.copy().move_to(DOWN * 2.5 + 3 * ÇY)
>     hat7 = yaprak5.copy().move_to(3 * ÇA - ÇY / 2)
>     hat8 = hat7.copy().move_to(-1.5 * ÇY + 3 * ÇA)
>     hat9 = hat7.copy().move_to(-2.5 * ÇY + 3 * ÇA)
>     hat10 = yaprak6.copy().move_to(DOWN * 3 - .5 * ÇA)
>     hat11 = hat10.copy().move_to(DOWN * 3 - 1.5 * ÇA)
>     hat12 = hat10.copy().move_to(DOWN * 3 - 2.5 * ÇA)
>     hat13 = yaprak1.copy().move_to(.5 * UP + 3 * -ÇY)
>     hat14 = hat13.copy().move_to(1.5 * UP - 3 * ÇY)
>     hat15 = hat13.copy().move_to(2.5 * UP - 3 * ÇY)
>     hat16 = yaprak2.copy().move_to(3 * -ÇA + .5 * ÇY)
>     hat17 = yaprak2.copy().move_to(1.5 * ÇY - 3 * ÇA)
>     hat18 = yaprak2.copy().move_to(2.5 * ÇY - 3 * ÇA)
> 
>     hat_a = Group(hat1, hat2, hat3, hat4, hat4, hat5, hat6, hat7, hat8)
>     hat_b = Group(hat9, hat10, hat11, hat12, hat13, hat14, hat15, hat16, hat17, hat18, )
>     hat = Group(hat_a, hat_b)
> 
>     big_circle = Circle(radius=3)
> 
>     flower = Group(çiçek1, orta, dış, hat, big_circle)
>     flower.set_color([PURPLE_E,DARK_BLUE,YENİ_RENK])
>     self.play(FadeIn(flower), run_time=3)
>     self.wait(2)
> ```
> 
> This is when ı use self.play(FadeIn(flower):
> 
> ![Adsız](https://user-images.githubusercontent.com/58697394/70448141-faa67280-1ab0-11ea-8402-ec5fc722f5aa.png)
> 
> And this is when ı use self.add(flower)
> ![Adsız](https://user-images.githubusercontent.com/58697394/70448835-fa5aa700-1ab1-11ea-930c-2b01fa1982e0.jpg)

**Comment by zavden** [comment]
Use `VGroup` instead `Group`

**Comment by leotrs** [comment]
@sexyzeky did you try using VGroup instead of Group?

**Comment by sexyzeky** [comment]
sorry, ı forgot the close issue. ı solved it thanks
