### ISSUE TITLE
Drawing motion graphs

### ISSUE THREAD

**Issue by stefanpatrichi** [3b1b/manim#831]
I know that this is not much of an _issue_, but more like a **question**.
How can we draw graphs in manim that are not necessarily functions (for example a position-time graph)? I've already tried to draw function graphs, but I also want to use manim for physics. Any answer is much appreciated!

**Comment by ddxtanx** [comment]
If you have both the x and y coordinates as a function of time, say as x(t) and y(t) then you can use ParametricFunctions like so

    f = lambda t: np.array([x(t), y(t), 0])
    func = ParametricFunction(f)

    self.play(ShowCreation(func))

Also, in the ParametricFunction instantiation, you can specify start time and end time with t_min=(start time) and t_max=(end_time) like so `ParametricFunction(f, t_min=0, t_max=1)`.

Hope this helps!

**Comment by stefanpatrichi** [comment]
Thanks!
