### ISSUE TITLE
No animations in this scene + Specified file not found

### ISSUE THREAD

**Issue by Timestark** [3b1b/manim#837]
Hello everyone, I've recently installed Manim and after playing a little on Eulertour, i decided to create my own scenes. 
I created a python file "bidule.py" in the main Manim folder with a "Test" scene inside but 2 problems occur : 
  1. When I enter `manim bidule.py Test -w` in the terminal, it spits out : 
`Media will be written to ./media\. You can change this behavior with the --media_dir flag.
No animations in this scene
Played 0 animations`
  Which is unexpected onsidering my code (I'll put it at the end)
  2. When I enter `manim bidule.py Test -pl`, it spits out :
```
Media will be written to ./media\. You can change this behavior with the --media_dir flag.
No animations in this scene
Played 0 animations



Traceback (most recent call last):
  File "c:\users\tvasi\appdata\local\programs\python\python37-32\lib\site-packages\manimlib\extract_scene.py", line 151, in main
    open_file_if_needed(scene.file_writer, **config)
  File "c:\users\tvasi\appdata\local\programs\python\python37-32\lib\site-packages\manimlib\extract_scene.py", line 35, in open_file_if_needed
    os.startfile(file_path)
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable: 'C:\\Manim\\manim_12_2019\\videos\\bidule\\1440p60\\Test.mp4
```
I think I need to first create the video in order to read it, but from what i've managed to undestand, -pl also creates/edits the video file if I'm not wrong... So there is a real problem going on. Is there a problem with my packages or ffmpeg ? I don't see where it is. I've seen other people struggling with similar problems, but their solutions did not work. Thanks in advance for your help.
Here is my python file : 
```
from manimlib.imports import *

class Test(Scene):
    def contruct(self):
        text = TextMobject(r"Bonjour, ceci est du \Latex")
        self.play(Write(text))
        self.wait()`
```

**Comment by Aathish04** [comment]
You've misspelled the word "construct" in the Test() class.
It's just a typo. Here's your fixed code:
`from manimlib.imports import *

class Test(Scene):
    def construct(self):
        text = TextMobject(r"Bonjour, ceci est du \Latex")
        self.play(Write(text))
        self.wait()`

**Comment by Timestark** [comment]
OMG I am sooo stupid !! -_-
Ok thank you very much, I'll test to see if there are any other problems as soon as I can

Thx again

**Comment by Aathish04** [comment]
No issues. Just close this issue if there are no problems. There are way too many dead issues that haven't been closed ;)

**Comment by Timestark** [comment]
Ok Everything's fine now.
I close the issue.

Thx again for your time !

**Comment by MengxingLiu** [comment]
Is there anyway the error could point to the line that caused the problem? in this case the line 
`def construct(self):`
