### ISSUE TITLE
Hi How can I configure the tex_template to write Bengali In Manim. 

### ISSUE THREAD

**Issue by sphuronacademy** [3b1b/manim#840]
How can write Bengali in Manim through Latex.  I have tried different compiler and packages but couldn't make it work. Here is one of my sample sentence. 

"এটি একটি  বাংলা বাক্য'"

**Comment by anil100391** [comment]
pdflatex engine is  not going to work for Bengali. You must have xelatex/lualatex installed for this to work. You should also have some bengali fonts installed. I am using Lohit Bengali font on ubuntu. Here are changes to get this working. I have modified OpeningManimExample from example_scenes.py

1. To use xelatex set TEX_USE_CTEX in manimlib/constants.py to True. 
2. Add following to ctex_template.tex (not tex_template.tex as xelatex uses ctex_template.tex instead)
`\usepackage{polyglossia}
\setmainlanguage[numerals=Devanagari]{bengali}
\setotherlanguage{english}
\newfontfamily\englishfont[Scale=MatchLowercase]{Linux Biolinum O}
\newfontfamily\bengalifont[Script=Bengali]{Lohit Bengali}
`
remove or comment out
`\usepackage[english]{babel}`

3. Finally try out creating a textMobject.
        title = TextMobject("এটি কিছুটা বেঙ্গালি", font="Lohit Bengali")

![image](https://user-images.githubusercontent.com/9294938/71539882-1e9afc80-2969-11ea-8f1d-0bd52abd991c.png)

![image](https://user-images.githubusercontent.com/9294938/71539954-e8aa4800-2969-11ea-829b-dc3cbba6c10c.png)
![image](https://user-images.githubusercontent.com/9294938/71539961-ffe93580-2969-11ea-94d2-375ffcaac783.png)
![image](https://user-images.githubusercontent.com/9294938/71539973-1e4f3100-296a-11ea-80b3-925bd2a73d05.png)

**Comment by sphuronacademy** [comment]
Thanks a lot. I have followed your steps. But it is still showing the following error,

![image](https://user-images.githubusercontent.com/59273373/71540334-03070600-2917-11ea-86b2-d8be82e2c72f.png)
![image](https://user-images.githubusercontent.com/59273373/71540342-1914c680-2917-11ea-8097-a0c109212733.png)





! Internal quantity `chardp' must receive a known value.
<to be read again>
                   ;
beginchar->...R1);charht:=(EXPR2);chardp:=(EXPR3);
                                                  w:=hround(charwd*hppp);h:=...
l.79 beginchar(1,24/22size#,23/22size#,1/22size#)
                                                 ; "pelny krzyz";
>> (0,0,line_thickness,0,0,line_thickness)
! Transform components aren't all known.
<to be read again>
                   ;
l.81   pickup pencircle scaled line_thickness;

[1]
>> 0.1314size
! Internal quantity `charwd' must receive a known value.
<to be read again>
                   ;
beginchar->...byte(EXPR0)else:0fi;charwd:=(EXPR1);
                                                  charht:=(EXPR2);chardp:=(E...
l.105 beginchar(2,24/22size#,23/22size#,1/22size#)
                                                  ; "lewy brzeg";
>> 0.12593size
! Internal quantity `charht' must receive a known value.
<to be read again>
                   ;
beginchar->...0fi;charwd:=(EXPR1);charht:=(EXPR2);
                                                  chardp:=(EXPR3);w:=hround(...
l.105 beginchar(2,24/22size#,23/22size#,1/22size#)
                                                  ; "lewy brzeg";
>> 0.00548size
! Internal quantity `chardp' must receive a known value.
<to be read again>
                   ;
beginchar->...R1);charht:=(EXPR2);chardp:=(EXPR3);
                                                  w:=hround(charwd*hppp);h:=...
l.105 beginchar(2,24/22size#,23/22size#,1/22size#)
                                                  ; "lewy brzeg";
>> (0,0,line_thickness,0,0,line_thickness)
! Transform components aren't all known.
<to be read again>
                   ;
l.107   pickup pencircle scaled line_thickness;

>> (0,0,border_line_thickness,0,0,border_line_thickness)
! Transform components aren't all known.
<to be read again>
                   ;
l.119 ...p pencircle scaled border_line_thickness;

[2]
>> 0.1314size
! Internal quantity `charwd' must receive a known value.
<to be read again>
                   ;
beginchar->...byte(EXPR0)else:0fi;charwd:=(EXPR1);
                                                  charht:=(EXPR2);chardp:=(E...

**Comment by sphuronacademy** [comment]
Hi, I tried opening it in TexStudio (with some text added in the body of the document) and it works there. But when I tried in Manim, it gave a new error now. Seems like we are going closer to the solution. 

Traceback (most recent call last):
  File "C:\manim_DEC\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "C:\manim_DEC\manimlib\scene\scene.py", line 53, in __init__
    self.construct()
  File "example_scenes.py", line 74, in construct
    title = TextMobject("হেলো", font="Lohit Bengali")
  File "C:\manim_DEC\manimlib\mobject\svg\tex_mobject.py", line 150, in __init__
    self.break_up_by_substrings()
  File "C:\manim_DEC\manimlib\mobject\svg\tex_mobject.py", line 190, in break_up_by_substrings
    sub_tex_mob.move_to(self.submobjects[last_submob_index], RIGHT)
IndexError: list index out of range
![image](https://user-images.githubusercontent.com/59273373/71546497-5e5fe500-2965-11ea-8b3b-fc016b8a6600.png)

**Comment by sphuronacademy** [comment]
Now it works finally. Thank you so much. 

![image](https://user-images.githubusercontent.com/59273373/71546586-6b310880-2966-11ea-882e-8f15f4f27de5.png)

**Comment by Ayan2357** [comment]
@anil100391  I tried the exact process that you mentioned, but it is still not working for me. As, soon as i turn TEX_USE_CTEX  to true, all my scenes starts showing an error.

Traceback (most recent call last):
  File "C:\Users\Ani-Ayan PC\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Ani-Ayan PC\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Manim\manim_3_feb\manim.py", line 2, in <module>
    import manimlib.config
  File "C:\Manim\manim_3_feb\manimlib\__init__.py", line 2, in <module>
    import manimlib.config
  File "C:\Manim\manim_3_feb\manimlib\config.py", line 8, in <module>
    import manimlib.constants
  File "C:\Manim\manim_3_feb\manimlib\constants.py", line 50, in <module>
    TEMPLATE_TEXT_FILE_BODY = infile.read()
  File "C:\Users\Ani-Ayan PC\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 660: character maps to <undefined>

What can be the problem?

**Comment by anil100391** [comment]
It says something about unicode decode error. Does scene render correct if you only use English characters?

**Comment by Ayan2357** [comment]
@anil100391 After setting the value true, every scene shows that error. I even tried it on the WrapSquare example in example_scenes.py, which has no text, but it still showed the error
