### ISSUE TITLE
LaTeX Error: Option clash for package inputenc

### ISSUE THREAD

**Issue by maxlukian** [3b1b/manim#843]
I am in the process of installing manimlib. Everything works except LaTex commands (such as TexMobject calls). Upon calling
`python3 -m manim test1.py Shapes -pl`
for the simple scene:
`class Shapes(Scene):
	def construct(self):
		text = TextMobject("hello")
		self.play(Write(text))`
I get the following error:
`Exception: Latex error converting to dvi. See log output above or the log file:`
The log file is as follows:
[2b721902e4189ef0.log](https://github.com/3b1b/manim/files/4008636/2b721902e4189ef0.log)

The most important line is:
`! LaTeX Error: Option clash for package inputenc.`

Any ideas on how to solve this? Thanks so much.

**Comment by quark67** [comment]
Running `python3 -m manim test1.py Shapes -pl` (as you do) will create a .tex file with a cryptic name (probably `2b721902e4189ef0` in your case)  in `manim/manimlib/files/Tex` (the Tex folder is created by manim). Can we see it? Have you tried to run it in a LaTeX editor? Is your LaTeX installation up to date?

**Comment by maxlukian** [comment]
Thanks so much for getting back to me. It does generate the .tex file. Here it is:

`\documentclass[preview]{standalone}

\usepackage[english]{babel}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{dsfont}
\usepackage{setspace}
\usepackage{tipa}
\usepackage{relsize}
\usepackage{textcomp}
\usepackage{mathrsfs}
\usepackage{calligra}
\usepackage{wasysym}
\usepackage{ragged2e}
\usepackage{physics}
\usepackage{xcolor}
\usepackage{textcomp}
\usepackage{microtype}
% \DisableLigatures{encoding = *, family = * }
\usepackage[UTF8]{ctex}

\usepackage[hangul]{kotex}


\usepackage[utf8x]{inputenc}
\linespread{1}

\begin{document}

\centering hello

\end{document}`

Running this in a LaTex editor gives the same exact error: `LaTeX Error: Option clash for package inputenc.`

I have run `brew cask install mactex` and I believe it is up to date.

**Comment by maxlukian** [comment]
Finally, I've figured this out. There were issues in my tex_file_writing.py file that I had to fix. Thanks for your help!
