### ISSUE TITLE
Can't animate VGroup containing images?

### ISSUE THREAD

**Issue by myraygunbarrel** [3b1b/manim#848]
I have a composition of vm-objects and images combined in VGroup. I'm trying to move entire composition, but getting an exception. For example:
```
class Test(Scene):
    def construct(self):
        circle = Circle().to_edge(RIGHT)
        image = ImageMobject('image.png').to_edge(LEFT)
        group = VGroup()
        group.add(circle, image)
        self.add(group)
        self.play(group.move_to, UP)
```
This code throws AttributeError:

```
AttributeError: 'ImageMobject' object has no attribute 'get_anchors'
```

**Comment by Elteoremadebeethoven** [comment]
#795

**Comment by myraygunbarrel** [comment]
Thanks a lot, `Group` instead of `VGroup` is worked. 
By the way, is there any system requirements for using manim? My macbook pro 13' 2018 crashes while trying to render animation with 6 png, 6 circles and 5 lines.

```
(venv) r@mpro:~/manim/project$ manim script.py MyScene -pl
Media will be written to ./media/. You can change this behavior with the --media_dir flag.
Killed: 9   
```

**Comment by Elteoremadebeethoven** [comment]
Manim was not created with the intention of handling many PNG images at the same time, but to create bezier curves. If you are going to use many png images, use a normal video editor.
