### ISSUE TITLE
Suggestion: Using z-order to define layer for Mobjects.

### ISSUE THREAD

**Issue by kolibril13** [3b1b/manim#852]
Matplotlib has a very nice method to define in which layer objects are shown on the screen with a parameter `zorder`.
![image](https://user-images.githubusercontent.com/44469195/71835887-05095b80-30b3-11ea-9a68-7da6253c6312.png) 
When working with manim, it's sometimes a little tricky to get the layers right, so what about an implementation, where you can write:
```py
d=Dot()
self.add(d, zordner= 1)
```
Furthermore, there could be defaults like:
* Dots at the first layer
* Text & Equations at the second layer
* Shapes on the third layer
* Functions and graphs on the fourth layer.

When I posted this text to the discord server, @eulertour wrote:
> I don't think it would require anything more than sorting scene.mobjects by z-index before rendering each frame
and since its already possible to assign arbitrary attributes to mobjects it may end up being a one-line change

**Comment by zimonitrome** [comment]
Thank you.

So there is no way to do even static ordering in GL huh?

I am just getting into manim. Do most people use ManimCE (community) instead of ManimGL (3b1b)?
