### ISSUE TITLE
svg file displayed incorrectly with TikZ on linux

### ISSUE THREAD

**Issue by alexander-schoch-github** [3b1b/manim#854]
This issue seems to only appear on linux (here: arch).

This is the code I ran using `python -m manim mwe.py -s` inside the `manim` folder:

```
from manimlib.imports import *

class TikzMobject(TextMobject):
    CONFIG = {
        "stroke_width": 3,
        "fill_opacity": 0,
        "stroke_opacity": 1,
    }

class ExampleTikz(Scene):
    def construct(self):
        circuit = TikzMobject(r"""
            \begin{tikzpicture}
                \draw (0,0) -- (1,0);
                \node at (1,0) {sometext};
            \end{tikzpicture}
            """
            )
        self.play(Write(circuit))
        self.wait()
```

Without any further configuration, the compilation fails due to an error with `dvisvgm`. After some searching online, the issue can be fixed by using `\documentclass[preview,dvisvgm]{standalone}` in the preamble. Now, if I check the corresponding `.svg` file using inkscape, everything looks the way it should be (same with `.tex` and `.dvi`). However, there appears to be some problem when creating a video/image with the svg file, as it looks like that:

![TIkZ MWE](https://user-images.githubusercontent.com/59538716/71857458-e5405a80-30e7-11ea-9c20-ddf338498c57.png)

This separation of text and lines happens with e.g. `circuitikz` or `chemfig` as well.

Interestingly, in contrast to many other issues here, the error (probably) happens _after_ executing `manimlib/utils/tex_file_writing.py`

**Comment by eulertour** [comment]
Please post/link the svg file.

**Comment by alexander-schoch-github** [comment]
The `.svg` file should be all right.

[svg_file.tar.gz](https://github.com/3b1b/manim/files/4029372/svg_file.tar.gz)
