### ISSUE TITLE
Overlapping regions

### ISSUE THREAD

**Issue by pedroslrey** [3b1b/manim#856]
I'm making an video in manim where I show two ovwwrlaping shapes, and I want to set one of the regions to be on the front, how can I do that?

**Comment by kolibril13** [comment]
```py
class Shapes(Scene):
    def construct(self):
        s1 = Square(fill_opacity=0.3).shift(LEFT)
        s2 = Square(fill_opacity=0.3, color=RED)
        self.add(s1)
        self.add(s2)
```
![Shapes](https://user-images.githubusercontent.com/44469195/72216435-4e2d3580-3521-11ea-8329-02ad9d7802a8.png)
and
```py
class Shapes(Scene):
    def construct(self):
        s1 = Square(fill_opacity=0.3).shift(LEFT)
        s2 = Square(fill_opacity=0.3, color=RED)
        self.add(s2)
        self.add(s1)
```
![Shapes](https://user-images.githubusercontent.com/44469195/72216445-6b620400-3521-11ea-9bd1-2d2c5eb67faf.png)

**Comment by kolibril13** [comment]
Ah, and there is the list  `self.mobjects`.
You can reorder this list, and will get a new order

**Comment by pedroslrey** [comment]
Thank you! I will see the mobject.py file to get some more information about reordering the list.

**Comment by pedroslrey** [comment]
I would like to fade in an mobject behind other mobjects, is there something to make this?

**Comment by pedroslrey** [comment]
I found out a way to do what i wanted thanks you!
I messd up with the mobjects list:

`
...
               self.mobjects = [filltriangle2, filltriangle3, fillarc2] + self.mobjects
		self.play(FadeIn(text), FadeIn(filltriangle2), FadeIn(fillarc2), FadeIn(filltriangle3))
		self.wait(6)
		self.play(FadeOut(filltriangle2), FadeOut(fillarc2), FadeOut(filltriangle3), FadeOut(text))
		...`
