### ISSUE TITLE
How to color elements of latex matrices

### ISSUE THREAD

**Issue by alexnk2** [3b1b/manim#859]
Hi, I wonder how to set a color to individual elements in a matrix.

`matrix2 = TexMobject(r"\begin{pmatrix} 4 \\ 3 \end{pmatrix}")`

I would like to colour the number 4 in red.
When I break down the TexMobject for the matrix into tuples in order to run 
`matrix2[x].set_color(COLOR)` I get an error.
Can somebody explain to me how I can split a matrix in Tex format.
Greatly appreciate it!

**Comment by zavden** [comment]
You have to indentify each element with:
```python
# You can use this without split it
matrix2 = TexMobject(r"\begin{pmatrix} 4 \\ 3 \end{pmatrix}")
matrix2[0].set_color(RED)
matrix2[1].set_color(ORANGE)
```

**Comment by alexnk2** [comment]
When I do:

`matrix2 = TexMobject(r"\begin{pmatrix} 4 \\ 3 \end{pmatrix}")
matrix2[0].set_color(RED)`
 
The whole matrix is coloured in RED. I only want the 4 to be coloured in RED.

**Comment by zavden** [comment]
Try `matrix2[0][1]`

**Comment by alexnk2** [comment]
Thanks, very clever

**Comment by zavden** [comment]
Don't forget close the issue
