### ISSUE TITLE
Trying to make a new shape but only appears black screen image

### ISSUE THREAD

**Issue by sexyzeky** [3b1b/manim#860]
I try to make convex lense. But not using SVGimages or other things. I want to define it in a class But ı'll get a black screen image. What should ı do? Ok, ı can fix it like following: a=ArcBetweenPoints(ORIGIN, UP, self.rad) and b=ArcBetweenPoints(UP, ORIGIN, self.rad) then add self.add(a,b). Ok, there is no problem. But why the self.add() wasn't used in Circle(Arc) class. How can it work? 
Here is the code. 
class YaşamÇiçeği(Mobject):

    CONFIG = {
        "rad" : TAU / 6,
    }

    def __init__(self, **kwargs):
        Mobject.__init__(self)
        ArcBetweenPoints(ORIGIN, UP, self.rad)
        ArcBetweenPoints(UP, ORIGIN, self.rad)

**Comment by sexyzeky** [comment]
Similarly Circle(Arc), I have changed the code as below. But its last code is only read so there appear an arc with start-point UP and end-point RIGHT. How can I add the two Arcs?

class YasamCicegi(ArcBetweenPoints):
    def __init__(self, **kwargs):
        ArcBetweenPoints.__init__(self, DOWN, LEFT, TAU/6)
        ArcBetweenPoints.__init__(self, UP, RIGHT, TAU/6)

**Comment by zavden** [comment]
Ah, I see the problem, you do not have the necessary OOP knowledge needed to use Manim, I recommend that you take [this FULL tutorial](https://docs.python.org/3/tutorial/classes.html) and then re-analyze the code that I left in the previous comment. I don't think it's right to be asking basic OOP questions in such an advanced library, such as Manim. I assure you it will be easier to understand, unlike I did everything I work for you, good luck.
