### ISSUE TITLE
Trouble with installing manim

### ISSUE THREAD

**Issue by 23-21-12-6** [3b1b/manim#863]
I have recently been trying to install manim onto my computer and believe to have done so along with all of the necessary software. I started by using the instructions in the README.md but since I ran into issues I have since been using the more comprehensive guide at [https://www.eulertour.com/learn/manim/index.html]. I moved forward until I had no more errors popping out. However, when I put `python -m manim -h` into the windows command prompt as suggested, I don't get any errors, but I also don't get help text as I should. I also ran `python -m manim example_scenes.py SquareToCircle -pl` with a similar result. No errors showed up in the prompt but the video didn't show up either.
I am new to programming in general so I ask for your patience and understandable answers (although that will up to me). Thanks for any help you give.

**Comment by PgBiel** [comment]
If nothing showed up at all, not even a loading bar indicating the progress of the animation rendering, then something is wrong. Care to share the logs? :)

Also, make sure you `cd` into the manim folder.

**Comment by 23-21-12-6** [comment]
Thanks for the reply.
I've now solved that problem. Turns out I didn't have the path configured properly. But it still isn't working properly. I'm having the same issue as this [https://github.com/3b1b/manim/issues/817](url), which they solved by using python3.7. Is there a way to fix this without installing 3.7? I have 3.8.

**Comment by PgBiel** [comment]
That's a very bizarre problem; it's probably due to a lack of updated versions of libraries for the latest Python. For now, use 3.7

**Comment by 23-21-12-6** [comment]
k, thanks.
