### ISSUE TITLE
AnimationGroup doesn't apply multiple animations to a single object

### ISSUE THREAD

**Issue by AberrantWolf** [3b1b/manim#865]
It seems that when creating an AnimationGroup with animations which affect the same object, e,g:

```
vgroup = Vgroup(rect1, rect2)
AnimationGroup(
    ApplyMethod(rect1.set_height, 2),
    ApplyMethod(vgroup.arrange, RIGHT)
)
```

That only the last animation is actually getting applied, and that they are not being combined. Is there a way to do this that I'm missing?

**Comment by PgBiel** [comment]
Try:
```py
vgroup = VGroup(rect1, rect2)
def modify(vg):
  vg[0].set_height(2)
  vg.arrange(RIGHT)
  return vg

self.play(ApplyFunction(modify, vgroup))
```

**Comment by AberrantWolf** [comment]
Okay, that works. And helped me understand the paradigm of what's going on here. Cheers!

**Comment by PgBiel** [comment]
You're welcome!
