### ISSUE TITLE
Matrices tex problems

### ISSUE THREAD

**Issue by alexnk2** [3b1b/manim#872]
I have been trying to insert variables into TexMobjects involving matrices like so:

```
class Test(Scene):
    def construct(self):
        a = 3
        matrix1 = TexMobject(r"\begin{pmatrix} ", a, r" \\ 4 \end{pmatrix}")
        self.add(matrix1)
```

but I get errors of the following type...

![Annotation 2020-02-03 234536](https://user-images.githubusercontent.com/59810189/73700752-4eaf8b00-46df-11ea-93c9-bc4d1398c742.png)

Any help much appreciated!

**Comment by Elteoremadebeethoven** [comment]
Use `Matrix`,  you can't break LaTeX environments in manim, just formulas

```python
class Matriz(Scene):
    def construct(self):
        matrix1 = Matrix([[1],[2]])
        self.add(matrix1)
```

**Comment by alexnk2** [comment]
Thanks
