### ISSUE TITLE
How to run Manim in Colab?

### ISSUE THREAD

**Issue by qo4on** [3b1b/manim#875]
I see a bunch of errors trying to run it with
`!pip3 install manimlib`

and manual
```
# Install python requirements
python3 -m pip install -r requirements.txt

# Try it out
python3 ./manim.py example_scenes.py SquareToCircle -pl
```

**Comment by Macorreag** [comment]
I have created a [Gist] (https://gist.github.com/Macorreag/abfc02b99a751431d8793e9c5506ef49) to explain how to install Manim in Colab.
I appreciate the improvements that we can make in it to facilitate the work with this tool
https://gist.github.com/Macorreag/abfc02b99a751431d8793e9c5506ef49

**Comment by jeemitsha** [comment]
> I have created a [Gist](https://gist.github.com/Macorreag/abfc02b99a751431d8793e9c5506ef49) to explain how to install Manim in Colab.
> I appreciate the improvements that we can make in it to facilitate the work with this tool
> https://gist.github.com/Macorreag/abfc02b99a751431d8793e9c5506ef49

![image](https://user-images.githubusercontent.com/51538320/104990722-2e3d2580-5a43-11eb-86ec-e986fcce5d37.png)
getting this error

**Comment by Macorreag** [comment]
> > He creado un [Gist](https://gist.github.com/Macorreag/abfc02b99a751431d8793e9c5506ef49) para explicar cómo instalar Manim en Colab. 
> > Agradezco las mejoras que podemos hacer en él para facilitar el trabajo con esta herramienta 
> > https://gist.github.com/Macorreag/abfc02b99a751431d8793e9c5506ef49
> 
> ![imagen](https://user-images.githubusercontent.com/51538320/104990722-2e3d2580-5a43-11eb-86ec-e986fcce5d37.png)
> obteniendo este error

In which cell do you get the error?

**Comment by Joocheol** [comment]
I found a way to run Mamin on Google colab.

https://financial-engineering.medium.com/i-found-a-way-to-run-mamin-on-google-colab-ef37d164c960

**Comment by DannyDannyDanny** [comment]
> I found a way to run Mamin on Google colab.
> 
> https://financial-engineering.medium.com/i-found-a-way-to-run-mamin-on-google-colab-ef37d164c960

From link above:
```
!sudo apt update
!sudo apt install libcairo2-dev ffmpeg texlive texlive-latex-extra texlive-fonts-extra texlive-latex-recommended texlive-science tipa libpango1.0-dev
!pip install manim
!pip install IPython --upgrade
```

From there you can use `from manim import *`

**Comment by DannyDannyDanny** [comment]
Manim doc has a [section on Google Colab](https://docs.manim.community/en/stable/installation/jupyter.html#google-colaboratory)
