### ISSUE TITLE
Issue when rendering only the OpeningManimExample scene

### ISSUE THREAD

**Issue by LachlanJS** [3b1b/manim#883]
Hello, wonderful Manim community :).

Following Theorem Of Beethoven's 1.1 tutorial, I ran into some trouble. The OpeningManimExample scene in example_scenes.py gives me an error from the following command:

python -m manim example_scenes.py OpeningManimExample -pl

The first parts of the scene are rendered until the number plane appears. Other scenes in example_scenes.py render just fine. I did have a lengthy installation process and had to fix a few problems but I managed and I think I have now installed everything correctly. All files referenced in the error message appear to be intact and have never been modified by accident to the best of my knowledge. 
I am running Windows 10 the latest version of Manim, and python 3.7.6.

The error message is as follows:

**Traceback (most recent call last):
  File "C:\Manim\manim-master\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "C:\Manim\manim-master\manimlib\scene\scene.py", line 53, in __init__
    self.construct()
  File "example_scenes.py", line 40, in construct
    grid = NumberPlane()
  File "C:\Manim\manim-master\manimlib\mobject\coordinate_systems.py", line 287, in __init__
    super.__init__(**kwargs)
TypeError: descriptor '__init__' of 'super' object needs an argument**

My apologies if this is a trivial problem, I did my best to find a fix.
My sincerest thanks to anyone who can help :).

**Comment by Elteoremadebeethoven** [comment]
Yes, it is a typo, [here](https://github.com/3b1b/manim/pull/877/files) is the solution.

**Comment by LachlanJS** [comment]
Thank you very much!

**Comment by LachlanJS** [comment]
> Yes, it is a typo, [here](https://github.com/3b1b/manim/pull/877/files) is the solution.

@Elteoremadebeethoven 
Would you be able to comment on this in your video? As it is a relatively new issue from what I can see? Just in case another encounters this problem :)

**Comment by Elteoremadebeethoven** [comment]
It is assumed that in my tutorials (at least the videos listed) you must use the version of February 3, 2019, I did this precisely to avoid this type of problem. If people want to use the latest version then they should be aware of the latest version. So no, I see no reason to comment, because in the future the same will happen.

**Comment by LachlanJS** [comment]
@Elteoremadebeethoven 

Oh okay. Fair enough. Is the version you quote in your video the most stable version or something?

**Comment by Elteoremadebeethoven** [comment]
It is the most stable to run the vast majority of old 3b1b videos, you can watch the video of "How to learn Manim by yourself", with the version of Feb/03/2019 you can run 50 or 60% of the old projects, and this will help you learn much more. But once you've learned the basics (when you get to video 8 of my tutorial) it's a good idea to start using the newest version. Do not forget to close the issue.
