### ISSUE TITLE
This is a BUG? about TexMobject Creat

### ISSUE THREAD

**Issue by guanglun** [3b1b/manim#886]
Input:        
`        TextTDK = TexMobject("""
            \\left.\\begin{matrix}
                123\\\\ 
                456
            \\end{matrix}\\right\\}
        """)`
Error.

input:
`        TextTDK = TexMobject("""
            \\left\\{\\begin{matrix}
                123\\\\ 
                456
            \\end{matrix}\\right\\}
        """)`
That's OK.

If I remove manimlib\mobject\svg\tex_mobject.py:remove_stray_braces,the first input will success.
Is this a BUG?

**Comment by Elteoremadebeethoven** [comment]
The one who is wrong is you, you forgot the point at the end.
```
TexMobject(""" \\left.\\begin{matrix} 123\\\\ 456 \\end{matrix}\\right.\\} """)
                                                                      |
                                                                    HERE
```

**Comment by Elteoremadebeethoven** [comment]
It's not a bug, you just can't draw a single brace in LaTeX using Manim, it's one of its limitations, but for that the Brace object was created.
```python
TextTDK = TexMobject(""" \\left.\\begin{matrix} 123\\\\ 456 \\end{matrix}\\right. """)
brace = Brace(TextTDK,RIGHT)
self.add(TextTDK,brace)
```

**Comment by Spirko** [comment]
You can fool manim's TeX-parsing code by matching your braces in TeX comments.  See:  https://reddit.com/r/manim/comments/fhcs0q/weekly_help_thread_ask_for_manim_help_here/fkedo5r/
