### ISSUE TITLE
No module named manim

### ISSUE THREAD

**Issue by Planeuge** [3b1b/manim#887]
Hi ! So, I tried to install manim but ran into an issue: I have successfully installed pip, cairo, ffmpeg and sox (and updated latex), but when I try to run a file, I get `/usr/bin/python: No module named manim` so I guess manim didn't install where it should have (and with further investigation, it looks like it didn't install at all). So, I'm kinda lost, I have tried many things, but I'm a beginner so I don't know what I should be looking for. I've read that the installation instructions are outdated, so I've tried installing some other ways around but still nothing. As I've said, I'm lost, and don't really even what to say to get some help.

I hope I've been clear enough, thanks in advance !

PS: I've also tried with `python3` and `python3.7` in the command line, same problem.

EDIT: Forgot to precise I'm on Ubuntu !

**Comment by martinwinter** [comment]
I have the same problem on macOS. I am still trying various things but suspect there may be a regression that was introduced recently.

**Comment by martinwinter** [comment]
@Planeuge Somebody on the Discord server suggested you need to `cd` into the manim folder if you are running it as a Python module. You’ll have to find that folder, of course.

**Comment by Planeuge** [comment]
I've (finally) found that folder where manim is installed, but I guess I now have to indicate it, because it's not where it's supposed to be installed ? And if I'm right, how do I do that ?

I've also tried (as suggested) to `cd` into that folder and running `python3 -m manim filename.py -pl` (the file I tested was an example file, I just can't remember the name) but I still get the same error message, so maybe I just didn't understand what you/they meant ?

**Comment by martinwinter** [comment]
I really don’t know exactly what to do, as I do not have Ubuntu myself. Maybe you could join the [Discord server](https://discord.gg/mMRrZQW) and ask people in the manim-help channels?

**Comment by Planeuge** [comment]
Well, it was my "rescue plan", I wasn't sure I could manage to install manim with the cloning method, but I gave it a try after uninstalling my first installation, and it worked like a charm ! I spent more time trying to make the first method work than just using the second method, but I guess I got some experience. Thanks anyway !

**Comment by ricardokl** [comment]
Get an example file, like this one: https://github.com/zimmermant/manim_tutorial/blob/master/manim_tutorial_P37.py
I tried using "python3 -m manim pymanim_tutorial_P37.py Shapes -pl" and got the "No module named manim" error
Next I ran just "manim pymanim_tutorial_P37.py Shapes -pl" and it worked fine.

I guess if you install via pip3 you don't need the "python3 -m" before it (compared to cloning the project)?

Running in Manjaro with kde.

**Comment by giacomovagni** [comment]
I am running into this issue at the moment. Stupid question but does the `venv` folder should be placed in the `manim` folder or outside in a general folder (let's say animation)?

**Comment by DeepMeditativeMind** [comment]
I have faced similar issues and this worked for me
cd manim
python -m pip install -r requirements.txt manim

Hope it helps

**Comment by djkinger** [comment]
This is happening because in the latest updates the python file 'manim' is in some other subfolder.
Try using the following code instead:
python -m manimlib example_scenes.py
