### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by sh0416** [3b1b/manim#888]
1. Steps to reproduce the issue (e.g. the command you ran)

Access to http://www.eulertour.com/learn/manim/.

2. The unexpected behavior that occurred (e.g. error messages or screenshots)

error messages: This site can’t be reached.

3. The environment (e.g. operating system and version of manim)

Is there anyone who knows the real documentation link? or is it just a traffic issue?

**Comment by ruben-ar14-mons** [comment]
I found following site: https://manim.readthedocs.io/en/latest/
But i think that it´s barely usable. But i think there are a few people like @3b1b that have open example projects - with these in mind you could learn by example.

If i have time after my bachelors thesis, i might give a better more in-depth documentation a try.

**Comment by Lutalli** [comment]
Same problem to me. But I'm using an offline version - you may check `manim\docs` and build the doc. For me, I ran `./make.bat latex` and successfully made a doc in the form of LaTeX.

**Comment by eulertour** [comment]
Sorry about that, I'm doing some work to revamp the site. I've removed the link for now but the docs can still be built from the repo as @Lutalli pointed out.

**Comment by sh0416** [comment]
Is there any documentation except that? I don't think it is informative. :(
Tutorial post is much more informative, but I am having difficulty developing my video.

**Comment by Lutalli** [comment]
You are right ... but I suppose we can just wait for the site to be fixed.

**Comment by subtra3t** [comment]
> Is there any documentation except that? I don't think it is informative. :(
> Tutorial post is much more informative, but I am having difficulty developing my video.

@sh0416 I think you would be better off using the [community edition](https://github.com/ManimCommunity/manim/), which has a [thorough documentation](https://docs.manim.community/) and a much larger [community](https://manim.community).
