### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by qo4on** [3b1b/manim#893]
I made a simple test where I draw multiple identical vertical lines from bottom to top in cycle. I found out that each new line renders much slower than previous one. Is it a bug or did I do something wrong?
```
def c(coord):
  if isinstance(coord, (np.ndarray, list)) and len(coord) == 3:
    return np.asarray(coord, dtype=np.float32) / 135
  else:
    return coord / 1.35

import numpy as np
from datetime import datetime

class mainScene(Scene):
  CONFIG = {
      "camera_config": {"background_color": '#ffffff'},
  }
  def construct(self):
    for j in np.arange(-958.5, 960, 2):
      start = datetime.now()
      for _ in np.arange(-540, 540, 2):
        line = Line(c([j, _, 0]), c([j, _+1, 0]), stroke_width=c(1), stroke_color='#000000')
        self.add(line)
        if _ == 538: print(int(j + 959.5), datetime.now() - start)
    
    self.wait(.1)

1 0:00:00.389817
3 0:00:00.927884
5 0:00:01.458466
7 0:00:01.970841
9 0:00:02.500315
11 0:00:03.015520
13 0:00:03.712525
15 0:00:04.210232
17 0:00:04.822479
19 0:00:05.358658
21 0:00:06.160043
```

**Comment by zavden** [comment]
I have no idea what you are trying to do, but if you use "datetime", the time you are capturing is the processing time, that is, the time it takes for your CPU to do the calculations. To use the animation time use `self.time`, like this:

```python
class mainScene(Scene):
    CONFIG = {
        "camera_config": {"background_color": '#ffffff'},
    }
    def construct(self):
        for j in np.arange(-958.5, 960, 2):
            start = self.time
            for _ in np.arange(-540, 540, 2):
                line = Line(c([j, _, 0]), c([j, _+1, 0]), stroke_width=c(1), stroke_color='#000000')
                self.add(line)
                if _ == 538: print(int(j + 959.5), self.time - start)
            
            self.wait(.1)
```

**Comment by qo4on** [comment]
I don't care about animation time. My question is about performance: why does each new `self.add(line)` take more time than previous one? How can I avoid that? How can I keep performance stable regardless of the number of drawn objects?

For example, when I have `100 000` consequtive `self.add(...)` code lines (of `self.play(...)`, it doesn't matter) which I'd like to draw in a predefined time schedule what should I do? After a couple of thouthands rendered objects the time that each new object needs becomes too large.

**Comment by zavden** [comment]
That is quite obvious if you think about how Manim should be working internally. Manim draws each object in each frame according to the preset order in the veritable [`self.mobjects`](https://github.com/3b1b/manim/blob/master/manimlib/scene/scene.py#L41), as you already know `self.add (mob)` adds `mob` to `self.mobjects`. That means that the more mobjects added to the animation, more mobjects each frame will have to draw, for memory consumption. If you add 1000 mobjects with `self.add` then in <b>each frame</b> the 1000 mobjects will have to be added according to the order of` self.mobjects`. There is no way around this because Manim was designed this way.

**Comment by qo4on** [comment]
Thanks a lot!
As for my code example: I `self.add` 540 lines, each line is 2 pixels long. If instead I `self.add` 1 line 1080 pixels long what the perfomance benefit will be? Will it be 540 times faster or there is something else?

**Comment by zavden** [comment]
I don't know that, you could try to add all the lines first in a VGroup and then add that VGroup with self.add. Surely there are libraries that help you measure the performance of your code. But again, Manim was not designed for complex animations, you must use the right tool for the right job.

**Comment by qo4on** [comment]
Ok, thank you. What is the best way to remove objects completely so that they can not slow down scene computation?

**Comment by zavden** [comment]
`self.remove(mob1,mob2,...)`
