### ISSUE TITLE
About the dt parameter in the add_updater function

### ISSUE THREAD

**Issue by woshichuanqilz** [3b1b/manim#895]
Here is my code 
If the update_text with dt parameter the movie work well if not the text in the movie don't move why this happened? 

```
class DebugTest(Scene):
    def construct(self):
        # def update_text(obj, dt): # the text will shift down
        #     obj.shift(DOWN * 0.1) # the text won't move. 
        def update_text(obj):
            obj.shift(DOWN * 0.1)

        text = TextMobject("Z")
        # text.add_updater(lambda d, dt: d.shift(0.1 * DOWN))
        text.add_updater(update_text)
        self.add(text)
        self.wait(10)
```
I check the code here but don't why this problem happened. 
![image](https://user-images.githubusercontent.com/11295355/75438521-0d836180-5993-11ea-9873-b5a0490d3dc8.png)

**Comment by Elteoremadebeethoven** [comment]
That's how manim is designed. When using the `dt` parameter you are telling Manim that you want the function to be executed at every moment of time, if you do not use the `dt` parameter then the function will only be executed when the object it refers to The function has changed. It is a bit complicated to understand at first glance, [here are two examples](https://github.com/Elteoremadebeethoven/AnimationsWithManim/blob/master/English/update_successions/update_successions.py#L184-L261) so you can better understand how these functions work.

**Comment by woshichuanqilz** [comment]
> That's how manim is designed. When using the `dt` parameter you are telling Manim that you want the function to be executed at every moment of time, if you do not use the `dt` parameter then the function will only be executed when the object it refers to The function has changed. It is a bit complicated to understand at first glance, [here are two examples](https://github.com/Elteoremadebeethoven/AnimationsWithManim/blob/master/English/update_successions/update_successions.py#L184-L261) so you can better understand how these functions work.

Thanks man, 

I check the code the dt is used in the wait function to judge weather the udpate is execuated.
![image](https://user-images.githubusercontent.com/11295355/75560639-84e2ef00-5a80-11ea-88e5-fc75124843a6.png)


Thanks again for you help.
