### ISSUE TITLE
Installation of Manim failed

### ISSUE THREAD

**Issue by MartinWy** [3b1b/manim#896]
### If this is a support request:

OSX high Sierra 
Macbook Pro 2011

I followed strictly ALL steps of the tutorial 
At the very end of the installation I get the following error:

ERROR: Could not find a version that satisfies the requirement opencv-python==3.4.2.17 (from -r requirements.txt (line 8)) (from versions: 3.4.8.29, 3.4.9.31, 4.1.2.30, 4.2.0.32)
ERROR: No matching distribution found for opencv-python==3.4.2.17 (from -r requirements.txt (line 8))

It might be that my  hardware is too old???
I noticed that there are requirement sheet less demanding in these cases ;-)

Many thanks

Martin

**Comment by Elteoremadebeethoven** [comment]
In summary, yes, your account is too old, I recommend you install Pyenv to have multiple versions of python, install 3.7.3 and then using that version install the [requirements of this](https://github.com/3b1b/manim/blob/3b088b12843b7a4459fe71eba96b70edafb7aa78/requirements.txt) version.

**Comment by MartinWy** [comment]
Thanks
just one question (since I am not advanced in these things) 
I had installed the environment as requested by the turorial. 
And I had python 3.7.3
since the requirement sheet has allready been installed, I only changed it directly: correct?) 

is that all or do I have to do the installation all over again?  

Is there a way to check whether now everything is fine?

**Comment by MartinWy** [comment]
sorry, I have 3.8.2 
looks like I am getting there :-) 
thanks

**Comment by MartinWy** [comment]
One (hopefully last question)
have downloaded pyhton 3.7 and put 3,8 in the trash
have re and overinstalled averything 
however: 3.8 will be installed again in the manim virtualenv
how to avoid that?

**Comment by MartinWy** [comment]
I give up.
   Erased everything 3 times, 
   installed everything from scratch according to the tutorial (which is great) 
   changed the requirement sheet to the above provided data
      still get the same error 

Collecting tqdm==4.24.0
  Using cached tqdm-4.24.0-py2.py3-none-any.whl (43 kB)
**ERROR: Could not find a version that satisfies the requirement opencv-python==3.4.2.17 (from -r /Volumes/Daten/Manim/manim/requirements.txt (line 8)) (from versions: 3.4.8.29, 3.4.9.31, 4.1.2.30, 4.2.0.32)
ERROR: No matching distribution found for opencv-python==3.4.2.17 (from -r /Volumes/Daten/Manim/manim/requirements.txt (line 8))**
(venv) Martins_Mac:Manim Martin$ 

Can it be, that in the new requirements.txt  the version of  opencv-python==3.4.2.17 needs to be changed?

**Comment by MartinWy** [comment]
ok, found out, that I had no opencv installed at all
so am cleaning that up ;-)
Thanks for all
