### ISSUE TITLE
some characters are missing

### ISSUE THREAD

**Issue by imzzy1201** [3b1b/manim#899]
Hello. I've just installed manim on Ubuntu and I ran the OpeningManimExample successfully, but there's problem about the video. 
![2020-02-29 17-19-01](https://user-images.githubusercontent.com/38782715/75604812-b6f36000-5b17-11ea-9d2e-946861b8d5e1.png)
The text here should be 'That was a transform' , but some characters are missing.

**Comment by sexyzeky** [comment]
If you didn't share the code, how can we help you? Please edit the issue and share the code. Maybe I can help you. If I couldn't, someone helps you more easy.
