### ISSUE TITLE
Color Spread

### ISSUE THREAD

**Issue by sexyzeky** [3b1b/manim#902]
Im going to colorize circle with blue and yellow. But instead of one direction like from left to right or from right to left, ı want to spread the colors from center to circumference. Can we do that. And ıf it is, how?

**Comment by Aathish04** [comment]
There is a `set_submobject_colors_by_radial_gradient` function. You can find it here:
https://github.com/3b1b/manim/blob/27a952b664fd6a540193cee4cb9254a758197c26/manimlib/mobject/mobject.py#L613

If you are done with the issues please close it. As you can see, we have a lot of resolved, yet open threads still hanging around ;).

**Comment by sexyzeky** [comment]
It didn't work, Could you check where the mistake ı made
class Coloring(Scene):
    def construct(self):

        c = Circle(fill_opacity=1)
        c.set_submobject_colors_by_radial_gradient(inner_color=YELLOW, outer_color=BLUE_D)
        self.add(c)

**Comment by Aathish04** [comment]
It appears `.set_submobject_colors_by_radial_gradient(i)` works differently (it puts up a gradient for sub-mobjects of a Group/VGroup. My bad!

**Comment by sexyzeky** [comment]
Oh, no solution has been founded yet..  Even so, thanks

**Comment by Tony031218** [comment]
> Oh, no solution has been founded yet.. Even so, thanks

You can create a `VGroup` containing many connected `Annulus`s, and then use this method, when the number of `Annulus`s is large, you can achieve the desired effect approximately.

**Comment by sexyzeky** [comment]
Great approximation! It can be also used to create an definition to achieve this aim. Thanks
