### ISSUE TITLE
Duplicate implementation of Integer?

### ISSUE THREAD

**Issue by bhbr** [3b1b/manim#91]
This here trips my Python up:

```
class Integer(VGroup):
...
class Integer(DecimalNumber):
...
```

resulting in:

```
File "/Users/Ben/Developer/manim/topics/numerals.py", line 69, in <module>
    class Integer(VGroup):
File "/Users/Ben/Developer/manim/topics/numerals.py", line 72, in Integer
    for i, c in enumerate(num_string):
NameError: name 'num_string' is not defined
```

This appears to be a recent change. Is it even possible to have one class inherit from two different superclasses? Or did a merge go wrong here?

**Comment by 3b1b** [comment]
The merge must have gone wrong.  I did indeed change it, as DecimalNumber fully subsumes the functionality of Integer.  If you see a merge conflict based on any committed changes you have, just delete the VGroup implementation.

As a sidenote, you certainly can have on class inherit from multiple others, but the syntax is "class Class(NameOfFirstSuperclass, NameOfSecondSuperclass)"

**Comment by eulertour** [comment]
Closing, as this issue is resolved.
