### ISSUE TITLE
Calculate the Elapsed Time

### ISSUE THREAD

**Issue by sexyzeky** [3b1b/manim#910]
I will add a voice on a manim video with a video editor. But to coincide the animation with corresponding voice segment, can we find that the time between two animation with a package in manim? Or an another advice?

**Comment by BenStigsen** [comment]
Well you could simply use the `time` module I'm pretty sure. So if we take one of the example scenes where a square is transformed into a circle.

```py
class SquareToCircle(Scene):
    def construct(self):
        circle = Circle()
        square = Square()
        square.flip(RIGHT)
        square.rotate(-3 * TAU / 8)
        circle.set_fill(PINK, opacity=0.5)

        self.play(ShowCreation(square))
        self.play(Transform(square, circle))
        self.play(FadeOut(square))
```
You could then keep track of the start time and end time, then calculate the elapsed time. So to calculate how long it to transform the square into a circle, `self.play(Transform(square, circle))` we could write the following:
```py
class SquareToCircle(Scene):
    def construct(self):
        circle = Circle()
        square = Square()
        square.flip(RIGHT)
        square.rotate(-3 * TAU / 8)
        circle.set_fill(PINK, opacity=0.5)
        self.play(ShowCreation(square))
        
        start_time = time.time() # Start of transform
        self.play(Transform(square, circle))
        elapsed_time = time.time() - start_time # Time it took to transform the square to a circle

        self.play(FadeOut(square))
```

**Comment by sexyzeky** [comment]
Could you show me an example how to read `elapsed_time` ? I'll be very thankful to you

**Comment by BenStigsen** [comment]
I'm not sure what you mean by reading elapsed time. You could print it out to a console.
I would append the time stamps to a text file, and then for video editing or voice over you can look at those timestamps in the txt file.

**Comment by sexyzeky** [comment]
Oh, okay thank you.

**Comment by sexyzeky** [comment]
With this solution, there is a problem. I think it doesn't measures the scene time but python's reading time. Here is the code and console's print:

```
class KaraTahta(Scene):
    def construct(self):
        a = Circle()
        start_time = time.time()
        self.play(ShowCreation(a), run_time=2)
        self.wait(3)
        elapsed_time = time.time() - start_time
        print(elapsed_time)
```
