### ISSUE TITLE
Can not run python3 -m pip install -r requirements.txt or pip3 install manimlib

### ISSUE THREAD

**Issue by 314har-code** [3b1b/manim#918]
I was following along with the installation video by @Elteoremadebeethoven and was not able to python3 -m pip install -r requirements.txt. The error says `ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'` even though the file does exist in the download folder and in the ManimInstall folder I made (from installation tutorial video). 

I then looked at the official manim page and the README says to do that for direct install, but I can also do pip3 install manimlib. When I try this I get the following errors: 
`ERROR: Could not find a version that satisfies the requirement opencv-python==3.4.2.17 (from manimlib) (from versions: 3.4.8.29, 3.4.9.31, 4.1.2.30, 4.2.0.32)`
`ERROR: No matching distribution found for opencv-python==3.4.2.17 (from manimlib)`

**Comment by artslidd** [comment]
What is your python version ?

**Comment by drewsilcock** [comment]
I'm seeing this when running `pip install manimlib` also. Info:

```bash
$ python --version
Python 3.8.0
$ pip --version
pip 20.0.2
```

**Comment by PommesPeter** [comment]
Have you checked your directory whether in the manim-master folder or not?
use cd to direct to the manim-master folder and run the python3 -m pip install -r requirements.txt

**Comment by PommesPeter** [comment]
Or you can upgrade your pip

**Comment by drewsilcock** [comment]
The issue with the opencv-python version complaining was for me just because I was using 3.8 instead of 3.7. Changing Python version using [pyenv](https://github.com/pyenv/pyenv) or similar fixes this.

**Comment by 314har-code** [comment]
Great. I fixed it by upgrading pip and python. Thanks!

**Comment by dreamrem** [comment]
hi ,..im having the same problem ..i tried changing python version and upgrading pip .. it's still saying the same thing in cmd " ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
what do i do ?
