### ISSUE TITLE
OSError: No file matching ./media\Tex\8cfe77fbfc75043d.svg in image directory

### ISSUE THREAD

**Issue by PommesPeter** [3b1b/manim#923]
Hi,
I meet this problem when I run the command "python -m manim example_scenes.py WriteStuff -pl" and "python -m manim example_scenes.py UpdatersExample -pl", I have no any clue to solve it. I have searched a lot of passages about this problem, but it doesn't work. And it is weird because I can run the command "python -m manim example_scenes.py SquareToCircle -pl".Here below is the report:
```
Media will be written to ./media\. You can change this behavior with the --media_dir flag.
Traceback (most recent call last):
  File "E:\Programing Project\python\manim-master\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "E:\Programing Project\python\manim-master\manimlib\scene\scene.py", line 53, in __init__
    self.construct()
  File "example_scenes.py", line 102, in construct
    tex_to_color_map={"text": YELLOW}
  File "E:\Programing Project\python\manim-master\manimlib\mobject\svg\tex_mobject.py", line 148, in __init__
    self, self.arg_separator.join(tex_strings), **kwargs
  File "E:\Programing Project\python\manim-master\manimlib\mobject\svg\tex_mobject.py", line 46, in __init__
    SVGMobject.__init__(self, file_name=file_name, **kwargs)
  File "E:\Programing Project\python\manim-master\manimlib\mobject\svg\svg_mobject.py", line 45, in __init__
    self.ensure_valid_file()
  File "E:\Programing Project\python\manim-master\manimlib\mobject\svg\svg_mobject.py", line 63, in ensure_valid_file
    self.file_name)
OSError: No file matching ./media\Tex\8cfe77fbfc75043d.svg in image directory
```
Appreciated who help me solve the problem!

**Comment by Micoael** [comment]
It may be caused by dvisvgm.
Check your dvisvgm version and path config.

**Comment by Micoael** [comment]
Dvidvgm helps you to convert tex files to svg files.
Please dive into that directory to find whether that tex file can be compiled or not.
If not, please check your LaTex version
Otherwise, check your dvisvgm version.

**Comment by PommesPeter** [comment]
Thanks for your reply.
I can find my .tex,.xdv,.aux file in the ./media/Tex directory. Is it means the file was compiled?
my latex version is 2.9.7029 and my dvisvgm version is 2.8.2

When I follow the tutorial to install the mainm, that guy who I follow can run the command "python -m manim example_scenes.py WriteStuff -pl" and his dvisvgm version is 2.8.2.

**Comment by PommesPeter** [comment]
> Dvidvgm helps you to convert tex files to svg files.
> Please dive into that directory to find whether that tex file can be compiled or not.
> If not, please check your LaTex version
> Otherwise, check your dvisvgm version.

Thanks for your reply.
I can find my .tex,.xdv,.aux file in the ./media/Tex directory. Is it means the file was compiled?
my latex version is 2.9.7029 and my dvisvgm version is 2.8.2

When I follow the tutorial to install the mainm, that guy who I follow can run the command "python -m manim example_scenes.py WriteStuff -pl" and his dvisvgm version is 2.8.2.

**Comment by PommesPeter** [comment]
> Dvidvgm helps you to convert tex files to svg files.
> Please dive into that directory to find whether that tex file can be compiled or not.
> If not, please check your LaTex version
> Otherwise, check your dvisvgm version.

I have solved this problem just now. 
I download a older version dvisvgm which is 2.6.3 and when I try again to run the command,it works
I appreciated you help me solve the problem.
