### ISSUE TITLE
Reconsidering TEX_USE_CTEX / using XeLaTeX

### ISSUE THREAD

**Issue by hanwenzhu** [3b1b/manim#924]
I worked on manim back in 2018. I added the function for using CTeX (XeLaTeX package for Chinese) and XeLaTeX instead of LaTeX using the flag `TEX_USE_CTEX` in constants.py (#315).

I have stopped working on manim since 2019, but over the months there are apparently more and more people who want to use LaTeX rendering in non-English languages, and even on very old issues I still occasionally see people asking how to do that... Looking back at my change I really should have **decoupled using CTeX (TeX template) from XeLaTeX (rendering tool)**. This has caused a *lot* of confusions and made weird hacks/fixes necessary for only using XeLaTeX, especially for a language that is not Chinese or English, with the most recent #858 and #840. It really should have been a flag `TEX_USE_XELATEX` and another flag `TEMPLATE_TEX_NAME`, and the flag `TEX_USE_CTEX` is such that when it is `True`, `TEX_USE_XELATEX` is `True` and `TEMPLATE_TEX_NAME` is `"ctex_template.tex"`; otherwise `TEX_USE_XELATEX` is `False` and `TEMPLATE_TEX_NAME` is `"tex_template.tex"`. Then set `TEMPLATE_TEX_FILE` to `os.path.join(os.path.dirname(os.path.realpath(__file__)), TEMPLATE_TEX_NAME)`. Corresponding logic: constants.py lines 74–79.

It might be even better to set it dynamically using a function or as a parameter of `TexMobject()`, (see issues like #891). I looked at the source code and this is definitely possible. The options I can think of are
1. Use the current `TEX_USE_CTEX`
2. Add flags `TEX_USE_XELATEX` and `TEMPLATE_TEX_NAME`, and rework `TEX_USE_CTEX`
3. Add parameters for `TexMobject()` like `use_xelatex=False` and `tex_template="tex_template.tex"`
4. Use the flags of 2. as a default, and make it possible to change the default using 3.

Not really sure if this is the right place to raise this issue.

**Comment by hanwenzhu** [comment]
I can do a PR for the change if needed

**Comment by hanwenzhu** [comment]
#723 is also a pretty good idea and there is a similar pr #745 although it doesn't decouple CTeX from XeLaTeX

**Comment by Ayan2357** [comment]
@hanwenzhu I have tried the process as described in #840. But as soon as i set TEX_USE_CTEX to true, all my scenes show this error 

Traceback (most recent call last):
  File "C:\Users\Ani-Ayan PC\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Ani-Ayan PC\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Manim\manim_3_feb\manim.py", line 2, in <module>
    import manimlib.config
  File "C:\Manim\manim_3_feb\manimlib\__init__.py", line 2, in <module>
    import manimlib.config
  File "C:\Manim\manim_3_feb\manimlib\config.py", line 8, in <module>
    import manimlib.constants
  File "C:\Manim\manim_3_feb\manimlib\constants.py", line 50, in <module>
    TEMPLATE_TEXT_FILE_BODY = infile.read()
  File "C:\Users\Ani-Ayan PC\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 660: character maps to <undefined>

I did not quite understand the alternative that you were suggesting. Can you be a little bit more clear as what i might try to get around this.

**Comment by hanwenzhu** [comment]
@Ayan2357 This was a feature request / discussion, not a solution (sorry that I didn't make this clear). Please raise a new issue for your problem (and remember to post your code and `tex_template.tex` or `ctex_template.tex` if you modified them; this will help a lot).

**Comment by hanwenzhu** [comment]
Closing as issue is fixed [downstream](https://github.com/ManimCommunity/manim/blob/005adf48e599ac5cbaf98ad8ae379da2974646cd/manim/utils/tex_templates.py#L69) at ManimCommunity. Anyone interested in multilingual support is recommended to use the community version.
