### ISSUE TITLE
installation of virtualenv failed using Catalina: errno 13

### ISSUE THREAD

**Issue by MartinWy** [3b1b/manim#927]
Hey 

After having had so many difficulties with my old Mac I have decided for a new (brand-new) MacBook Pro 16'' running on Catalina. It was time anyway.

Following the tutorial I have installed 
home-brew 
python 
Cairo  
pkg-config

installing of the virtual environment it gives  the following errno 13:

_Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/3.7'
Consider using the `--user` option or check the permissions.

You are using pip version 19.0.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

trying to upgrade pip to 20.0.2 gave the same errno 13

found out that it might be an issue with rights but am not sure what exactly to do
any advice?

Would be thankful for help

**Comment by Aathish04** [comment]
Use the `sudo` prefix when running the command to generate the Virtual Environment.

Something like this:
`sudo python3 -m venv ManimEnv`

**Comment by MartinWy** [comment]
many thanks. It worked. Was guessing, but did not want to mewl with sudo without knowing that this is the right thing to do.
Now got another issue. Will open separately
