### ISSUE TITLE
Test failed:  No such file or directory: 'ffmpeg': 'ffmpeg'. Actually IT IS

### ISSUE THREAD

**Issue by MartinWy** [3b1b/manim#929]
working on OS X Catalina
Macbook 16 ''

Running the Test on step 9, I ran into this error
I actually HAD Installed ffmpeg as requested 

"/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg': 'ffmpeg'

I then checked, if ffmpeg is surely installed:

(venv) martin@Martins-MBP manim % pip3 install ffmpeg
Requirement already satisfied: ffmpeg in ./venv/lib/python3.7/site-packages (1.4)
(venv) martin@Martins-MBP manim % 

Any suggestions?

**Comment by Aathish04** [comment]
Have you installed FFMPEG through Homebrew as well?

The Python package is just a way for python to interface with the command line tool FFMPEG, which must be installed separately.

Install it with `brew`:

`brew install ffmpeg`

It will take some time and install a lot of dependencies.

**Comment by MartinWy** [comment]
thanks. It worked. no idea why it was not installed outside the vent? AM I missing sth? in the tutorial this it is not mentioned, that it also has to be installed by brew

now, I (hopefully) final issue arose, running the WriteStuff file.


(venv) martin@Martins-MBP manim % python3 -m manim example_scenes.py WriteStuff -pl
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/martinwyrwich/Animations/manim/manim.py", line 2, in <module>
    import manimlib
  File "/Users/martinwyrwich/Animations/manim/manimlib/__init__.py", line 4, in <module>
    import manimlib.extract_scene
  File "/Users/martinwyrwich/Animations/manim/manimlib/extract_scene.py", line 9, in <module>
    from manimlib.scene.scene import Scene
  File "/Users/martinwyrwich/Animations/manim/manimlib/scene/scene.py", line 16, in <module>
    from manimlib.mobject.svg.tex_mobject import TextMobject
  File "/Users/martinwyrwich/Animations/manim/manimlib/mobject/svg/tex_mobject.py", line 12, in <module>
    from manimlib.utils.tex_file_writing import tex_to_svg_file
  File "/Users/martinwyrwich/Animations/manim/manimlib/utils/tex_file_writing.py", line 59
    return result
         ^
SyntaxError: invalid syntax

Any idea?

**Comment by Aathish04** [comment]
I'll need some more info. Are you using the Pip installed manim version?
Are you using the cloned Github repo? (MUCH better IMHO)
What guide are you using?

**Comment by MartinWy** [comment]
I have used pip3 
I followed the tutorial on the manim site for installation.  (update 02/19/20)

I installed brew 
brew install python3
brew install cairo
brew install pkg-config
pip3 install virtualenv

www.tug.org/mactec/mactex-download.html
created animation folder

gig clone https://github.com/3b1b/manim.git

created virtualenv vent
source Vene/bin/activate

pip3 install sox
pip3 install ffmpeg
pip3 install latex
pip3 install pycairo
pip3 install -r requirements.txt

modified the constants file

Created output folder
Test worked fine

modified 
tex_template.tex
tex_file_writing.py

here I am

**Comment by Aathish04** [comment]
Since you are using the cloned GitHub repo for Manim, you have to use it like this:

`python3 manim.py <full path to your animation>`

Manim.py is present inside the Manim repository that you cloned, so once you are inside the Virtual Environment:

`python3 manim/manim.py <full path to your animation>`

Should work.

If it doesn't, try and read through this:

https://repperiumsci.blogspot.com/2019/12/my-adventures-with-manim-part_22.html?m=1
Many Manim users on MacOS have reported that following those instructions led to a clean, succesful install.

**Comment by MartinWy** [comment]
thx. 
As I still did not get it 100% right, I have followed your link and started all over again.
Everything went well, except the WriteStuff part.

In the other tutorial I had to change two filed tex_template...
This "new" tutorial did not speak about it.
Is this still needed???

**Comment by MartinWy** [comment]
(ManimEnv) martin@Martins-MBP manim % python manim.py example_scenes.py
Media will be written to /Users/martinwyrwich/Animations/output/. You can change this behavior with the --media_dir flag.
1: OpeningManimExample
2: SquareToCircle
3: UpdatersExample
4: WarpSquare
5: WriteStuff

Choose number corresponding to desired scene/arguments.
(Use comma separated list for multiple entries)
Choice(s): 3
sh: latex: command not found



Traceback (most recent call last):
  File "/Users/martin/Animations/ManimEnv/manim/manimlib/extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "/Users/martin/Animations/ManimEnv/manim/manimlib/scene/scene.py", line 53, in __init__
    self.construct()
  File "example_scenes.py", line 122, in construct
    include_sign=True,
  File "/Users/martin/Animations/ManimEnv/manim/manimlib/mobject/numbers.py", line 38, in __init__
    for char in num_string
  File "/Users/martin/Animations/ManimEnv/manim/manimlib/mobject/numbers.py", line 38, in <listcomp>
    for char in num_string
  File "/Users/martin/Animations/ManimEnv/manim/manimlib/mobject/svg/tex_mobject.py", line 44, in __init__
    self.template_tex_file_body
  File "/Users/martin/Animations/ManimEnv/manim/manimlib/utils/tex_file_writing.py", line 19, in tex_to_svg_file
    dvi_file = tex_to_dvi(tex_file)
  File "/Users/martin/Animations/ManimEnv/manim/manimlib/utils/tex_file_writing.py", line 67, in tex_to_dvi
    "See log output above or the log file: %s" % log_file)
Exception: Latex error converting to dvi. See log output above or the log file: /Users/martin/Animations/output/Tex/701bbfb7cb8d210c.log

**Comment by Aathish04** [comment]
The `sh: latex: command not found` leads me to believe that something has gone horribly wrong with your LaTeX installation.
How did you install LaTeX?

If you don't want to waste time troubleshooting your TeX install, which you _could_ do, please perform a reinstall of LaTeX.

**Comment by MartinWy** [comment]
I have installed via clicking on the the latex package and letting the installation run

**Comment by MartinWy** [comment]
how can I uninstall properly?

**Comment by MartinWy** [comment]
ok, I am not installing agagin following also here the "new" guide
will keep you posted

**Comment by Aathish04** [comment]
From which site did you download the latex package?
The recommended way for intalling LaTeX was detailed in the Link I sent you.
`brew install mactex` or `brew install mactex-no-gui` or `brew install miktex-console` or `brew install basictex`.

Before you install through any of those methods:
To uninstall LaTeX, if you installed by DOWNLOADING, follow:
https://www.tug.org/mactex/uninstalling.html

But, you would have already made a 3gb download of MacTex. I would recommend keeping that pkg safe.
If you are OK with making another 3gb download, you can install:
`brew install mactex` or `brew install mactex-no-gui`
If you do not want to:
`brew install miktex-console`

If you are an advanced user of the Command Line and are OK with spending most of your time using LaTeX in the Command Line:
`brew install basictex`

**Comment by Aathish04** [comment]
From which site did you download the latex package?
The recommended way for intalling LaTeX was detailed in the Link I sent you.
`brew install mactex` or `brew install mactex-no-gui` or `brew install miktex-console` or `brew install basictex`.

Before you install through any of those methods:
To uninstall LaTeX, if you installed by DOWNLOADING, follow:
https://www.tug.org/mactex/uninstalling.html

But, you would have already made a 3gb download of MacTex. I would recommend keeping that pkg safe.
If you are OK with making another 3gb download, you can install:
`brew install mactex` or `brew install mactex-no-gui`

If you do not want to:
`brew install miktex-console`

If you are an advanced user of the Command Line and are OK with spending most of your time using LaTeX in the Command Line:
`brew install basictex`

**Comment by MartinWy** [comment]
it worked: great Many THANKS I think it from the beginning was the LATEX installation which was causing problems.
now I can concentrate in programming and not primarily on OS issues 
Again: MANY Thanks
Martin

**Comment by Aathish04** [comment]
Great! Please make sure to close this issue if you are done. As you can
see, we have a lot of resolved issues that have been abandoned...
