### ISSUE TITLE
AttributeError: 'Camera' object has no attribute 'frame'

### ISSUE THREAD

**Issue by doan797** [3b1b/manim#965]
Hi,
I would like to run the phyton code from .../from_3b1b/active/sir.py but I am getting below error:
AttributeError: 'Camera' object has no attribute 'frame'

The steps I follow:
1- I am running "manim SIN.py" command through terminal
2- It returns the possible scenes, then I select 7 (CentralMarketLessFrequent)
(actually, the same thing appears for most of the scenes)
When I select #122 (WideSpreadTesting) it creates separate video files but fails to combine them and returns the same error
3- The code is running on Windows 10, manimlib version 0.1.10

Any help is appreciated. Thanks in advance.

**Comment by doan797** [comment]
I solved it by generating a new class with the required attributes.

**Comment by mrhenriksen** [comment]
@doan797 I have the same problem but is very new to manim/Python. Could you elaborate on your solution? Best regards

**Comment by jkremser** [comment]
solution to this issue is changing the
```
MyAwesomeScene(Scene):
   self.play(Write(Text("Hello camera")))
```
to
```
MyAwesomeScene(MovingCameraScene):
   ...
```
