### ISSUE TITLE
No file matching in image directory

### ISSUE THREAD

**Issue by Yoannson** [3b1b/manim#967]
Hello,
I manage to install almost everything with a manim tutorial by "theorem of Beethoven" on Windows 10
https://www.youtube.com/watch?v=ZltiKHFWmv8
Everything went fine, and at the end, the first test "transform square in circle" works fine, but the LaTeX test went wrong. 
![Capture1](https://user-images.githubusercontent.com/63317875/78715518-ce471980-791d-11ea-8330-e9d7b63da791.PNG)
I don't know what to do, I don't understand what's going on.
If anyone can help, I would really appreciate.
Thanks for all,
Yoann

**Comment by Elteoremadebeethoven** [comment]
Please read what your terminal says, it is understood that the `dvisvgm` command is not recognized as an internal command, that is, it was not included when you installed LaTeX, that could happen for two things, or you only installed the basic version or there was an error in the installation, investigate how to install that dependency in some forum.

**Comment by Yoannson** [comment]
I use LaTeX on a daily basis, I had probably an old version of MikTex. I unsinstalled and reinstalled it, everything works now.
Thanks for the help !

**Comment by Elteoremadebeethoven** [comment]
Ok, please close the issue
