### ISSUE TITLE
Getting Error While running pip3 install -r requirment.txt 

### ISSUE THREAD

**Issue by Mathoholic** [3b1b/manim#970]
`Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

c:\manim>python -m pip install -r requirements.txt
Ignoring pycairo: markers 'sys_platform == "linux"' don't match your environment

Requirement already satisfied: argparse==1.4.0 in c:\program files\python37-32\l
ib\site-packages (from -r requirements.txt (line 1)) (1.4.0)
Requirement already satisfied: colour==0.1.5 in c:\program files\python37-32\lib
\site-packages (from -r requirements.txt (line 2)) (0.1.5)
Requirement already satisfied: numpy==1.16.4 in c:\program files\python37-32\lib
\site-packages (from -r requirements.txt (line 3)) (1.16.4)
Requirement already satisfied: Pillow==5.2.0 in c:\program files\python37-32\lib
\site-packages (from -r requirements.txt (line 4)) (5.2.0)
Requirement already satisfied: progressbar==2.5 in c:\program files\python37-32\
lib\site-packages (from -r requirements.txt (line 5)) (2.5)
Requirement already satisfied: scipy==1.3.0 in c:\program files\python37-32\lib\
site-packages (from -r requirements.txt (line 6)) (1.3.0)
Requirement already satisfied: tqdm==4.24.0 in c:\program files\python37-32\lib\
site-packages (from -r requirements.txt (line 7)) (4.24.0)
Requirement already satisfied: opencv-python==3.4.2.17 in c:\program files\pytho
n37-32\lib\site-packages (from -r requirements.txt (line 8)) (3.4.2.17)
Collecting pycairo>=1.18.1
  Using cached pycairo-1.19.1.tar.gz (205 kB)
Collecting pydub==0.23.0
  Using cached pydub-0.23.0-py2.py3-none-any.whl (28 kB)
Processing c:\users\wayne tower\appdata\local\pip\cache\wheels\00\6e\d4\7c4b7bc2
2c090baf4f470e7f35c4f22206277229bdb6607df6\pyreadline-2.1-py3-none-any.whl
Building wheels for collected packages: pycairo
  Building wheel for pycairo (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Program Files\Python37-32\python.exe' -u -c 'import sys, setupto
ols, tokenize; sys.argv[0] = '"'"'C:\\Users\\WAYNET~1\\AppData\\Local\\Temp\\pip
-install-172ou340\\pycairo\\setup.py'"'"'; __file__='"'"'C:\\Users\\WAYNET~1\\Ap
pData\\Local\\Temp\\pip-install-172ou340\\pycairo\\setup.py'"'"';f=getattr(token
ize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'
\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d
 'C:\Users\WAYNET~1\AppData\Local\Temp\pip-wheel-0yqjrek4'
       cwd: C:\Users\WAYNET~1\AppData\Local\Temp\pip-install-172ou340\pycairo\
  Complete output (18 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.7
  creating build\lib.win32-3.7\cairo
  copying cairo\__init__.py -> build\lib.win32-3.7\cairo
  copying cairo\__init__.pyi -> build\lib.win32-3.7\cairo
  copying cairo\py.typed -> build\lib.win32-3.7\cairo
  running build_ext
  building 'cairo._cairo' extension
  creating build\temp.win32-3.7
  creating build\temp.win32-3.7\Release
  creating build\temp.win32-3.7\Release\cairo
  C:\Program Files\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3
 /GL /DNDEBUG /MD -DPYCAIRO_VERSION_MAJOR=1 -DPYCAIRO_VERSION_MINOR=19 -DPYCAIRO
_VERSION_MICRO=1 "-IC:\Program Files\Python37-32\include" "-IC:\Program Files\Py
thon37-32\include" "-IC:\Program Files\Microsoft Visual Studio 14.0\VC\INCLUDE"
"-IC:\Program Files\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Fil
es\Windows Kits\8.1\include\shared" "-IC:\Program Files\Windows Kits\8.1\include
\um" "-IC:\Program Files\Windows Kits\8.1\include\winrt" /Tccairo/device.c /Fobu
ild\temp.win32-3.7\Release\cairo/device.obj
  device.c
  c:\users\wayne tower\appdata\local\temp\pip-install-172ou340\pycairo\cairo\pyc
airo.h(37): fatal error C1083: Cannot open include file: 'cairo.h': No such file
 or directory
  error: command 'C:\\Program Files\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.e
xe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for pycairo
  Running setup.py clean for pycairo
Failed to build pycairo
Installing collected packages: pycairo, pydub, pyreadline
    Running setup.py install for pycairo ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files\Python37-32\python.exe' -u -c 'import sys, setup
tools, tokenize; sys.argv[0] = '"'"'C:\\Users\\WAYNET~1\\AppData\\Local\\Temp\\p
ip-install-172ou340\\pycairo\\setup.py'"'"'; __file__='"'"'C:\\Users\\WAYNET~1\\
AppData\\Local\\Temp\\pip-install-172ou340\\pycairo\\setup.py'"'"';f=getattr(tok
enize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'
"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --re
cord 'C:\Users\WAYNET~1\AppData\Local\Temp\pip-record-wa2qfl0f\install-record.tx
t' --single-version-externally-managed --compile --install-headers 'C:\Program F
iles\Python37-32\Include\pycairo'
         cwd: C:\Users\WAYNET~1\AppData\Local\Temp\pip-install-172ou340\pycairo\

    Complete output (18 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.7
    creating build\lib.win32-3.7\cairo
    copying cairo\__init__.py -> build\lib.win32-3.7\cairo
    copying cairo\__init__.pyi -> build\lib.win32-3.7\cairo
    copying cairo\py.typed -> build\lib.win32-3.7\cairo
    running build_ext
    building 'cairo._cairo' extension
    creating build\temp.win32-3.7
    creating build\temp.win32-3.7\Release
    creating build\temp.win32-3.7\Release\cairo
    C:\Program Files\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /
W3 /GL /DNDEBUG /MD -DPYCAIRO_VERSION_MAJOR=1 -DPYCAIRO_VERSION_MINOR=19 -DPYCAI
RO_VERSION_MICRO=1 "-IC:\Program Files\Python37-32\include" "-IC:\Program Files\
Python37-32\include" "-IC:\Program Files\Microsoft Visual Studio 14.0\VC\INCLUDE
" "-IC:\Program Files\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program F
iles\Windows Kits\8.1\include\shared" "-IC:\Program Files\Windows Kits\8.1\inclu
de\um" "-IC:\Program Files\Windows Kits\8.1\include\winrt" /Tccairo/device.c /Fo
build\temp.win32-3.7\Release\cairo/device.obj
    device.c
    c:\users\wayne tower\appdata\local\temp\pip-install-172ou340\pycairo\cairo\p
ycairo.h(37): fatal error C1083: Cannot open include file: 'cairo.h': No such fi
le or directory
    error: command 'C:\\Program Files\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl
.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Program Files\Python37-32\pyt
hon.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\
WAYNET~1\\AppData\\Local\\Temp\\pip-install-172ou340\\pycairo\\setup.py'"'"'; __
file__='"'"'C:\\Users\\WAYNET~1\\AppData\\Local\\Temp\\pip-install-172ou340\\pyc
airo\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.r
ead().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file_
_, '"'"'exec'"'"'))' install --record 'C:\Users\WAYNET~1\AppData\Local\Temp\pip-
record-wa2qfl0f\install-record.txt' --single-version-externally-managed --compil
e --install-headers 'C:\Program Files\Python37-32\Include\pycairo' Check the log
s for full command output.

c:\manim>`

**Comment by p14jeffwest** [comment]
It seems that pycairo installation was failed while automatic installation. Then, what about to try manual installation for pycairo and then re-try installation for requirement.txt.

To install pycairo manually:
  - download package for windows from: https://www.lfd.uci.edu/~gohlke/pythonlibs/#pycairo
  - filename: pycairo-1.18.2-cp37-cp37m-win_amd64.whl
  - After downloading the file, run below command in the directory of download file exist
     > pip3 install pycairo-1.18.2-cp37-cp37m-win_amd64.whl

**Comment by Mathoholic** [comment]
Thanks, I resolved this issue. 

But now I am facing another issue.
Though I started different issue for it.

Need help in this issue. Please have a look.

https://github.com/3b1b/manim/issues/978

**Comment by yoshiask** [comment]
@eulertour This has been resolved
