### ISSUE TITLE
Exception: Latex error converting to dvi. See log output above or the log file: ./media\Tex\4475e3a270ecfb06.log

### ISSUE THREAD

**Issue by nakulkhambhati** [3b1b/manim#972]
I tried to open the example scene WriteStuff, following the youtube tutorial (https://www.youtube.com/watch?time_continue=492&v=ZltiKHFWmv8&feature=emb_logo)
it worked for SquareToCircle but not for WriteStuff which tells me that latex is not working. I think it may have something to do with my path variables but im not too sure how they work. I have installed miktex only for my user, so i only changed user variables and not system variables. This is my path variable: C:\Users\Nakul Khambhati\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\Nakul Khambhati\AppData\Local\Programs\Python\Python37\;C:\MiKTeX 2.9\miktex\bin\x64\;C:\FFmpeg\bin;C:\sox-14-4-2;

I tried reinstalling Miktex too but nothing seems to work. Can someone please help? I am interested in coding math videos.

**Comment by Elteoremadebeethoven** [comment]
There are a lot of problems like yours, both here on [Github](https://github.com/3b1b/manim/issues?q=latex+error) and [Stackoverflow](https://stackoverflow.com/search?q=%5Bmanim%5D+latex), check them out.
