### ISSUE TITLE
Latex error

### ISSUE THREAD

**Issue by tshrpl** [3b1b/manim#976]
## setup
vmware-player (15.5.1 build-15018445)
guest: zorin-os (ultimate 15.2) (ubuntu based linux distro)
#### dependencies
pre-installed: ffmpeg (version 3.4.6-0ubuntu0.18.04.1) , SoX (v14.4.2) , python (3.7.5)
rest installed by following commands (as root):
``` bash
root@vm3:~/Desktop/manim$ apt install python3.7-dev libcairo2-dev
root@vm3:~/Desktop/manim$ apt install libjpeg-dev libgif-dev libffi-dev
root@vm3:~/Desktop/manim$ apt install texlive-latex-extra texlive-fonts-extra
root@vm3:~/Desktop/manim$ exit
math_fan@vm3:~/Desktop/manim$ latex
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=latex)
 restricted \write18 enabled.
**^C
```
Not sure about cairo

#### manim installation
``` bash
math_fan@vm3:~/Desktop/manim$ pip3 --version
pip 20.0.2 from /home/math_fan/.local/lib/python3.7/site-packages/pip (python 3.7)
math_fan@vm3:~/Desktop/manim$ pip3 install pipenv
(...)
math_fan@vm3:~/Desktop/manim$ pipenv install manimlib
(...)
```
## error
``` bash
math_fan@vm3:~/Desktop/manim$ pipenv shell
shared directory already mounted at /shared_with_host :)
(manim) math_fan@vm3:~/Desktop/manim$ manim examples.py WarpSquare -pl
Media will be written to ./media/. You can change this behavior with the --media_dir flag.

File ready at /home/math_fan/Desktop/manim/videos/examples/480p15/WarpSquare.mp4

Played 2 animations
(manim) math_fan@vm3:~/Desktop/manim$ manim examples.py WriteStuff -pl
Media will be written to ./media/. You can change this behavior with the --media_dir flag.

Traceback (most recent call last):
  File "/home/math_fan/Desktop/manim/.venv/lib/python3.7/site-packages/manimlib/extract_scene.py", line 150, in main
    scene = SceneClass(**scene_kwargs)
  File "/home/math_fan/Desktop/manim/.venv/lib/python3.7/site-packages/manimlib/scene/scene.py", line 52, in __init__
    self.construct()
  File "examples.py", line 102, in construct
    tex_to_color_map={"text": YELLOW}
  File "/home/math_fan/Desktop/manim/.venv/lib/python3.7/site-packages/manimlib/mobject/svg/tex_mobject.py", line 144, in __init__
    self, self.arg_separator.join(tex_strings), **kwargs
  File "/home/math_fan/Desktop/manim/.venv/lib/python3.7/site-packages/manimlib/mobject/svg/tex_mobject.py", line 44, in __init__
    self.template_tex_file_body
  File "/home/math_fan/Desktop/manim/.venv/lib/python3.7/site-packages/manimlib/utils/tex_file_writing.py", line 19, in tex_to_svg_file
    dvi_file = tex_to_dvi(tex_file)
  File "/home/math_fan/Desktop/manim/.venv/lib/python3.7/site-packages/manimlib/utils/tex_file_writing.py", line 67, in tex_to_dvi
    "See log output above or the log file: %s" % log_file)
Exception: Latex error converting to dvi. See log output above or the log file: Tex/34b95eca9f7c5b73.lo
```

line 130-160 of the corresponding log file (can not upload the log file on github)
```
Package: amssymb 2013/01/14 v3.01 AMS font symbols
(/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty
Package: amsfonts 2013/01/14 v3.01 Basic AMSFonts support
\symAMSa=\mathgroup4
\symAMSb=\mathgroup5
LaTeX Font Info:    Overwriting math alphabet `\mathfrak' in version `bold'
(Font)                  U/euf/m/n --> U/euf/b/n on input line 106.
))

! LaTeX Error: File `dsfont.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.7 \usepackage
               {setspace}^^M 
Here is how much of TeX's memory you used:
 2150 strings out of 494924
 28322 string characters out of 6180768
 86804 words of memory out of 5000000
 5479 multiletter control sequences out of 15000+600000
 3640 words of font info for 14 fonts, out of 8000000 for 9000
 14 hyphenation exceptions out of 8191
 34i,0n,56p,236b,36s stack positions out of 5000i,500n,10000p,200000b,80000s

No pages of output.
```

**Comment by Aathish04** [comment]
It appears as though you haven't installed the doublestroke font package for LaTeX.

Please try running `tlmgr install dsfont`.
If you are on a Debian based system, `sudo apt-get install texlive-fonts-extra ` may serve better.

**Comment by tshrpl** [comment]
I tried `texlive-fonts-extra` earlier, no use ...

**Comment by Aathish04** [comment]
Is it the same package that’s missing?

Note that for Manim to work properly, you need at least following latex packages:

texlive texlive-latex-extra texlive-fonts-extra
 texlive-latex-recommended texlive-science texlive-fonts-extra tipa

**Comment by tshrpl** [comment]
I don't have `texlive-science` package ......... will try now ...


> what is tlmgr?

**Comment by Aathish04** [comment]
> I don't have `texlive-science` package ......... will try now ...
> 
> > what is tlmgr?
> 
> edit:
> 
> ```shell
> math_fan@vm3:~/Desktop/manim$ sudo apt install texlive-science
> (...)
> math_fan@vm3:~/Desktop/manim$ pipenv shell
> Launching subshell in virtual environment…
> shared directory already mounted at /shared_with_host :)
> (manim) math_fan@vm3:~/Desktop/manim$ manim examples.py WriteStuff -pl
> Media will be written to ./media/. You can change this behavior with the --media_dir flag.
> Writing "\centering This is a some text" to Tex/34b95eca9f7c5b73.tex
> Writing "\centering This is a some" to Tex/533bb993195a5b38.tex
> Writing "\sum_{k=1}^\infty {1 \over k^2} = {\pi^2 \over 6}" to Tex/ba3a204c589a1eb6.tex
> 
> File ready at /home/math_fan/Desktop/manim/videos/examples/480p15/WriteStuff.mp4
> 
> Played 3 animations
> ```
> 
> ### @Aathish04 thank you so much
> turns out this was a missing package issue

Oh, btw, `tlmgr` is the "TexLiveManaGeR".

It can install packages for LaTeX.
