### ISSUE TITLE
while an animation is playing, some other animations plays one by one

### ISSUE THREAD

**Issue by sexyzeky** [3b1b/manim#979]
I want to play Write(A) and Write(B) while the p is moving. But A must be written before B. How can ı do that?

```
class Examples(Scene):
    def construct(self):
        p = Dot()
        A = TextMobject("A").move_to(UP)
        B = TextMobject("B").move_to(DOWN)
                

   
```

**Comment by Ammar34** [comment]
**You need to specify where you want the p to move. I assume you want to move it in any arbitrary direction. Here is how you do it.**

```
class Example(Scene):
    def construct(self):
        p = Dot()
        A = A = TextMobject("A").move_to(UP)
        B = TextMobject("B").move_to(DOWN)

        self.play(Write(A), Write(B), p.move_to, LEFT * 3)


```
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/12208432/79171084-94d54900-7e0a-11ea-9fb1-dad9ff42a022.gif)

**Comment by sexyzeky** [comment]
Thanks, but here, A and B is written at the same time. How can A become first? I try this:
```
class Example(Scene):
    def construct(self):
        p = Dot()
        A = TextMobject("A").move_to(UP)
        B = TextMobject("B").move_to(DOWN)
        
        while self.play(p.shift(LEFT*2)):
            self.play(Write(A))
            self.play(Write(B))
            break
        self.wait(0.2)
```
But it didn't work.

**Comment by zavden** [comment]
You can use Successions, [here](https://github.com/Elteoremadebeethoven/AnimationsWithManim/blob/master/English/update_successions/successions_in_recent_versions.py) are examples.
