### ISSUE TITLE
Copying style and position of TexMobject

### ISSUE THREAD

**Issue by stevenschn** [3b1b/manim#982]
I saw it somewhere in the manim tutorial by TheoremofBeethoven but I cannot find it anymore.

I have the following TexMobject:
        
```
        formula = TexMobject("2x", "=", "8")
        formula.move_to(DOWN*2)
        formula[0].set_color(RED)
        formula[2].set_color(BLUE)
```

Now the seperate parts are already individually aligned on the screen. Now I want to change ```formula[0]``` to for example ```x```, but with the same style and position as it currently is. 

How do I do that most efficiently? I could create a new TexMobject, then move it to ```formula[0]``` and set the color again to RED, but I think you can copy all those attributes/properties, right?

**Comment by raghavg123** [comment]
You can try this:
```py
x=TexMobject("x")
x.become(formula[0],copy_submobjects=False)
```

**Comment by stevenschn** [comment]
Thanks! Do I understand correctly that this differs from ```.copy()``` in the way that it does not copy the actual text itself, but that it in other ways is the same?

**Comment by stevenschn** [comment]
> ```python
> ```python
> x.become(formula[0],copy_submobjects=False)
> ```
> 
> 
>       
> ```

This would actually replace ```x``` by the value from ```formula[0]```, so this unfortunately does not work.

**Comment by p14jeffwest** [comment]
I think it's not an excellent way to meet your request, but anyway, it works. :)

What about below style? 

`
        formula = TexMobject("2x", "=", "8")
        formula.move_to(DOWN * 2)
        formula[0].set_color(RED)
        formula[2].set_color(BLUE)

        self.add(formula)
        self.wait()

        x = TexMobject("x", color=RED).move_to(formula[0])
        self.play(ReplacementTransform(formula[0], x))

        self.wait()
`

**Comment by raghavg123** [comment]
> > ```python
> > ```python
> > x.become(formula[0],copy_submobjects=False)
> > ```
> > 
> > 
> >       
> > ```
> 
> This would actually replace ```x``` by the value from ```formula[0]```, so this unfortunately does not work.

That's what the `copy_submobjects=False` is for though?

**Comment by stevenschn** [comment]
> I think it's not an excellent way to meet your request, but anyway, it works. :)
> 
> What about below style?
> 
> ```
>         formula = TexMobject("2x", "=", "8")
>         formula.move_to(DOWN * 2)
>         formula[0].set_color(RED)
>         formula[2].set_color(BLUE)
> 
>         self.add(formula)
>         self.wait()
> 
>         x = TexMobject("x", color=RED).move_to(formula[0])
>         self.play(ReplacementTransform(formula[0], x))
> 
>         self.wait()
> ```

This is what I normally do, I was just hoping there was a more elegant way. 

> > > ```python
> > > ```python
> > > x.become(formula[0],copy_submobjects=False)
> > > ```
> > 
> > 
> > This would actually replace `x` by the value from `formula[0]`, so this unfortunately does not work.
> 
> That's what the `copy_submobjects=False` is for though?

That is what I thought as well, but even so it copies the actual letters used.

**Comment by PgBiel** [comment]
I don't know if I understood your problem correctly; I think you're looking for
```py
formula[0].match_style(x)
```
It makes the stroke, the fill, and the background-related properties the same.

**Comment by stevenschn** [comment]
> I don't know if I understood your problem correctly; I think you're looking for
> 
> ```python
> formula[0].match_style(x)
> ```
> 
> It makes the stroke, the fill, and the background-related properties the same.

This is exactly it! Thank you! I will now close this issue.
