### ISSUE TITLE
Is it possible to fade every object out from a scene?

### ISSUE THREAD

**Issue by DennisMamedov** [3b1b/manim#992]
I'm just wondering if there's a quick and easy way to fade everything (the entire scene) out, instead of doing it manually through hardcoding.

Thanks!

**Comment by Elteoremadebeethoven** [comment]
See [this](https://github.com/Elteoremadebeethoven/AnimationsWithManim/blob/master/English/extra/faqs/faqs.md#remove-all-objects-in-screen)

**Comment by Level-314** [comment]
This is how I do it:

        self.play(
            *[FadeOut(mob)for mob in self.mobjects]
        )

**Comment by pdfarrell1** [comment]
That's what I was looking for. Thanks!

**Comment by theactualmariluski** [comment]
Thanks!
