### ISSUE TITLE
Add new word in sentence

### ISSUE THREAD

**Issue by sexyzeky** [3b1b/manim#993]
I wrote "It is an apple" on the screen. And ı want to add "delicious". Do ı create an animation that while "delicious" is written from its origin ("c") to its each edge ("d" and "s"), "It is an" and "apple" move to left and right ,respectively, propotional to lenght of "delicious". I only could this:

```
class Example(Scene):
    def construct(self):
        sent = TextMobject("It is an", "\r apple")

        delicious = TextMobject("delicious").next_to(sent[0], RIGHT*.5)
        apple = sent[1].copy().next_to(delicious, RIGHT*.5).shift(DOWN*.05)

        self.play(Write(sent))
        self.play(ShowCreation(delicious, run_time=1.2),
                  ReplacementTransform(sent[1], apple))

```

**Comment by stevenschn** [comment]
I guess you could use next_to for both sent[0] and sent[1]. I would guess something like the following:

class Example(Scene):
    def construct(self):
        sent = TextMobject("It is an", "\r apple")
        delicious = TextMobject("delicious")

        self.play(Write(sent))
        self.play(ApplyMethod(sent[0].next_to(delicious,LEFT), 
                      ApplyMethod(sent[1].next_to(delicious, RIGHT))
        self.play(ShowCreation(delicious))

**Comment by sexyzeky** [comment]
But in here the "delicious" does not satisfy the creation from its center toward its edges

**Comment by stevenschn** [comment]
and if you would use ```GrowFromCenter```? Would that meet your needs?
